### ISSUE TITLE
coordinated copulas 

### ISSUE THREAD

**Issue by gossebouma** [UniversalDependencies/docs#1011]
I am struggling with the correct analysis of a sentence containing 2 coordinated copulas (present and past tense)

_Alle mensen die nu "ontdekkers" worden genoemd zijn en waren, op ieder gebied van het denken, mensen die goed bekend waren met de gedachtengangen van hun voorgangers en geleerd in dat wat er voor hen kwam._

_All people who are called inventors  **are and were**  ..  persons that were well aware of the ideas of those before them_

My current analysis has

nsubj(persons,people)
cop(persons,are)
conj(are,were)
cc(and,were)

but the validator complains that cop is not supposed to have dependents 

There is a long discussion of similar cases here [coordinated auxs](https://github.com/amir-zeldes/gum/issues/107) but no clear conclusion. 

One option is to go for an analysis where these are actually 2 full sentences, the second one elided except for the copula. (Actually, the underlying treebank annotation does exactly this). I tried to reconstruct that, but it would mean that the second copula (_waren_) is a conj of the head of the first conjunct, i.e. the head of the predicate, which follows the copulas. Now the validator complains that there is a conj relation which is not left-to-right. 

The only way to avoid the latter error is perhaps to consider everything up to 'en' as a conjuct and everything following it as the second conjuct:

[ nsubj cop ] en [cop predicate]

This seems extremely ugly to me, and it leaves the status of the first copula unclear (orphan to the nsbubj?)

Any other suggestions?

**Comment by gossebouma** [comment]
Fixed it, there was some interacting issue. 2nd cop is acually allowed as dep of 1st cop

**Comment by nschneid** [comment]
Yes, see this item in the guidelines: https://universaldependencies.org/u/overview/syntax.html#coordinated-function-words
