### ISSUE TITLE
Co-relative relative Clauses in Saraiki 

### ISSUE THREAD

**Issue by meesumalam** [UniversalDependencies/docs#1014]
Hi all,

I am annotating Saraiki under UD annotation scheme, I am stuck at making decision on following corelative relative clause in Saraiki. Translation is "I saw the farmer who slept in the house" lit translation " Which farmer was sleeping in the house he I saw".

           جیڑا            زمیندار    گھر         ستا    پیا      ہا     میں           اوں   کوں   ڈٹھا
                                                                            VERB   ACC PRON       PRON AUX AUX VERB     NOUN  NOUN-          ADJ
                                                                          see-PST ACC 3SG-Distal 1SG AUX AUX sleep-PST Home Farmer-M-SG REL-M-SG 

Thanks

**Comment by dan-zeman** [comment]
![image](https://github.com/UniversalDependencies/docs/assets/663752/6d182a65-15a4-489e-aabc-55d31646ca24)

**Comment by meesumalam** [comment]
Thanks, I think jeda and farmer will go with "amod" relation as it is functioning as relative adjective. Thoughts ?

**Comment by dan-zeman** [comment]
> Thanks, I think jeda and farmer will go with "amod" relation as it is functioning as relative adjective. Thoughts ?

For me the main difference between `ADJ` and `DET` is the `PronType` feature. Since it is relative, I would give it `PronType=Rel` and then tag it `DET` rather than `ADJ`. Consequently the relation would also be `det` and not `amod`.

**Comment by meesumalam** [comment]
Thank you so much.

Meesum
________________________________
From: Dan Zeman ***@***.***>
Sent: Wednesday, February 28, 2024 2:04 AM
To: UniversalDependencies/docs ***@***.***>
Cc: Alam, Meesum ***@***.***>; Author ***@***.***>
Subject: [External] Re: [UniversalDependencies/docs] Co-relative relative Clauses in Saraiki (Issue #1014)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Thanks, I think jeda and farmer will go with "amod" relation as it is functioning as relative adjective. Thoughts ?

For me the main difference between ADJ and DET is the PronType feature. Since it is relative, I would give it PronType=Rel and then tag it DET rather than ADJ. Consequently the relation would also be det and not amod.
