### ISSUE TITLE
incoherence of `acl:relcl` versus `acl` distinction

### ISSUE THREAD

**Issue by jonorthwash** [UniversalDependencies/docs#1015]
According to the docs, `acl:relcl` is semi-mandatory when an adjectival clause (`acl`) is a relative clause.

However, the [`acl:relcl`-specific documentation](https://universaldependencies.org/u/dep/acl-relcl.html) seems to suggest that for English the decision of when to use `acl:relcl` versus `acl` comes down to whether the `acl` is indicated by a subordinated finite phrase (`acl:relcl`) or a participle (`acl`).  Implicit in the language used is that participle `acl`s in English are not relative clauses.  However, I can't think of any example of an `acl` that _isn't_ a relative clause.  For example, in _the man *seen with the book*_, is _seen with the book_ not a relative clause?

In most Turkic languages, relative clauses are only ever formed using participles, and participles always indicate relative clauses—i.e., there's a one-to-one relationship.  English has an additional strategy for making relative clauses (which it seems to rely on a bit more than the one with participles), but I see this as a one-to-many relationship: one semantic structure (a relative clause) and two strategies (subordination of a finite clause, and using an adjectival clause).

Given how the relation subtype `acl:relcl` is used in English, it seems to me that it would make sense to rename it to `acl:subord` or similar.  Distinguishing between two strategies is fine, but calling one of them a relative clause when they both are doesn't seem consistent with a UD-style approach.  Meanwhile, it seems a bit silly to be semi-mandated to annotate all Turkic `acl`s as `acl:relcl` just because they all use participles.

**Comment by nschneid** [comment]
There are different traditions of the term "relative clause" in English grammar. The one adopted for UD corpora, and more recently detailed in the [English docs](https://universaldependencies.org/en/dep/acl-relcl.html), excludes participial clauses as you point out, following the *Cambridge Grammar of the English Language*. There are many nuances but a general summary is that relative pronouns like *which* are taken as characteristic of English relative constructions, and such relativizers cannot occur with participial clauses (_*the man which seen with the book_).

Note that the universal guidelines say "In other languages however, the distinction between finite and non-finite clauses may not exist or may not be used as a criterion for relative clauses." Documentation of how `acl:relcl` is used in languages beyond English would certainly be welcome.

**Comment by jonorthwash** [comment]
> Documentation of how `acl:relcl` is used in languages beyond English would certainly be welcome.

Well per the definition you just provided, there is no such thing as a relative clause in languages like Kyrgyz.  Despite the vast literature on them.  So I guess we just go on labelling them as `acl` and not worry too much when someone publishes papers surveying how many UD languages are RC-less.

But if you're really interested, there's quite a large body of literature on relative clauses (although I think we're using this term differently—see below) in Turkic (https://doi.org/10.1093/oso/9780198851509.003.0032 for an overview of what's going on in Turkish), and there's also a recent paper that goes into some depth on Turkic participles / verbal adjectives that form `acl`s == relative clauses (https://doi.org/10.1515/flin-2022-2045).

I think falling back on a grammatical tradition that limits the label for a semantic structure to one syntactic implementation thereof is very un-UD-like.  Is there anything else in UD that works this way?

(So it seems `acl` is used in a way that maps to what I understand "relative clause" to mean, and `acl:relcl` is used in English treebanks to mean "relative clause implemented using relativisers".)

**Comment by nschneid** [comment]
It is a fair point that typologists would define relative clauses more broadly than some English grammars. If UD corpora were created from scratch this may have come out differently—but the starting point for UD was a bunch of treebanks annotated in language-specific ways that followed particular interpretations of terms. For English the starting point was Stanford Dependencies. I was not involved in UD in the early years but my impression is that it was first determined that not all languages had relative clauses so it could not be a "universal" relation, and instead should be a subtype of `acl`, but over time it became clear that lots of languages do want to distinguish relative clauses from the broader `acl` category (and perhaps this has certain implications for enhanced UD), so the subtype was deemed "semi-mandatory".

In practice, IMO you should feel free to use `acl:relcl` for the participial ones in Turkic and not worry about how it is applied in English. Longer-term (UDv3?) perhaps relative clauses deserve a top-level relation with a more uniform definition.

**Comment by nschneid** [comment]
> (So it seems `acl` is used in a way that maps to what I understand "relative clause" to mean,

`acl` is still broader than `acl:relcl`—e.g. it includes adnominal argument clauses (e.g. "a chance **to present the company's story**" in EWT). Nobody would call this a relative clause, right?

**Comment by dan-zeman** [comment]
> So I guess we just go on labelling them as `acl` and not worry too much when someone publishes papers surveying how many UD languages are RC-less.

Using always `acl:relcl` and never plain `acl` is not necessarily a bad thing (provided that your language does not have constructions like _a chance to present the story_, in which the adnominal clause is not relative).

Another bit to the puzzle is that in enhanced dependencies the relation between the predicate of the relative clause and its antecedent would be added. With `acl:relcl` it might be clearer why the added relation is there. (On the other hand, I have proposed that this enhancement should be used also with participial modifiers (even in Czech and English where we don't mak them as `acl:relcl`) and then the label of the relation would not matter again.)

**Comment by Stormur** [comment]
I definitely agree that participial adnominal clauses should be labelled as relative ones, if we do have this `:relcl` subtype.

The guide lines as they stand now are too language-specific, and annotating based on the presence of a relative pronoun (and by the way, for many treebanks, not even of a generically, non-core relative element like _where_ or _how_) is a kind of contextual annotation. 

I get that some parts of the guide lines try to bring forth examples from specific languages, but I often see that many take this then as "universal hints".

**Comment by amir-zeldes** [comment]
I would not claim that the distinguishing characteristic of relcl is necessarily having a relative pronoun, although that is probably sufficient. I think the more important point about relatives is that the nominal to which the clause is attached is encoded as a participant in the clause (this can sometimes be elliptical, e.g. in zero relatives, but such participation still saturates an argument slot). This has come up as a criterion in the suggestion for annotating adnominal infinitives with preposition stranding as relatives. For example:

  * A table on which we write - relative, table is encoded as a location in the clause, expressed by relative
  * A table for writing - regular acl, no expression of the table being, say, the location of the writing (although it probably is)
  * A table the purpose of which is to write - relative, like the first example
  * A house for living (e.g. as opposed to an airbnb) - acl, same as the second
  * A house in which to live - relcl, explicit relative pronoun
  * A house to live in - this was the corner case in the relative infinitive discussion - arguably the "in" satisfies relative encoding, i.e. the locative function of the matrix house inside the subordinate clause is indicated

And I think other types of encoding like indeclinables ("where" and languages with a unique relative particle), or resumptive pronouns, would all be fair game for relcl, even without a proper relative pronoun, which is primarily an Indo-European phenomenon.

**Comment by nschneid** [comment]
@amir-zeldes So this is getting into the weeds re: English-specific criteria, but I think there are adnominal participial clauses that can only be interpreted as the head noun being a participant:

- the dancers performing on stage
- the money given to charity

But a relativizer cannot be added without making the clause finite (_*the dancers who performing on stage_, _*the money which given to charity_).

And to add to your examples there is also

- a house for living in

which is a preposition stranding but still not relative (per the English-specific definition) because you cannot say _*a house in which for living_. This contrasts with the infinitival paraphrase, _a house to live in / a house in which to live_, so the infinitival one is arguably relative while the participial one is not. Infinitival relatives have always just been `acl` in English corpora though (so far, anyway; I started an effort to change that but never got very far: UniversalDependencies/UD_English-EWT#324).

**Comment by dan-zeman** [comment]
> there are adnominal participial clauses that can only be interpreted as the head noun being a participant:
> 
> * the dancers performing on stage
> * the money given to charity
> 
> But a relativizer cannot be added without making the clause finite

Yes, these are cross-linguistically relative clauses, even if English-internal grammatical tradition may not like the term in this situation.

**Comment by jonorthwash** [comment]
> > So I guess we just go on labelling them as `acl` and not worry too much when someone publishes papers surveying how many UD languages are RC-less.
> 
> Using always `acl:relcl` and never plain `acl` is not necessarily a bad thing (provided that your language does not have constructions like _a chance to present the story_, in which the adnominal clause is not relative).

This is essentially what the [Turkish grammar](https://doi.org/10.1093/oso/9780198851509.003.0032) I referenced calls "pseudo-relative clauses", and they are indeed present in Turkic.  Quoted from said source:

> In the sentences that follow, however, the relative clause is placed before a noun which itself is not relativized. In other words, in the next examples _vaka_ ‘case’, _an_ ‘moment’, _zaman_ ‘moment’, _akşam_ ‘evening’, _gün_ ‘day’, _sene_ ‘year’ and _yıl_ ‘year’ are not the object of some verb or the core of some adverbial phrase. For this reason clauses of this type are known as pseudo-relative clauses. These are widespread for expressions of time and place

The problem is that I don't really agree with the argumentation.  In the examples given in the source, they really all do feel like nouns extracted from an adverbial phrase of some sort, e.g. As of the day we got married she wanted to learn photography", it's easy enough to understand "day" as extracted from "we got married" ("we got married [on that day]").

Examples more like _a chance to present the company's story_ are discussed in [the paper](https://doi.org/10.1515/flin-2022-2045) I referenced, and are also attested in Turkic.  Example (19d) translates as "I didn't have the nerve to go to the library".  The paper tentatively treats "to go to the library" as an adjectival clause, but also mentions that it could just as easily be analysed as an adverbial clause, dependent on the verb (which in this case is literally "wasn't enough", i.e. "wasn't enough for going to the library").  Since unambiguous examples (in Tatar) seem to be really hard to find, it was concluded that grammaticalisation from an adverbial analysis to an adjectival analysis was possible (either as having already occurred, or as a future path).  This would mean that Tatar might (have) acquire(d) verbal adjectives which do not function to form RCs.

If _a chance to present the company's story_ really is unambiguously an adjectival clause, then I agree that it probably isn't a relative clause (_they presented the company's story [using one chance]_ or something does seem like a bit of a stretch).  And perhaps it really has grammaticalised from ambiguous cases—e.g., in _they had a chance to present the company's story_, it seems like _to present the company's story_ could just as easily be `advcl` to _had_, and maybe even _had a chance_ is a LVC?  (Note that _they took a chance to present the company's story_ seems a bit weird—_took a chance in presenting_ seems to work better—and it shouldn't be if it's `acl` and there's no LVC here.)  So if this is all correct, which I'm still not positive about, then in my mind then it would be a case of `acl` being used in a more expansive way than the default `acl`==RC usage, extended diachronically via examples of `advcl` that lend themselves to reanalysis as `acl`.

**Comment by sylvainkahane** [comment]
There are cases where the clause clearly depends on _chance_ and must be `acl`:

> I had to leave without any chance to present the company's story.
My last chance to present the company's story is over.

**Comment by nschneid** [comment]
> So if this is all correct, which I'm still not positive about, then in my mind then it would be a case of `acl` being used in a more expansive way than the default `acl`==RC usage, extended diachronically via examples of `advcl` that lend themselves to reanalysis as `acl`.

Sounds good to me—I don't think UD means to claim that plain `acl` should be more common or more central than `acl:relcl` in the language. If relative clauses are the main type of adnominal clause then `acl:relcl` can be the "default" for that language.

**Comment by jonorthwash** [comment]
Okay, I believe I understand the disticntion as UD sees it.  Ignoring Engilsh for a moment, `acl:relcl` is for adjective clauses _implemented using any strategy_ that can be understood to be relative clauses (almost all RCs in Turkic).  And `acl` is for what the above-referenced Turkish grammar calls "pseudo-relative clauses"—that is, adjectival clauses that are semantically difficult to understand as relative clauses.

Just to make sure, is it okay to label all `acl:relcl` as just `acl` in a given treebank?  Or if it can be interpreted as a relative clause, then it needs to be labelled `acl:relcl`?

**Comment by dan-zeman** [comment]
> Just to make sure, is it okay to label all `acl:relcl` as just `acl` in a given treebank? Or if it can be interpreted as a relative clause, then it needs to be labelled `acl:relcl`?

It is somehow OK because subtypes are optional. On the other hand, `acl:relcl` is one of the "semi-mandatory subtypes" (see https://universaldependencies.org/u/dep/index.html), so it should be used in a language that has relative clauses. But it brings us back to the question whether we want to use the cross-linguistically applicable definition of relative clause, or the narrower one that would align with traditional terminology in English. I would say that the semi-mandatoriness covers the narrow sense, while other languages are a gray zone.
