### ISSUE TITLE
complements of "be"

### ISSUE THREAD

**Issue by jonorthwash** [UniversalDependencies/docs#1019]
In various Turkic treebanks, the verb _ol-_ / _бол-_ "be" is treated as a `VERB`, instead of `AUX` for copula constructions (see e.g. note at bottom of https://universaldependencies.org/tr/dep/cop.html).

There are a few reasons it was done this way, which I'm happy to get into.

But then how should complements of _be_ verbs be treated?

E.g. _Deniz doktor olacak_. "Deniz will be a doctor."

Is _doktor_ `xcomp` or `obj` of _olacak_ "will be"?

In UD_Turkish-BOUN these nominal complements are treated as `obj`.  Adjectival complemenets of _ol-_ are sometimes treated as `amod` (which definitely doesn't seem right to me) and sometimes as `obj`.

**Comment by jonorthwash** [comment]
A few examples from UD_Turkish-BOUN:
```conllu
22	gerçek	gerçek	ADJ	Adj	_	23	obj	_	_
23	olmayan	ol	VERB	Ptcp	Polarity=Neg|Tense=Pres|VerbForm=Part	24	acl	_	_
```

_gerçek_ means "true, real"

```conllu
12	doğru	doğru	ADJ	Adj	_	13	amod	_	_
13	olmadığını	ol	VERB	Ptcp	Aspect=Perf|Case=Acc|Number=Sing|Number[psor]=Sing|Person=3|Person[psor]=3|Polarity=Neg|Tense=Past|VerbForm=Part	8	conj	_	_
```

_doğru_ means "correct"

**Comment by dan-zeman** [comment]
`amod` is incorrect, even if _doğru_ means "correct" :-)

`obj` under something that is almost a copula does not seem right either.

We normally recommend `xcomp` for dependents of "to become" and other pseudo-copulas (secondary predication). So I would go with `xcomp` here, too.

**Comment by jonorthwash** [comment]
> We normally recommend `xcomp` for dependents of "to become" and other pseudo-copulas (secondary predication).

This is actually one of the reasons we annotate these verbs as `VERB` and avoid `cop` relations: they usually also mean "become".

> So I would go with `xcomp` here, too.

Thanks, that's what I was thinking, but I couldn't find anything in the docs.

**Comment by jonorthwash** [comment]
> `amod` is incorrect, even if _doğru_ means "correct" :-)
> 
> `obj` under something that is almost a copula does not seem right either.

Should an issue be filed against UD_Turkish-BOUN?

**Comment by dan-zeman** [comment]
> > `amod` is incorrect, even if _doğru_ means "correct" :-)
> > `obj` under something that is almost a copula does not seem right either.
> 
> Should an issue be filed against UD_Turkish-BOUN?

Yes, please.

**Comment by Stormur** [comment]
> > We normally recommend `xcomp` for dependents of "to become" and other pseudo-copulas (secondary predication).
> 
> This is actually one of the reasons we annotate these verbs as `VERB` and avoid `cop` relations: they usually also mean "become".

Just a side-question: is this meaning of "become" tied to particular TAME combinations?

**Comment by jonorthwash** [comment]
> Just a side-question: is this meaning of "become" tied to particular TAME combinations?

No, not really.  In fact, the example sentence above, _Deniz doktor olacak_, could be read "Deniz will be a doctor" or "Deniz will become a doctor".  Likewise, _Deniz doktor oldu_ could be read "Deniz was a doctor" or "Deniz became a doctor."  I think.

In a Turkic language with more explicit aspect marking (e.g., Central Asian Turkic languages, which use auxiliaries to do this, and even some have different morphology e.g. for imperfects), I think you do get some differences.  E.g., in Kyrgyz _Дениз доктур болуп калды_ would mean "Deniz became a doctor" and _Дениз доктур болчу_ would mean "Deniz was / used to be a doctor", without any ambiguity in translation between "become" and "be".

**Comment by jonorthwash** [comment]
> Likewise, _Deniz doktor oldu_ could be read "Deniz was a doctor" or "Deniz became a doctor." I think.

Perhaps a native speaker doesn't get the "Deniz was a doctor" reading.  This might be better expressed by _Deniz doktordu_ (with a defective copula verb, not the _ol-_ verb).  I defer to native speakers.

**Comment by jonorthwash** [comment]
> > > `amod` is incorrect, even if _doğru_ means "correct" :-)
> > > `obj` under something that is almost a copula does not seem right either.
> > 
> > 
> > Should an issue be filed against UD_Turkish-BOUN?
> 
> Yes, please.

Done.
