### ISSUE TITLE
Dative Subjects Saraiki

### ISSUE THREAD

**Issue by meesumalam** [UniversalDependencies/docs#1022]
We have sentences in Saraiki where the subject is experiencer not agent. I need guidance on the annotations I am working on for UD.
Eng: I am thirsty.
Eng(lit): me thirst affected[attached] is

1SG.Obl-Dat thirst[f]  attach.PP.SG.F Aux.Pres
میکوں[mainku] تریۂ[tareh] لگی[lagi] ہے[hai]

First Annotation:
```
1	میکوں	_	PRON	_	_	3	nsubj	_	_
2	تریۂ	_	NOUN	_	_	3	obj	_	_
3	لگی	_	VERB	_	_	0	root	_	_
4	ہے	_	AUX	_	_	3	aux	_	_
```
Second Annotation [this is what Punjabi treebank is also mentioned in the paper]
```
1	میکوں	_	PRON	_	_	3	obl:agent	_	_
2	تریۂ	_	NOUN	_	_	3	obj	_	_
3	لگی	_	VERB	_	_	0	root	_	_
4	ہے	_	AUX	_	_	3	aux	_	_
```

Please guide, 
if you have any questions please let me know.

Meesum

**Comment by dan-zeman** [comment]
I am assuming that a subject (= agent) of a primary transitive predicate (such as X hits/hurts/kills Y) would not take the dative form, right? Nor would the dative be used for the object (= patient) of a primary transitive predicate? Then the dative nominal is not a core argument and does not qualify as a subject in the UD framework, despite the fact that it may be traditionally called "logical subject" or "dative subject" in non-UD approaches. The analysis with `obl` (or a subtype thereof) seems thus to be the correct one.

On the other hand, if تریۂ _(tareh)_ "thirst" is in the nominative form and its gender / number / person is cross-referenced by the form of the verb, then it is the subject (`nsubj`) and not an object, regardless the semantic role. I think it is indeed the case — the glosses suggest that _tareh_ is feminine and the verb is in feminine singular form (regardless of the gender of the experiencer), plus the auxiliary _hai_ seems to be 3rd person singular (here I'm guessing based on similarity with Urdu/Hindi; I might be mistaken).

**Comment by dan-zeman** [comment]
Related old issue: https://github.com/UniversalDependencies/docs/issues/248

**Comment by meesumalam** [comment]
Thanks,

yes, the subject of transitive verbs does not take the dative form and same for the objects. 

Though the aux is same as in Urdu and Hindi, but it is not agreeing with the subject but providing the tense information (present in the given sentence). Based on my understanding of your comment it should be like :   

```
1	میکوں	_	PRON	_	_	3	obl:agent	_	_
2	تریۂ	_	NOUN	_	_	3	nsubj	_	_
3	لگی	_	VERB	_	_	0	root	_	_
4	ہے	_	AUX	_	_	3	aux	_	_

```

Please correct me if I misunderstood.

**Comment by dan-zeman** [comment]
> ... Based on my understanding of your comment it should be like :
> 
> 1 میکوں _ PRON _ _ 3 obl:agent _ _ 2 تریۂ _ NOUN _ _ 3 nsubj _ _ 3 لگی _ VERB _ _ 0 root _ _ 4 ہے _ AUX _ _ 3 aux _ _
> 
> Please correct me if I misunderstood.

Yes, this is how I would annotate the sentence – perhaps I would be just hesitant about the "`:agent`" in `obl:agent`, as it suggests a different semantic role than experiencer. But then we admit the same inaccuracy with passives (where the oblique "agent" does not necessarily have the proto-agent role), so it is probably OK here, too.

**Comment by meesumalam** [comment]
Thank you :)
