### ISSUE TITLE
Misidentified Lemmas in Spanish

### ISSUE THREAD

**Issue by qmalvido** [UniversalDependencies/docs#1023]
Using version 2.13 of the treebanks of Spanish AnCora.
In the file _es_ancora-ud-train.conllu_
__"tener"__ is erroneously identified as a lemma of __"que"__ in lines 222543, 439627, and 493566.
There are some additional mistakes in the lines immediately around the ones aforementioned.

**Comment by dan-zeman** [comment]
Thank you for reporting this. Fixed now in the dev branch.
