### ISSUE TITLE
acl vs xcomp vs advcl

### ISSUE THREAD

**Issue by nesor** [UniversalDependencies/docs#1026]
In https://universaldependencies.org/u/overview/complex-syntax.html#adnominal-clause-modifiers, "sad" in the sentence "She entered the room sad" is acl, not so far below in https://universaldependencies.org/u/overview/complex-syntax.html#secondary-predicates it is advcl. Perhaps the latter is correct, given this:

The result is that in She entered the room sad, sad is considered a modifier (not complement) of the verb, with the relation [advcl](https://universaldependencies.org/u/dep/advcl.html) instead of xcomp. (This was [changed](https://universaldependencies.org/changes.html#optional-depictives) from the previous approach which analyzed the secondary predication directly with [acl](https://universaldependencies.org/u/dep/acl.html), because the nominal predicand is not always overt, and even when it is, the adjective does not really belong to the same nominal phrase.)

**Comment by nschneid** [comment]
Whoops, will fix
