### ISSUE TITLE
Create treebank without syntactic dependencies

### ISSUE THREAD

**Issue by MateDideba** [UniversalDependencies/docs#1029]
For my master's research, I am developing a Georgian corpus annotated according to Universal Dependencies (UD) guidelines. I am curious if it is possible to submit the corpus to UD without annotations for syntactic dependencies.

**Comment by dan-zeman** [comment]
If it does not have syntactic dependencies, it is not a treebank – by definition :-) (the term treebank means that there are (dependency-syntactic) trees).

Any treebank released in UD is required to have at least the UPOS tags and the dependency relations (HEAD + DEPREL) verified manually, so the simple answer is no. It is true that there are "treebank" repositories in the UD Github space that currently contain only morphological annotation. Hopefully somebody will add syntax to them in the future and they will be included in the official release packages.

**Comment by MateDideba** [comment]
Thank you very much for your answer!
