### ISSUE TITLE
Some Broken or missing treebank links

### ISSUE THREAD

**Issue by Abhishek-P** [UniversalDependencies/docs#1033]
Making note of broken or missing treebank links in documentation that should be fixed

- [ ]  [IAHLT](https://universaldependencies.org/treebanks/he_iahltwiki/index.html) link is missing in Hebrew page
- [ ] Broken link for [Egyptian-Ujaen](https://universaldependencies.org/treebanks/egy_ujaen/index.html) in Egyptian page

**Comment by amir-zeldes** [comment]
Thanks for reporting - RE IAHLT I see this link [https://www.iahlt.org/](https://www.iahlt.org/) on the page you linked to, which seems to be working as of now - if there is still a non-working link, could you let me know where it is?

**Comment by dan-zeman** [comment]
> Thanks for reporting - RE IAHLT I see this link https://www.iahlt.org/ on the page you linked to, which seems to be working as of now - if there is still a non-working link, could you let me know where it is?

I suppose it is not about an existing nonworking link but about a nonexisting link that should be there - at the bottom of every [language index page](https://universaldependencies.org/he/index.html), there are links to the (automatically generated) treebank hub pages, but the links themselves are not automatically generated, so they are sometimes missing if a new treebank is added to the language.

**Comment by Abhishek-P** [comment]
Yes. That was it, I will make the fix and raise a PR for these, just wanted to make a list so, we could fix in bulk.

**Comment by Abhishek-P** [comment]
Sorry made mistake with the sync, posted new PR.
