### ISSUE TITLE
Repository for new treebank

### ISSUE THREAD

**Issue by MateDideba** [UniversalDependencies/docs#1041]
As part of my master's project at the University of Strasbourg, I have created annotations in UD format that I wish to upload to a GitHub repository. The project is not yet finished and is missing syntactic dependencies, but I wanted to have a repository already set up so I can continue working on it. The part-of-speech tagging and morphological annotations have already been completed in my corpus.

Best regards,

**Comment by dan-zeman** [comment]
This request is now being processed via e-mail.
