### ISSUE TITLE
docs site has stopped building

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#1047]
It looks like updates since July 9 have not been published.

I believe @dan-zeman is on vacation—is there anyone else with the power to fix this?

**Comment by AngledLuffa** [comment]
It doesn't appear to be a github action 🤷

**Comment by dan-zeman** [comment]
> It looks like updates since July 9 have not been published.
> 
> I believe @dan-zeman is on vacation—is there anyone else with the power to fix this?

Yes, I am on vacation. But I never had the power to fix this kind of issues. @fginter maintains the server that renders the pages.
