### ISSUE TITLE
Enhanced dependencies + ellipsis: Restoration of more than one verb

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/docs#1053]
It is my understanding that if clauses are coordinated and share the same elements, those can be omitted in the first and appear fully in the last such as:
>I keep the girl away from the fire and you keep the cat away from the water.

In Middle Persian, a verb-final language, this would result in:
>I the girl from the fire and you the cat from the water away keep.

UD only restores the verb here, which is counter-intuitive:
>I the girl from the fire (keep) and you the cat from the water away keep.

instead of:

>I the girl from the fire (away keep) and you the cat from the water away keep.

Are we allowed to restore more than the verb?
Note that one or more restore elements would then depend on the restored root and they would not be "conj" to the existing root (which is the example given in the UD documentation).

Consider also the following example:
> My father planned and built his house all by himself + my brother planned and built his house in the same way.

This would result in the Middle Persian structure: 

>My father his house all by himself planned and built and my brother in the same way.

Are we allowed to restore both verbs? I.e.:

>My father his house all by himself planned and built and my brother in the same way (planned and built).

Can we indicate each verb by a consecutive number? This means: "planned" as .1 and "built" as .2 ?

**Comment by amir-zeldes** [comment]
Yes, I agree there should be multiple ellipsis nodes in cases like this, and I don't think there's any rule against it. UD_English-GUM has quite a few cases like that, for example:

```CoNLL-U
1	Both	both	CCONJ	CC	_	2	cc:preconj	2:cc:preconj	Discourse=joint-other_m:45->43:2:_|Entity=(57-person-giv:inact-cf1-2,4-coref
2	Chao	Chao	PROPN	NNP	Number=Sing	6	nsubj:pass	6:nsubj:pass	Entity=(6-person-giv:act-cf2*-1-coref-Yuen_Ren_Chao)
3	and	and	CCONJ	CC	_	4	cc	4:cc	_
4	Yang	Yang	PROPN	NNP	Number=Sing	2	conj	2:conj:and|6:nsubj:pass	Entity=(51-person-giv:inact-cf5-1-coref-Buwei_Yang_Chao)57)
5	were	be	AUX	VBD	Mood=Ind|Number=Plur|Person=3|Tense=Past|VerbForm=Fin	6	aux:pass	6:aux:pass	_
6	known	know	VERB	VBN	Tense=Past|VerbForm=Part|Voice=Pass	0	root	0:root	MSeg=know-n
7	for	for	ADP	IN	_	10	case	10:case	_
8	their	their	PRON	PRP$	Case=Gen|Number=Plur|Person=3|Poss=Yes|PronType=Prs	10	nmod:poss	10:nmod:poss	Entity=(100-abstract-new-cf6-3-sgl(57-person-giv:act-cf1-1-ana)
9	good	good	ADJ	JJ	Degree=Pos	10	amod	10:amod	_
10	senses	sense	NOUN	NNS	Number=Plur	6	obl	6:obl:for	MSeg=sense-s
11	of	of	ADP	IN	_	12	case	12:case	_
12	humor	humor	NOUN	NN	Number=Sing	10	nmod	10:nmod:of	Entity=100)|SpaceAfter=No
13	,	,	PUNCT	,	_	14	punct	14:punct	_
14	he	he	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	6	parataxis	14.2:nsubj:pass	Discourse=elaboration-additional:46->45:0:ref-prs-474,486+sem-lxchn-484,493,496|Entity=(6-person-giv:act-cf2*-1-ana-Yuen_Ren_Chao)
14.1	was	be	AUX	VBD	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	_	_	14.2:aux:pass	CopyOf=-1
14.2	known	know	VERB	VBN	Tense=Past|VerbForm=Part|Voice=Pass	_	_	6:parataxis	CopyOf=6
15	particularly	particularly	ADV	RB	Degree=Pos	18	advmod	18:advmod	MSeg=particul-ar-ly
16	for	for	ADP	IN	_	18	case	18:case	_
17	his	his	PRON	PRP$	Case=Gen|Gender=Masc|Number=Sing|Person=3|Poss=Yes|PronType=Prs	18	nmod:poss	18:nmod:poss	Entity=(101-abstract-new-cf7-2-sgl(6-person-giv:act-cf2*-1-ana-Yuen_Ren_Chao)
18	love	love	NOUN	NN	Number=Sing	14	orphan	14.2:obl:for	_
19	of	of	ADP	IN	_	21	case	21:case	_
20	subtle	subtle	ADJ	JJ	Degree=Pos	21	amod	21:amod	Entity=(102-abstract-new-cf8-2-sgl
21	jokes	joke	NOUN	NNS	Number=Plur	18	nmod	18:nmod:of	Entity=102)|MSeg=joke-s
```

**Comment by dan-zeman** [comment]
In the first example, I would also restore _away_ although it is not directly the predicate. Maybe the Persian example should be added to the guidelines?

In the second example, I would restore both the verbs. Since they are predicates, this is even less questionable. I do not think we have been showing exactly this (coordination of verbs) but we definitely have examples where two verbs are restored because they are in `xcomp` relation _(Susan wants to go to Prague and Jane [wants to go] to Rome.)_

**Comment by bulbulistan** [comment]
Thank you both!
