### ISSUE TITLE
nor/CCONJ: Feature to indicate negation?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#1056]
English "nor" (and arguably, "neither" when paired with "nor") are coordinating conjunctions that express negation.

Should this be indicated in features? Neither the [`PronType=Neg`](https://universaldependencies.org/u/feat/PronType.html#Neg) nor the [`Polarity=Neg`](https://universaldependencies.org/u/feat/Polarity.html) docs mention CCONJ words as possible targets. The former uses phrasing like "negative pronoun, determiner or adverb" and "pronominal words"—is "nor" a pronominal word? If not, maybe `Polarity=Neg` is the right solution.

**Comment by amir-zeldes** [comment]
I think it's not PronType=anything because it's not a pronoun. As for Polarity=Neg, I'd be all for it, but as I recall, the Core Group voted against anything in English being Polarity=Neg except for "not" in UniversalDependencies/UD_English-EWT#526

So while I also definitely think Polarity=Neg is appropriate, it would also be appropriate for negation with "no", "non" as a token, and arguably morphological negation of adjectives within tokens (un-). But since it's been ruled on quite recently, I imagine the answer is still that it only applies to "not", making it a non-useful (not a useful?) feature in English - see the thread above for discussion.

**Comment by Stormur** [comment]
I do not see reasons not to annotate it and all other negative words with `Polarity=Neg`. What was the rationale for English treebanks?. But just as a comment, I notice that this feature is eschewed in more than one treebank.  

By the way, there is a big "confusion area" in the guidelines between `PronType=Neg` and `Polarity=Neg`. I remember that in the first times I had real difficulties in trying to wrap my head around them. But in the end, it appears that `PronType=Neg` does not really make sense (a pronoun etc. is always a type, and can also be negative), so I would not see it as an alternative.

**Comment by nschneid** [comment]
> I recall, the Core Group voted against anything in English being Polarity=Neg except for "not" in [UniversalDependencies/UD_English-EWT#526](https://github.com/UniversalDependencies/UD_English-EWT/issues/526)

`Polarity=Neg` is documented in English for both "not" and interjection "no": https://universaldependencies.org/en/feat/Polarity.html Determiner "no" is `PronType=Neg` (recall "PronType" is not literally just pronouns, but also pro-forms generally). The core group ruled out using `Polarity` for content lexemes (incl. those with derivational morphology), preferring to restrict it to the grammatical as opposed to lexical expressions of negation. Because "nor" is a function word I think it is fair game under this principle.

**Comment by amir-zeldes** [comment]
OK, happy to discuss it with the group and I'd definitely support more use of Polarity in English. Currently it's not useful at all IMO.

**Comment by nschneid** [comment]
The Core Group has no objection to `Polarity=Neg` for neither/CCONJ and nor/CCONJ. Updated the validator to allow it; still need to document and implement across treebanks.

**Comment by amir-zeldes** [comment]
What about as a determiner in "neither one"?

**Comment by nschneid** [comment]
That's PronType=Neg

**Comment by amir-zeldes** [comment]
Oh right!
