### ISSUE TITLE
[Middle Persian] How absolute is the rule [L3 Syntax right-to-left-conj] Relation 'conj' must go left-to-right?

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/docs#1057]
Middle-Persian is a head-final language, so we have many `conj` relations that go right to left and the validator script complains about them. I have also checked other head-final languages in [grew match](https://universal.grew.fr/), like Turkish and modern Persian and could not find any instances of `conj` going right to left.

On the other hand, there is the example in the [Turkish documentation](https://universaldependencies.org/tr/dep/orphan.html) which contains a clear instance of a right-to-left `conj`. So I am wondering, how absolute is the rule?

**Comment by ftyers** [comment]
Coordination is not a headed/dependency relation, so the relation must go left-to-right. However, if this is hard to teach to annotators. you could always have them do right-to-left and then flip the heads with a script before release. This is what we did with Kazakh.

**Comment by sylvainkahane** [comment]
@ftyers Francis, I really disagree with your statement that "coordination is not headed". Of course, there is a tradition of a symmetrical analysis of coordination. But it has been shown by several studies that coordination is in fact asymmetric (see "asymmetric coordination" on gg scholar). In "Mary and Peter", "and Peter" is a phrase, but not "Mary and". By this, we mean that "And Peter" can stand alone (Spk1: I invited Mary, Spk2: And Peter?), but not "Mary and", which will be considered as uncompleted. It is possible to have a double coordination "and Mary, and Peter", which also forces us to consider that "and Mary" is a phrase. We can add that it is common in English to have a sentence starting by "And" but it is impossible to end a sentence by "and". It will also difficult to defend a symmetrical analysis when the CCONJ is not between the two conjuncts (cf. Lat. "Senatus populusque Romanus") or when only one of the two conjuncts bears the case marker.

Note that in head-final languages the situation is reversed and the CCONJ forms a phrase with the first conjunct ([Mary and] Peter). In head-final languages you have sentences ending by a CCONJ but not sentences starting by a CCONJ. This is [what you observe in Beja](https://universal.grew.fr/?custom=66f4333e7846a) for instance. Clearly in head-final languages, the last conjunct is the head. It is why all people working on head-final languages have asked to suppress the constraint on `conj` being from left to right whatever the language. In our Beja treebank, we use `dep:conj` to avoid this constraint and to have a reasonable analysis.

**Comment by nschneid** [comment]
The [`conj` page](https://universaldependencies.org/u/dep/conj.html) is authoritative here regarding UD's approach:

> Coordinate structures are in principle symmetrical, but the first conjunction is by convention treated as the parent (or “technical head”) of all subsequent coordinated clauses via the conj relation.

There can be linguistic arguments for and against, but it is a well-established principle in UD at this point, so the validator will not accept a right-headed `conj`. @bulbulistan, thanks for pointing out the Turkish documentation page—it appears to be an error.

**Comment by dan-zeman** [comment]
> @bulbulistan, thanks for pointing out the Turkish documentation page—it appears to be an error.

Yes, it was an error. For some reason, the example also used the old `dobj` relation instead of v2 `obj`. I fixed it now in docs (although it has not yet propagated to the website).
