### ISSUE TITLE
Error while validating 

### ISSUE THREAD

**Issue by gracanunes** [UniversalDependencies/docs#1068]
Today (December, 4), every attempt to save annotations in my projects ( JUR_STJ and JUR_STF) results in validating error (Request failed with status code 500 X). Even so, the annotations are preserved. 
Yesterday, when leaving the project and then returning, I saw that the last modifications had been lost.

**Comment by dan-zeman** [comment]
Are these UD projects?

**Comment by gracanunes** [comment]
Yes
https://arborator.grew.fr/#/projects/JUR_STF
https://arborator.grew.fr/#/projects/JUR_STJ

**Comment by dan-zeman** [comment]
Ah, but you are not referring to a repository in the UD GitHub space, right? Problems with Arborator must be reported and resolved on the Arborator site, with the maintainers of that site.

This issue tracker is for discussion about the UD guidelines.

**Comment by gracanunes** [comment]
OK, I´m sorry. Thank you
