### ISSUE TITLE
miminal sentence count 

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/docs#1069]
Greetings

What is the minimal sentence count required for a treebank? Trying to submit for Tigrinya and possibly Oromo

Thanks!

**Comment by dan-zeman** [comment]
Hi Josiah, info like this is given in the [release checklist](https://universaldependencies.org/release_checklist.html). Concretely, "minimum requirement on treebank size: 20 sentences and 100 words (both numbers must be reached or exceeded; it shouldn’t be difficult to reach with a translation of the examples from the [Cairo Cicling Corpus](https://github.com/UniversalDependencies/cairo/blob/master/translations.txt))."
