### ISSUE TITLE
Guidelines for lemmas

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#115]
The UD documentation does not currently have detailed guidelines for `LEMMA` (see e.g. [format](http://universaldependencies.github.io/docs/format.html) and [morpho](http://universaldependencies.github.io/docs/u/overview/morphology.html) overviews).

While it's desirable to allow language-specific variation in guidelines for this field, having at least recommendation-level guidelines would help reduce arbitrary differences. This issue is for discussing the guidelines for lemmas.

**Comment by manning** [comment]
Closing as not currently active and not a clear bug. Reopen if more discussion needed?
