### ISSUE TITLE
Documentation for multiple treebanks for a single language (diff etc.)

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#116]
Both the presentation and the organization of the documentation source have until now implicitly assumed that there is a single body of documentation for each language and that treebank-specific documentation (such as "diffs" documenting when a treebank fails to follow the UD standard on some point) is found under the documentation for its language.

In particular, a number of treebank-specific diffs have so far been written into the general POS tag / feature / relation documentation for different languages. This is OK as long as there is one treebank per language, but becomes problematic when more than one is included for some language, as real-world treebanks will almost inevitably differ in some aspects of their annotation.

How should the documentation be organized -- both in terms of presentation and source documents -- when several treebanks are included in UD for a single language?

**Comment by manning** [comment]
It would be nice if the pull requests could be handled and this could be resolved....

**Comment by dan-zeman** [comment]
Since both the pull requests concern Finnish, @fginter & @spyysalo , could one of you please take care of them?

**Comment by fginter** [comment]
Done. We have used the style suggested by @manning as well, so this pull req should be compatible. I'll check and edit as needed. Also added @jpiitula as contributor so we don't need pull requests anymore.

**Comment by manning** [comment]
Thx!
