### ISSUE TITLE
Documentation of enhanced dependencies (e.g. xsubj)

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#119]
Should "enhanced" dependencies encoded in the `DEPS` field be documented similarly to "basic" dependencies? For example, if a language adds an "enhanced" `xsubj` dependency, should this appear along with other dependency types in the language-specific documentation, or be documented separately (where)?

We (Turku) would suggest to document these similarly to "basic" dependencies.

**Comment by msklvsk** [comment]
If I still want to differentiate `nsubj:x`/`csubj:x`, `nsubj:sp` for secondary predication, and `nsubj:rel` for relative clauses, where should I add the documentation for these relations? Is putting it alongside basic subtypes fine? e.g. `docs/uk/dep/nsubj-x.html`.

**Comment by dan-zeman** [comment]
I guess file-wise it is fine. But links to these files should lead from a separate section that is just about enhanced dependencies and makes it clear that these extensions are not used in basic dependencies, otherwise it may be confusing.
