### ISSUE TITLE
Language-particular repository naming

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#141]
I was wondering if it would be better to call the language-specific repositories something like UD_English or UD_Finnish rather than just "English".  The latter is a bit too general and under-informative once you have a checkout sitting on your hard disk....

**Comment by fginter** [comment]
That is a good idea. GitHub automatically maintains redirects for renamed repositories, so repos that have already been cloned will continue working. On a related note: how can we decrease the chance people will clone the repos and use whatever data is there, as opposed to grabbing the official release zip file? I mean, if google brings them into the GitHub project, they see all these juicy repos with the data, and assume that's what they are to use. Maybe the repos could have the latest official release in the master branch, and whatever ongoing work in a dev branch...?

**Comment by dan-zeman** [comment]
@fginter : This is exactly what Lindat is for: permanent link to the frozen data. But as a precaution, we should probably also follow your suggestion with the dev branch, if we have the need to put there anything at all. I mean, all sites probably have their primary versioning elsewhere,  and the diffs at Github are not available for large files anyway.
@manning : I'm OK with the renaming.

**Comment by fginter** [comment]
@dan-zeman: definitely, I only worry about people who land directly in the repo list and miss the main page of the project. I'll rename the repos later today if I don't hear any objections.

**Comment by fginter** [comment]
No objections -> repos renamed.

**Comment by nschneid** [comment]
(ignore the above commit, that should have referred to an issue in another repo)
