### ISSUE TITLE
Are we okay to remove the `data` repo?

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#142]
Does anyone know of a reason why we should not delete the `data` repo?

**Comment by spyysalo** [comment]
It's possible that someone may have committed new material there after the split to language-specific repos. If the language-specific repos have the latest content, I'd support simply deleting `data`.

**Comment by dan-zeman** [comment]
If someone has committed new material, they are probably able to commit it to the language-specific repos too. I strongly support deleting `data` to avoid confusion. (Previously I renamed the Czech data in `data` to OBSOLETE*, for the same reason.)

**Comment by fginter** [comment]
I think Irish may have had commits after the split into per-language repos. @tlynn747 - could you pls check the status, i.e. everything that's in `data` has been propagated into `UD_Irish`? Thanks!

**Comment by tlynn747** [comment]
Everything in UD_Irish is now up-to-date.

Thanks
Teresa

2015-01-14 5:37 GMT-06:00 Filip Ginter <notifications@github.com>:

> I think Irish may have had commits after the split into per-language
> repos. @tlynn747 <https://github.com/tlynn747> - could you pls check the
> status, i.e. everything that's in data has been propagated into UD_Irish?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UniversalDependencies/docs/issues/142#issuecomment-69904318>
> .
>



-- 
*Slán agus Beannacht*

**Comment by fginter** [comment]
Thanks. The `data` repository has been deleted now. I have a full copy locally just in case.
