### ISSUE TITLE
Validation errors (Release 1)

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#143]
I added lists of UD relations and CPOS tags into the validator and ran `validate.py --noecho` on all the datasets currently in the language-specific repos. I am seeing quite a few validation errors. The most common cases are `_` values in these two columns. Also, there is some noise in the CPOS (eg DT for DET, ITJ for INTJ).

**Comment by ryanmcd** [comment]
On Wed, Jan 14, 2015 at 12:02 PM, Filip Ginter <notifications@github.com>
wrote:

> I added lists of UD relations and CPOS tags into the validator and ran validate.py
> --noecho on all the datasets currently in the language-specific repos. I
> am seeing quite a few validation errors. The most common cases are _
> values in these two columns. Also, there is some noise in the CPOS (eg DT
> for DET, ITJ for INTJ).
>
Perhaps the "_" case comes from the CoNLLU format?

1 Producto _ NOUN _ _ 15 nmod _ _
2-3 del _ _ _ _ _ _ _ _
2 de _ ADP _ _ 4 case _ _
3 el _ DET _ _ 4 det _ _
4 fin _ NOUN _ _ 1 nmod _ _

These tokens do not necessarily have tags/labels I believe.

**Comment by fginter** [comment]
Right! I'll modify the SW to allow these selectively.

**Comment by fginter** [comment]
With the fixed version of the validator Czech, Finnish, Spanish validate. English, French, Hungarian,  Irish, and Swedish do not. I am currently checking only the universal relations and CPOS against the UD lists. I'll try to have a language-specific support ready later today.

**Comment by ryanmcd** [comment]
Thanks Filip. I will fix the French data (one instance of PRT).

**Comment by fginter** [comment]
Hi. I added a `--lang` option to the validator. Currently it specifies which language-dependent relations are allowed. Run with `--lang=cs` etc. The lists are in data/deprel.XX and I gathered them from the data (i.e. the validation is a no-op now :) I checked their occurrence counts and it looked okay except for Irish, where `xcomp:prep` has only a single occurrence.  Please edit these files at will.

**Comment by msimi** [comment]
Hi, could you tell me where to find the validator?
I would like to run it on the Italian data before publishing them.

--- Maria

**Comment by spyysalo** [comment]
@msimi : the validator is available from https://github.com/universaldependencies/tools .

**Comment by fginter** [comment]
Hi. It is in the `https://github.com/UniversalDependencies/tools` tools repository. If you want it to validate correctly also the relation types, please add the file `data/deprel.it` which lists the Italian-specific relations and then run with `python validate.py --lang=it`.

**Comment by tlynn747** [comment]
Will fix these errors in the finalised version of the data - due to be completed in the next week or so.

Thanks for highlighting.

**Comment by fginter** [comment]
Hi. Just a tally of where we are at the moment: `cs, fi, fr, es` validate, `en, hu, ga, sv` do not. To validate your dataset, run `python validate.py --noecho --lang=xx file.conllu` where `xx` is the code of your language. Currently, language-specific deprels are being checked and their source is in `data/deprel.xx` under tools. To turn off checking the deprels against the lists, run with `--no-lists`.

**Comment by msimi** [comment]
Thank you. I was able to validate the Italian data. 

I noticed that the ordering of morphological features is checked after reducing to lowercase, even if the features are in mixed case.
If this should be so (but I find it a little bit awkward) it may be worthwhile to add this aspect to the documentation when talking about canonical ordering of features.

It is not the same ordering. For example:
'NumType' < ‘Number'
while
'NumType'.lower() > 'Number'.lower()

— Maria

**Comment by spyysalo** [comment]
@msimi : this is an intended part of the format specification, documented at http://universaldependencies.github.io/docs/format.html#morphological-annotation as follows:

> features should as far as possible be selected from the universal feature inventory and be sorted alphabetically by attribute names. [...] In sorting, uppercase letters are considered identical to their lowercase counterparts

Suggestions on how to clarify this are very welcome!

**Comment by msimi** [comment]
Sorry, that is very clear indeed. I was reading the documentation here:
http://universaldependencies.github.io/docs/u/overview/morphology.html <http://universaldependencies.github.io/docs/u/overview/morphology.html>

— Maria

**Comment by dan-zeman** [comment]
I clarified the other piece of documentation (morphology.html). Thanks for pointing that out.
