### ISSUE TITLE
Small website suggestions for v1.0

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#145]
A couple of little website suggestions that I think it would be great to fix. :)

1. If you go there for the first time – and we're now expecting more newcomers – I think it is less clear than it could be where to start. Two alternative ways of dealing with that would be: a) Put a little item with yellow background after "Introduction to Universal Dependencies" saying something like "Newcomers start here" or b) Add an "About" item on the very top row. I think people often look for something like that on the top row of site items, but none of ours address a newcomer.  (The information is obviously there, I think it just doesn't stand out where to begin at present.)

2. The list of contributors on the Introduction page doesn't correspond to the list at the end of @jnivre's recent message. Inter alia, it misses Cristina Bosco, Richárd Farkas.

**Comment by spyysalo** [comment]
Missing contributors added in 56f9ffdbaa97505ccd86b27e67cdfa0bdb3fb5ad, tentatively closing as resolved.
