### ISSUE TITLE
Layout of UD syntactic relations table

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#146]
Hi Sampo, if sometime you're filled with energy and love, I think the UD dependencies table would be a little nicer if you swapped the positions of "Coordination" and "Case-marking, prepositions, possessive".

That way, `case` would be in a cell next to `mark` and we mainly have a verb dependent row and a noun dependent row at the top of the table (even though a few things in the noun-dependent row, like `compound` can be used with other heads, so it's not quite that simple).  And the "Coordination" relations would be next to the "Loose joining relations", with which they share most, and you are often choosing between.  So, I just think it's a slightly more natural organization.

**Comment by dan-zeman** [comment]
+1
(but I'm afraid it means writing a script that changes all current languages, and changing the script that adds a new language)

**Comment by dan-zeman** [comment]
Closing. This issue seems obsolete now that 1. the table has been upgraded to v2; 2. the documentation is being reworked with much less focus on these tables.
