### ISSUE TITLE
UPOS vs. UFeatures

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#147]
Some people share direct links to the description of the universal POS tagset, and they are disappointed that it does not cover "everything". They overlook that there are also the universal features. I had to explain this twice in the last week.

Would anyone object if I put a link from the UPOS page to the UFeatures page? I hope it could satisfy at least some of the potential users.

**Comment by manning** [comment]
Sounds good to me.

**Comment by dan-zeman** [comment]
ok, done
