### ISSUE TITLE
English token/POS tag escaping?

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#148]
@jnivre questioned whether we should still be escaping parentheses as "-LRB-" etc. in the words and fine-grained POS tags (following LDC conventions) or moving to just using "(". We should decide what is best here. I think this escaping was a dumb convention, but there would now be a fairly high inter-operability cost among tools to abandon it. Happy to get opinions on which seems best! (From @slavpetrov, @ryanmcd, @yoavg ... or anyone else!)

**Comment by spyysalo** [comment]
+1 for dropping these escapes, they are unnecessary in CoNLL-U and can be easily introduced if necessary when converting to other formats.

**Comment by dan-zeman** [comment]
+1 for dropping them from word forms. I do not see the interoperability cost. Yes, some formats (Penn bracketing) need to escape "(", and some tools may be used to it. Some other tools want to see the real token, so if converting between "-LLB-" and "(" is a measurable cost at all, it has always been there.

Not sure whether we have to do the same with the POS tags. You could say that -LLB- was the tag for the "(" token. But then again, the tags in the fifth column are out of the reach of the UD standard, hence you decide how they are defined :-)

**Comment by slavpetrov** [comment]
I am several months late, sorry about that. I am also in support for
dropping the escaping (of both tags and tokens). This has caused me more
trouble than it has helped for anything. Some tools might have to be
updated (e.g. tokenizers) but I think we will be better off in the long run
without the escaping.

**Comment by spyysalo** [comment]
This is assigned for "later", but as it seems there's consensus on dropping PTB-style escapes and implementation is technically trivial, perhaps this could still make 1.1?

**Comment by jnivre** [comment]
This is clearly for the UD_English team to decide, but I would strongly advocate dropping the PTB-style escapes. As far as I know, no other language uses anything similar, and for applications like cross-lingual learning it would clearly be convenient to be able to assume that identical punctuation marks really are identical across languages.

**Comment by manning** [comment]
We have unescaped the tokens back to ( and ) now!  So, I'm going to close this issue. At present, the language-particular tags are still -LRB- and -RRB-. It's less clear to me whether we should change those.
