### ISSUE TITLE
Wrong dependencies inside Czech MWEs

### ISSUE THREAD

**Issue by e-bej** [UniversalDependencies/docs#150]
In complex prepositions ("na rozdil od", "ve srovnani s", ...), each non-first word should depend on the first word. But it is not the case, e.g. in sentence no. 2314 in dev-test (search for "širokorozchodnou") or in sentence no. 2846 ("investovaly").

Edit: "its left neighbour" -> "the first word", as @jnivre pointed out. Thanks.

**Comment by jnivre** [comment]
There seems to be some confusion here. According to the general guidelines, all non-first elements in an MWE should depend on the first element, not its left neighbor. Or have I misunderstood something here?

**Comment by dan-zeman** [comment]
Yes, @jnivre is right. But there definitely is a bug and the sentences mentioned by @e-bej do not adhere to either of the rules. I am looking into it.

**Comment by e-bej** [comment]
@jnivre: Thanks for your comment, I updated the description. As @dan-zeman has already said, the bug is there anyway.

**Comment by dan-zeman** [comment]
I found and fixed the bug in our data processing pipeline (Treex r14659). It should be OK in the next release of the data.
