### ISSUE TITLE
Unclear how to reconcile token and sub-token annotation

### ISSUE THREAD

**Issue by reckart** [UniversalDependencies/docs#153]
I have looked into implementing a reader and writer for CoNLL-U for DKPro Core, but I have some doubts regarding the format specification. The examples below come from the CoNLL-U format specification and documentation.

*Example 1*

    3-4    al        _
    3      a         a
    4      el        el

I assume this snippet means that the document text contains "al" and not "a el" - so when reading this, "al" is what I would like to interpret as document text. So "a" and "el" would become annotations on the "al" text span. However, as it is, it is impossible relate the subtokens to offsets in the main token, e.g. information that "el" corresponds to the "l" in "al". So I suppose I can only ignore the subtokens. But then hits the next problem that most annotations are not available on the main token, e.g.:

*Example 2*

    2-3   haven't   _      _       _     _                                 _   _
    2     have      have   VERB    VB    Number=Sing|Person=1|Tense=Pres   0   root
    3     not       not    PART    RB    Negative=Neg                      2   neg

The documentation says that it is easy to extract an approximation like this:

*Example 3*

2     haven't   _      VERB    _     Negative=Neg|Number=Sing|Person=1|Tense=Pres   0   root

but it does not specify any annotation-independent rules on how to do that... and it loses information. I believe format alone does not contain enough information to condense Example 2 to Example 3.

So I suppose my questions are: 
* are there any (tagset-independent) rules to aggregate sub-token annotations to the token-level?
* would it be feasible to extend the format to allow sub-tokens to refer to offsets within the main token, e.g.

```
2-3   haven't   _      _       _     _                                 _   _
2(0-4)     have      have   VERB    VB    Number=Sing|Person=1|Tense=Pres   0   root
3(4-7)     not       not    PART    RB    Negative=Neg                      2   neg
```

**Comment by spyysalo** [comment]
> would it be feasible to extend the format to allow sub-tokens to refer to offsets within the main token

In previous discussion (e.g. #110) the consensus has been that the general case cannot be solved. Quoting @jnivre from (a quote in) that issue:

>  it is a fundamental assumption that words do not have to be recoverable from the tokens by segmentation. [...] The only thing we assume is that a token may correspond to more than one word, but the nature of the mapping is (and should be) left unspecified.

> This is not just a technical nuisance, it is an important theoretical issue. With all due respect for agglutinating languages, concatenation is not the only process by which complex word forms can be formed. Assuming that the beginning and end of words correspond to character offsets in tokens is simply not a valid assumption in the general case. All we can say is that the token “vamonos” somehow contains the two words “vamos” and “nos”, occurring in that order. (Some people would even question the assumption that they occur in an ordered sequence, but I don’t think we need to go that far.)

**Comment by reckart** [comment]
@spyysalo I see the point. Another case where this is hardly solvable would be "à" in Portuguese which is a concatenation of "a a" ("to the"). 

Looking at the example you provided, for morphological features a simple concatenation might be viable. For the POS, I suppose one could use the POS of the head element in the sub-tokens, provided that dependencies are available. Is that roughly what you had in mind when stating that token-level annotations can be extracted from the sub-token annotations? Maybe any additional rules?

**Comment by spyysalo** [comment]
I'm afraid I don't have a general algorithm -- the text isn't mine, and I'm working on a language (Finnish) where this is basically a non-issue -- so I'll defer to others (@jnivre?) on this point.

**Comment by dan-zeman** [comment]
I suspect there is no general, language-independent algorithm. The heuristics I would suggest are:

  * If one subtoken is a head on which all other subtokens depend (directly or indirectly), then use the UPOS, HEAD and DEPREL of this head for the whole token.
  * Otherwise, if they have a common parent, this will be naturally also the parent of the whole token. One of the subtokens must be chosen as the main one, and the whole token will get UPOS and DEPREL of the main subtoken. There is no general rule as to how the main token should be chosen. We should design a rule for every type of fused token we encounter. In some cases, the rule will be applicable to multiple languages. For instance, one type would be "preposition+article" and it would cover German zum, French aux and Spanish al, among others. And the rule might say that in these cases, the whole token should be treated as preposition.
  * At the moment I am not aware of examples where the subtokens do not even have a common parent. But if they do, it is no more difficult than the previous example. Quite likely we want to identify the main subtoken that will represent the whole.

**Comment by jnivre** [comment]
I implemented a heuristic conversion in the first validation script. I am not sure what Filip has done with this after he took charge of the validator, but it should be available somewhere. There can definitely be cases where the two subwords of a token do not have the same parent, so the conversion will always be heuristic. Character offsets are not used in UD and wouldn't help with the conversion anyway as far as I can see. :)

**Comment by fginter** [comment]
The original code is in this commit https://github.com/UniversalDependencies/tools/commit/98f6cfc1220d93c1f6bbe16305fd9412e172b2b4 and the original heuristic seems to be here https://github.com/UniversalDependencies/tools/blob/98f6cfc1220d93c1f6bbe16305fd9412e172b2b4/conll-u.py#L36 Transferring this into a separate script for manipulating (validated) conllu files is on the TODO. :)

**Comment by spyysalo** [comment]
Proposing to close as no issue remains, feel free to reopen if you disagree.
