### ISSUE TITLE
Feedback words as non-roots

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#155]
I found twenty-something sentences in the Swedish treebank that have the following basic structure:

Yes, we have applied for membership.

My automatic converter produced:

root(ROOT, Yes)
parataxis(Yes, applied)

But I changed this to:

root(ROOT, applied)
discourse(applied, Yes)

Do people agree with this treatment? If yes, I can write a "specific construction" section about this type of sentence, which should occur in many language. If no, we have an issue. :)

**Comment by dan-zeman** [comment]
I agree with the treatment, which means we have an issue in Czech :-) In PDT, this is sometimes analyzed as coordination ("Yes" is one conjunct, the rest the other) and sometimes as parenthetical ("Yes" is attached as ExD_Pa to the predicate of the following clause). The latter is closer to the proposed treatment but it also seems to be the less frequent of the two. I have not investigated what my automatic converter produces for this, but I doubt it is what we want.

**Comment by manning** [comment]
I also agree that using discourse is best here. 

(Though the parataxis analysis isn't untenable. Presumably it is what you should get for "I agree, we should apply for membership.")

**Comment by jnivre** [comment]
I agree. The parataxis analysis would imply that "yes" is treated as a clause in itself, or as a zero-place predicate, which is plausible semantically but somewhat less plausible syntactically. Let's go for discourse then. Unless there are more comments, I will close this issue and write something for the specific construction documentation.

**Comment by jnivre** [comment]
I have added feedback words to the documentation of specific constructions, under a new heading "Clause-external elements" (for lack of a better term). I am now closing this issue.
