### ISSUE TITLE
Numbers and letters used to index items in itemized lists

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#156]
Imagine a list of sentences (or just of phrases) where each item has a letter or a number instead of just a bullet character:

Entry will not be granted unless:
a) The person is an EU citizen.
b) His/her passport will not expire during the next six months.

How should we tag the "a" (and "b"), where should we attach it and what the relation label should be?

The POS tag is not `PUNCT` because it is an alphanumeric character. (Note that bullet characters are punctuation, at least according to the note that appears in documentation of `SYM`.) And I was not able to identify the appropriate dependency relation. Perhaps `discourse`? But its description mentions interjections in the first place.

Note: #106 dealt with a different aspect of lists.

**Comment by jnivre** [comment]
I checked the Swedish treebank and what comes out of the automatic conversion is _nummod_ for "1." but _nmod_ for "a)". This is basically because "1." is tagged as a numeral and "a)" as a noun. Seems somewhat arbitrary and perhaps not what we want.

**Comment by manning** [comment]
These kind of list structures occur quite a bit in the English Web Treebank, and we have discussed them. The one thing that seems very clear is that the content and not the marker of each item should be the head. De facto, we have also been using _nummod_ – regardless of whether it is numerals or roman numerals or letters – for the dependency. But, we don't want to make a strong argument for that. It just seemed the least bad thing to do by the time we discussed this case, after the UD 1.0 dependency set was frozen.  

(That is, earlier we had introduced the `list` dependency to have something for organizing the items of lists and had started using `appos` for joining the items of key-value pairs in lists like "Name: Stuart Smith", but it seemed like these couldn't also be `appos`, and they are a form of numbering, so, it seemed the least bad choice at the time.  Better suggestions for the future welcome!  But we probably do want to be careful about introducing too many extra relations for paralinguistic elements.)

**Comment by jnivre** [comment]
I agree that using _nummod_ consistently is better than differentiating on the basis of form. I will try to implement this in the next version of the Swedish data -- unless we think of something better first.

**Comment by jnivre** [comment]
Quick follow-up: What do you do with bullets and dashes in lists without numbering (itemize vs. enumerate)?

**Comment by msimi** [comment]
Why not use a generic “dep” or “sym” for both numbered (numbers, letters) and unnumbered (bullets, dashes) list markers?

— Maria

**Comment by jnivre** [comment]
There is no syntactic relation _sym_ (only a postag SYM). I suppose _dep_ could be an alternative, although this should be used as restrictively as possible.

**Comment by manning** [comment]
Bulleted lists: There don't actually seem to be clear cases of that in the corpus that I could find ... if only because they didn't make it through LDC pre-procesing. But based on similar things that do happen, I imagine they might have become SYM/punct. It's arguable whether that is right, though. You might want to regard it as definitional that PUNCT are punct and SYM are non-punct.

**Comment by manning** [comment]
More discussion may be needed here, but I think we have an interim solution for the original question, so closing this for now.

**Comment by dan-zeman** [comment]
Thanks, a bit late but I agree with the solution and will try to implement it as well.

As for the bulleted lists, we actually do not have directly the Unicode bullet character in PDT, but I think thre are dashes ("-") or asterisks ("*") with the same function. And these naturally get tagged PUNCT. ("*" could be also a SYM in other contexts, if the PDT tagset had the corresponding tag. But I'd prefer PUNCT/punct and I take it this is the current approach. Let's open a separate issue, if people find this to be an issue.
