### ISSUE TITLE
Cleft sentences

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#162]
Are there any guidelines on how to annotate cleft sentences like:

It is clefts (that) I am talking about.
It is only now that I realize they are a problem.

In the automatic conversion of the Swedish treebank, these end up being analyzed with the copula as the root, the focus element as "dep" and the rest as a relative clause. For the first example above this becomes:

root(ROOT, is)
nsubj(is, It)
dep(is, clefts)
acl:relcl(clefts, talking)

This is probably not what we want, for several reasons. How do people deal with these in other languages?

**Comment by dan-zeman** [comment]
I *think* we would get the following analysis if it was in PDT:

root(ROOT, clefts)
nsubj(clefts, It)
cop(clefts, is)
acl(It, talking)

I would find this analysis OK, despite the non-projectivity. I don't have a real example, though. I don't expect this to occur in huge numbers (perhaps even less than in English because the free word order gives us other means to shift the focus).

**Comment by jnivre** [comment]
Why would you attach the acl to "It". I think "It" is an expletive, as it would be also in Swedish (which is another problem with the automatically produced conversion). I think the one that is most compatible with the rest of our guidelines is something like:

root(ROOT, clefts)
expl(clefts, it)
cop(clefts, it)
acl:relcl(clefts, talking)

Possibly, there should be a special subtype of acl for this.

**Comment by dan-zeman** [comment]
cop(clefts, it) is a typo, it should be cop(clefts, is), right?

Attaching the clause to "It" is how some similar situations are analyzed in PDT. We do not distinguish expletives of this sort. (There are occurrences of the pronoun _to_ “it” that are redundant and they get a special dependency label. But they are different, they do not replace the subject.)

**Comment by jnivre** [comment]
Yes, it's a typo.

**Comment by jnivre** [comment]
For v1.1 I adopted the following analysis for Swedish:

It is clefts that I am talking about

root(ROOT, is)
expl(is, It)
dislocated(is, clefts)
acl:relcl(clefts, talking)

This is a slight abuse of "dislocated", since "clefts" is not a dislocated dependent of "is" but rather of the predicate or the relative clause ("talking about clefts"). However, it is a convenient way of specifying that this dependent has to be interpreted elsewhere. And by following the path: acl:relcl -> nmod, we can figure out how to interpret it.

I am closing this issue for now. We may want to reopen it later.

**Comment by fosterjen** [comment]
Cleft constructions are very common in Irish and in keeping with our analysis of all other Irish copular constructions we analyse them as  COP PRED SUBJ.

So, for 

_It is clefts that I am talking about_

we have

_cop(clefts, is)_
_csubj:cleft(clefts, talking)_

Note that we don't have the equivalent of the expletive "It" in Irish clefts. For version 1.1, we are introducing a subtype of csubj called csubj:cleft.

We realise this analysis is quite different to the ones that have been proposed. We'll revisit the issue again for the next release.

**Comment by jnivre** [comment]
It seems that there are variations in cleft constructions across languages, and you analysis makes sense for Irish. It might be worth putting together a subgroup to work out guidelines for how to deal with these in different languages.

**Comment by yuvalpinter** [comment]
With regards to POS tagging, would this make the `is` an AUX?

**Comment by jnivre** [comment]
Yes. The current guidelines for AUX say: "The class AUX also include copulas (in the narrow sense of pure linking words for nonverbal predication)."
