### ISSUE TITLE
Prepositional phrases and adverbs as predicates with copulas?

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#163]
@jnivre mentioned in #161: “now that the previous exception involving prepositional phrases has been eliminated...” I remember we have discussed this somewhere but I could not find the relevant issue to reference from here.

My conversion of the Czech treebank (PDT) uses the `cop` relation for the instances of the verb _to be_ that have a `Pnom` argument (meaning “nominal predicate”) in the original treebank. This includes nouns, pronouns, adjectives and passive participles in nominative or instrumental. It does not include adverbs and prepositional phrases. So for instance in the Czech equivalent of _my daughter is in the office,_ _is_ is not a copula. It is analyzed as a main verb expressing existence of the subject at a given point in space and time, and the prepositional phrase _in the office_ just further specifies parameters of this existence.

Am I understanding correctly that this is not how the same sentence is analyzed in English UD? If so, @hajic, do we want to change our conversion or at least the guidelines? It would mean that _to be / být_ is almost always auxiliary or copula — unless there is no argument that we could promote as the predicate. I'm personally in favor of keeping the current approach, i.e. mapping between `Pnom` in PDT and `cop` in UD.

**Comment by hajic** [comment]
Well if it is the case that for English & others, then we have to do it, too. (Seems of course weird to promote just about any word to be a predicate - even Russian which does not use copulas in Pnom-like constructions uses other verbs for locations ("nakhohdjitsya") and other adverbials - but if that's the least weird way "on average" across languages, then why not.) 

Jan

**Comment by dan-zeman** [comment]
Well, Russian actually could omit the verb, I guess ("он в школе" = lit. "he in school" is still grammatical, isn't it?)

What I find really weird about it is that I would lose the parallelism between the following sentences within one language:

* _Dan je uvnitř._ “Dan is inside.”
* _Dan se nachází uvnitř._ lit. “Dan finds himself inside.”, meaning “Dan is inside.”
* _Dan zůstává/stojí/sedí/čeká... uvnitř._ “Dan stays/stands/sits/waits... inside.”

**Comment by jnivre** [comment]
This is discussed in the LREC paper and it is explicitly stated that the new treatment of prepositional phrases allows us to analyze these sentences in a parallel fashion:

She is nice
She is an idiot
She is in shape

Now, when it comes to adverbs and prepositional phrases denoting locations, one can discuss whether "is" is still a copula, or whether it is the existential "is". And if a language uses a different verb for these, then that is evidence not to use the copula analysis. But otherwise, the general guidelines as of UD v1 is that copulas can never be heads (except through promotion by elision). This is why I was puzzled by the contradictory statements about the clause case.

**Comment by jnivre** [comment]
I will add the examples from the LREC paper to the documentation for "cop" and close this issue.

**Comment by jnivre** [comment]
Added the example "Sue is in shape" to the documentation for cop and close the issue.

**Comment by dan-zeman** [comment]
OK, thanks. I will update the Czech guidelines so that the verb in the Czech equivalent of "to be in shape" is a copula, while in locational phrases it is not.

**Comment by hajic** [comment]
OK, I agree. Thanks! 

-- Jan
