### ISSUE TITLE
Formatting and structure of the specific syntax section

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#165]
http://universaldependencies.github.io/docs/u/overview/specific-syntax.html

The page is already quite long and it may still grow. Should we perhaps

* split it to multiple pages corresponding to current sections
* the main page would be just an index of specific problems, i.e. it would be somewhat similar to the index of dependency relations, only the scope of individual problems would be larger than just a single relation
* the new pages focusing on individual problems would be cross-linked between languages (including only languages where the same problem arises), similarly to how tags, features and relations are cross-linked now

?

**Comment by spyysalo** [comment]
I guess we'll want to split it eventually, but as this will make it more difficult to add new entries, perhaps we should split late rather than early -- I believe many contributors know how to edit, but not add new pages to a collection.

How about adding a TOC for the time being?

**Comment by dan-zeman** [comment]
That is absolutely right.
Is there any automated way of adding and maintaining a TOC, or should I just create it manually?

**Comment by spyysalo** [comment]
Just manually, I'm afraid.
