### ISSUE TITLE
Changelog in README

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#173]
It would be nice to document what has changed in each dataset from one release to the next. To encourage a consistent way of providing this documentation, I propose to add the following to the [release checklist](http://universaldependencies.github.io/docs/release_checklist.html) after the "*The README file should minimally contain ...*" list:

> For previously released corpora, the README file should also include a "[changelog](http://en.wikipedia.org/wiki/Changelog)" section summarizing changes between versions e.g. as follows
>
>```
>Changelog
>
>2015-05-15 v1.1
>
>    * Added lemmas
>
>    * Corrected tokenization in sentences 123 and 456
>```

**Comment by dan-zeman** [comment]
Good suggestion.

**Comment by spyysalo** [comment]
Thanks! If there are no objections, I'll add this in tomorrow.
