### ISSUE TITLE
Within-sentence discourse relations

### ISSUE THREAD

**Issue by yoavg** [UniversalDependencies/docs#174]
@rtsarfaty and me are working on finalizing the Hebrew version. And have some cases we'd like to consult about. The first has to do with marking within-sentence discourse relations:

In many cases, one S sentence contains several S sentential clauses with some rethoric relation between them (sometimes also maintaining anaphors that tie the sentences together):

-John walked, he fell. (Temp ordering)
-John hit a wall, he fell. (Cause relation)
-John hit a wall, the wall is a part of a big construction site. (Elaboration)
-John hit a wall, he hits one wall every day (...)

Many times, these two S elements are also separated by parataxis:

-John walked, we saw; he fell.

And there can be a sequence of more than two, with discourse connectors:

-John walked, he saw us, and then, surprisingly, he fell.

Now, clearly UD do not intend to provide a discourse relations annotation scheme -- but what is the generic relation between such S elements? One possibility is conjunction, though this discourse level conjunction is very different from standard NP conjunction or PP conjunction.

How would you annotate it? How did you handle such cases in your data?

**Comment by spyysalo** [comment]
[`parataxis`](http://universaldependencies.github.io/docs/u/dep/parataxis.html) should apply at least to some of these.

**Comment by dan-zeman** [comment]
In PDT, some of these would be `parataxis`; the rest would be coordination of clauses.

**Comment by yoavg** [comment]
@dan-zeman , how do you decide which is which? 

We also thought of marking it as `conj`, but note that the current guidelines state the `conj` relation is for elements connected by a coordinator (and, or, but) -- which is not the case here.

**Comment by dan-zeman** [comment]
Sorry, I was a bit too vague here. PDT has a flag for "parenthesis", which would be used for injected phrases such as  "I think" in "He is now at home, I think, sitting and waiting for us." My current converter will turn the parenthesis flag to `parataxis`.

The rest is likely to end up as coordination of clauses. Comma (or other punctuation) is also a coordinator, if there is no conjunction word. This is primarily the approach taken from PDT, but even the UD 1.0 guidelines (http://universaldependencies.github.io/docs/u/dep/conj.html) admit that there are asyndetic coordinations that lack the coordinating conjunction.

On the other hand, apparently some people's position here is that some of the loosely connected clauses should be labeled `parataxis` (http://universaldependencies.github.io/docs/u/dep/parataxis.html, the "bearded dragons" example). But frankly I do not attempt to distinguish these from coordination. In the current Czech data they'll remain connected using `conj`.

**Comment by yoavg** [comment]
We'll probably also go with the `conj` relation, which seem more correct here. (For Hebrew, we will probably end up marking it as `conj:discourse` or something similar to distinguish it from coordinating conjunctions.
