### ISSUE TITLE
Conjunctions of modifiers

### ISSUE THREAD

**Issue by yoavg** [UniversalDependencies/docs#175]
In the Hebrew constituency tree bank, which is our source, we have the following peculiarity. In a sentence like (sent 1 in the tb)

- the workers traveled from Israel to Thailand 

The two PP phrases are simply modifiers of "traveled". But in:

- the workers traveled from Israel to Thailand, and from there to the US.

We have a nested conjunction : "from Israel to Thailand" conjoins PPs, "from there to the US" is another PP conjunction, and we have a conjunction relation between these two conjunctions.
But then the question to ask is, if we want to be consistent, then in the simpler case shouldn't "from Thailand to Israel" be a conjunction as well? Clearly this marks a certain non-arbitrary construction of modifiers.

Reflections/suggestions on how to solve these cases in a consistent way would be welcome.

**Comment by dan-zeman** [comment]
I would say that the first analysis (two modifiers of _traveled_, no `conj`) is correct and should be applied also in the second sentence. Then the orphaned modifiers in the second clause of the second sentence (with missing verb) should be attached to their counterparts using the `remnant` relation:

remnant(Israel, there)
remnant(Thailand, US)

I am not sure whether it is doable to recognize these cases and transform them automatically. If not, then the Hebrew documentation should have a Diff section saying that while the abovementioned solution would be correct, the current data deviate from it.
