### ISSUE TITLE
Appositions in German

### ISSUE THREAD

**Issue by GHWally** [UniversalDependencies/docs#180]
Dear all,

I have a problem with the annotation of the following German noun phrases:

meine Tante Klara (my aunt Klara)
das Thema Arbeitslosigkeit (the topic unemployment)
der Milliardär Ross Perot (the billionaire Ross Perot)

nmod(Tante, meine)
??(Tante, Klara)

and

drei Gläser trockener Rotwein (three glasses (of) dry red wine)
ein Sack Reis (a bag (of) rice)
eine Tüte gerösteter Kastanien (a bag (of) roasted chestnuts)

nummod(Gläser, drei)
amod(Rotwein, trockener)
??(Gläser, Rotwein)

canoo.net [0] calls these constructions appositions: 
The first one is called close apposition in contrast to wide apposition (the president of Germany, Joachim Gauck, ...).
The second one is called partitive apposition.

I believe that this phenomenon does not occur in English as extensively as English always needs the preposition between the nouns. I guess I could introduce subclasses of appos, e.g. appos:close and appos:partitive, but I don't want to extend the label set if it is not necessary. On the other hand, it doesn't feel right to call it simply appos instead and nmod would mark it as optional. How do you solve this in the other languages?

And one additional thought: concerning the partitive appositions, I would normally annotate the measure noun (Gläser in drei Gläser Rotwein) as the head, as this is the noun that morphologically agrees with a verb in subject position. But semantically, one could argue that the second noun carries more content.

If this has been discussed before, could someone point me to the right place?

Thanks for your help
Wolfgang

[0] http://www.canoo.net/services/OnlineGrammar/Satz/Satzgliedbau/Nomen/Apposition.html?lang=en

**Comment by dan-zeman** [comment]
The genitive (partitive) modifier is a `nmod` and yes, _Gläser_ is the head:

nmod(Gläser, Rotwein)

We have the same in Czech and it's in other languages too. The analysis is parallel to other genitive modifications that do not have the partitive interpretation, such as _drei Gläser meines Vaters_.

As for _meine Tante Klara_, I would do:

det(Tante, meine)
nmod(Tante, Klara)

Here both nouns (Tante and Klara) agree in case, gender and number, which makes them much closer to apposition than the genitive modification above. But at least in the Czech data, we do not annotate this as `appos`. We understand apposition as a post-modification marked by punctuation, for example

_Klara, meine Tante, wohnt in dieser Stadt._ “Klara, my aunt, lives in this city.”

**Comment by GHWally** [comment]
> Am 12.05.2015 um 15:20 schrieb Dan Zeman <notifications@github.com>:
> 
> The genitive (partitive) modifier is a nmod and yes, Gläser is the head:
> 
> nmod(Gläser, Rotwein)
> 
> We have the same in Czech and it's in other languages too. The analysis is parallel to other genitive modifications that do not have the partitive interpretation, such as drei Gläser meines Vaters.
> 
okay, I kind of see why nmod would make sense here. Especially if it makes it comparable to Czech and the other languages. The problem in German is that in most cases, the second noun is not going to be in genitive case, but will normally be in nominative case or it may agree with the first noun. These things depend on whether the first noun is singular or plural, or whether the second noun is modified by an adjective or not.

> As for meine Tante Klara, I would do:
> 
> det(Tante, meine)
> nmod(Tante, Klara)
> 
> Here both nouns (Tante and Klara) agree in case, gender and number, which makes them much closer to apposition than the genitive modification above. But at least in the Czech data, we do not annotate this as appos. We understand apposition as a post-modification marked by punctuation, for example
> 
> Klara, meine Tante, wohnt in dieser Stadt. “Klara, my aunt, lives in this city.”
> 
Here I'm less convinced. I agree that it is not normal apposition as in your example. But there is no requirement that Tante und Klara must agree in case, number, and gender.
In the example 

Unser Gast redet über [das Thema Arbeitslosigkeit] (Our guest talks about the topic unemployment)

Thema is in accusative case as governed by the preposition über, but Arbeitslosigkeit is nominative case.
It's the same in 

Ich sehe das Haus meiner Tante Klara (I see the house of my aunt Klara)

Here, Klara stays nominative case, but Tante is in genitive case now.

**Comment by dan-zeman** [comment]
I see your point. If the agreement were a formal requirement for `appos`, then this would actually be a sign that we should indeed use `nmod` instead of `appos`. But you're right there is no such requirement. And even I mentioned agreement only because it was my immediate impression that this would hold for the appositions in the Czech data... I would have to check that.

Now we do have the equivalent of das Thema Arbeitslosigkeit in Czech, and it is an `nmod`, not `appos`. I am not claiming that this is the only possible interpretation of the UD guidelines. It is a legacy of the PDT annotation style in the first place. But one which I agree with, and which would require specialized heuristics should we separate it from the other nmods.

**Comment by yoavg** [comment]
Fwiw, in the Hebrew Treebank we opted to mark the "my aunt Kalara" case as appositive, regardless of whether it has a comma between `aunt` and `Klara` or not.

**Comment by GHWally** [comment]
I guess, I'll go with nmod for both cases for now. I think It should in principle be possible to change the annotation later.
Thanks for the help!

**Comment by jnivre** [comment]
This one seems ready to be closed, even though there is a discrepancy between the Hebrew and the Czech (and German?) annotation that needs to be discussed at some point. Just as a piece of information, Swedish traditional grammar also uses the notion of apposition more widely:

The city Stockholm
Stockholm, the largest city in Swedish

The traditional analysis would say that "Stockholm" is the head in both cases, and that city is a "fixed apposition" (cf. narrow) in the first case and a "loose apposition" (cf. wide) in the second. It is highly probably that we imported this from the German tradition.

**Comment by manning** [comment]
For the record in case anyone comes here, as noted in #415, the advice here is no longer the preferred UDv2 structure which would use `flat` for _der Milliardär Ross Perot:_

det(Milliardär, der)
flat(Milliardär, Ross)
flat(Milliardär, Perot)
