### ISSUE TITLE
Feature ordering to reflect the order of morphemes?

### ISSUE THREAD

**Issue by esolak** [UniversalDependencies/docs#183]
We are working on adapting the UD framework to Turkish dependency parsing.

The UD guidelines dictate an alphabetical ordering of the features in CoNLL-U format. As features  correspond more or less to morphemes, this ordering would loose the information contained in the ordering of the morphemes in the inflection of the surface form of a word. However, in Turkish, the ordering of the inflection groups have an effect on the dependency relations. So if we use solely the features (with POS and token itself) in training the models, alphabetical ordering seems a bit odd.

Here is an example to illustrate the problem:

"masadakilerin", that which belongs to the ones at the table
masa-da-ki-ler-in
table.LOC.REL.PLU.GEN

and

"masanınkilerde", at the ones that belong to the table
masa-nın-ki-ler-de
table.GEN.REL.PLU.LOC

have the same set of morphemes, in different order. Thus, their feature sets are exactly the same. Moreover their main POSTAGs are both NOUN.

One solution would be to embed the morpheme order within the language specific CPOSTAGs use them in training but this seems to go counter the idea of having a universal set of morphological features.

Another odd situation arises when we have multiple occurrence of the same morpheme in a production as in

"masalardakiler" - the ones at the tables
masa-lar-da-ki-ler
table.PLU.LOC.REL.PLU

Here we would have to have two number features with the same value, Number=Plur, among the set of features.

So I was thinking if the feature ordering might need to be introduced in the future versions of the UD format.

**Comment by yoavg** [comment]
Can you provide an example on how the ordering (or the doubling) of morphological information affect the dependency relations?

**Comment by miguelballesteros** [comment]
well that depends on whether you take the whole set of features as a single string or not... most people split them into a set of values using the delimiter |, but you can always use the whole string as a feature. 
See MaltParser for instance, you can either Split(InputColumn(FEATS, Input[0]),\) or  simply InputColumn(FEATS, Input[0]).

**Comment by esolak** [comment]
Elaborating on the examples above, a simple pair could be

masadakilerin gördüğü kitap - the book that the ones at the table saw
table.LOC.REL.PLU.GEN see.PART.P3SG book.NOM

Here, the a dependency arrow is from "gördüğü" to "masadakilerin" and its label would be "nmod" as the first two words form a GEN-POSS construction.

For the second one;

masanınkilerde gördüğü kitap - the book that he saw at the ones belonging to the table
table.GEN.REL.PLU.LOC see.PART.P3SG

Again, the dependency arrow goes from the second word to the first one. But this time, I would label it as "advmod" as the first word, adverbially modifies the root verb "see".

Sorry, if these examples seem a bit contrived. I hope I can come up with simpler examples soon.

**Comment by jnivre** [comment]
There is a long discussion about Turkish inflectional groups in issue #125 (recently closed). I think the point here is that we need to split the tokens into multiple "words" (corresponding to inflectional groups). Each unit will then have its own (unordered) set of features. An alternative is to use layered features, but that doesn't seem like the right thing to me here.
