### ISSUE TITLE
possession expression

### ISSUE THREAD

**Issue by CatalinaMaranduc** [UniversalDependencies/docs#186]
In Romanian we have a lot of forms for possession expressing.
Cartea Mariei. (Mary's book) - a noun in genitive case.  (1)
Cartea ei (her book) - a personal pronoun in genitive case (2)
Cartea sa (her book) - a possessive determiner (3)
Cartea-i (her book) - a personal pronoun in dative case (4)
Cartea-și (her book) - a reflexive pronoun in dative case (5)
Și-a pierdut cartea (she lost her book) - a reflexive dative possessive pronoun subordinate of the verb (6)
I-a pierdut cartea (he lost her book) - a personal dative possessive pronoun subordinate of the verb (7)
Can I mark all the possessive forms in some way?
(although all may have special values, such as ”she is the author of the book”)
in (1), (2), (4) and (5) can I mark ”Maria”, ”ei”, ”i”, ”și”  as nmod:poss?
in (3) ”sa” is a det, the possessive resulting from the annotation of part of speech. 
in (6), (7) can I mark this sense language specific as iobj:poss ?

**Comment by CatalinaMaranduc** [comment]
Arguments for interpreting (6), (7) as iobj:poss = they are core dependencies of verb; the verb cannot have another iobj besides that with possessive value, and this value is often interpretative..

**Comment by dan-zeman** [comment]
Marking (1), (2), (4) and (5) as `nmod:poss` sounds good to me and this label has been used in several other languages (en, fi, fr, es, sv – see http://universaldependencies.github.io/docs/ext-dep-index.html).

And I like the analogy of `iobj:poss` for (6) and (7) too.

**Comment by jnivre** [comment]
This sounds good to me too, but I think the general division between "det" and "nmod:poss" should be discussed at some point. I think we have an inconsistency across languages in that some use "det" and some use "nmod" (with or without ":poss") for possessive determiners/pronouns ("my book" and similar).

However, this particular issue seems to be resolved, so I'll close it.
