### ISSUE TITLE
Apposition

### ISSUE THREAD

**Issue by gcelano** [UniversalDependencies/docs#190]
Hi all,

I am wondering whether there is an "agreed-on" way to annotate a that-clause like the following:

"I read books for this reason, that I get smarter"

or similarly

"I love this, that you respect everyone" 

Thanks

**Comment by tdozat** [comment]
I think this is a place for the [`dislocated`](http://universaldependencies.github.io/docs/u/dep/dislocated.html) relation:

"I read books for this reason, that I get smarter"
dislocated(reason, smarter)

"I love this, that you respect everyone"
dislocated(respect, this)

**Comment by jnivre** [comment]
Dislocation can definitely be used, but note that the dislocated element should be attached to the verb, that is, to the governor of the element that it doubles for.

If you want to have it attached to the noun/pronoun, you would have to use acl, I think, but this would be a non-prototypical use of that relation.

**Comment by gcelano** [comment]
The dislocated relation is appealing. In German, however, I see that a sentence such as

Da kann man darüber hinwegsehen, dass es außerhalb der Aachener	City liegt	

is annotated as ccomp(hinwegsehen, liegt), even though I would say that the dass-clause "explains"  darüber (so I would take this example as similar to the ones I made). 

My English sentences were actually fictitious examples to show what happens in Ancient Greek, which is in this respect very similar to German.

What about acl? This seems to me to be a more suitable candidate.

**Comment by gcelano** [comment]
Hi Joakim, I see your answer only now! It would be interesting to know how this phenomenon has been annotated for other languages.

**Comment by jnivre** [comment]
Hmm ... I wonder how to search for such examples in the existing treebanks. 

It is clear that acl should be used for the following similar cases:

I read books for the reason that I get smarter.
I love the fact that you respect everyone.

**Comment by gcelano** [comment]
Maybe acl is the best solution. In "the reason that", the that-clause explains "reason" and is focal, which is similar to what happens in "I read the books for this reason, that ...". The dislocated element seems to be more of a topical nature.

**Comment by dan-zeman** [comment]
Seems like this issue can be closed. Before doing so, just a note on that German sentence by @gcelano :

_Da kann man darüber hinwegsehen, dass es außerhalb der Aachener City liegt_
[en] Here can one about-the-fact ignore that it outside the Aachen City lies.

I agree that the clause modifies _darüber_ and not the verb. I have seen a few treebanks (Czech for sure but I believe there were more) where you would have acl(darüber, liegt). However, in the examples I am talking about, there is a pronoun in place of _darüber_, i.e. the `acl` relation makes sense as an analogy to clauses modifying nouns. The trouble here is that _darüber_ is adverb, and adverbs normally do not get `acl` modifiers, so I would probably go for `advcl` instead. (Note that there could be a noun phrase instead, such as _da kann man über den Fakt hinwegsehen, dass ... liegt_; then we would have acl(Fakt, liegt).
