### ISSUE TITLE
Ellipsis in comparison

### ISSUE THREAD

**Issue by daghaug** [UniversalDependencies/docs#192]
Is there a standard way of treating ellipsis in comparisons where two elements (but not the verbs) remain in the comparative clause? The guidelines mentions cases where the verb in the comparison clause remains ("as much flour as the recipe *called* for") or cases where only one element remains ("he plays better drunk than *sober*"). In these cases there is a clear element that can be promoted to `advcl`. But what if two arguments remain? This is a not infrequent pattern in Latin. One example is literally "could not reach the same ports which the others [reached]". "which the others" is an elliptical clause with a subject and an object but no verb. It seems arbitrary to promote one of the two to serve as the head of the comparative clause.

**Comment by dan-zeman** [comment]
Ellipsis needs more attention in the future versions of the standard. I guess you could use the `remnant` relation for this. Not sure whether it has been used in comparisons elsewhere.

**Comment by daghaug** [comment]
I thought about using `remnant` but that misses the point that "which the others" elaborates on "same" as in other comparison constructions.

I am converting the PROIEL treebank (Ancient Greek, Latin, Gothic, Classical Armenian and Old Church Slavic) to UD. The source representation has explicit empty nodes. So I am just going to eliminate those using `remnant`for now, and then I can change my conversion if and when the standard evolves.

**Comment by jnivre** [comment]
Sounds good to me. I will close this issue for now, but ellipsis definitely needs to be revisited more generally, as suggested by Dan.

**Comment by manning** [comment]
Agreed. I think our attempted method of avoiding empties via the remnant relation is in retrospect not fully successful....  Good discussion topic for the meeting in September.
