### ISSUE TITLE
Fronted relative clauses with empty copula in Kazakh

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#193]
Hey there!

In Kazakh there is a structure like:

    Шашы       ұзын     қызды     көрдім.
    Hair.3SG   long     girl.ACC  see.PAST.1SG

    "I saw the girl whose hair is long."

You could analyse this as having an empty copula acting as a relativiser between "long" and "girl", where the dependency structure would be:

    subj(ұзын, Шашы)
    cop(ұзын, -)
    acl(қызды, ұзын)
    obj(көрдім, қызды)
    root(-, көрдім)

But as the copula never surfaces in this construction in Kazakh (not in any person, though it appears in other tenses for 3rd person only, e.g. Шашы ұзын болатын қызды көрдім. "I saw the girl whose hair will be long."), this would break the lexical-rule. However, in other Turkic languages (e.g. Turkish) you find the copula here:

    Saçı        uzun    olan        kızı           gördüm.
    Hair.3SG    long    be.REL      girl.ACC       see.PAST.1SG

    subj(uzun, Saçı)
    cop(uzun, olan)
    acl(kızı, uzun)
    obj(gördüm, kızı)
    root(-, gördüm)

So we were thinking of maintaining this structure in Kazakh, but just dropping the null copula. Does anyone else have any suggestions ? Particularly, is our analysis for Turkish what would be expected in UD ? (It diverges somewhat from the METU treebank analysis of this structure).

**Comment by dan-zeman** [comment]
Your Turkish analysis is what I would do in UD (except that the label for nominal subject is `nsubj`). And I would do the same thing in Kazakh, as the two sentences are almost perfectly parallel, only the copula (a leaf node) is missing in Kazakh.

BTW, does the `.3SG` tag in your example mean that there is a possessive suffix (“her hair”)?

**Comment by jonorthwash** [comment]
Yes, the `.3SG` tag (which is `px3sg` in our analyser) indicates a possessive suffix.

**Comment by makazhan** [comment]
Should we emphasize relativeness, i.e.:
acl:relcl(қызды, ұзын)
acl:relcl(kızı, uzun)

**Comment by dan-zeman** [comment]
Well, at the moment it is optional and up to you. It is one of the most widely applied "language-specific" relation but some languages/treebanks do not use it (yet) even though relative clauses exist in those languages. Perhaps it is better to do it (use `acl:relcl`) unless you have reasons against it (e.g. you are converting an existing corpus and the distinction is not readily available there).

**Comment by jonorthwash** [comment]
Maybe we should note that the Turkish way of doing this type of relative clause is the way Kazakh usually does relative clauses that modify nouns—i.e., with a verb phrase where the last verb has been made into a verbal adjective.  In these cases, I suppose the main verb (whether it's last or not, since an auxiliary could have the verbal adjective morphology) would have an acl relation to the noun it modifies.  It seems a little weird to have an acl relation between a noun and an adjective, but since there's a copula involved, it makes some sense.

**Comment by coltekin** [comment]
The sentence without *olan* works in Turkish too: 
```
Saçı      uzun   kızı      gördüm.
Hair.3SG  long   girl.ACC  see.PAST.1SG
```
For me, this would be more natural (unless I want to say something like '(of those three girls) I saw the girl with long hair').

**Comment by manning** [comment]
These answers look right to me. The optionality or non-appearance of the copula in many constructions in many languages was one of the key reasons for trying to avoid it being the head.
