### ISSUE TITLE
Coordinating clausal and non-clausal modifiers

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#195]
I can't find this in the documentation on conjunction, so will bring it up here. In Turkic languages (and in many other language families) it is possible to coordinate clausal modifiers with non-clausal modifiers. For example:

Verbal adjective:

        Арық   және  тез   жүгіретін   спортшылар   жақсы көремін.
        adj     cc   adv   v.adj       n.pl         v.pres.1sg
        Skinny and   fast  running     athletes     I.like             
       "I like athletes who are skinny and run fast."
    
Here "арық" is an adjective (so it should get amod) and "тез жүгіретін" is a verbal adjective clause -- kind of like a relative clause in English (acl). When you coordinate them, should the final relation (to "спортшылар" athletes) be amod or acl ? (The order of the conjuncts could easily be inverted with the same meaning).

Verbal noun:

        Би     билегенді     және    тойларды   ұнатамын
        n      v.noun.acc    cc      n.pl.acc   v.pres.1sg
        Dance  dancing       and     parties    I.like
       "I like dancing and parties."

Here "би билеуді" (dance dancing) is a verbal noun in accusative which is like a clausal complement (ccomp) and "тойларды" (parties) is a normal noun in the accusative (dobj). 

Verbal adverb:
    
        Тапсырманы   тез    және    ешкімден   көмек   сұрамай     жазыңыз!
        n.acc        adv    cc      prn.abl    n       v.neg.adv   v.imp.2pl
        Exercise  quickly and noone.from  help  not.asking  write!
       "Do the exercise quickly and without asking anyone for help!"
    
Here "тез" (quickly, advmod) is coordinated with "ешкімден көмек сұрамай" (without asking anyone for help, advcl).

So in these cases, are there guidelines for what the relation between the head conjunct and the word it depends on should be ?

**Comment by dan-zeman** [comment]
Good point. Unfortunately, the Stanford style of coordination (which is what we use in UD) cannot express that each conjunct has a different relation to the parent of the whole coordination. At least not using the _basic_ dependencies.

I would use the relation that is appropriate for whatever is the head conjunct. Then I would add an _enhanced_ dependency in the `DEPS` column. It would go from the parent of the coordination to the other conjunct and it would have the other relation label.

**Comment by jnivre** [comment]
I agree with Dan. Use the appropriate relation for what happens to be the head and add the other info in the enhanced dependencies. This touches on a more general issue, which has been discussed before, namely the fact that Stanford relations (often) specify both the function to the head and the form of the dependent. In this particular case, one would like to abstract over the latter and simply say that the relation is "modifier of noun" (or perhaps simply "modifier"). But with the current guidelines, this is not possible.

**Comment by manning** [comment]
I agree too. That is what we do. The role is determined by the head. In the enhanced dependencies, the correct role can be shown for each conjunct (though in practice for our software, at present we only do that for `nsubj`/`nsubjpass`).
