### ISSUE TITLE
"at least": MWE, or not?

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#202]
There seems to be an inconsistency in UD 1.1 English. The phrase _at least_ is sometimes analyzed as `mwe(at, least)`, sometimes as `case(least, at)`. Could it be done consistently? Which one is correct? Or are there context-based reasons to distinguish the two analyses?

To see examples, you may go to http://lindat.mff.cuni.cz/services/pmltq/ud_en/query and try the query

  `a-node [form="least"]`

or

  `a-node [form="least", child a-node [form="at"]]`

or

  `a-node [form="at", child a-node [form="least"]]`

**Comment by sebschu** [comment]
We do indeed treat _at least_ in two different ways depending on the context.

If it is not used for quantities, e.g. in _At least I like dogs_, then we treat it as a MWE.

If it is used with a quantity, e.g. in _She has at least two dogs_, then we analyze it as `case(least,at)`.

This is also documented at http://universaldependencies.github.io/docs/en/dep/mwe.html

**Comment by dan-zeman** [comment]
Oh, thanks. I found it so surprising that I did not even bother to look for this example in the documentation.
