### ISSUE TITLE
Copulas in Czech

### ISSUE THREAD

**Issue by ptakopysk** [UniversalDependencies/docs#207]
Various things are marked as copulas in Czech. The prototypical copula is 'být', and there can be other verbs, but the non-být cases should really be looked upon, as many of them are e.g. nouns, etc.
https://lindat.mff.cuni.cz/services/pmltq/ud_cs/query
`a-node [deprel = 'cop', lemma != 'být']`

**Comment by dan-zeman** [comment]
Permanent link to the search query: http://hdl.handle.net/11346/PMLTQ-OMDL
See also: http://bionlp-www.utu.fi/dep_search/?search=%28%21VERB%29+%3Ccop+_&db=UD_Czech-dev

**Comment by dan-zeman** [comment]
Note also this general issue about copulas: https://github.com/UniversalDependencies/docs/issues/170#issuecomment-209994648

**Comment by dan-zeman** [comment]
Most of the cases turned out to be annotation errors in PDT 3.0. Fixed in UD 1.3.
