### ISSUE TITLE
web site language links don’t work on chromium with https everywhere extension

### ISSUE THREAD

**Issue by flammie** [UniversalDependencies/docs#209]
If I open the https://universaldependencies.github.io/docs/ on my chromium, none of the language links work. In address bar there's a shield icon telling me: https://support.google.com/chrome/answer/1342714?hl=en-GB

This may confuse some of the users. It may be caused by https everywhere extension I have installed though.

**Comment by dan-zeman** [comment]
I confirm that this happens in Windows Chrome 45.0.2454.85 m, but only if you use the HTTPS protocol instead of plain HTTP. So it probably is caused by the extension in your case, although in theory other users may decide to use HTTPS even without the extension. ( @spyysalo may know how to avoid the issue; I don't )

**Comment by spyysalo** [comment]
Thanks for the report!

Replicated on Chrome 47.0.2503.0 canary, which gives console messages like the following:

```
Mixed Content: The page at 'https://universaldependencies.github.io/docs/u/pos/index.html'
was loaded over HTTPS, but requested an insecure stylesheet
'http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic&subset=latin&effect=smoothing'.
This request has been blocked; the content must be served over HTTPS
```

Switching to HTTPS for all `<link>`s might work.

**Comment by sebschu** [comment]
You can also omit the protocol name, e.g. "//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic&subset=latin&effect=smoothing".

The browser will then load the font via http or https depending on the protocol of the embedding site.

**Comment by spyysalo** [comment]
@sebschu : thanks, I didn't know about that!

1c8bea3082b70b48f9f4d68385799e9b2f2632a6 implements the `https://` option, but feel free to switch if the protocol-relative form is preferred.

Works for me now. @flammie, could you please check and close if the original issue is resolved?

**Comment by flammie** [comment]
Seems to work, thanks.
