### ISSUE TITLE
new front page (please read - you need to edit your readmes)

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#216]
Hi all,

@spyysalo @jnivre @dan-zeman @mcdm @fginter spent some time behind the scenes preparing a new frontpage for the UD site, sporting a "treebanks at a glance" table. This is something which was raised in Uppsala, namely that there is not a good overview of all the UD treebanks and the tab interface does not do the trick. This, we hope, will be an improvement.

The data for the table is gathered from two places: 1) the conllu files for all counts etc and 2) a machine-readable section of the readme files for every treebank (which I pre-filled and committed). This section is documented [here](http://universaldependencies.github.io/docs/language_metadata.html) (don't worry it's very very simple) and as far as I can tell, there is only one column right now that definitely needs your attention, namely data source, which is either `automatic conversion`, `automatic conversion + manual check`, or `native UD annotation`. Only you know, so please go to your readme, and fill that value. While you are at it, update anything else you see.

The table will now be updated every few hours or so, but ultimately the updates will be live. Bear with us.

As always, report any problems. We're sure few things got broken. Pre-empting an obvious feedback: We are currently working on getting the browser "Back" button functioning properly. :)

Hope you like the new table. :)

F

**Comment by manning** [comment]
Looks great! 

Question: Should we define the boundary better between "automatic conversion + manual check" vs. "native UD annotation".  Many, many treebanks used pre-labeling tools plus manual correction and refinement.  E.g., the Penn Treebank.  Which would it count as?  Specifically for our English UD, if it was done by starting with an SD conversion but then humans went through the whole thing, does that count as "native UD annotation"?

**Comment by jnivre** [comment]
Good idea. I think it should count as native UD. Perhaps we should say something like:

automatic = completely automatic, no manual check except for basic sanity checks

automatic + manual = automatic + some form of systematic manual validation (for example, some specific construction types all through the corpus, but not sentence by sentence and word by word)

native UD annotation = every sentence has been checked manually (regardless of whether a converter, parser or whatever was used to create the first version)

Another option would be to change the terminology to something like "automatic", "semi-automatic", "manual".

**Comment by fginter** [comment]
> Another option would be to change the terminology to something like "automatic", "semi-automatic", "manual"

That sounds very good

**Comment by dan-zeman** [comment]
+1

**Comment by dan-zeman** [comment]
If every sentence has been reviewed by a human, then I believe it counts as "native UD annotation". Preprocessing is just an annotation tool, even if it involves a parser. It makes the job of the human annotator easier but it does not take the responsibility from them. 

Dan

**Comment by fginter** [comment]
Do I go ahead and replace the strings to "automatic" "semi-automatic" and "manual" in all readmes?

**Comment by jnivre** [comment]
Fine with me.

**Comment by fginter** [comment]
Done.
