### ISSUE TITLE
Docs master branch should be removed

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#217]
I see a sporadic activity in the `master` branch of the docs, and someone seems to be merging `pages-source` into it occasionally, but it is now some 300 commits behind. As far as I know, nothing should be going on there, and we should all be editing the `pages-source` branch. I suggest `master` be removed to avoid mishaps.

**Comment by spyysalo** [comment]
related: http://stackoverflow.com/a/17396552

**Comment by fginter** [comment]
I think @ftyers may have been the last one touching `master`. I'll wait a day or two and if I see no objections, I will wipe it.

**Comment by ftyers** [comment]
Yeah, that was my mistake, I merged into the wrong branch (git newbie here). No complaints from me to remove it.

**Comment by fginter** [comment]
No prob, @ftyers. The very existence of this branch in `docs` is confusing. I wiped it now.
