### ISSUE TITLE
Negative=Yes vs. Negative=Neg

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#218]
I originally meant to create this issue at the UD_Finnish repository but then I realized it applies to UD_Finnish-FTB too. The Finnish treebanks use a language-specific value `Negative=Yes` while the universally available values are `Neg` and `Pos`.

I understand that there is no use for `Negative=Pos` in Finnish. It is used in some languages where certain parts of speech systematically mark or do not mark negativeness. It is definitely not necessary to mark everything non-negative as `Pos`. But: is there a reason to use the `Yes` value instead of `Neg`? I now that by dropping `Pos` the feature has become binary and for features that are binary on the universal level we use `Yes`. But I would like to "annotate the same thing same way in all the languages", as we always proclaim, and I tend to believe that `Negative=Neg` and `Negative=Yes` are actually the same thing.

The Finnish documentation (http://universaldependencies.github.io/docs/fi/feat/Negative.html) does not even mention the `Yes` value so people will probably assume that there is one of the universal values. Similarly, if the Finnish teams insist on keeping `Yes`, it should be added to the language-specific overview here: http://universaldependencies.github.io/docs/ext-feat-index.html

(NB: I am now myself not 100% convinced that we need `Negative=Pos`. It is a legacy of some tagsets that systematically distinguish negative and affirmative. But that would be a discussion for the next version of the universal standard, while language-specific features can be modified earlier.)

**Comment by spyysalo** [comment]
A quick look at the converter code suggests `Negative=Yes` is generated from OMORFI `SUBCAT=Neg` for verb forms other than participles (which have `PartForm=Neg`) and further that only forms of the negation verb _ei_ have this feature. (http://universaldependencies.github.io/docs/fi/feat/Negative.html agrees.)

I'm inclined to agree that `Negative=Neg` and `Negative=Yes` are the same. Given that it's a binary feature, one could agree that `Negative=Yes` is the more consistent choice, but I have no problem going with `Negative=Neg`.

A confirmation would be nice, though; @fginter, @jmnybl do you remember this? (note: we seem to have discussed this in https://github.com/TurkuNLP/UniversalFinnish/issues/89, and it's distinct from https://universaldependencies.github.io/docs/fi/feat/Connegative.html)

**Comment by yoavg** [comment]
Negative=Pos sounds very weird to me. Perhaps we should consider at some
point to change this to Polarity=Neg/Pos ?

**Comment by fginter** [comment]
I found that discussion in https://github.com/TurkuNLP/UniversalFinnish/issues/89 as well. This does seem like a bit arbitrary departure from the UD standard, so I guess it would not hurt to replace these using a perl one-liner. But of course we then need to remember to update the parsing pipeline as well.

**Comment by dan-zeman** [comment]
@yoavg : I agree that `Negative=Pos` sounds weird. The feature used to be called `negativeness`, and `negativeness=pos` sounds a little bit less weird to me, but still weird. I think that years ago the value was `aff` (for _affirmative_, instead of _positive_) and I do not remember the reason why it was changed to `pos`.

`Polarity` is not bad. If we decide to go for it in the future, then `Pos` will be IMHO better value than `Aff`.

Unfortunately, unlike adding new features/values, renaming is an unpopular measure that has a large potential to break tools and stored data, while the benefit is only aesthetical (speaking from experience). I am not strictly against renaming, but I think we should not hurry with that. And we should gather other candidates, so that if we rename anything at all, we try to do the changes at once.

**Comment by spyysalo** [comment]
+1 for making UD Finnish conform, +1 for making renaming a separate issue

**Comment by dan-zeman** [comment]
Thanks, @spyysalo ! I am leaving this issue open for now, feel free to close when it is done.

I started a new issue #219 about renaming, to keep this one about Finnish.

**Comment by fginter** [comment]
I removed Negative=Yes from the validator data, so now Finnish doesn't validate. That will keep reminding us. :)

**Comment by dan-zeman** [comment]
Both Finnish treebanks have been fixed. Closing this issue.
