### ISSUE TITLE
conj:preconj vs. cc:preconj

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#221]
@kajad pointed this out; I am not sure whether it has been discussed but I don't see the corresponding issue here.

The documentation of the language-specific relations (http://universaldependencies.github.io/docs/ext-dep-index.html) lists `cc:preconj` for English. So does the English documentation (http://universaldependencies.github.io/docs/en/dep/cc-preconj.html). However, the version 1.1 English data contain `conj:preconj` instead (and the validator's tools/data/deprel.en also lists `conj:preconj`, otherwise the data would not validate).

The discrepancy should be fixed in version 1.2 data (both in UD_English and in tools). Personally I believe that `cc:preconj` is indeed correct, because the words are not conjuncts. Is it OK to modify the validator's list of English relations, which would make the current English data invalid, as a reminder?

**Comment by jnivre** [comment]
Definitely OK.

**Comment by manning** [comment]
Agreed. This was (yet another) bug.

**Comment by manning** [comment]
Fixed in our version 1.2 release candidate.

**Comment by dan-zeman** [comment]
I found the same issue in Persian, @mojgan-seraji .

**Comment by mojgan-seraji** [comment]
Fixed!

**Comment by dan-zeman** [comment]
Wonderful, thanks!
