### ISSUE TITLE
alternatives

### ISSUE THREAD

**Issue by verginicabm** [UniversalDependencies/docs#224]
In case you confronted a similar example to the one below, please let me know how you annotated the texts between brackets. Otherwise, maybe you have a solution. Meanwhile, we marked them as "dep", of course.

Here is the example:

Testul (ele) efectuat (e) arata ca...
Test-the (s-the) made (plural agreement) show that.... ("arata" is a homonymous form: both for 3 sg and 3 pl)
"The test(s) made show that..."

I am interested in the relation linking "ele" to "Testul" and, respectively, "e" to "efectuat".

**Comment by dan-zeman** [comment]
Very interesting. It actually occurs in Czech too, but I did not encounter it in the data we have, so I don't have a solution.

I would be tempted to abuse the `reparandum` relation for this, although its original purpose was different (http://universaldependencies.github.io/docs/u/dep/reparandum.html).

**Comment by manning** [comment]
I have no great answer either.  To the extent that it is showing a singular/plural alternative, it doesn't seem to me that `reparandum` is right -- there is no repair where the previous _test_ is overridden. If I were to use a non-`dep` relation, I'd go with `goeswith` since the second half can be seen as part of the word of the first half. But maybe `dep` is just okay here?

**Comment by manning** [comment]
I'm going to close this issue for now, since it seems like there's not something to fix here, and it's been up for a couple of weeks....

**Comment by dan-zeman** [comment]
I would not use `goeswith`. It sort of works in English where you just glue _test_ and _s_. But in other languages you would have to first remove a suffix from the first part, then add the suffix corresponding to English _s_. Czech would be the case in some instances. I am not a speaker of Romanian but I suspect the above example of _testul_ is also the case—I would first remove _ul_, then add _ele_ instead.

**Comment by verginicabm** [comment]
Indeed, mere adding inflection (as in English test/s) is not enough, when morphology allows for alternations in the stem (floare/flori "flower/s"). 

Verginica Mititelu, PhD 

Senior researcher III, NLP Group 
Research Institute for Artificial Intelligence "Mihai Draganescu", 
Romanian Academy 

----- Original Message -----
