### ISSUE TITLE
Invalid dependency relation 'subj:cop' in Hebrew

### ISSUE THREAD

**Issue by jimmycallin** [UniversalDependencies/docs#225]
The dependency relation _subj:cop_ can be found in the Hebrew treebank:

Examples:

```
15  גבר  _   NOUN    NOUN    Gender=Masc|Number=Sing 18  subj:cop    _   _
21  אשה  _   NOUN    NOUN    Gender=Fem|Number=Sing  23  subj:cop    _   _
3   טורקיות  _   NOUN    NOUN    Gender=Fem|Number=Plur  8   subj:cop    _   _
1   ביתן    _   NOUN    NOUN    Gender=Masc|Number=Sing 4   subj:cop    _   _

grep "\ssubj:cop\s" he-ud-train.conllu | wc -l
     354
```

_subj_ isn't a valid relation, and should probably be _nsubj_.

**Comment by yoavg** [comment]
This is correct, the relation should be nsubj.
We will fix this for the next release, hopefully sooner.

**Comment by jnivre** [comment]
Well, since the next release is on Sunday, I guess sooner would have to be tomorrow or the day after. :) I wonder how this slipped through the validation process, though. @fginter Was it possibly the case that the validation script only checked whether the language-specific relations were listed in the documentation and had the form "uni:spec" without actually checking that "uni" was a valid universal relation. If it was, has this check been added now?

**Comment by yoavg** [comment]
Wow. I am a bit out of sync with the world, apparently :) 
I will do my best to squeeze this fix in my schedule..

**Comment by jnivre** [comment]
If it is just a matter of replacing "subj:cop" by "nsubj:cop", you might be able to delegate. Then again, it looks like a 5 minute job. :)

**Comment by yoavg** [comment]
It is just a matter of changing subj:cop to nsubj:cop , but I wanted to apply the fix at the level of the automatic conversion chain, and not as a post-process. In any case, this proved to be easy enough, so done, and the fixed version is now pushed.

**Comment by jnivre** [comment]
Great, thanks!

Joakim

On 29 Oct 2015, at 16:10, Yoav Goldberg <notifications@github.com<mailto:notifications@github.com>> wrote:

It is just a matter of changing subj:cop to nsubj:cop , but I wanted to apply the fix at the level of the automatic conversion chain, and not as a post-process. In any case, this proved to be easy enough, so done, and the fixed version is now pushed.
