### ISSUE TITLE
Improve Introduction to UD web page

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#226]
The Introduction to UD web page would be way more useful to newcomers if it actually gave an **example** of UD, perhaps the same sentence in 2 or 3 languages. I.e., the kind of thing that we have in our intro UD slides.

**Comment by spyysalo** [comment]
@manning : if this is still relevant, I'll volunteer to convert examples to CoNLL-U for the v2 intro page if somebody can send me some of those slides.

**Comment by spyysalo** [comment]
I've added two examples from @dan-zeman (thanks!) to http://universaldependencies.org/introduction.html . Closing this, please consider opening new issues for changes or extensions.
