### ISSUE TITLE
Change naming in CoNLL-U: CPOSTAG --> UPOSTAG

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/docs#229]
Should  we maybe change the field naming on the CoNLL-U documentation page and anywhere else it occurs?  With the current CPOSTAG and POSTAG, the implication has to be that the POSTAG is primary, which is clearly now wrong. 

How about UPOSTAG and XPOSTAG or something like that?  (XPOSTAG is inspired by the fact that @honnibal chose to refer to the detailed tags as XPOS in #212.

**Comment by fginter** [comment]
This has been bugging me ever since.  +1

**Comment by dan-zeman** [comment]
Definitely yes. I have been actually referring to the first one as "UPOS" in most communication with strangers and was not even aware that we still use the CPOS(TAG) label in our documentation.

XPOS(TAG) sounds good, too. I would not necessarily include the "TAG" part but that's not a real problem.

**Comment by manning** [comment]
Okay, I'm calling this a (small) quorum and have changed it. So I'll close this for now. I left it as UPOSTAG, XPOSTAG for now. I'm not against changing it to UPOS, but maybe UPOSTAG is clearer to a new user?

**Comment by dan-zeman** [comment]
Thanks! You're right, `UPOSTAG` is more self-explaining. Besides, if I now say UPOS somewhere inofficially, it will be much easier to match it against existing documentation.
