### ISSUE TITLE
Treebank links are broken

### ISSUE THREAD

**Issue by dalton** [UniversalDependencies/docs#231]
The links on https://universaldependencies.github.io/docs/index.html are broken and you cannot download treebanks, 

>    Version 1.1 treebanks http://hdl.handle.net/11234/LRT-1478. Released May 15, 2015. Note: English data in the release were corrected on May 26, 2015. If you have downloaded the data before this date,  please re-download.
>    Version 1.0 treebanks are archived at http://hdl.handle.net/11234/1-1464. Released Jan 15, 2015.

Both links result in

> Error - System Error
> 
> The handle you requested --
> 
> 11234/LRT-1478
> 
> -- cannot be found.

**Comment by dan-zeman** [comment]
Thanks for reporting. To me it seems as an error around the handle.net service (a provider of persistent IDs), which I am reporting further.

As a temporary measure, you can use the direct link to the repository (a link that is not declared as persistent, but currently works for me):

UD1.1 ... https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/LRT-1478
UD1.0 ... https://lindat.mff.cuni.cz/repository/xmlui/handle/11234/1-1464

**Comment by dan-zeman** [comment]
It works for me now. Closing the issue. Hopefully it was just a temporary outage.
