### ISSUE TITLE
Auto-links broken in static HTML export

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#232]
Auto-links stop working when the documentation is exported as static HTML and opened from the filesystem.

This is likely related to failure to identify the root "URL".

**Comment by dan-zeman** [comment]
Pardon my ignorance about how Jekyll works and what are “our” additions to the page-generation process.

I do not think that we can or shall identify the root position on any filesystem in an offline copy of the pages. I thought that we should aim for relative paths in hyperlinks. When linking from `/en/pos/index.html` to `/en/pos/ADJ.html`, the link would not be `<a href="/docs/en/pos/ADJ.html" class="doclink doclabel" title="en-pos ADJ">ADJ</a>` as it is now, but rather just `<a href="ADJ.html" class="doclink doclabel" title="en-pos ADJ">ADJ</a>`.

The referring page is generated from `_en-overview/pos-index.md`. The table of POS tags is included from `_includes/en-pos-table.html` but the target addresses are not there; are they inserted by Jekyll? The alphabetical listing of POS tags is generated more directly, using the `[tag]()` construct. If it is the nature of Jekyll to generate absolute URLs from these constructs, then we have a problem.

If changing the links to relative means writing a script that will go through all the generated HTML pages and convert all absolute paths to relative, then we probably do not need to include the script in the page-generation process at Github. Instead, I could just run the script as part of preparation of the next release.

**Comment by spyysalo** [comment]
The generation of links from the `[tag]()` syntax is ours -- this is the auto-linking feature that aims to simplify the link syntax in the documentation and abstract over the directory structure. The latter was required to make links work e.g. in the single-page pos/feats/deps documents, which are located at the root: a static relative link could work either on the single-page document or the tag/feat/dep - specific document, but not both.

I think your suggestion to have a separate script that fixes these links for distribution is probably the best way to go. I'll try to have this working for the next release.

**Comment by dan-zeman** [comment]
This seems like something none of us is able to fix with the current website-building system. Postponing indefinitely.

**Comment by dan-zeman** [comment]
Making a static copy completely self-contained is not (and apparently will not be any soon) our top priority. Closing.
