### ISSUE TITLE
Auto-validation clutters the history

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#233]
There are automatic validation runs every two hours, and their result is displayed in the Github pages (http://universaldependencies.github.io/docs/validation.html). This proved extremely useful especially in the period before the new release.

We may want to turn this feature off until about a month before the next release. Or we may even leave it running permanently. Either case however, I wonder whether it would be better to only update Github if _validation status_ of any corpus changed. The page changes even if validation status does not, because the heading says what time the last validation was run. Unfortunately it means that we have hundreds of commits in the repository that are inconsequential and that befog the more interesting commits in the history:

![image](https://cloud.githubusercontent.com/assets/663752/11168934/3956a4f4-8ba5-11e5-9c74-6f96fd41d82d.png)

Excluding the timestamp from the report would help with this: the page would not change and a commit would not appear in the history. But it is actually also useful to see what time it was and how long shall we wait until we know that our data passed the validation.

Perhaps the auto-validation could be modified so that it only generates a report when any of the data repositories and/or the tools repository have changed? That does not happen so often. And these are the moments when the person who did the change is possibly eager to see the new validation result. Thus even if the changed data passed the validation and the validation result did not change, they would see the new timestamp and know that they are fine (if the report were not generated at all, they might think that something went wrong and the validation has not run at all).

**Comment by fginter** [comment]
Agreed. This is nuisance. I'll turn this off now and will try to find a way to only run the validation when some data changes. I think the timestamp is quite useful so people know they were picked up by the system. I hope organization hooks could be used here so we don't have to set up a hook for every repo.

**Comment by dan-zeman** [comment]
Looks like it works much better this time, so I am closing the issue. Thanks, @fginter !
