### ISSUE TITLE
Reduplicative plural in Indonesian

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#238]
Indonesian forms plural of nouns by repeating the noun twice. Example: _oleh negara-negara nordic_ “by nordic countries”; _negara_ = “country”. This is called reduplication and it is not limited to Indonesian.

It could be analyzed at the level of morphological features (`Number=Plur`) but tokenization would have to keep _negara-negara_ as one token; this is not what we have in our Indonesian treebank. In contrast, there are three tokens, _negara - negara_.

Since the reduplicated part is treated as a separate word (and provided we want to keep it that way), we need a language-specific relation to attach the reduplicated part to the first part. The treebank currently uses `mwe` but it is wrong because `mwe` is to be used only with function expressions, such as multi-word prepositions. (Side note: I discovered this by checking that no node has `mwe` and `name` children at the same time. Most treebanks comply with this rule, except for 1 occurrence in French, 9 occurrences in Italian and **72** occurrences in Indonesian. See http://hdl.handle.net/11346/PMLTQ-SUPM).

What about `nmod:plur` (an analogy to `nmod:poss` for _'s_ in English)?

**Comment by ftyers** [comment]
How about using `goeswith` and mark the first (or last) noun as plural.

```
0    oleh       PREP    ...   _                        1     case
1    negara   NOUN   ...  Number=Plur                  0     root
2    -            PUNCT   ...  _                       1     punct
3    negara  NOUN   ...  _                             1     goeswith
4    nordic  ADJ    ...  _                             1     amod
```

The docs say "This relation links two parts of a word that are separated in text that is not well edited. ", you could consider this just suboptimal tokenisation.

**Comment by manning** [comment]
Still lots of details to work out in UD! 

I would like to suggest using `compound`.  Probably as a language specific `compound:plur`, as @dan-zeman suggests.  I can see the argument for `goeswith`, but I originally thought of that more clearly as mistakes of writing, which isn't really the case here. That is, if we take the 5 relations in the "Compounding and unanalyzed" bucket, `name` and `foreign` have fairly clear, specialized semantics, and then of the other 3, my take is that `goeswith` is for a word split in writing, normally as an error (under the original assumptions of no spaces in words, `mwe` is restricted to grammatical expressions that behave like function words, and so other linguistic processes for putting together words are `compound`.  I think this is pretty clearly `compound`.

p.s. In Indonesian, it's somewhat debated as to whether it is really right to view reduplication as a straightforward plural marker, though, actually, that seems to be increasingly true in modern Indonesian. See, e.g., http://sealang.net/sala/archives/pdf8/rafferty2002reduplication.pdf .

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_Indonesian/commit/3beab3a9126021cace8ad0937b5bd9a95ae7873f

**Comment by nschneid** [comment]
See also #307, where the decision was also `compound`.
