### ISSUE TITLE
New text for the Introduction page of the Latin-ITT treebank (and slightly changing the name of the treebank)

### ISSUE THREAD

**Issue by passarom** [UniversalDependencies/docs#239]
The current Introduction page for the the Latin-ITT treebank is wrong. The Latin-ITT is not based on the Latin Dependency Treebank, but on the Index Thomisticus Treebank.
Please, change the contents of the Introduction page, by replacing the current text with the one reported below. Please, link the words "Index Thomisticus Treebanks" to the following URL: http://itreebank.marginalia.it.
Furthermore, since the "official" acronym for the Index Thomisticus Treebank is IT-TB and not ITT, it would be good to rename Latin-ITT into Latin-ITTB.
Thanks.

Marco Passarotti

New text for the Introduction page 

The Latin-ITTB UD treebank is based on the Index Thomisticus Treebank (IT-TB), currently maintained at Università Cattolica del Sacro Cuore, Milan, Italy. The treebank consists of texts by Thomas Aquinas.

The morphological and syntactic annotation of the Latin-ITTB UD treebank is the result of a conversion process made by Marco Passarotti (Milan) and Dan Zeman (Prague).

**Comment by gcelano** [comment]
Hi Marco, 

The introductory page is common to all Latin treebanks. I have provisionally modified it, so it comprises a brief description for each of them, including the one for the ITT(B). As for the name of the repository, I am not sure whether changing it without concomitant changes can raise errors anywhere else.

@fginter, @dan-zeman, or anyone else who knows, any suggestions?

**Comment by fginter** [comment]
Changing the name is a relatively major operation because all links from external resources like the query system etc will need to be changed as well.  I hope this could wait till the next release now that the docs page is fixed and makes it clear what is what.

**Comment by passarom** [comment]
Sure, we can wait the next release before changing the name of the Index Thomisticus Treebank from Latin-ITT to Latin-ITTB.
Many thanks, Giuseppe, for changing the Introduction. It looks perfect. Following what said above and to be consistent with the name of the treebank in the current release, may you please rename the name of the IT Treebank in the Introduction from Latin-ITTB to Latin-ITT?
Thank you.

Marco

**Comment by dan-zeman** [comment]
I just changed the introduction to mention Latin-ITT, and added hyperlinks to the websites of ITTB and PROIEL. Sent invitation to @passarom so you get write access to the documentation. As for renaming the repo, I agree with @fginter (anyway, people are not supposed to take the data directly from the repo. And the official release 1.2 contains ITT. Sorry, Marco, I should have asked you whether the acronym is OK.)
