### ISSUE TITLE
Textual references

### ISSUE THREAD

**Issue by daghaug** [UniversalDependencies/docs#240]
One of the users of our biblical data (Greek, Latin, Gothic, Old Church Slavonic) has asked whether we could add textual references to the CoNLL-U files. This makes particular sense for our data because it is parallel across four languages, and because there are unannotated translations available in lots of languages. We do make the textual references available in other exports of our data, but this particular user's goal is to "use Universal Dependencies-compatible annotations with a corpus of unannotated translations", so it would be convenient to have them in CoNLL-U as well.

I realize that textual references may not be as necessary for other treebanks in UD, but before we go ahead and think about ways to add them, I wanted to ask if there are others who do see this need, and whether this should be encoded in a standard way. 

The verse division in the bible cuts across sentences, so we need references at the token level, i.e. a comment line before the sentence will not do. Is it a good solution to add them in the MISC column? Say reference="LUKE 7.17"? Could we use inline comments at the end of each line to mark that it is not part of the linguistic data? Other solutions?

**Comment by fginter** [comment]
I think we have been informally keeping the MISC field in the format attr=value|attr=value so that is probably fine. If the divisions cut across sentences only rarely, you could also consider the sentence metadata:

```
#reference 1-15 LUKE 7.17
#reference 16-23 LUKE 7.18
```

this would be quite readable and wouldn't populate the MISC field with same values most of the time.

**Comment by dan-zeman** [comment]
I would avoid spaces in any token-related values, regardless the quotation marks. (And the space would actually violate our guidelines, see http://universaldependencies.github.io/docs/format.html.) So I vote for something like this in the MISC field:

<pre>ref=LUKE_7.17</pre>

A related point: I have been thinking that some corpora (Ancient Greek and Latin in particular) should have the `sent_id` comment (used as example but not required in our guidelines) that would uniquely identify
1. The original text
2. Sentence number within the text

So the user can extract particular documents and, if possible, also order the sentences within the document. Additional metadata about the document might be provided in the README.txt file. This is particularly important for treebanks containing different domains, and for diachronic corpora where the source texts span several centuries of evolution of the language. In AGDT and LDT such information is available and we are losing it by merging all the documents into just three files.

Ideally, this could be done for other treebanks too, except those that are based on shuffled texts. I would not make this a strict requirement, but a recommendation for corpora where it is possible.

**Comment by gcelano** [comment]
If in a considerable number of treebanks sentence identifiers are desirable, the idea to introduce a specific column for this information is well worth considering.

**Comment by dan-zeman** [comment]
Unlike Dag's references, a sentence ID is not different for different tokens, so it does not go to columns.

**Comment by gcelano** [comment]
I meant word identifiers, of course. These are particularly relevant for poetry, for example.

**Comment by daghaug** [comment]
OK, so we will go for Dan's solution, and perhaps add sent_id comments as well. They are certainly useful.
