### ISSUE TITLE
Drop restriction on (non-)finiteness for xcomp

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#245]
The universal documentation of the comp relation still says that these complements are always non-finite. If we agree that the defining characteristic is obligatory control, then this is too restrictive. Persian, for example, has cases of finite complements with obligatory control.

**Comment by jnivre** [comment]
On second thought, I think we should address this properly in v2 of the guidelines, so I am closing this.

**Comment by dan-zeman** [comment]
Don't we want to collect issues here that will affect the v2 guidelines? We could create a milestone and tag the issues properly.

**Comment by jnivre** [comment]
Sounds like a good idea. But we should probably go through many of the old issues and tag them appropriately too.

**Comment by dan-zeman** [comment]
Reopening and assigning to the milestone "universal v2".

**Comment by manning** [comment]
In your initial comment, I presume you mean xcomp where you write comp @jnivre.  

I agree. And I even think we could just change the definition right now. In my head I've distinguished between clarifications, improvements and extensions appropriate for other languages of this sort as okay to do in v1 versus more major changes, which include changing the dependency or UPOS set for sure.

**Comment by jnivre** [comment]
Yes, it should be comp. Shall I just change the definition and close the issue then?

**Comment by dan-zeman** [comment]
+1 :-)

**Comment by jnivre** [comment]
Fixed and closed.
