### ISSUE TITLE
Refreshing web contents of http://universaldependencies.org/docs/

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#246]
Following https://github.com/UniversalDependencies/docs/issues/215

I edited (& committed & pushed) https://github.com/UniversalDependencies/docs. The change caused automatic regeneration of https://github.com/UniversalDependencies/universaldependencies.github.io, so far so good. But after 20 minutes I still do not see the change at http://universaldependencies.org/docs/ on reload.

I hope it's not my browser's cache. I tried a different browser and I see the same there. If the pages are just redirected to Github, could there be another cache in the way? The expected change is a new line for Russian on the title page, and non-zero corpus size of Catalan and Spanish-AnCora.

**Comment by spyysalo** [comment]
Is http://universaldependencies.org/ updated? I think `/docs` is no longer attached to the update system, and should probably be replace with a redirect.

**Comment by dan-zeman** [comment]
Aha, http://universaldependencies.org/ is updated. But http://universaldependencies.github.io/docs/ redirects to http://universaldependencies.org/docs/. We need to fix this redirect because http://universaldependencies.github.io/docs/ has long been _the_ homepage of UD and it is likely referenced from many places by now.

**Comment by fginter** [comment]
Hi. I'd love to fix this redirect but I have no idea how this redirect happens, it's a part of GitHub magic. What do you guys think we should do? One option would be to kill the gh-pages branch of docs. This would probably result in a 404 on the old address. Other option would be to keep the .io pages updates as well in parallel with the .org ones.

**Comment by fginter** [comment]
I think I now understand why we get a redirect to universaldependencies.org/docs. The reason is that universaldependencies.org stands for the whole organisation and the docs repo has a gh-pages branch. This is great, because we will be able to get universaldependencies.org/tools to work, etc. I now added a redirect for index, so now navigating to universaldependencies.org/docs gets you to the right place. If this seems like a workable solution, I could replace each and ever html with a redirect to the .org version. That way also existing links will point to the right place.

**Comment by dan-zeman** [comment]
My main concern was about docs/index.html because we have been distributing the URL leading to that file for quite a while. Adding redirects from all docs/*.html files would certainly not hurt. When (if) the time comes to rethink the directory structure (maybe because we add a gh-pages branch for tools or another repo), hopefully we will have had a long enough grace period for users to learn the new URL.

**Comment by spyysalo** [comment]
http://universaldependencies.org/docs/index.html and http://universaldependencies.github.io/docs/index.html redirect to http://universaldependencies.org/ for me (as intended), are you getting a different result?

**Comment by dan-zeman** [comment]
No, I'm getting the same result. What I meant to say was that the issue is resolved but @fginter 's suggestion for additional redirects sounds also good.

**Comment by fginter** [comment]
+1 will look into it when I have a moment

**Comment by dan-zeman** [comment]
@fginter : Anything new here, or shall we just close the issue?

**Comment by fginter** [comment]
I think the fixed links pretty much removed this problem. So maybe we can close
