### ISSUE TITLE
Clarify documentation of formal vs. logical subjects in existential phrases

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#251]
https://github.com/UniversalDependencies/UD_English/issues/9#issuecomment-182407227 revealed a gap in our guidelines. I am tentatively targeting this issue for the UD v2 milestone. It may require changing the UD English data, thus it may be viewed as change of the guidelines rather than just making them clearer.

**Comment by manning** [comment]
I tried to make some small clarifications and improvements to the wording of nsubj and dobj, which I think are in line with current practice. Certainly they are for English. So maybe we could close this issue, since any guideline revisions would be part of a more general process.
