### ISSUE TITLE
Titles and names in Germanic languages

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#253]
For phrases of the type "King George", we find four different analyses in the Germanic treebanks:

Danish:
appos(King, George)

English:
name(King, George)

Norwegian:
appos(George, King)

Swedish:
nmod(George, King)

The Norwegian analysis violates the guidelines, which say that appositions should follow the head noun. The English analysis is dubious as "King" is arguably not a proper name (although it might be tagged PROPN because of the underlying PTB tags). The Danish and Swedish analysis disagrees about what is the head, "King" or "George", but I would argue that the relation should be "nmod", not "appos", regardless.

It would be interesting to hear how this is treated in German and Dutch, as well as in any other language of course.

**Comment by dan-zeman** [comment]
German: I found at least two different analyses, see http://hdl.handle.net/11346/PMLTQ-PN9I

appos(King, George)

compound(George, King)

but the `compound` analysis clearly violates the guidelines.

**Comment by dan-zeman** [comment]
Dutch: http://hdl.handle.net/11346/PMLTQ-CRUM

appos(King, George)

But note that this search goes to UD1.2.

**Comment by dan-zeman** [comment]
FWIW, in PDT (Czech) we have nmod(George, King) in sentences like "the England's king George tried to..." but we would use appos(George, King) in sentences like "George, the king of England, tried to..."

**Comment by jnivre** [comment]
FWIW, this is exactly as I think it should be. George is the head in both cases, but only the second case fits the definition of apposition (under the current guidelines).

FYI, in the Swedish grammar tradition, the term "apposition" would be used in both cases, but with a subdivision between "fixed apposition" ("King George") and "loose apposition" ("George, King of England"). Perhaps this is what underlies the use of "appos" for the former relation in Norwegian.

**Comment by jnivre** [comment]
There is another case found in UD_Norwegian, which probably has to be seen as a bug given the current version of the guidelines:

svenskekongen, Carl Gustaf, [the Swedish king, Carl Gustaf,]
appos(Carl, svenskekongen)
name(Carl, Gustaf)

Given the guidelines, it seems it would have to be:

appos(svenskekongen, Carl)

Because of the punctuation, we get this minimal pair:

svenskekongen Carl Gustaf
nmod(Carl, svenskekongen)

svenskekongen, Carl Gustaf,
appos(svenskekongen, Carl)

**Comment by jnivre** [comment]
Does anyone want to argue against the conclusion that this is what we should do:

King George
nmod(George, King)

George, King of England
appos(George, King)

Are we ready to close this?

**Comment by liljao** [comment]
I agree with the analysis and am taking steps to adopt this analysis for Norwegian.

**Comment by TCGWim** [comment]
An example in Latin: "flumen Rhodanus, qui ..." = the river Rhone, that ...
Now 'flumen' is neuter, 'Rhodanus' is masculine and 'qui' is masculine (not neuter), so 'qui' is agreeing with 'Rhodanus', not with 'flumen'.
So in Latin 'Rhodanus' is head of the NP, with 'flumen' as modifier.
When we use 'appos' as deprel, 'flumen' would be the head of the NP, or we should make the guidelines more flexible.
If we use 'nmod' 'Rhodanus' can be the head.

**Comment by jnivre** [comment]
Thanks, Wim. This seems perfectly consistent with the analysis we adopted for the Scandinavian languages.

**Comment by dan-zeman** [comment]
I know this thread is primarily about Germanic languages, but for the record, it would be different in Czech, where you could say (paraphrasing Wim's example) _řeka Rýn, která..._ = "the river Rhine, which". _řeka_ and _která_ are feminine while _Rýn_ is masculine.

**Comment by jnivre** [comment]
Good point! This seems to indicate that the head status is different in different languages.

**Comment by TCGWim** [comment]
In Latin grammar both "King George" and "George, King of England" are called appositions. The former is a restrictive apposition and the latter a non-restrictive apposition (Pinkster 2015 §11.80). A motivation to use nmod for the former is that you are free to decide which of the two nouns you make the head. But that is not a good argument. It would be better to have freedom of choice for the head in an apposition.

**Comment by jnivre** [comment]
This is exactly as in Swedish grammar (and we presumably got it from Latin). However, the current guidelines seem to follow the current NLP tradition, where apposition is only used about the non-restrictive case. Maybe something to discuss for v2.

**Comment by dan-zeman** [comment]
Closing as this is a v1 issue (now we have `flat:name` instead of `name`) and there are (or have been) newer issues with a similar topic.
