### ISSUE TITLE
Mix of "name" and "foreign" in Norwegian

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#254]
The Norwegian treebank has a mix of "name" and "foreign" relations in the names of dishes like "Coquilles St. Jacques Prince de Norvège", where "de" is "foreign" and the others "name". This is reflected also in the postag, which is "X" in the former case and "PROPN" in the latter. Ideally, I think these should be given a compositional analysis, but a mix of "name" and "foreign" should definitely be avoided.

**Comment by spyysalo** [comment]
Related SETS search: http://bionlp-www.utu.fi/dep_search/?db=Norwegian&search=_+%3Ename+_+%3Eforeign+_

Hits also for Danish: http://bionlp-www.utu.fi/dep_search/?db=Danish&search=_+%3Ename+_+%3Eforeign+_

**Comment by liljao** [comment]
Thanks for pointing this out, this will be fixed for the next release.

**Comment by jnivre** [comment]
Great! Question of procedure: Should we close this issue now that it has been resolved, or should Lilja close it when the change has been implemented?

**Comment by spyysalo** [comment]
I'd suggest to close when fixed.

**Comment by dan-zeman** [comment]
I would assign the issue to Lilja and leave it open until a fixed version of the data is available in the dev branch.

Odesláno ze Samsung Mobile

-------- Původní zpráva --------
Od: Joakim Nivre notifications@github.com 
Datum:16. 02. 2016  14:29  (GMT+01:00) 
Komu: UniversalDependencies/docs docs@noreply.github.com 
Předmět: Re: [docs] Mix of "name" and "foreign" in Norwegian (#254) 

Great! Question of procedure: Should we close this issue now that it has been resolved, or should Lilja close it when the change has been implemented?

**Comment by liljao** [comment]
I agree, leave it open until I get around to fixing (and closing) it.

Lilja

2016-02-16 14:51 GMT+01:00 Dan Zeman notifications@github.com:

**Comment by liljao** [comment]
This has now been fixed.

The bug basically ocurred in two types of structures:
- foreign names, such as _Alice in Chains_, where _in_ received the `foreign` relation and the other elements `name`. The updated version assigns `name` to all elements of the foreign name.
- whole clauses or sentences in a foreign language where punctuation due to a bug received the `name` relation. This has now been changed to `punct`.
