### ISSUE TITLE
The use of "case" vs. "mark" in subordinate clauses

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#257]
In many languages, adverbial clauses are introduced by a combination of a preposition or adverb and a general complementiser like English "that" or Romance "que". In the Scandinavian treebanks, there are three different treatments of these (with Swedish being inconsistent):

Danish: mark + mark
Ex: for/mark at/mark ... VERB/advcl

Norwegian: case + mark
Ex: for/case at/mark ... VERB/advcl

Swedish: mwe
Ex: för/mark att/mwe ... VERB/advcl

In addition, Swedish adopts the Norwegian analysis when the verb is in the infinitive:

Ex: för/case att/mark VERB-INF/advcl

As a point of comparison, English seems to adopt the mwe analysis at least for "so that".

**Comment by dan-zeman** [comment]
German: `mark` + `aux` prevails but there are other solutions including `aux` + `aux`
Ex: um/mark ... zu/aux VERB/advcl
http://hdl.handle.net/11346/PMLTQ-RRUF

**Comment by jnivre** [comment]
The use of "aux" for the infinitive marker is a well-known bug in the German data (inherited from the original Stanford dependencies via UDT), so we shouldn't take this too seriously.

In general, I think we need to distinguish two cases here. The first is a compositional construction involving a preposition (often selected by the matrix clause verb) and a subordinate clause. For example:
1. Jag räknar med dig (I count on you)
2. Jag räknar med att vinna (I count on to win = I count on winning)
3. Jag räknar med att du vinner (I count on that you win = I count on you winning)

1 is "nmod" and 2-3 are "advcl". But the question is what to do with the preposition "med" (literally "with") in the three cases. For me it seems very natural to use the "case" relation in all three cases, but it seems that some treebanks assume that the change from "nmod" to "advcl" also necessitates a change from "case" to "mark". This is certainly a coherent position, but we need to agree.

The second case is one where there is a subordinating conjunction formed by a preposition or adverb + a complementiser and where both elements together clearly perform a subordinating function (rather than the preposition being selected by the matrix clause verb). Compare:

1.a Jag gör det, fastän du inte gillar det. (I do it, although you don't like it.)
1.b Jag gör det, även om du inte gillar det. (I do it, even if you don't like it.)
2.a Jag gör det, eftersom du inte gillar det. (I do it, since you don't like it.)
2.b Jag gör det, därför att du inte gillar det. (I do it, because you don't like it.)

In 1, we have two concessive adverbial clauses, and in 2 we have two causal adverbial clauses. In the a-sentences, there is a single-word marker ("fastän", "eftersom"), and in the b-sentences there are multiword markers ("även om", "därför att"). For these I would argue that the "mwe" analysis should be used, but it is important not to confuse this case with the first one.

In addition, it may be the case that finite and non-finite clauses need to be treated differently. For example, the multiword markers seem to be found primarily with finite clauses, at least in Swedish.

**Comment by dan-zeman** [comment]
I prefer saying that if a preposition is attached to a verb, the relation is `mark` and not `case`. (I would also extend the rule to non-verbal predicates but here one would have to be careful whether the preposition performs the subordinating function for the whole clause, or whether it is really a case-like modifier of the nominal, i.e. there is a prepositional phrase functioning as predicate).

A `mwe` analysis in the second batch of examples is certainly conceivable but here the exact set is for you native speakers to decide :-)

**Comment by jnivre** [comment]
I understand the idea that subordinating markers on predicates should be "mark" and not "case", but in the first batch of examples the point is that you have both a subordinating marker ("att") and a case marker ("med"). This is a type of structure that is rare in English but quite frequent in other Germanic languages. In some sense, the first marker ("att") attaches to the predicate in order to turn it into a subordinate clause, which could be used as a complement clause, and then the case marker ("med") turns this potential complement clause into an adverbial clause, just like it can be used to turn a potential nominal complement into an nmod. Calling both the function words "mark" would miss the parallelism to the nominal case and would also suggest that they both have the same function.

**Comment by dan-zeman** [comment]
For me, a case implies a nominal, but that is probably biased by "my set of languages". In Czech you could not escape it: you would say either "I count with winning" (where "winning" is a normal noun) or "I count with it, that.SCONJ you win" (where the case is applied to the pronoun, not to the subordinated clause). There are probably languages where clauses can have morphological cases (at least infinitives and participles can have them; but I don't know examples of languages where this would be possible with finite clauses) and then it makes sense that their relation with adpositions is also labeled `case`.

If verbs are allowed to have `case` children, it will be no longer possible to automatically dismiss them as bugs. That is of course no good reason for a rule, but we should keep that in mind and document carefully under what circumstances and in which languages a preposition attached to a clause is `case`, and when it is a `mark` (if at all). Or did you mean to propose that in Swedish an `ADP` is either `case` or `mwe` but never `mark`?

**Comment by jnivre** [comment]
I am not sure what I am proposing, but the general rule would be that ADP is case and SCONJ is mark, and that ADP and SCONJ sometimes merge to form an MWE as mark. But I can clearly see the value of restricting case to nominals, so perhaps we should try to find another solution. Perhaps it should be viewed as analogous to "from under X", where even though there is a recursive structure such that "from" applies to "under X", the dependency structure just has two flat "case" dependents.

**Comment by LarsAhrenberg** [comment]
Maybe there are too many distinctions here: ADPs and SCONJs perform similar functions as Joakim notes. Many words, such as 'before' or 'after' will be ambiguous in POS-assignment with the suggested parallellism. 'Before Christmas' is clearly nominal while 'Before they arrived' is clearly clausal. But both 'before arriving' and 'before arrival' is possible, I think. Similar examples can be found for Swedish at least.

**Comment by jnivre** [comment]
All things considered, it seems that the best solution is to use "mark" whenever an adposition or subordinating conjunction is attached to a predicate that heads a subordinate clause. This means that Swedish and Norwegian should change the "case + mark" cases to "case + case". It is still possible to use the "mwe" analysis for cases where the ADP + SCONJ combination is really a fixed MWE. This means we can now consider any occurrence of "case" attached to a verb as an error. Note, however, that we cannot automatically assume that a "mark" attached to a noun is an error, since the noun may be used as the predicate of a nominal clause, as in "I think that he is a fool", where mark(fool, that) is the correct analysis.

Unless there are new arguments, I think we should close this issue and let Lilja and me implement the necessary changes. We should also check what Dutch and German does in these cases. (English seems to have uniformly case + case or mwe).

**Comment by LarsAhrenberg** [comment]
Don't you mean 'This means that Swedish and Norwegian should change the "case + mark" cases to "mark + mark" (when attached to a predicate that heads a subordinate clause)??

**Comment by jnivre** [comment]
Yes, I do. Sorry.

**Comment by jnivre** [comment]
I fixed this issue for Swedish in v1.3. As far as I know, it has not been fixed for Norwegian, so I am assigning it to Lilja for v2.

**Comment by liljao** [comment]
I actually fixed this for v1.3 but forgot to update here. I am closing this issue then.

**Comment by jnivre** [comment]
Excellent, thanks!
