### ISSUE TITLE
Norwegian bugs

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#264]
Here are a couple of minor things I found when going through the Norwegian data. Some of them look like bugs, others are less clear, but it may be worth looking at them (both in the specific sentences and generally in there treebank). Sentence numbers start from 1 at the beginning of the training set.

17: "Bak" compound:prt -> advmod
49: acl -> acl:relcl, mark -> advmod 
20: "det" should be attached to verb as "dislocated" instead of to "bryllupet" as "appos" (I think)
20: "heller" should be "advmod", not "nmod" (I think)

On the whole, I think the quality of the Norwegian data looked very good.

**Comment by liljao** [comment]
Thanks, this is really helpful!

**Comment by liljao** [comment]
I have now had a look at the reported bugs in the Norwegian data and have fixed some of them and left others for later, as they represent well-known issues that require some manual effort. 
I am closing this issue now.
