### ISSUE TITLE
Bugs in Danish

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#265]
Here are a number of suspicious things I found when looking through the Danish data. I think most of them are conversion bugs, but they may be worth looking at. Sentence numbers start at 1 in the training set. Let me know if you need more info.

2: acl:relcl for non-relative clause 
4: acl:relcl for parenthetical (should be parataxis)
5: nmod -> appos
6, 50: conj attached to cc instead of first conj
7: garbled; wrong root (parataxis); wrong compound:prt; wrong mwe 
11: nmod attached to verb particle
18: For otte miljoner = cc -> nmod
19: et eller andet - missad coordination

**Comment by jnivre** [comment]
Here are some more:

20: Alene i Hamburg; ophobet skrab 
21: wrong root (parataxis); ud = nmod -> compound:prt; nmod attached to particle
28: garbled; main clause treated as xcomp
29: garbled: dels på - dels på
30: wrong structure for "Berlingske Tidendes afslag"; nmod:tmod -> advmod
39, 41: wrong root (expl)
43: skyldige = amod -> nmod [bug]
44: wrong root [clausal predicate with copula] + parenthetical and punctuation wrong attachment [bug]
39, 41: wrong root (expl)
43: skyldige = amod -> nmod [bug]
44: wrong root [clausal predicate with copula] + parenthetical and punctuation wrong attachment [bug]
39, 41: wrong root (expl)
43: skyldige = amod -> nmod [bug]
44: wrong root [clausal predicate with copula] + parenthetical and punctuation wrong attachment [bug]
50: garbled; conditional treated as coordination

**Comment by jnivre** [comment]
I have changed the milestone to v2 for this one, but I would be happy to know that someone in the UD_Danish team is actively working on these issues. My impression is that Anders is not active anymore. Who else should we assign?

**Comment by bplank** [comment]
Hi Joakim, 

All the members of the Danish team changed country and affiliation in the last 2 months, which was why it was so silent from our side.. @hectormartinez is nowadays more involved in Catalan and Spanish; but we'll try to fix issues for v2 now established in the Germanic issues section. 

In the long run, however, we might have to find other members of the Danish NLP community to help the analysis and the upkeep

**Comment by jnivre** [comment]
Thanks, Barbara. This is what I suspected. Let's hope that someone can take over.

**Comment by KennethEnevoldsen** [comment]
Hi @jnivre I am currently looking into polishing up the DDT. I am not a linguist so wouldn't be able to 100% verify these things, but if I make a PR would you have the time to give it a glance?

**Comment by dan-zeman** [comment]
I will be happy to look at the PR too, although Joakim will obviously be much better in understanding Danish.

**Comment by jnivre** [comment]
Hi @KennethEnevoldsen! I’m sorry I missed this. I will be happy to check the PR.

**Comment by KennethEnevoldsen** [comment]
Wonderful to hear will have a look at it after the weekend
