### ISSUE TITLE
Bugs in Swedish

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#266]
Some things that I noticed in the Swedish data:

21: lever tillsammans = compound:prt -> advmod
28: det räcker = nsubj -> expl?
38: annan kommun än hemortskommunen = det + ... + acl -> amod + ... + advcl?
41: för skattskyldig = advmod -> nmod

**Comment by dan-zeman** [comment]
@jnivre, have these bugs been fixed?

**Comment by jnivre** [comment]
Embarrassingly enough, the answer is no. I will take care of this (but not now).

**Comment by jnivre** [comment]
Fixed in 2.3.
