### ISSUE TITLE
Possessive Determiners/Pronouns in English

### ISSUE THREAD

**Issue by vsoto** [UniversalDependencies/docs#269]
In the universal POS documentation, the following are listed as possessive determiners: "possessive determiners: my, your, his, her, its, our, their".

However  in the english documentation page for PRON, those possessive determiners are treated as Pronouns, and the same can be observed when inspecting the English Corpus. That corpus is described as "a gold standard Universal Dependencies corpus for English" and hand-corrected. 

So is the treatment of the possessives as pronouns a mistake that should be corrected?

**Comment by dan-zeman** [comment]
The borderline between pronouns and determiners has been disputed quite a bit in UD, see e.g. https://github.com/UniversalDependencies/docs/issues/159 or http://universaldependencies.org/2015-08-23-uppsala/determiners.html. It will be probably changed in the version 2 of the guidelines but it is not yet clear how exactly. For the time being, the approach taken in UD English is a language-specific deviation from the universal guidelines.
