### ISSUE TITLE
Right-headed names in English

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#270]
Names appear to be mostly (always) right-headed in English. See, for example, sentence 1 and 11 in the training set.

**Comment by manning** [comment]
I agree that this doesn't conform and reflects the original assumptions of right-headed NPs in the Penn Treebank. But there isn't the time/energy to fix this for v1.3....

**Comment by dan-zeman** [comment]
Closing. We now have `flat:name` (or just `flat`) and the validator makes sure it is left-to-right.
