### ISSUE TITLE
Bugs involving complement clauses in English

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#271]
I have found instances in the English treebank of interrogative complement clauses annotated as if they were conditional averbial clauses. Examples:

"You wonder if he was manipulating the market with his bombing targets."
"... you never know where you may get stuck."

I have also found instance of main clauses being annotated as a complement clauses:

"My neighbourhood has been surrounded by American troops ..., helicopters have been circling/ccomp ..."
"Yesterday there were tons of them ..., they only came/ccomp out"
"And there is nothing we can do ..., people are living/ccomp ..."
This should be parataxis or possibly conj.

**Comment by manning** [comment]
I checked 40 files somewhat randomly (taking files with "if" or "whether" in them and only looking for "if" and "whether" clauses) and changed 7 decisions, 5 from `advcl` to `ccomp` and 2 from `ccomp` to `advcl`. So, my feeling is that the annotation quality could be higher (!), but that there isn't a systematic problem here. I also then fixed the cases mentioned in @jnivre's issue above - thanks!

So, I'm going to close this issue for now, but am happy to deal with any other concrete error cases that people find.
