### ISSUE TITLE
Improve cross-language consistency of feature values.

### ISSUE THREAD

**Issue by MathieuDehouck** [UniversalDependencies/docs#274]
Dear All,

When working in a multi-language setting some features occurring in different languages have the same surface value while having different semantic.

The problem appears for example for Case=Com.

In Irish, Com is the value representing the 'Common' case (Nominative, Accusative), while in Estonian, Com represents the Comitative.

Maybe the Irish 'Com' could be replaced by 'Nom,Acc', or a new value could be defined.

**Comment by spyysalo** [comment]
@MathieuDehouck : thank you for reporting the discrepancy.

`Case=Com` is part of the universal feature inventory (i.e. not a language-specific extension) and is defined as standing for comitative: http://universaldependencies.org/u/feat/Case.html#com-comitative--associative . It should not be used with different meanings.

@tlynn747 : could you please check this?

**Comment by tlynn747** [comment]
@spyysalo @MathieuDehouck @dan-zeman Please note that we're addressing this in the v2 updates.

**Comment by dan-zeman** [comment]
OK, @tlynn747, can the issue be closed then?
