### ISSUE TITLE
Possessive pronouns in Bulgarian

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#277]
In UD_Bulgarian 1.2, possessive pronouns are attached to the possessed noun using the `case` relation. Perhaps this is meant as an analogy to the attachment of the English possessive morpheme _-’s_ but I believe it is wrong. It should be `nmod` or `nmod:poss`.

[bg] Ротата им , кажи-речи , е цялата нашенска . 
Their platoon , pretty much , is all ours .
The possessive pronoun им “them” is attached to the noun as case.

[bg] Днес тревожният покой дебне малката ни къща . 
… little our house .
There is case(малката, ни). I think it should be nmod(къща, ни).

**Comment by osenova** [comment]
Thanks, Dan! I know this problem - it was really paired with the English possessive 's, but surely it is not adequate for Bulgarian. I will change this, but I think that it is better to use the relation DET as for full-fledged possessive pronouns мой, моя, мое / ми.

**Comment by dan-zeman** [comment]
`DET/det` is indeed better for the full-fledged possessives. I was not sure how the short _ми_ relates to them; but no objection :)
