### ISSUE TITLE
Compounds vs. named entities in Croatian

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#284]
The Croatian treebank uses the `compound` relation for multi-word named entities that have internal syntactic structure and could be analyzed as normal phrases. (They actually are normal phrases, but in the given context the whole phrase also refers to a concrete entity.) Normal non-compounding relations such as `nmod`, `amod` and `case` should be used instead.

[hr] _Osim toga , mnoge tvrtke koje su privatizirane promijenile su lokaciju poslovanja , i vrlo često se zaposleni , kao što je Berisha , brišu s isplatnih lista , što dovodi do čestih prosvjeda ispred Agencije za privatizaciju ._

compound(Agencije, privatizaciju) should be `nmod`.

[hr] _Seb Bytyci , izvršni ravnatelj Instituta za balkansku politiku , slaže se s time ._

_Instituta za balkansku politiku_ is connected using `compound` but it should be `nmod` and `amod`.

**Comment by dan-zeman** [comment]
The bug still exists in UD 2.4.

**Comment by tsamardzic** [comment]
Added to my TODO for Croatian, thanks!

**Comment by dan-zeman** [comment]
Changing the milestone to the next release. The bug still exists in v2.6. Specifically, _agencije za privatizaciju_ occurs once in train and once in dev, both occurrences are analyzed as `compound`.

**Comment by tsamardzic** [comment]
We are on it! Should be fixed for v2.7.

**Comment by tsamardzic** [comment]
Done!
