### ISSUE TITLE
SpaceAfter=No in Slovenian

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#285]
[sl] _Kaj se je zgodilo, sem izvedel šele naslednjega dne iz časopisja," je v intervju za Stampoiz Torinaizjavil morilec._

In UD 1.2, multiple sentences seem to have issues with the `SpaceAfter=No` feature (MISC column). Like this one: “Stampoiz”, “Torinaizjavil”.

**Comment by kajad** [comment]
Fixed for release v1.3.
