### ISSUE TITLE
The mwe relation in German

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#288]
As the content validation reveals, German has a number of right-headed instances of the `mwe` relation, see http://bionlp-www.utu.fi/dep_search/?search=_+%3Cmwe%40R+_&db=UD_German-dev

In some cases (e.g. _ein wenig_ “a little”), simply switching the direction will help. However, elsewhere (e.g. the _Alles in Allem_ “all in all” instances), the multi-word expression has normal dependency relations inside, and the `mwe` relation is oddly used to attach the MWE to the outer predicate:

mwe(PREDICATE, Alles)
nmod(Alles, Allem)
case(Allem, in)

Either we can abandon the MWE analysis and find a suitable relation between the predicate and the head of the MWE (`nmod` in this case). Or we can link the members of the MWE using `mwe`, and also find a suitable relation with the predicate:

advmod(PREDICATE, Alles)
mwe(Alles, in)
mwe(Alles, Allem)

The inventory of the cases where one cannot switch the direction of `mwe` has to be created manually, but the test has only 29 hits, so no real problem here.

**Comment by yv** [comment]
MWE is relatively non-specific in that it applies to a lot of constructions.
also <advmod (dieser Bäcker hat ...)
which would be consistent with the second solution.

I could not edit the trees in SETS. I hope everything is ok.

**Comment by dan-zeman** [comment]
This should be partially fixed in UD 1.4.
