### ISSUE TITLE
Equivalence of PUNCT and punct

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/docs#291]
The current guidelines seem to presuppose that PUNCT always has the function punct and vice versa. (At least our content validator seems to presuppose this.) We have two systematic cases in the Swedish treebank that seems to violate this assumption (in one direction):

room + board
conj(room, board)
cc(room, +)

9 - 5
nummod(9, 5)
case(5, -)

There is a clear intuition that + and - are alternative forms of "and" and "to" in these cases. Does this mean that they should also be tagged CONJ and ADP, or should the form take priority (in which case it seems we should allow PUNCT with other functions than punct).

There are even more subtle cases like /, which is sometimes used as cc (or) and sometimes as case (per).

**Comment by dan-zeman** [comment]
As I understand the guidelines, these symbols should be tagged `SYM` and not `PUNCT`.

As for the equivalence, the current guidelines support at least one direction (PUNCT => punct), although I would find violating the other direction rather weird:

http://universaldependencies.org/u/dep/punct.html
_This is used for any piece of punctuation in a clause, if punctuation is being retained in the typed dependencies._

**Comment by jnivre** [comment]
You're right. I should have known this. Closing and fixing.
