### ISSUE TITLE
Coarse <-> Fine Tags

### ISSUE THREAD

**Issue by slavpetrov** [UniversalDependencies/docs#297]
It has been pointed out to me that the Italian and Spanish treebanks have a non-deterministic mapping of fine to coarse tags. In particular, the same 'fine' tag is mapped to different 'coarse' tags depending on the context. In both languages the fine POS-tag NO (ordinal number) is mapped both to PRON and ADJ coarse POS tags. I don't know whether we ever explicitly said that coarse and fine tags need to form a hierarchy, but I think it would be desirable if they did. Otherwise the relationship would be inverted and suggest that the coarse tags are actually finer.

The reason this came up is that SyntaxNet adds the coarse tags by mapping the fine tag deterministically (i.e. no more prediction and we hence wouldn't have a process of figuring out which coarse tag to use). I think this is better than having a separate prediction for the coarse tags.

What do you think about fixing this by adjusting the data and enforcing such a contract going forward?

**Comment by akutuzov** [comment]
The same is true for the English treebank, by the way. For example, the fine tag VB is mapped to VERB and AUX coarse tags, but there are many other cases as well.
Because of this, SyntaxNet is unusable on the UD English treebank, until one manually fixes these inconsistencies.

**Comment by dan-zeman** [comment]
We don't have anything like "coarse" and "fine" tags in UD. We have UPOS and XPOS. The latter is optional, taken from a language-specific tagset, if people want to keep it. So it can be really anything. I don't think we need any hierarchy here; that would kill the freedom people have in preserving their "national" tagsets.

If SyntaxNet needs to interpret these two columns differently, then I think people need to adjust their data (as they often need with other tools, too). The easiest thing would be to just copy UPOS to XPOS. (Or, perhaps, to concatenate UPOS and original XPOS in XPOS; that would create the "hierarchy".)

**Comment by dan-zeman** [comment]
Related: https://github.com/tensorflow/models/issues/118

**Comment by dan-zeman** [comment]
Perhaps we should put a warning about this somewhere on universaldependencies.org? And there was another format-related problem when people used CoNLL-U in programs which expected CoNLL-X, such as MaltParser; that could be described in the same section.
