### ISSUE TITLE
Nitpicking

### ISSUE THREAD

**Issue by omriabnd** [UniversalDependencies/docs#300]
Hi,
I there might be an inaccuracy in the phrasing here:
http://universaldependencies.org/u/overview/syntax.html
"This means that the dependencies can be thought of as a directed acyclic graph which is a tree (i.e., which has a single root)." 
But it is not equivalent for a DAG to be a tree and to have a single root. Are UDs required to be trees or single-rooted DAGs?
Thanks,
Omri

**Comment by fginter** [comment]
The validator enforces single-rootedness, so currently all UD data is single-rooted trees and I believe will stay so also in the future. I think you can just go ahead, edit the docs to be more clear in this respect, and close the issue. :)

**Comment by omriabnd** [comment]
OK. Thanks. I proposed a change.
