### ISSUE TITLE
Suggested clarification: English dative objects

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#301]
The [`iobj`](http://universaldependencies.org/docs/en/dep/iobj.html) documentation doesn't specify whether _to_-datives are included. It might be worth mentioning that they fall under `nmod`, as [that page](http://universaldependencies.org/en/dep/nmod.html) makes clear with an example.

**Comment by dan-zeman** [comment]
Fixed through https://github.com/UniversalDependencies/docs/commit/3b5dd583df6c034ccf12ff26d0f3dd155ef5943d
