### ISSUE TITLE
Partitives

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#302]
Are English partitives/collectives/measure phrases treated as regular PPs ("some of the answers", "a bunch of kids", "a grain of salt")? The [`nmod` documentation](http://universaldependencies.org/en/dep/nmod.html) has an _of_ example, but not a partitive.

**Comment by nschneid** [comment]
@sebschu

**Comment by ngiordani** [comment]
Yes! And @sebschu worked on changing this for the enhanced dependencies, but in the basic flavor we treat these as PPs.
