### ISSUE TITLE
English compound documentation

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#304]
The definition of [`compound`](http://universaldependencies.org/en/dep/compound.html) only mentions noun compounds. What about adjectival compounds like "a medium-large company"? Or "high-achieving student"? Or "rate-limited API"?

**Comment by nschneid** [comment]
@sebschu

**Comment by ngiordani** [comment]
We also treat those as compound! I think the documentation was probably imported from the old nn relation docs for SD, which were in fact concerned only with nouns. No longer the case!
