### ISSUE TITLE
English compound:prt clarification

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#305]
Should [`compound:prt`](http://universaldependencies.org/en/dep/compound-prt.html) only apply to _idiomatic_ verb particles, or also spatial ones like "She brought down the bed/She brought the bed down"? What about "Come over (here)"?

**Comment by nschneid** [comment]
@sebschu

**Comment by ngiordani** [comment]
Yup, just idiomatic!

**Comment by nschneid** [comment]
I would like to revisit the idiomaticity distinction that is made for `compound:prt` vs. `advmod`. What is the motivation? This rule seems to be anomalous in prioritizing semantic considerations over syntactic ones.

PTB tag guidelines say "the idiomaticity of a particular collocation is not a diagnostic for the distinction" and give a manner adverb insertion test. @amir-zeldes would also prefer to follow PTB, as discussed in UniversalDependencies/UD_English-EWT#116.

I do see that the idiomaticity test is given on the [universal guidelines page](https://universaldependencies.org/u/dep/compound-prt.html), not just the [English page](https://universaldependencies.org/en/dep/compound-prt.html). Does that mean it is in use for other languages?

**Comment by LarsAhrenberg** [comment]
I use the distinction both for Swedish and English (-Lines) although it is not so easy to make consistently. I make the distinction based on the interpretation of the particle. If it can be interpreted literally (directional or locative) I annotate it advmod, but if not, compound:prt. In the latter case the verb + particle can be seen as a lexical unit with a non-compositional meaning. I think the explanation using the word 'idiomatic' can be improved, perhaps avoiding that word altogether.

**Comment by amir-zeldes** [comment]
I think what counts as a compound is a language internal thing (at least for non-phrasal-verbs that is very clearly the case in current UD). For example in German, the things known as particles (as opposed to prefixes) have very clear morphosyntactic behaviors (insertion of a circumfixed past marker, word order in main and subordinate clauses), which cut across semantic classes. 

Maybe it makes sense for some language to make the distinction based on a class of spatial items which share some morphosyntactic properties, but I'm also skeptical that directional or locative semantics should be part of a universal-level syntax annotation guideline.

**Comment by nschneid** [comment]
> Maybe it makes sense for some language to make the distinction based on a class of spatial items which share some morphosyntactic properties, but I'm also skeptical that directional or locative semantics should be part of a universal-level syntax annotation guideline.

I could see a semantic property as valid as part of the definition of a comparative concept. In fact, we might say that one of the characteristics of what we call verb particles crosslinguistically is that they *can* bear directional or locative semantics in prototypical uses (with some verbs in some contexts), and specific morphosyntactic properties of verb particle constructions vary by language. But applying the semantic criterion at the *token* level seems problematic if we are trying to annotate syntax.

**Comment by colinbatchelor** [comment]
Irish has `compound:prt` - see https://universaldependencies.org/ga/dep/compound-prt.html but I will confess that I haven't implemented it for Scottish Gaelic because I'd need to create pretty detailed documentation to make sure I was doing it consistently.
I'd want, for example, to be sure of lots of the examples for _cuir_ here: https://faclair.com/ViewDictionaryEntry.aspx?ID=4CFD8CA09114C7C95730C6240C8706FE

I imagine the validation script would be a bit of a beast too.
