### ISSUE TITLE
English sentential adverbs

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#306]
The guidelines don't explicitly address sentential adverbs (like "maybe" or "unfortunately" when indicating the speaker's perspective). Should they always be dependents of the head of the sentence, via a [`discourse`](http://universaldependencies.org/en/dep/discourse.html) relation?

**Comment by nschneid** [comment]
@sebschu

**Comment by ngiordani** [comment]
We've been making them advmod on the root. But discourse is certainly not crazy. I guess we've been trying to keep the list of discourse-labeled items small.
