### ISSUE TITLE
Imitative reduplication

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#307]
This happens in English and probably other languages as well: "The pig went oink oink oink." "The bunny went hop hop." `mwe`? `goeswith`? `compound`?

**Comment by nschneid** [comment]
@sebschu

**Comment by ngiordani** [comment]
Well, mwe is (in theory at least :)) only for function words and goeswith is for things that would normally be spelled together, so I think compound is a good option here.
