### ISSUE TITLE
Tag questions

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#309]
The [English syntax notes](http://universaldependencies.org/en/overview/specific-syntax.html) don't seem to address tag questions: "You don't like my hair, **do you?**" [`dislocated`](http://universaldependencies.org/docs/en/dep/dislocated.html), perhaps?

**Comment by nschneid** [comment]
@sebschu

**Comment by sebschu** [comment]
We use the [`parataxis`](http://universaldependencies.org/u/dep/parataxis.html) relation for tag questions. I added an example to the documentation.
