### ISSUE TITLE
English NP postmodifiers

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#310]
What to do about NP postmodifiers like:
- "else"
- "both"/"all" in "we both/all had hamburgers" (these are sometimes called postdeterminers)
- "alone" in "One cannot live by bread alone"

**Comment by nschneid** [comment]
@sebschu

**Comment by manning** [comment]
Presumably we'd call _both_ and _all_ a det even when following a pronoun.

**Comment by manning** [comment]
_alone_ is tricky, since it's a sort of adverbial snuck into a noun phrase. But are we better off nevertheless calling it a post-posed amod? Presumably the same analysis would be used for _else_. Not so sure on these ones. Open to discussion of what seems best. (The Penn Treebank people never seemed to be sure either. Sometimes they become an ADVP inside an NP, sometimes an ADJP, sometimes they have no phrasal structure of their own.)

**Comment by manning** [comment]
UD_English does mainly analyze _else_ as amod. At least in the 90% of cases when the LDC annotators called _else_ an adjective. We should probably fix the remainder to be consistent.

**Comment by nschneid** [comment]
[Query for `amod` postmodifiers](http://bionlp-www.utu.fi/dep_search/?db=English&search=_+%3Camod%40L+_) — includes "else" and "alone"

**Comment by nschneid** [comment]
1. The postmodifying `amod` examples in the corpus include:
   - another looting...similar to the one that took place last April: `amod(looting, similar)`
   - employees unable to attend: `amod(employees, unable)`
   - diplomats intimately involved with the meeting: `amod(diplomats, involved)`
   
   Should these be treated as reduced relative copular clauses and thus [labeled with `acl`](http://universaldependencies.org/en/overview/specific-syntax.html)? Or does `acl` only apply when the dependent is a verb?
2. The following look like appositives to me, though [appos](http://universaldependencies.org/en/dep/appos.html) is described as requiring two NPs. And oddly, the "Appositives" section of [specific constructions](http://universaldependencies.org/en/overview/specific-syntax.html) is empty:
   - Labat, 24, was booked Tuesday: `amod(Labat, 24)`
   - 56 points, enough to meet the minimum requirement: `amod(points, enough)`
3. This feels a bit like [parataxis](http://universaldependencies.org/en/dep/parataxis.html):
   - He came across as a bright person, very personable: `amod(person, personable)`

**Comment by amir-zeldes** [comment]
About 2: This has always seemed a bit off to me, but in OntoNotes, ages after commas are treated as appositions on the coreference level as well. Their argumentation was that in something like "Labat, 24", the "24" can be taken to stand for "a 24-year-old", so it's really a normal NP. 

I can also see how 24, taken literally, is really just an attribute of Labat, but if consistency with coref annotation schemes is desirable, then that's another argument for making this be appos.

**Comment by dan-zeman** [comment]
I wonder whether this issue is still an issue or is it ready to be closed?
