### ISSUE TITLE
English "not X but Y" construction

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#311]
"Not X but Y" or "Not only X but (also) Y": Should the first part be a [`cc:preconj`](http://universaldependencies.org/docs/en/dep/cc-preconj.html)? It seems analogous to both-and, either-or, etc.

**Comment by nschneid** [comment]
@sebschu

**Comment by nschneid** [comment]
Reopening as this remains inconsistent in English-EWT.

## Not X but Y

E.g. "Not cheep , but very fast"; "They are not a national park , but are extremely beautiful .". This is treated as coordination, and "not" attached as `advmod`.

## Not only X (but (also)) Y

This is the harder and more frequent case. Several analyses are found:

### With *but*

1. Not only are these people completely inefficient and ineffective , but they just do n't give a darn .

       advmod(only, Not)
       cc:preconj(inefficient, only)
       conj(inefficient, give)
       cc(give, but)

2. ... used every day not only by terror chiefs but also by Western media .

       advmod(only, not)
       cc:preconj(chiefs, only)
       conj(chiefs, media)
       cc(media, but)

3. Not only that , but he told us , via his manager , that it was our responsibility ...

       advmod(that, Not)
       advmod(that, only)
       conj(that, told)
       cc(told, but)

### Without *but*

4. Bush not only showed-1 up , he showed-2 up a lot .

       advmod(only, not)
       advmod(showed-1, only)
       conj(showed-1, showed-2)

5. Not only am I being bilked for money I do not owe , the office staff is rude to boot .

       advmod(only, Not)
       cc:preconj(bilked, only)
       conj(rude, bilked)

6. not only is this place too expensive for what it is , it s horrible !

       advmod(only, not)
       advmod(expensive, only)
       advcl(horrible, expensive)

7. Not only did Bush not know who General Pervez Musharraf was , he seems ...

       advmod(only, Not)
       advmod(know, only)
       parataxis(seems, know)


To summarize:

* Usually `advmod(only, not)`, but occassionally "only" and "not" are sister `advmod`s.
* The relation of "only" to its head varies: `cc:preconj`, `advmod`
* Without *but*, the relation between the two parts of the expression varies: `parataxis`, `conj` (in both directions), `advcl`

The analysis in (1) and (2) using `cc:preconj` makes the most sense to me for the coordination with *but*.

The sentences without *but* seem perfectly natural, too. It is less natural to omit the *but* if the second part is not a finite clause: "used every day not only by terror chiefs but also by Western media" sounds elliptical if shortened to "used every day not only by terror chiefs, also by Western media"; and "used every day not only by terror chiefs, by Western media" sounds completely bad. Thus, I think the `advcl` analysis as in (6) makes sense: the first part is a subordinate clause (kind of like a concessive?), rather than a coordination conjunct.

I presume `cc:preconj` should only be used with coordination, not subordination, so attaching "only" as `advmod` seems reasonable in the cases without *but*.

**Comment by jnivre** [comment]
First of all, I think it is coordination in all cases. Depending on your preference, you could perhaps use parataxis when there is no overt "but", but there is no evidence that there is subordination, so "advcl" is out. I am less certain about the relation for the "not only". At first, I thought "advmod" seemed fine (and I think this is what we have in the Swedish treebanks) but I agree that "not only" ... "but" has some affinities with "both ... and" and "either ... or", so "cc:preconj" is definitely worth considering. What speaks against is that the second part can be omitted. Compare:

both X and Y
X and Y
*both X, Y

either X or Y
X or Y
*either X, Y

not only X but Y
X but Y
not only X, Y

**Comment by nschneid** [comment]
I found a discussion in the Cambridge Grammar of the English Language (p. 1314):

![img](https://user-images.githubusercontent.com/985263/39192302-e777ed44-47a6-11e8-9793-8d6810d65d9d.png)

"It is questionable whether this construction is a case of asyndetic coordination or simply one of juxtaposition."

**Comment by jnivre** [comment]
Juxtaposition would imply that "parataxis" is the right relation.

**Comment by amir-zeldes** [comment]
The examples in 66 in the Cambridge grammar all don't have 'but', so I think parataxis is right, but if there is a 'but', I would say it's a regular conj. I also like sticking the negation on 'only'. I think there is a prosodic difference if it's (not (only X)), and the default reading I get for these is ((not only) X). But that may be subjective...

**Comment by jnivre** [comment]
I agree it should be "conj" if there is an overt "but".

**Comment by nschneid** [comment]
As to the no-*but* case: Under current guidelines, `conj` would cover asyndetic coordination, whereas `parataxis` would cover juxtaposition. There are other cases where it is difficult to distinguish the two: #541 

Should we err on the side of parallelism with the *but* case and call both `conj`?

**Comment by dan-zeman** [comment]
+1 for calling both `conj`.

**Comment by jnivre** [comment]
Fine with me too.

**Comment by sylvainkahane** [comment]
If I understood what the Cambridge grammar says, "not only X but Y" can be subordinated, but "not only Y, Y" cannot. It is correct, we have two different constructions, which justifies to have two different relations. I think that `conj` is clear for "not only X but Y" and that `parataxis` is a good option to mark the contrast between the two constructions.

In French we have the same two constructions: "non seulement X mais Y" and (with more difficulties) "non seulement X, Y". Only the former is subordinatable and interstingly the complementizer is repeated, which is a very good argument for coordination: "je pense **que** non seulement X, mais **que** Y" or "je pense non seulement **que**  X, mais **que** Y".

**Comment by nschneid** [comment]
> If I understood what the Cambridge grammar says, "not only X but Y" can be subordinated, but "not only Y, Y" cannot.

I think that is the claim, though I'm not sold on it. The supposed ungrammatical example they give does seem a bit odd, but I found a couple examples on the web that sound fine:

* It was a brave thing to say at the time, **since not only** was it a strain, it was probably the largest strain, at least among professional Jews whom many in the media like to pretend speak for the entire community.
* Saxon is a fascinating case, **since not only** does she have her own stress to contend with, she has the inherited (within limits) stress of her subjects and their loved ones and the theoretical realm in which she seeks to determine the role of stress in both developing and/or compounding heart disease.

So maybe it is possible with a long subordinate clause that is subsequent to the matrix verb.

**Comment by dan-zeman** [comment]
I do not think there is much benefit in distinguishing the "two different constructions" by labeling one as `conj` and the other as `parataxis`. I have the feeling that `parataxis` itself mixes various constructions that are more different from each other than this.

**Comment by sylvainkahane** [comment]
It is true that `parataxis` must be refined, but the coordination is a quite well defined construction.  I don't know examples of a coordination XY where XY has not the same distribution as X and Y (except for the agreement). It is possible that _not only_ without _but_ works as a kinf of exclamative word that take the head of the sentence and change its distribution. But the data are flimsy since @nschneid has given us examples of subordination, so we can retain `conj`.
