### ISSUE TITLE
English nmod:npmod documentation

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#312]
[`nmod:npmod`](http://universaldependencies.org/docs/en/dep/nmod-npmod.html) lists several scenarios in which a noun phrase functions as an adverbial modifier.
- Presumably this excludes adverbial PPs? The noun is just an `nmod` of the verb, right?
- Should adverbial nouns like "home" in "We went home" be listed?
- "Nominal modifiers not introduced by a preposition or not ‘s genitives": should this read "not marked by a preposition or genitive 's"?

**Comment by nschneid** [comment]
@sebschu

**Comment by sebschu** [comment]
> Presumably this excludes adverbial PPs? The noun is just an nmod of the verb, right?

Yes, that's correct.

> Should adverbial nouns like "home" in "We went home" be listed?

Currently, we (or actually the LDC) are tagging "home" as an `ADV` and attaching it with an `advcl` relation.

> "Nominal modifiers not introduced by a preposition or not ‘s genitives": should this read "not marked by a preposition or genitive 's"?

Yes.
