### ISSUE TITLE
Fix POS tags of “muito” in UD_Portuguese

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#314]
Most of the occurrences of _muito_ were originally tagged "adv &lt;quant&gt;". The "quant" part caused Interset to take it as indefinite quantifier, which later led to `DET` in UD. It should be `ADV` instead.

**Comment by dan-zeman** [comment]
Apparently the adverbial instances of _muito_ have already been fixed. There are still a few others which are tagged `DET` but these indeed modify a noun, as in _muito tempo_ "much time". I think these are fine as determiners. Tentatively closing the issue.

**Comment by arademaker** [comment]
From @dan-zeman comment on https://github.com/UniversalDependencies/UD_Portuguese/issues/1#issuecomment-241219083

**Comment by dan-zeman** [comment]
@arademaker : So what is the issue now?
