### ISSUE TITLE
Vocative in imperatives in Uralic

### ISSUE THREAD

**Issue by flammie** [UniversalDependencies/docs#320]
We are currently in process of writing the general guidelines for Uralic languages, and have come upon a disagreement. 

In sentences such as:

```
"Nyisd ki az ablakot, Sam!" (hun) 
"Avaa ikkuna, Sam!" (fin)
```

Should the relations dep(Nysid, Sam) and dep(Avaa, Sam) be nsubj or vocative?

I was thinking that cause it agrees with plurals like so:

   "Avatkaa ikkuna, Sam ja Max"

it seems like nsubj could be right?

**Comment by manning** [comment]
If the nominal is clearly vocative, as in the examples here (I believe), then I think the right answer is to label them vocative. Even though vocatives commonly co-occur with a null subject, it seems that the correct grammatical relation here is vocative.

**Comment by dan-zeman** [comment]
I agree with @manning. In a sense, `vocative` can be seen as a special type of subject, if we admit that imperative verbs have subjects at all. If we label it `nsubj` here, then we should probably use `nsubj` everywhere, and the `vocative` relation would have no use. But I like the idea of having a separate label for vocative “subjects”.

(NB: In Czech, the imperative would also use 2nd person plural form when addressing multiple people. But in addition the nouns would have vocative suffixes while normal subjects are in nominative.)

**Comment by vinczev** [comment]
I'd say it is vocative, as at least in Hungarian we can easily add the 
pronominal subject ("te") in such cases, which should be nsubj then:

"Te nyisd ki az ablakot, Sam!" (Open the window, Sam or You should open 
the window, Sam)

Thus:

nsubj(nyisd, te)
vocative(nyisd,Sam)

We can do that in the plural too:

"Ti nyissátok ki az ablakot, Sam!" (You guys should open the window, Sam)

So I think it is the (hidden) pronoun that triggers the agreement, not 
the vocative phrase.

**Comment by osenova** [comment]
Thank you all for the nice discussion!

In Bulgarian we always differentiate between vocative and nsubj in cases with proper or common names:
E.g.: Ivan/Mister (vocative), pro-drop/you (nsubj) come here.

In cases with ‘hey you’ we assume that the pronoun ‘you’ has two syncretic forms – vocative and nominative.
So, we could have two situations: Hey you (vocative), come here! and You (nsubj) come here!
In the former disagreement is allowed: Hey you (SG), you(PL) come here!, while in the latter no disagreement is allowed: You(SG) come (PL) here!
For us the vocative is always pragmatically distinguished (also by the punctuation role).

Here is a link to our paper with our views on the vocative: http://web.stanford.edu/group/cslipublications/cslipublications/HPSG/3/osenova.pdf

Best,
Petya and Kiril

**Comment by ftyers** [comment]
We have stated vocative as a Uralic standard in the documentation, with examples from Estonian and Finnish. There is only one example in the Hungarian treebank, which is pretty long: 

> Akkoriban kezdtem egyre jelentősebb szerepeket kapni , s egy Bánk bán után , amelyben akkor Biberachot alakítottam , Palló Imre , a kiváló bariton azt mondta nekem : " Gyuri fiam/_vocative_ , name felejtsd el , előadás után indulás haza .

So I haven't included it yet.

https://github.com/UniversalDependencies/docs/blob/pages-source/_urj-dep/vocative.md
