### ISSUE TITLE
acl:relcl consistency issues in Uralic

### ISSUE THREAD

**Issue by flammie** [UniversalDependencies/docs#325]
We are comparing Uralic languages and treebanks for dependencies now.

There is an inconcsistency between UD_Finnish and UD_Estonian, and UD_Finnish_FTB and UD_Hungarian for the acl:relcl dependency relation, the former two using it and latter two aren’t.

In general the relcl seems to us like a uralic-wide feature at least, a short explanation should appear in http://universaldependencies.org/urj/dep/acl.html

**Comment by manning** [comment]
I guess that to some extent it is optional whether languages/treebanks want to use the specializations of universal dependencies like "relcl". But, yes, it does seem to me too that Hungarian also has the same kind of finite relative clauses for which relcl was intended.
