### ISSUE TITLE
English conventions for free relative clauses

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#326]
The [English syntax notes](http://universaldependencies.org/en/overview/specific-syntax.html) devote a section to free relatives.
1. Some of the examples use `rcmod`, which I take it has been replaced by `acl:relcl`. Should they be replaced?
2. I am confused about the distinction between free relatives and other WH-clauses.

The page states: "In the canonical case, wh-clauses function as interrogative clauses or as adverbial clauses. In these cases, the head of the wh-clause is taken to be the verb". Examples:   
- (131) I need to know who you are planning to leave with .
- (132) When you leave , be sure to let me know .

"In free relative constructions, the wh-clause functions as an argument in the lower clause. In these cases, the wh-phrase is deemed the head of the construction". Examples:
- (133) I 'll have whatever she 's having .
- (134) I love how well everyone behaved .

Should that read "the wh-clause functions as an argument in the **higher** clause"? I.e., the free relatives are arguments to the matrix verbs _have_ in (133) and _love_ in (134)?

**Comment by nschneid** [comment]
CC: @ida-szubert

**Comment by sebschu** [comment]
> Some of the examples use rcmod, which I take it has been replaced by acl:relcl. Should they be replaced?

Yes, this is wrong. I replaced all of these with`acl:relcl`.

> Should that read "the wh-clause functions as an argument in the _higher_ clause"?

Yes. I also fixed that.

In case you are interested, you can find more information on free relatives in [de Marneffe et. al (2013)](http://www.ling.ohio-state.edu/~mcdm/papers/depling.pdf) and in [Bresnan and Grimshaw (1978)](https://www.jstor.org/stable/4178069?seq=1#page_scan_tab_contents).
