### ISSUE TITLE
Should 'going to' future get special treatment?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#327]
Currently, there is no disambiguation between "going to" when it marks future time (= "gonna") vs. when it marks a destination or purpose of motion.

[This query](http://bionlp-www.utu.fi/dep_search/?db=English&search=going+%3Excomp+%28_+%3E+to%29) shows both kinds of results: "2005 is going to rock" and "I am going out tonight to get wasted" both have an `xcomp` linking "going" to the infinitive verb and, the "to" is a `mark` dependent of the infinitive verb.

To disambiguate, the future usage could arguably be analyzed as [`mwe`](http://universaldependencies.org/en/dep/mwe.html) (as we have done in the [MWE annotations](https://github.com/nschneid/nanni/wiki/MWE-Annotation-Guidelines) for STREUSLE). A similar policy could apply to "ought to", "about to", "have to" (obligation or necessity), and other "quasi-modals".

**Comment by sebschu** [comment]
Thanks for pointing this out -- this is actually an annotation error. _wasted_ in "I am going out tonight to get wasted" should actually be attached to _going_ with an `advcl` relation, as "to get wasted" is not a complement of the verb. 

If _going_ is used as a motion verb, the locative goal is attached with an `nmod` relation.

I'll fix the example in the treebank but I think in general it is easy to disambiguate these cases without analyzing _have to_ as a `mwe`.

**Comment by nschneid** [comment]
OK great. I looked through the first 60 examples that from the above query. The only other one that looks suspicious is:

"I was just going to sleep anyway"—ambiguous without more context, but my default reading is not future
