### ISSUE TITLE
Features for infinitives and participles / Uralic consistency issues

### ISSUE THREAD

**Issue by flammie** [UniversalDependencies/docs#328]
This is an inconsistency we noticed while describing Uralic best practices for dependencies: most Űralic languages have numerous verbal forms called infinitives and participles, and there are inconsistencies in features used to mark these. (Sorry for sending two issues in one report, I think they cannot be solved separately from each other)

For Infinitives:
Finnish UD uses `VerbForm=Inf` and `InfForm` as language specific features, with values of: `InfForm={1,2,3}`, Estonian has basically same set of forms but uses `VerbForm={Sup,Ger}`  for infinitive forms with suffix "ma", "e" and just `VerbForm=Inf` for the infinitive with suffix "da" only.

For Participles:
Finnish UD uses `VerbForm=Part` and `PartForm` as language specific features, with values of: `PartForm={Pres,Past,Agt,Neg}`, Estonian has basically same set of forms but uses: , but `VerbForm=Part` with `Tense={Past,Pres}`. Hungarian uses `VerbForm={PartPres,PartPast}` for participles. 

Suggested:
- VerbForm should tell the syntactic function of the form, e.g. Part, Inf, Ger, Trans, Fin
- The specification of which verb form it is should be done using normal features, and only including those relevant, so if Tense is not relevant, leave it out
- If The exact morpheme (i.e. "da", "A", "e", "nUt" as well as "1, 2, 3, ...") is stored, it should go in the misc column

(Some) Rationale:
I think for participles, it might make sense to unify for Estonian approach of using `VerbForm=Part` and `Tense=`. I am not so sure mapping different infinitives to `VerbForm={Sup,Ger}` would not be faced with some resistance in Uralic linguists, practically this might be the most sensible way.

**Comment by dan-zeman** [comment]
Note that Finnish infinitives have also been discussed in #107.

**Comment by dan-zeman** [comment]
Any development here? @jmnybl @jpiitula @kailimp @flammie @rueter @nikopartanen @vinczev
