### ISSUE TITLE
POS tags of time specifications

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#331]
In expressions like _they close at 4 pm_, the number _4_ is a separate token and there is no doubt it shall be tagged `NUM`. If the time specification is _4:30_ instead, some treebanks tag it `NUM` too, apparently as an analogy to decimal numbers (_3.14_ or _3,14_ depending of what the local decimal separator is). However, the specification could also read _4h30_. Now it is clearly no longer a pure number, because of the _h (hours / heures / horas / hodin / whatever)._ One may thus want to opt for `NOUN` or `SYM` instead of `NUM`. Moreover, one could argue that the _4:30_ form is read/understood _four hours thirty_ and should not be `NUM` either.

Background: This issue was originally raised by @vcvpaiva in https://github.com/UniversalDependencies/UD_Portuguese/issues/4 but I am moving it here because it is something that could and should be standardized on the universal level.

**Comment by manning** [comment]
In English, following what the LDC annotators do, we do regard "4:30" and purely numeric data expressions like 7/11/2004 as NUM. The argument for calling these NUM isn't very strong, but I tend to feel that there's even less reason to call them SYM or NOUN. Are there any clear arguments from other languages, or should we just call them NUM and move on?

**Comment by dan-zeman** [comment]
Should we extend the same treatment to "4h30" then?

**Comment by claudiafreitas** [comment]
@dan-zeman , any news here?

> The argument for calling these NUM isn't very strong, but I tend to feel that there's even less reason to call them SYM or NOUN. Are there any clear arguments from other languages, or should we just call them NUM and move on?

And what about ADV? "Adverbs are words that typically modify verbs for such categories as _time_..."

1. The meeting will be at _3:30pm_
2. The meeting  will be at _15h30min_ 
3. The meeting will be _tomorrow_

Should we consider 20h30min a single token? (I think so, just checking). And what if there is a blank? “20h 30min”? Still a single token? (I think so…)

**Comment by dan-zeman** [comment]
I don't think we must introduce tokens with spaces just because they happen to be complex time expressions. Connecting _20h_ and _30min_ via a `flat` relation looks perfectly satisfying to me.

**Comment by arademaker** [comment]
What about http://universaldependencies.org/u/dep/nummod.html ??

We will have cases with flat and  nummod ? I suspect many parsers will not take into consideration the misc column for learn the spaceAfter as a justification for the flat. We will introducing inconsistencies for the parsers.

We can also use the multiword tokens.

Sent from my iPhone

**Comment by vcvpaiva** [comment]
but @dan-zeman  just to be clear,  do we say that _4:30pm_ or _4h30min_ are NUM, just as much as _4:30_?
or de we say _4h and 30 min_  is flat, so _4h30min_ is flat too?
maybe the question was answered in a meeting somewhere, but it's not in the thread. sure tomorrow is an adverb, but the specific times don't feel adverbial to me.

**Comment by dan-zeman** [comment]
No, I don't think it has been discussed in a meeting. Looking at the thread above, it seems acceptable (or at least not worse that the other options) to say that _4:30pm_ is `NUM`. Same for _4h30min_ if it is one token.

**Comment by vcvpaiva** [comment]
thanks then.
