### ISSUE TITLE
Can "not only" and "but also" be marked as mwe?

### ISSUE THREAD

**Issue by yaqinwang** [UniversalDependencies/docs#333]
Can the fixed expression "not only" and "but also" be marked as mwe?

**Comment by nschneid** [comment]
[Treebank search for "not only"](http://bionlp-www.utu.fi/dep_search/?db=English&search=not+%3C+only)

It looks like the annotations are not entirely consistent. Some attach "only" to its head with `cc:preconj`, others use `advmod`.

Something to keep in mind is that "but (also)" is optional: "Bush not only showed up, he showed up a lot."

There are also "but also" occurrences without "not only": "a bar would be nice but also something unique".

**Comment by nschneid** [comment]
See also #311

**Comment by yaqinwang** [comment]
Thanks for your comments! The search page is helpful for me.
