### ISSUE TITLE
Apposition in Kurdish

### ISSUE THREAD

**Issue by MemduhG** [UniversalDependencies/docs#334]
We came across a sentence the annotation of which seems to be tricky, with regards to subject, apposition and their relation.

_Hingê ez û xweha xwe Cûlya; em her du jî du-salî bûn_
So I and my sister Julia; we both were two-year-olds.

Either _ez û xweha xwe Cûlya_ "I and my sister Julia" or _em her du_ "we both" should be the subject, with the other one attached as `appos`. I am not sure which one should be the subject, as the part that would usually be considered an apposition is given before rather than after what would be the subject.

**Comment by dan-zeman** [comment]
This looks like a perfect example of the `dislocated` relation, http://universaldependencies.org/u/dep/dislocated.html

I would make _em her du_ the subject and _ez û xweha xwe Cûlya_ a dislocated dependent, both attached to the main predicate.

**Comment by ftyers** [comment]
This looks good, thanks! :)
