### ISSUE TITLE
Determiners in German UD Data

### ISSUE THREAD

**Issue by alanakbik** [UniversalDependencies/docs#337]
Hello all, 

we have been looking into the German UD datasets to see why numbers reported for German are generally lower than for other languages (for instance, the monolingual baselines reported [here](https://pdfs.semanticscholar.org/481e/de306724e285225f00898d6305a0593d424b.pdf)). 

We found a number of inconsistencies and potentially suboptimal annotations and would like to check back with the community. For instance, there are a large number of "det"-dependencies that probably should not be marked as determiners:

**Genitive noun modifiers**
In the training data, there are over 6000 nouns marked as determiners. These seem to be genitive nouns that modify another noun. For instance, in "Behebung der Probleme" (the fixing of problems), the noun "Probleme" is marked as determiner to "Behebung" (fixing). Another example is "Behandlung verschiedenster Leidern" (treatment of various ills) in which the noun "Leiden" (ills) is marked as "det" to "Behandlung" (treatment). 

We suggest to use an "nmod" dependency here, like in other noun modifiers, possibly subtyped as "nmod:gen" to indicate the genitive nature of the noun modification. 

**Possesives**
Possessives are sometimes marked as "nmod:poss" and sometimes, in over 300 cases, as "det". For instance, in "meine Frau" or "meine erste Wahl", the possesive "meine" is marked as "det". 

Both issues are fairly easy to correct automatically. Should the community agree to these changes, we could potentially commit these corrections.  

Kind regards, 
Alan

**Comment by dan-zeman** [comment]
Thanks for the report. Genitive nouns attached as `det` are clearly a bug; fixed in https://github.com/UniversalDependencies/UD_German/commit/8912522fd89f80733fb2428f9b36cd4c72804059. Attachment of possessive determiners was unified to `det:poss` in https://github.com/UniversalDependencies/UD_German/commit/ba56df74028a156a473ec19f2e84fce8baed6107.

**Comment by alanakbik** [comment]
Sure! Glad we could help!
