### ISSUE TITLE
det:predet is not attested in the Russian treebanks

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#340]
det:predet is mentioned as a language-specific relation for Russian. Why?
I could not find any traces of this relation in two Russian treebanks (Google and SynTagRus) and in the documentation.

**Comment by dan-zeman** [comment]
Did you mean in the lists of language-specific relations for the validator, in the tools repository (http://github.com/UniversalDependencies/tools/tree/master/data)? I suspect that these files were just cloned from English. I removed `det:predet` and also `conj:preconj` now.
