### ISSUE TITLE
Tokenization of words with hyphens

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#342]
Originally mentioned by @olesar in #341 but it is a separate issue, hence I am moving it here:

In UD_Russian-SynTagRus v.1.4:
- words with hyphen are treated as separate tokens linked with "goeswith", in line with UD-Russian-Google
- do we really need this?
- http://universaldependencies.org/u/overview/tokenization.html has no guidelines on that.

Olga

**Comment by ftyers** [comment]
In some languages bound morphemes are written with a hyphen, consider Mari:

```
пӧртем "my house"
пӧртем-влак "my houses"
пӧрт-влакешем "into my houses"
```

I wouldn't like to split this. And I think that clitics in the Romance languages (as in Portuguese, Catalan, Sardinian [where they use · not -]...) are better kept as a single token and dealt with using the CoNLL-U standard.

**Comment by dan-zeman** [comment]
I think that dealing with hyphens should be language-specific. Sometimes it may be even useful to have different rules for different usage within one language.

Unfortunately, there are interferring technical issues. It would be nice if the low-level tokenization could work independently of the language, using just Unicode character properties and maybe a few regular expressions to capture things like e-mail addresses.

**Comment by olesar** [comment]
Exactly, we use "different rules for different usage" (i.e. lemmas) in the Russian National Corpus. However, it is not convenient if we evaluate other tools. In RU-EVAL evaluation tracks, we use the maximum split strategy.On the other hand, this involves the over-use of "X" pos-tags in a treebank, or it changes the usage pattern of other pos-tags (ADV, ADJ, NOUN). Olga

**Comment by spyysalo** [comment]
@dan-zeman : did v2 bring any clarity to this issue?

> words with hyphen are treated as separate tokens linked with "goeswith", in line with UD-Russian-Google

This does not agree with the definition of http://universaldependencies.org/u/dep/goeswith.html .

**Comment by dan-zeman** [comment]
@spyysalo : I do not think it has been discussed during the preparation of v2 guidelines.

`goeswith` is wrong, and it is still (UD release 1.4) used in UD_Russian, see the treebank statistics at http://universaldependencies.org/ru/dep/goeswith.html. I am re-classifying this issue as a bug in UD_Russian. It seems to have been fixed in UD_Russian-SynTagRus: `grep goeswith` returns nothing there.

**Comment by olesar** [comment]
In UD_Russian-Google, we just kept them "as is" using data from Google - while waiting for the decision. Now it is clear that it is definitely a bug, so we will work with that.In the original UD_Russian-SynTagRus treebank, they have a separate POS and separate deprel for such things, which is converted into ADJ;compound in UD.1. I am not sure that this is the right way to go. The main issue with the hyphenated words is that they can have two endings, one before hyphen and another one in the final position (and sometimes these word parts differ in gender, or number, etc). Shell we use three tokens and appos in this case then? Olga

**Comment by dan-zeman** [comment]
If it is three tokens, the hyphen should be attached to the dependent word using the `punct` relation.

Which word is the dependent and what is its relation to the governor should be decided individually for different classes. There are two instances in the treebank statistics referenced above, and they are not the same. In the case of _Буркина - Фасо_, I think we should do

flat(Буркина, Фасо)
punct(Фасо, -)

although I am not completely sure about the `flat` relation. It is not so flat because _Буркина_ would inflect and _Фасо_ would not, so maybe `nmod` is an alternative. But I would not use `appos`. And both words should be tagged `PROPN`.

The other example is _1960 - х_ “1960s” (`Case=Gen`). Here I believe it would be appropriate to collapse it to one token, tagged `ADJ Case=Gen|Number=Plur|NumType=Ord`. Unfortunately it would make the first-level tokenization less low-level and more language-dependent. But splitting it to three tokens and then joining them back with `goeswith` does not make much sense, and `goeswith` is meant for “poorly edited source text,” while here the source was OK. `fixed` is not suitable either because this is not a fixed multi-word expression. And _-х_ is not a syntactic word, it is just a morpheme (plural genitive adjectival suffix), thus even `compound` seems a bit off.

**Comment by dan-zeman** [comment]
Edit: Perhaps I was mistaken in claiming that _Буркина_ can inflect. _Burkina_ can inflect in Czech but maybe not in Russian. In the cited example, it should actually be in genitive _(Burkiny)_ but it is in the base form instead.

**Comment by olesar** [comment]
The right example is Moskva-reka and Rostov-na-Donu. Indeed, Burkina-Faso is like Pa-de-Kale in Russian (not inflected). Some toponyms can follow both models so we would like to distinguish them.
