### ISSUE TITLE
Error in ADP POS tag for French language

### ISSUE THREAD

**Issue by MacMachin** [UniversalDependencies/docs#343]
There are errors in the page ADP for French language due to orthographic errors in the initial texts:
- "à" is <b>never</b> an <code>AUX</code> or a <code>VERB</code>, the <code>VERB</code> is "a" without the accent ;
- "à" is not a <code>NOUN</code>, in the example it should be written with quotes because the text speaks about the word "à" ;
- "par" is <b>never</b> a <code>VERB</code>, the <code>VERB</code> is "part" or "pars" ;
- "sur" could be an <code>ADJ</code> but not in the example given where it should be written "sûr" with a circumflex accent ;

**Comment by olesar** [comment]
I am mostly out of email until October 11.
Olga

**Comment by mcdm** [comment]
@MacMachin These are not errors. The statistics below the POS guidelines are automatically computed. As you say, there are orthographic errors in the original texts, but we annotate the data with the intended POS. So if "à" is used as a verb, it is tagged VERB.

**Comment by MacMachin** [comment]
@mcdm What a silly answer ! These are not errors but there are errors !
Your parser is not able to detect errors and you are proud of that ? And you want to keep them ?
If your data are not reliable they are not useful. You should better correct them.

**Comment by mcdm** [comment]
@macmachin I think you are misunderstanding things here. The statistics are just counts, not results from a parser. We are doing corpus annotation, and we keep the text _as is_: if the text is incorrect, we don't modify it.
