### ISSUE TITLE
Inconsistency in dislocated doc page

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/docs#345]
on page http://universaldependencies.org/fr/dep/dislocated.html:
it is written: 

_"Dislocated elements are attached to the same governor as the dependent that they double for."_ 

but in the example, the governor of _Pierre_ is _l'_; it should be _aime_.

**Comment by manning** [comment]
I agree, this is wrong. I've corrected the documentation example, but the one example of actual use in the treebank is also wrong in the same way, as this page also shows. This anti-pattern has also been picked up in other languages. There are also a couple of examples in English which are wrong in the same way. We should try to get this all correct for v2.

**Comment by manning** [comment]
Sending to @mcdm

**Comment by mcdm** [comment]
This has been fixed in the French treebank in v1.4.
