### ISSUE TITLE
Sorani Clitics with Verbs and Segmentation

### ISSUE THREAD

**Issue by MemduhG** [UniversalDependencies/docs#346]
The segmentation of Sorani is an issue that I believe concerns many similar languages, particularly those in the Iranian family like Persian. Working on the morphological analysis of the language I saw that with ergativity in particular, Sorani can get quite complicated, with regards to the positions of agreement affixes and pronominal clitics. I am not yet going to go into possessives or compare them with those of Persian, because that might make an already complicated issue even more difficult to puzzle out.

I am writing in a transliteration of the Perso-Arabic script.

I will go over a number of past tense, ergative examples first, but there are situations in the present tense where segmentation of clitics is an issue as well. As a rule of thumb, the agentive clitic/affix seems to precede the patient agreement, with the exception of the third person, where the rule is reversed. 
# Past

The following seem to be roughly hierarchical in terms of choice of position of the pronominal clitics.

If there is a non-pronominal object explicitly written out, the agentive clitic is joined to the end of this object.  

_sêvaka-**m** khward_ I ate the apple
_sêvaka-**m** nekhward_ I didn't eat the apple

When there is a substantive that forms a light verb construction together with the verb, the agentive clitic is at the end of the substantive.

_bang-**im** kird_     I called him.
_bang-**im** nekird_ I didn't call him.
_bang-**im** kirdit_     I called you.

For transitive verbs not in a light verb construction, with a pronominal patient and agent, both are at the end of the verb, in an order depending on the person.

_khward-**im**_ I ate it/him/her (third person agreement is lack of suffix)
_khward-**im**-it_ I ate you
_khward-im-**î**_   It ate me. The third person singular agentive goes to the end, as opposed to the others.

The tricky bit about this last category is negation, where the agentive affix is added to the end of the negative prefix.

_na-**m**-khward_    I didn't eat it.
_na-**y**-khward-im_ It didn't eat me.

It looks like we might need to split them into more tokens, however I do not know exactly what the relation, lemma or features of the split tokens will be. In situations like the earlier _namkhward_ (I didn't eat it), a possible splitting could be roughly:

```
1-2 namkhward
1   m       m   PRON    _    Person=1|Number=Sg
2   nakhward    khwardin    VERB    _    Tense=Past|Negative=Neg|Person=3|Number=Sg
```

This would make it syntactically match the pattern of when it takes a non-pronominal object.

```
1-2 Sêvakam
1   sêvaka sêv    NOUN    
2   m       m   PRON    _    Person=1|Number=Sg
3   nekhward    khwardin VERB    Tense=Past|Negative=Neg|Person=3|Number=Sg
```
# Present

A similar situation is the present tense conjugation of the verb "to want" (wistin). Pronominal clitics attached to the object along with the unchanging form of the verb give the personal agreement. 

_Sêvaka-m dawe_ I want the apple
_Sêvaka-m nawe_ I don't want the apple
_Sêvaka-t dawe_   You want the apple
_Sêvaka-y dawe_   He/she/it wants the apple
...

In situations where the complement does not precede the verb, the agreement is as follows. The pronominal clitic comes after the modal prefix. 

_da-m-awe_ I want
_da-t-awe_   You want
...

This is the case for any present transitives with a pronominal objects, except the object is what takes the place between the present indicative modal prefix _da_ and the rest of the verb.

_da-y-khom_  I am eating it
_da-m-khwa_ It is eating me

Reference: Thackston, Sorani Kurdish - A Reference Grammar with Selected Readings

**Comment by dan-zeman** [comment]
Since the agreement morphemes can attach to other words and not just the verbs, separating them as syntactic words is probably the best way to go. (If they stayed with the verb, we could also say they are the `Person` feature of the verb.)

So is there any issue with attaching the clitic to the verb as `nsubj`? (And in the case of _khward-im-î_, the _î_ would be attached as `dobj`.)

**Comment by ftyers** [comment]
I think your description and proposal is pretty fine. And agree with Dan that using standard relations `nsubj` and `dobj` is the way to go. However, is it possible to have an expressed pronoun too ? e.g. would something like "Man sêvaka-m dawe" be possible ?

**Comment by MemduhG** [comment]
I think a pronoun is usually not present if there is a pronoun of the same number/person as a clitic on the verb, but I do not think it is impossible. In the case of _Min sêvaka-m dawe_ how would it be parsed? It looks more like agreement when there is both a pronoun and an agent clitic. This could be a possible solution:

```
1    Min    min    PRON    conj    3    
2-3    sêvakam
2    sêvaka    sêv    NOUN    dobj    4
3    m    m    PRON    nsubj    4
4    dawe    wîstin  VERB  root    0
```

When they are _not_ the same person it would probably end in the unbound pronoun being an `nmod`. I wonder if it would make sense to use `nmod` for all such situations even if they do agree. It would especially make sense, I think, for situations where the verb _wîstin_ "to want" does carry a pronominal clitic. The example below is _damawe bichim_, "I want to go."

```
1-2    Damawe
1    m    m    PRON        Person=1|Number=Single    nsubj    2
2    dawe    wîstin    VERB    Tense=Present    root    0
3    bichim    chun    VERB    Mood=Subjunctive|Person=1|Number=Single    ccomp 2
```

As far as I know it is possible to add a pronoun before this. So this is roughly how it would look with an `nmod` relation: 

```
1    Min    min    PRON    Person=1|Number=Single    nmod    3
2-3   Damawe
2    m    m    PRON        Person=1|Number=Single    nsubj    3
3    dawe    wîstin    VERB    Tense=Present    root    0
4    bichim    chun    VERB    Mood=Subjunctive|Person=1|Number=Single    ccomp    3
```

**Comment by dan-zeman** [comment]
This sounds like clitic doubling to me, in which case one of the pronouns (_min_?) would be `expl`. What would it mean if the full pronoun is not the same person and number as the clitic?

BTW, shouldn't _bichim_ in the above examples be `xcomp` instead of `ccomp`?

**Comment by MemduhG** [comment]
I would be happy with `expl` for doubled clitics. AFAIK if they are not the same number and person then the full pronoun is an indirect object. 

As for _bichim_, I neglected to put in the verbal agreement in my original comment, it has first person singular agreement. Since it has agreement and works as a clausal object I thought `ccomp` would fit, however I am happy to make any changes on advice.

**Comment by dan-zeman** [comment]
OK, I am not sure about _bichim_. If its agreement could differ from that of _damawe_, resulting in something like English _I want him to go_, then it is indeed `ccomp`.

**Comment by MemduhG** [comment]
Yes, you could say "I want him to go" with different agreement, _damawe biche_. 

Something I am concerned about is that in situations like "I want the apple" _Sevakam dawe_, there is no agreement on the verb _dawe_. If it were a past/ergative construct we could say it was 3rd person singular, but I am not quite sure what to make of its agreement now.

**Comment by dan-zeman** [comment]
If I am understanding it correctly, the only agreement in _damawe_ was the clitic that we separated. If you have _Sevakam dawe_, you again separate the clitic (now from _sevakam_) and attach it to _dawe_ as the subject. So the two situations are similar. Seems that _dawe_ itself does not have the `Person` and `Number` features, as long as we consider the clitic a separate syntactic word.
