### ISSUE TITLE
Language-specific PronTypes in Italian

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#353]
http://universaldependencies.org/it/feat/PronType.html
http://universaldependencies.org/v2/features.html

When looking for possible extensions of the feature set for UD v2, I came across several Italian-specific values of the `PronType` feature: `Clit`, `Predet` and `Ord`. I was wondering whether there are possibly better ways of annotating these words.

The examples in the documentation of `PronType=Clit` seem similar to what is labeled as personal pronoun (`PronType=Prs`) in other languages (including e.g. Spanish). Many languages have two possible forms of personal pronouns, short/clitic, and full/nonclitic. The usual solution is that both forms are `PronType=Prs`, and another, language-specific feature distinguishes between the forms. `Variant=Short` is used in some treebanks but maybe we could define something like `Clitic=Yes`. Or are there reasons in Italian to say that _mi, lo, si_ etc. are not `Prs`? @msimi @SimonettaMontemagni @alessandrolenci 

Another specific value is `PronType=Predet`. Used for (pre)determiners like _tutti_ “all”, _entrambi_ “both”. Again, I think that being placed before another determiner is a property orthogonal to our pronoun types. These two instances should be simply `PronType=Tot`.

And finally, `PronType=Ord`. Used for ordinal numerals like _primo_ “first”, _secondo_ “second”, _terzo_ “third”. In UD, these are not pronouns or determiners but adjectives (`ADJ`). And their ordinal status should be marked by `NumType=Ord`, which is a universal feature. So unless I am missing something, I believe that `PronType=Ord` should be removed from Italian.

**Comment by msimi** [comment]
Hi Dan,

we discussed (with Simonetta, Cristina and the rest of the team) your proposal for UD v2 concerning Italian PronTypes and here are the conclusions.

> The examples in the documentation of PronType=Clit seem similar to what is labeled as personal pronoun (PronType=Prs) in other languages (including e.g. Spanish). Many languages have two possible forms of personal pronouns, short/clitic, and full/nonclitic. The usual solution is that both forms are PronType=Prs, and another, language-specific feature distinguishes between the forms. Variant=Short is used in some treebanks but maybe we could define something like Clitic=Yes. Or are there reasons in Italian to say that mi, lo, si etc. are not Prs? @msimi https://github.com/msimi @SimonettaMontemagni https://github.com/SimonettaMontemagni @alessandrolenci https://github.com/alessandrolenciPronType=Clit: We agree to use PronType=Prs with the addition of Clitic=Yes. Clitics are in fact personal pronouns with a special status. The new feature Clit=Yes accounts for this.
> 
> Another specific value is PronType=Predet. Used for (pre)determiners like tutti “all”, entrambi “both”. Again, I think that being placed before another determiner is a property orthogonal to our pronoun types. These two instances should be simply PronType=Tot.
> 
> PronType=Predet: As far as we continue using the relation type det:predet, this feature is not really needed; we can use the more standard PronType=Tot.
> And finally, PronType=Ord. Used for ordinal numerals like primo “first”, secondo “second”, terzo “third”. In UD, these are not pronouns or determiners but adjectives (ADJ). And their ordinal status should be marked by NumType=Ord, which is a universal feature. So unless I am missing something, I believe that PronType=Ord should be removed from Italian.
> 
> PronType=Ord: We have been using PRON for ordinals only when they have a pronominal function (ex Il primo ad arrivare "The first to arrive”). Simonetta says that they have a "hybrid status” between pronouns and adjectives.  No objection then to treat them as adjectives ADJ also in these cases. We have other cases of adjectives in noun role. The feature will be NumType=Ord.

Maria & c.

**Comment by dan-zeman** [comment]
Great, thanks. As for the pronominal ordinals, I did not know that you were actually distinguishing specific usage. I am still slightly in favor of keeping them as `ADJ` because I believe that this is what most UD treebanks do, and one POS category can indeed perform different functions.
