### ISSUE TITLE
nmod:comp in Turkic

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#355]
The Turkish documentation defines a language-specific relation `nmod:comp` (http://universaldependencies.org/tr/dep/nmod-comp.html). It is not listed in the table of Turkish relations but it is listed in the documentation of `nmod`, and although the current link from `nmod` is broken, the page exists.

However, the Turkish data (UD 1.4) does not use `nmod:comp`. Is it because there are no instances of the comparative relation in this particular dataset? I don't speak Turkish but with the help of MT, I think that this segment at least could be a candidate:

* _benden daha büyük bir kardeşim olsaydı_ `nmod:comp(büyük, benden)`

Will the relation be used in Turkish in the future? We are discussing with @marhabaeli what to do with similar constructions in Uyghur and obviously we want to stay similar to Turkish if possible.

**Comment by MemduhG** [comment]
There are a number of places we have deviated from Çağrı's ideas, certain
types of nmod are part of this. We are making some more corrections in our
treebank as of now, we will update the documentation as we go.

I am happy to contribute to these discussions for the time being, until the
documentation is fixed.

**Comment by dan-zeman** [comment]
@MemduhG thanks! Just to make it clear: I am interpreting your answer so that

* you are not going to introduce `nmod:comp` in the data
* you intend to remove it from the documentation

right?

**Comment by ftyers** [comment]
In the Kazakh treebank, following the Finnish treebank, we were planning to use `advcl` for this relation (planning to, but haven't yet as we haven't yet got any examples in our data). Although in the English treebank `nmod` seems to be used. Perhaps this should be something to look at cross-lingual standardisation for ? In any case Turkish--Uyghur--Kazakh should do it the same way.

**Comment by MemduhG** [comment]
Yes on both accounts @dan-zeman .

I am not quite sure how `advcl` would be used here, @ftyers , could you give an example?

**Comment by ftyers** [comment]
Here is how it is done in Finnish:

http://universaldependencies.org/fi/overview/specific-syntax.html#Comparatives_and_superlatives

Taking a second look, it seems like we might have chosen the wrong language to base the Kazakh annotation on, as it seems like "Keittiö on pienempi kuin olohuone ." could also be "Keittiö on pienempi kuin olohuone _on_ ." ... e.g. it's treated as some kind of elliptical clause. Where in Turkic, that kind of reading is not possible. So, I think that it would be a good idea, to pan-Turkically go for `nmod:comp` for these. They should be fairly easy to annotate/convert as if you have an ablative noun dependent on an adjective in most cases it will be this.

**Comment by MemduhG** [comment]
We are fine with `nmod:comp` too then. We're going to convert them for v2. We should go through some other similar situations in Kazakh/Turkish/Uyghur in the near future.

**Comment by dan-zeman** [comment]
Agreed, thanks.
