### ISSUE TITLE
Layered features: format documentation, validator support and test cases

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#36]
251d67a96e8340e025c59b54618e8810bf8b0b87 documents layered features on http://universaldependencies.github.io/docs/features.html. http://universaldependencies.github.io/docs/format.html, the `validate.py` script, and test cases should be updated to match.

**Comment by Stormur** [comment]
It seems that layered features, in particular for the possessor's number `Number[psor]`, are not accepted by the current validator. I am incurring in the errors:

```
[Line 10 Sent dev-s1]: [L4 Morpho unknown-feature-value] Unknown feature-value pair 'Number[psor]=Plur'.
[Line 69 Sent dev-s2]: [L4 Morpho unknown-feature-value] Unknown feature-value pair 'Number[psor]=Sing'. 
```

Validation was done with the latest python-3 script available. Note that these features were automatically generated through _iset_ values. 

Is it only my problem?

**Comment by bguil** [comment]
It should be defined in the language specific features values: see for instance https://github.com/UniversalDependencies/tools/blob/master/data/feat_val.fr

**Comment by Stormur** [comment]
Thank you!

By the way, why isn't it considered standard?

**Comment by dan-zeman** [comment]
Because every language can have its own layer types, and some languages do not use layers at all. Admittedly, the `[psor]` layer is probably the most widely used one.

**Comment by Stormur** [comment]
But can we not see this one (and probably others) as a potentially universally appearing morphological feature that simply is accepted when present, without need to specify it as a language-specific feature? Just to simplify debugging :-)

**Comment by dan-zeman** [comment]
I actually think that we should do the opposite: even for the universally defined features and values, we should list the languages where they are relevant, and report an error elsewhere. But don't worry, no such change is going to take place before release 2.5 :-)
