### ISSUE TITLE
Enhanced dependencies documentation

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#360]
For clarity, all the examples in [Enhanced dependencies](http://universaldependencies.org/u/overview/enhanced-syntax.html) should show both the _basic_ and _enhanced_ dependencies, ideally side by side.
Currently, only the Relative clauses subsection shows both.

Even better than side-by-side visualization would be if the `sdparse` extension could parse the full CoNLL-U format and show the enhanced dependencies below the sentence (and basic dependencies above). I think this will be very useful for all the UD v2 docs.
I mean something like [tikz-dependency](https://www.ctan.org/pkg/tikz-dependency) can do
![](https://a.fsdn.com/con/app/proj/tikz-dependency/screenshots/semantics.png/182/137)

**Comment by sebschu** [comment]
Yes, I agree that would make it easier to understand the differences between the basic and the enhanced representation.

@fginter @spyysalo Is there a way to have two trees side by side or should I simply put them below each other for now?

**Comment by martinpopel** [comment]
see an exampe of side-by-side using html table: http://universaldependencies.org/sandbox.html#conll-u-example
it seems that the `width` parameter is needed

**Comment by dan-zeman** [comment]
And BTW it is also possible to use colors to distinguish relations added in the enhanced representation from those that are also part of the basic representation. (I would not use this in case that basic relations are _removed_ from enhanced representation, although one could use a third color for that. But if relations are only added, a colored structure may be better.)

See here for an example: http://universaldependencies.org/docsv1/u/dep/conj.html

**Comment by martinpopel** [comment]
Thanks Dan, I like the idea with colors (maybe even for the removed dependencies), see http://universaldependencies.org/sandbox.html#pirate-example and a related issue #363.

**Comment by spyysalo** [comment]
@martinpopel : nice, I like the side-by-side idea. Would you be willing to prepare a pull request implementing this for the http://universaldependencies.org/u/overview/enhanced-syntax.html page?

@jnivre : would you accept a revision of the enhanced-dependencies documentation where the basic and enhanced version were shown side-by-side?

**Comment by jnivre** [comment]
Either side-by-side or color is fine by me, and I agree that it is a good idea to show both basic and enhanced in the documentation of enhanced.

**Comment by martinpopel** [comment]
OK, I will try to prepare a PR with side-by-side examples for the enhanced-syntax.html with colors (switched: red=basic-only, blue=enhanced-only, as suggested by @bguil in #366).

**Comment by dan-zeman** [comment]
Thanks for the PR. I have edited a few minor points in the examples and added a few new examples.

**Comment by sebschu** [comment]
@martinpopel thanks so much for doing this -- looks great! Just one thing, could you perhaps add glosses to the Czech(?) examples? (either below the examples or as the lemmata as you did for they German example.) Thanks!

**Comment by martinpopel** [comment]
The Czech example was added by @dan-zeman (who also fixed errors in my examples, thanks Dan). I can add the English glosses, but in this case I would prefer to give an English example "the man in whose house we live" (or "the man whose house we live" - as non-native speaker I am not sure which is better English). Generally, I think the universal docs should use English examples, unless illustrating a phenomenon not present in English. Dan, was there a reason for Czech example?
I agree this example should be there because it shows that in basic deps "whose" depends on "house" as `det`, but in enhanced deps "man" depends on "house" as `nmod` (unlike in the previous examples where the deprel is always the same).

**Comment by dan-zeman** [comment]
@martinpopel : Yes, there was a reason for using Czech. First, I was confident that this is correct and fluent language. Second, I was confident that this is how I would do it in the Czech data and I can make it happen (while I was not completely sure that the English team would have the annotation exactly the way I would show here). And finally (and most importantly), it better illustrates what I had in mind, while the English translations would be only approximately similar. We have a PRON there, and the preposition must come before it (and not at the end of the sentence), and in the second example it is indeed a DET and not a PRON; and you have the case markings which are not present in English.

**Comment by dan-zeman** [comment]
@sebschu : English glosses, UPOS tags and features added throughout the section on relative clauses.
