### ISSUE TITLE
Brat fails on empty nodes

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#363]
According to the v2 [specification of CoNLL-U](http://universaldependencies.org/format.html#words-tokens-and-empty-nodes), empty nodes and enhanced dependencies are allowed, but [Brat](http://universaldependencies.org/visualization.html) fails on empty nodes, e.g.
```
~~~ conllu
# visual-style 6 7 obj color:red
# visual-style 5.1 5 nsubj color:red
# visual-style 2 5.1 conj color:red
# visual-style 5 6 remnant color:blue
# visual-style 2 5 conj color:blue
1   I    _ _ _ _ 2 nsubj   _  _
2   like _ _ _ _ 0 root    _  _
3   tea  _ _ _ _ 2 obj     _  _
4   and  _ _ _ _ 5 cc      _  _
5   you  _ _ _ _ 2 conj    5.1:nsubj  _
5.1 E5.1 _ _ _ _ _ _       2:conj _
6   rum  _ _ _ _ 5 remnant 5.1:obj _
7   .    _ _ _ _ 2 punct   _  _
~~~
```

Also, Brat should distinguish *basic* and *enhanced* dependencies. I have two suggestions:
- Enhanced-only deps in red, basic-only deps in blue, basic&enhanced in black. This corresponds to the example above, just the `visual-style` comment lines would not be needed and Brat would do it automatically.
- If the set of enhanced dependencies is not equal to the set of basic dependencies, enhanced dependencies are shown below the sentence.

**Comment by spyysalo** [comment]
Thanks! The CoNLL-U v2 issue is not with brat but rather with conllu.js, the JS library that is used to parse and convert CoNLL-U data into the brat format. I've opened an issue for that here: https://github.com/spyysalo/conllu.js/issues/15 .

Please open a separate issue regarding the visualization of enhanced dependencies. I think others might have opinions on the best way to do this, and the name of this issue doesn't clearly signal this is the place to discuss the topic.

**Comment by spyysalo** [comment]
Now renders as shown below (see also http://universaldependencies.org/sandbox).

<img width="298" alt="image" src="https://cloud.githubusercontent.com/assets/587850/21252262/cf746530-c398-11e6-8bd0-f16cda565553.png">
