### ISSUE TITLE
instructions for UD annotation tools

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#373]
http://universaldependencies.org/tools.html#brat-rapid-annotation-tool

says "brat is a browser-based tool for text annotation. The brat visualization component is used in the UD documentation system and the tool can be easily configured for UD annotation (TODO: link instructions)." 

Does anyone knows the step-by-step? I would be glad to help on debug it and publish the revised instructions.

**Comment by spyysalo** [comment]
Thanks for offering to help! The basic steps are

1. Tokenize source texts
2. Set up tokenized texts in brat
3. Copy in UD config (https://github.com/nlplab/brat/tree/master/configurations/Universal-Dependencies)
4. Annotate
5. Convert brat standoff format to CoNLL-U

Caveats: the config is for UD v1 and needs to be updated, I'm not aware of a published brat-to-CoNLL-U conversion that I could be confident in recommending, and brat lacks direct support for multiword tokens.

**Comment by dan-zeman** [comment]
I have written a script that I used to convert the annotation of the Cairo Cicling Corpus. You may want to have a look whether it helps you. It resides at

https://github.com/UniversalDependencies/cairo/blob/master/weaver/brat2conllu.pl

**Comment by jnivre** [comment]
There is also WebAnno, which Richard Eckhart de Castillo set up specifically for UD last year, so that it allows two-level word segmentation and a distinction between basic and enhanced dependencies. We should really test this and see how it works.

**Comment by spyysalo** [comment]
+1 for including WebAnno! ( @reckart )

**Comment by reckart** [comment]
@spyysalo I have submitted a pull request ;)

**Comment by spyysalo** [comment]
Thanks, merged!

**Comment by amir-zeldes** [comment]
Should we add Arborator to this page?

https://arborator.ilpga.fr/

It has both a great project management system and a quick copy-paste mode without setting up a project, very convenient:

https://arborator.ilpga.fr/q.cgi

It's what we use for UD_Coptic.

**Comment by dan-zeman** [comment]
@amir-zeldes : Yes, please go ahead and add it.

**Comment by nschneid** [comment]
I opened an issue here: https://github.com/kimgerdes/arborator/issues/6

**Comment by amir-zeldes** [comment]
I've added it, but I can't seem to make the image work. I added it to docs/img/ - is that wrong?

**Comment by nschneid** [comment]
Looks good to me.

**Comment by spyysalo** [comment]
Updated title to reflect the broader discussion here. The description of other tools would also benefit from step-by-step instructions for how to get started using them for UD annotation.

**Comment by amir-zeldes** [comment]
Oh, weird, it just took much longer to appear than the text edit. I see it fine now too.

**Comment by spyysalo** [comment]
@arademaker : are you still interested in testing and publishing more detailed instructions?

**Comment by arademaker** [comment]
@spyysalo , yes, I can help on that. We will try to document it probably opening a new subpage for brat linked to http://universaldependencies.org/tools.html. Does that make sense?

**Comment by spyysalo** [comment]
@arademaker Works for me, thanks!
