### ISSUE TITLE
Visualizations broken on enhanced dependencies page

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#375]
Visualizations on the page http://universaldependencies.org/u/overview/enhanced-syntax.html currently show "edit" tabs despite being defined in the source as

    <div class="conllu-parse" tabs="no">

Additionally, clicking on some of the edit tabs fails to bring up the edit window in FF 50.0.

Possibly related: #370

**Comment by spyysalo** [comment]
Worse, mousing over the labels makes them disappear (still FF 50.0, doesn't happen in Safari)

<img width="514" alt="image" src="https://cloud.githubusercontent.com/assets/587850/21209961/ed90a97c-c2ba-11e6-924f-b928f5caf70f.png">

**Comment by spyysalo** [comment]
@martinpopel : could you please check if this is related to the changes in #370?

**Comment by spyysalo** [comment]
The tab hiding appears to relate to sloppy checking of the `tabs` option in annodoc: https://github.com/spyysalo/annodoc/blob/gh-pages/lib/local/annodoc.js#L1085

**Comment by spyysalo** [comment]
Tab issue fixed, disappearing labels remain.

**Comment by dan-zeman** [comment]
> disappearing labels remain.

They do not disappear in my Chrome 55. I also tried Firefox and had to apply several updates (did not use FF for a while). While I did observe the disappearing of labels in FF 40, it was OK in 43.0.1, 47.0.2 and 50.1.0.

**Comment by spyysalo** [comment]
@dan-zeman : thanks for checking! I tried updating FF to 50.1.0, but the issue unfortunately persists for me.

**Comment by spyysalo** [comment]
Issue does not show up on Chrome 55.0.2883.95 or Safari 9.1 (11601.5.17.1),  but does on FF 50.1.0 (all on OSX 10.11.4 (15E2066)).

Also, I could not replicate this in http://universaldependencies.org/sandbox.html (b4af97352e1add5f1570bfbb530b4a41efaf6bd1).

Closing as likely browser bug.
