### ISSUE TITLE
how to annotate citations in scientific articles ?

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#381]
Examples:

> It first transforms the graph into a tree, then decodes into a string using a weighted tree-to-string transducer and a language model (Graehl and Knight, 2004).

But we can also have things like

> Mamede, and Markov (2014) discuss lexical and parsing issues of integrating a lexicon-grammar of Portuguese.

Besides the format, the citation can be related to the whole sentence or only to a specific word or phrase.

**Comment by nschneid** [comment]
See http://www.isi.edu/~ulf/amr/lib/amr-dict.html#citation — does that answer your question?

**Comment by jnivre** [comment]
For parenthetical citations, I would use parataxis. For syntactic citations, whatever relation is relevant in the syntactic structure (nsubj in the above example). For the internal structure of the citation, I would probably choose flat in v2. How does that sound?

**Comment by nschneid** [comment]
(Oops, I got my GitHub issue trackers crossed. Ignore my comment about AMR.)

**Comment by livyreal** [comment]
cool, @nschneid, we are thinking on AMRs too. :)

@jnivre I think parataxis is good too, but for internal structure I was thinking on using `nummod`. `nummod` is for quantity, but I'd like to preserve the information that we have dates (numbers) inside the reference.

**Comment by dan-zeman** [comment]
I agree with @jnivre about the external relations. Within the citation, I would stick with normal guidelines whenever applicable. _Graehl and Knight_ is coordination. _2004_ is `nummod` – although I think it would be nice to distinguish numbers-identifiers from numbers-quantities, we do not do that in UD (except for SynTagRus, which I believe has a language-specific extension of `nummod` for that purpose).

**Comment by jnivre** [comment]
Graehl and Knight is definitely coordination. Using nummod for 2004 is fine too, although I think eventually some subtype of flat could be an alternative (to capture the distinction @dan-zeman cares about).

**Comment by amir-zeldes** [comment]
Just noticed this and wanted to add an option for posterity: we've been using `nmod:tmod` for the year (so paraphrased: "Smith 2010" = "Smith in 2010"). We were unhappy with `nummod` for the same reasons.
