### ISSUE TITLE
Sentence-initial empty nodes?

### ISSUE THREAD

**Issue by spyysalo** [UniversalDependencies/docs#382]
The brief section on empty nodes at http://universaldependencies.org/format.html states

> Immediately after a word with index i, it is possible to insert one or more empty nodes indexed i.1, i.2, etc.

This suggests that empty nodes cannot appear in sentence-initial position. Is this correct? (If not, are IDs 0.1, 0.2 etc OK?)

(Related to #363)

**Comment by dan-zeman** [comment]
I do not see why sentence-initial empty nodes should be forbidden. I think that this is just an oversight.

**Comment by spyysalo** [comment]
I would tend to agree. If there are no objections, I'll revise the documentation to indicate that sentence-initial empty nodes are allowed and should have IDs of the form 0.1, 0.2, etc. (@jnivre)

**Comment by jnivre** [comment]
OK
