### ISSUE TITLE
language codes in treebank subdirs

### ISSUE THREAD

**Issue by jorgtied** [UniversalDependencies/docs#389]
At some point, the UD repository changed the naming policies to use language names for treebank sub-directories instead of ISO language codes. I would prefer to have consistent identifiers for languages in both, file names and their paths within the repository. This would make it much easier to loop through all languages with scripts and makefiles without mapping ISO codes to language names and vice versa. Could you consider a change in future releases?

I would prefer ISO-639-2 3-letter codes at all places. Symbolic links from directories with language names to their corresponding variants with language codes would be a possible solution that works for me (that's how I handle it for my purposes already now).

**Comment by fginter** [comment]
I think symlinks would work. Renaming the repos probably not. This is also related to #339 so I'll take care of both. Maybe I could produce a script in `tools` which would generate these symlinks...?

**Comment by gcelano** [comment]
As for the codes, there is a new resource,  http://glottolog.org, which aims to provides ID for all languages, including minority ones. This is extremely useful.

Il giorno 28 dic 2016, alle ore 16:28, Filip Ginter <notifications@github.com> ha scritto:

I think symlinks would work. Renaming the repos probably not. This is also related to #339 so I'll take care of both. Maybe I could produce a script in tools which would generate these symlinks...?

**Comment by fginter** [comment]
@jorgtied How should we handle languages with multiple treebanks? I.e. what kind of naming/symlink structure would be good for English which has 3 treebanks? Should top-level be something like
```
...
eng/
  eng_train.conllu
  ...
eng-esl/
   eng-esl_train.conllu
   ...
eng-lines/
   eng-lines_train.conllu
   ...
...
```

So you could loop over the directories and in each directory you could assume the existence of `${DIRNAME}-(train|dev|test).conllu`

?

[Edit: dashes, not underscores]

**Comment by fginter** [comment]
https://github.com/UniversalDependencies/tools/commit/14359ba66d8c68803225d37066bb39fe5ddf76c3

I think this should do the trick. Feel free to reopen, if the script doesn't do what you need.

**Comment by arademaker** [comment]
Hi @fginter it is not clear what we must do in the repos . What does this script do?

**Comment by fginter** [comment]
You point this script to a directory with UD repositories (downloaded or cloned from GitHub) and it will generate a directory with all the necessary symlinks named consistently using the 3-letter codes. It does not require nor make any changes to the repos, and is provided only to make the easy-to-script directory structure which @jorgtied hoped for.

Running

```
$ python3 create_iso_639_3_symlinks.py ../../UD_PROJHOOK/UD-dev-branches symlinked_ud
```

will output:

```
# note: assuming 'Ancient Greek' in UD and 'Ancient Greek (to 1453)' in ISO 639-3 are same language
mkdir -p /home/ginter/UD/tools/symlinked_ud/grc
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Ancient_Greek/grc-ud-dev.conllu /home/ginter/UD/tools/symlinked_ud/grc/grc-ud-dev.conllu
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Ancient_Greek/grc-ud-train.conllu /home/ginter/UD/tools/symlinked_ud/grc/grc-ud-train.conllu
# note: assuming 'Ancient Greek' in UD and 'Ancient Greek (to 1453)' in ISO 639-3 are same language
mkdir -p /home/ginter/UD/tools/symlinked_ud/grc-proiel
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Ancient_Greek-PROIEL/grc_proiel-ud-dev.conllu /home/ginter/UD/tools/symlinked_ud/grc-proiel/grc-proiel-ud-dev.conllu
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Ancient_Greek-PROIEL/grc_proiel-ud-train.conllu /home/ginter/UD/tools/symlinked_ud/grc-proiel/grc-proiel-ud-train.conllu
mkdir -p /home/ginter/UD/tools/symlinked_ud/ara
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Arabic/ar-ud-dev.conllu /home/ginter/UD/tools/symlinked_ud/ara/ara-ud-dev.conllu
ln -s /home/ginter/UD_PROJHOOK/UD-dev-branches/UD_Arabic/ar-ud-train.conllu /home/ginter/UD/tools/symlinked_ud/ara/ara-ud-train.conllu
...
```

which can be piped into `bash` to actually create all these links. With a `--copy` it will use `cp` rather than `ln -s`.

**Comment by arademaker** [comment]
OK but we haven't made any change in the rules yet, right? No changes in the repos names or files are mandatory, right?

**Comment by fginter** [comment]
Everything stays as is. I do not believe we will want to rename all the repositories and all the files. This would have major consequences throughout the validation pipeline and the docs system. So this script should let us have our cake and eat it.
