### ISSUE TITLE
Images on the tools page overlap with following sections

### ISSUE THREAD

**Issue by reckart** [UniversalDependencies/docs#391]
The screenshot images on the tools page float right, but the float is not cleared when the section for the next tool starts. That makes the screenshots stack up in odd ways.

To fix this, I see two options:

* a CSS `clear: both` could be added before each section in `tools.md`
* change the `css/style.css` and add `clear: both` to the `h3` style

However, I am unsure what is the better option. Adding `clear: both` stanzas in the `tools.md` seems to be adding too much styling in the page while changing the global stylesheet may be overkill and have unforeseen consequences on other pages.

Any opinions?

**Comment by fginter** [comment]
Let's test `clear:both` in `css/style.css` and click around to see if anything got affected badly, and undo if yes. :) The docs don't take *that* long to rebuild. :)

**Comment by reckart** [comment]
The tools page looks better now. I clicked around through some other pages which also still look good - so I guess this was a good fix.

**Comment by fginter** [comment]
Thanks!
