### ISSUE TITLE
SpaceAfter=No forbidden for words

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#407]
Just to make sure I am getting this right. I now added a check into the validator which forbids SpaceAfter=No on **words** which are a part of a **token**. So

```
# This is OK
2-3 .... SpaceAfter=No
2  .... _
3  ...  _

# This is not
2-3 ... _
2 ... _
3 ... SpaceAfter=No
```

I think the former makes sense because the tokens are what corresponds to the `text =` attribute and also because the `FORM` columns of the words do not have to catenate into the `FORM` column of the token.

Is this ok?

**Comment by foxik** [comment]
Yes, it is exactly the behaviour specified by the [CoNLL-U format specification](http://universaldependencies.org/format.html), quoting from the "Untokenized Text" section:

> Every token after which there was no space in the original text should contain SpaceAfter=No in its MISC field. Note that this feature applies to the token level, not to the word level. Syntactic words that are just part of surface tokens will be ignored during detokenization and thus do not need the feature.

**Comment by fginter** [comment]
I should have RTFM. Thanks! :smile:
