### ISSUE TITLE
Possessives with secondary 

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#409]
We have a question with how to annotate (1), especially with respect to (2)

```
(1) Mul on laps haige.
     Me-on is child ill
    `I have a poorly child' / `My child is poorly'

(2) Mul on laps.
     Me-on is child
    `I have a child' / *`child is mine'
```

We think the analysis should be:

``` 
1 Mul       4    nmod:own
2 on         4   cop
3 laps       4   nsubj
4  haige   0    root
```

Is there a similar case in Finnish or other languages? I know in Spanish you can say something like "Tengo las manos congeladas" but this is a slightly different construction.

**Comment by jnivre** [comment]
Shouldn't it be "obl" or "obl:own", rather than "nmod:own" given that it attaches to the predicate?

**Comment by ftyers** [comment]
Yes, read `obl:own` for `nmod:own`, well spotted!

**Comment by dan-zeman** [comment]
Isn't it secondary predication? I see two predicates there: "child is on me (I have a child)" and "child is ill". That could lead to something like

```
  1   Mul     PRON   0   root
  2   on      AUX    1   cop
  3   laps    NOUN   1   nsubj
  4   haige   ADJ    3   acl
```

**Comment by jnivre** [comment]
Well, it depends on which paraphrase you trust. If it essentially means "my child is poor", I don't think it should be analysed as secondary predication.

**Comment by kmuis** [comment]
Nominal in adessive  (pronoun 'mul' in the example) in this kind of constructions is termed „external possessor”; I would rather agree with the annotation proposed by ftyers, so 'haige' would be the root.

**Comment by dan-zeman** [comment]
OK, fine with me.

**Comment by ftyers** [comment]
@fginter can something similar be done in Finnish, if so, what is the analysis that you use there ?

**Comment by jmnybl** [comment]
In Finnish you can say "_mulla on lapsi sairaana_", but I did not find this from our treebank. But we have "_sulla on koti olemassa_" (on_you is home existing), which means "you have a home" and "the home exists". Is this something similar?

**Comment by ftyers** [comment]
@jmnybl If you had "mulla on lapsi sairaana" in the treebank how would it be analysed ? @kmuis does this look like the same thing?

**Comment by kailimp** [comment]
The typical pattern is:
[Noun-adessive] [is] [shortened sentence]
Mul on auto roostes
I-ad is car in the rust - My car is rusting
Naisel on kõrvaklapid peas
Woman-ad is earphones in the head - A woman wears earphones
Mul on kõht tühi
I-ad is stomach empty - I am hungry
But one could also say
Mul läks kõht tühjaks
I-ad went stomach empty-trans - I became hungry
Mul jäi kõht tühjaks
I-ad remained stomach empty-trans - I remained hungry

I would analyse it as
Obl-poss root xcomp
Now, the question is what is the head of the shortened clause
Mul on kõht tühi
obl-poss root ncubj:cop xcomp
Mul on kõrvaklapid peas
obl-poss root xcomp obl ?
Mul on kodu olemas - I-ad is home exist-in
obl-poss root nsubj xcomp?

**Comment by kmuis** [comment]
I would still say that it should be annotated as a copular clause,
annotating the external possessor (mul, naisel) as obl:poss. roots would be
roostes, peas, tühi; I'm not so sure about 'olemas'.
Mul on kõht tühi vs Mul läks kõht tühjaks - we annotate differently Ma olen
kodus (I'm at home) and Ma läksin koju (I went home) anyway?

**Comment by jmnybl** [comment]
@ftyers That's a tricky question, I'm happy we don't have it. :)

I can imagine making it copula structure based on the category 4b, so "mulla" would be root and "lapsi sairaana" would be subject or maybe clausal subject if you want to analyse it as a shortened copula clause. Or do lapsi >nmod sairaana.

I think our plan was to make these copulas such that the owner is root and the owned thing is copula subject. That way we would not have nmod:own or obl:own anymore, but would attached the :own suffix to somewhere else.
