### ISSUE TITLE
Examples of function-word dependents in ellipsis

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#419]
There is a [section](http://universaldependencies.org/u/overview/syntax.html#the-status-of-function-words) saying that function words should have no dependents, with just 4 exceptions.
One of the exceptions is [promotion by head elision](http://universaldependencies.org/u/overview/syntax.html#promotion-by-head-elision) and this subsection gives three example sentences.
The first sentence (*Bill could not answer, but Ann could.*) is OK - it shows how *Ann* depends on *could*.
However, I don't understand the second (*The address she wrote to.*) and third (*I know how.*) example sentence.
Why are they listed in this subsection?
They show head promotion, but no dependents of function words (as far as I understand it).
Shouldn't we provide better examples (where ADP and SCONJ have dependents) because of head promotion?

**Comment by dan-zeman** [comment]
I think that this section is OK now. "Promotion by Head Elision" is a subsection of "The Status of Function Words", and I would argue it belongs there. The superordinate section is not _only_ about the fact that function words cannot have dependents.
