### ISSUE TITLE
Validation shows only treebanks A-N

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#422]
See http://universaldependencies.org/validation.html
UD Norwegian-Bokmaal is the last treebank on that page.

**Comment by arademaker** [comment]
Wow ! What happens ? 

Alexandre 
Sent from my iPhone

**Comment by fginter** [comment]
This one is because the validator prints traceback which contains the literal string `<module>` which in turn looks like html which in turn confuses the browser. :rofl: Temporary fix now in place. What bugs me is that I fixed this months ago and have no clue how this problem made it back!

**Comment by fginter** [comment]
...i.e. all the rest of the page was hidden under the Norwegian tab because the browser was waiting for the `</module>` that never came... :)
