### ISSUE TITLE
goeswith lemma and upos

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/docs#424]
[The definition of goeswith](http://universaldependencies.org/u/dep/goeswith.html) does not specify how to annotate LEMMA and UPOS.

* lemma=form.lower(), upos=reconstructed_upos
```
# text = Never the less, I agree.
1 Never  never ADV   _ _ 6 advmod   _ _
2 the    the   ADV   _ _ 1 goeswith _ _
3 less   less  ADV   _ _ 1 goeswith _ SpaceAfter=No
4 ,      ,     PUNCT _ _ 6 punct    _ _
5 I      I     PRON  _ _ 6 nsubj    _ _
6 agree  agree VERB  _ _ 0 root     _ SpaceAfter=No
7 .      .     PUNCT _ _ 6 punct    _ _
```

* head_lemma=reconstructed_lemma, nonhead_lemma=empty, upos=X
```
# text = Never the less, I agree.
1 Never  nevertheless X     _ _ 6 advmod   _ _
2 the    _            X     _ _ 1 goeswith _ _
3 less   _            X     _ _ 1 goeswith _ SpaceAfter=No
4 ,      ,            PUNCT _ _ 6 punct    _ _
5 I      I            PRON  _ _ 6 nsubj    _ _
6 agree  agree        VERB  _ _ 0 root     _ SpaceAfter=No
7 .      .            PUNCT _ _ 6 punct    _ _
```
Of course, there are many other options and their combinations, e.g.:
* UD_English uses lemma=form.lower(), upos=X.
* I can imagine head_upos=reconstructed_upos, nonhead_upos=X.
* Or someone may want to analyze "*standing*" as lemma=stand, upos=VERB even if it is a goeswith part of "*notwithstanding*".

**Comment by dan-zeman** [comment]
Related: #330

**Comment by lauma** [comment]
Just a note: I am currently redoing some parts of Latvian UD transfromation scripts and I got to this problem as well. I will at least for now use "head_lemma=reconstructed_lemma, nonhead_lemma=empty, upos=X" variant, as it is the one I can get from the original data. 

Explanation about original data: In original data we have PDT-inspired error correction, thus, there is available information that (a) two tokens form a single morphological unit, and (b) what are the correct lemma, form and postag for this unit. However there is no information, what could be sensible lemmas or tags for each of the parts.

**Comment by dan-zeman** [comment]
The examples in the [recommendations on typos](https://universaldependencies.org/u/overview/typos.html) keep the lemma and part of speech with the first part and treat the non-first parts as unknown words.
