### ISSUE TITLE
Fail validation on missing/incomplete metadata

### ISSUE THREAD

**Issue by fginter** [UniversalDependencies/docs#427]
We need to add metadata check into validate.html  Thanks @habeanf for the suggestion

**Comment by dan-zeman** [comment]
The new (but external) validation page, http://quest.ms.mff.cuni.cz/cgi-bin/zeman/unidep/validation-report.pl, now has it. Metadata are not checked by `validate.py` but by a separate script, [check_files.pl](https://github.com/UniversalDependencies/tools/blob/master/check_files.pl#L12-L20), which takes the name of a UD treebank repository as the argument, assumes that a clone of the repository is a subfolder of the current folder, checks the existence of the requred files and the metadata in the README file.

As expected, some valid treebanks became invalid when this test was added.
