### ISSUE TITLE
Other uses of XPOSTAG and DEPS columns?

### ISSUE THREAD

**Issue by ermanh** [UniversalDependencies/docs#433]
Can the 5th (XPOSTAG) and 9th (DEPS) columns be used for secondary POS tags and dependency relations other than those mentioned in the [CoNLL-U format page](http://universaldependencies.org/format.html)?

Specifically, we have a corpus of learner text where there are a lot of ungrammatical phenomena, and there are cases where we want to have two layers of annotations, one where we tag/label a word according to its _morphological shape_ and the other where we tag/label it according to its _syntactic distribution_. For example,

(1) I afraid him. (Intended/correction: "I am afraid of him.")

In the above sentence, for the _morphological_ annotation we want to treat "afraid" literally and tag it as `ADJ`, and then label either `obl(afraid, him)` or `dep(afraid, him)` (but not `obj(afraid, him)` since adjectives do not take direct objects). However, the _syntactic_ distribution points towards "afraid" being used as a transitive verb, and we would like to be able to give a second layer of annotation for this, where "afraid" is tagged `VERB` and has "him" as its direct object, `obj(afraid, him)`, so that we can capture the information that the learner misused this adjective as a verb.

Would the above case be an acceptable use of the XPOSTAG and DEPS columns, or would we need to place them in the last, MISC column instead?

**Comment by jnivre** [comment]
The XPOSTAG is intended for a language-specific tagset, so I think it would be misleading to use it for this, even though it wouldn’t violate any rules. DEPS is reserved for the enhanced dependency representation and can definitely not be used for this. So my recommendation would be to either use MISC or add an extra layer using a standoff scheme.

Joakim

**Comment by ermanh** [comment]
Thanks @jnivre. I suspected as much, but wanted to double check. By "add an extra layer using a standoff scheme" do you mean adding additional columns for our own purposes, but that those columns would still eventually have to be collapsed into MISC if presented as a UD treebank?

**Comment by jnivre** [comment]
For your own purposes, you can of course use any format you like, but by standoff I mean storing annotations in a separate file that references the CoNLL-U file. As of v2, all sentences and words have unique IDs, so this should work fine. In general, I think we should encourage people who want to add special-purpose annotation to use this technique, rather than cramming everything into the MISC field. Our plan was to provide instructions for this together with v2, but unfortunately there was not time to work this out. Hopefully, it can be added soon enough, although right now the upcoming tutorial, workshop and shared task tend to consume all our time.

**Comment by ermanh** [comment]
I see, that makes a lot of sense (storing annotations in a separate file). Indeed the MISC field could get very unwieldy (we are also planning to include alignments with the parallel corpora we're building). Looking forward to the instructions whenever they're ready!

**Comment by dan-zeman** [comment]
There are emerging guidelines for standoff annotation in connection with the PARSEME annotation of multi-word expressions (@ceramisch, @savary). We hope to have them incorporated in the UD guidelines later this year. Leaving this issue open as a reminder.

**Comment by dan-zeman** [comment]
A year ago, the standoff guidelines were added to the documentation, see [here](https://universaldependencies.org/ext-format.html).
