### ISSUE TITLE
Parataxis with a prepositional phrase in Breton

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#434]
There is what is traditionally called an "inflected, or conjugated" preposition in Breton "eme-" which is usually glossed as "said", e.g. emezon "I said", emezout "You said", emezi "She said" etc.

```
Va gwalenn  aour    , emezi      , zo  kouezhet   er        mor   amañ  .
My ring     of.gold , said.she   , is  fallen     in.the    sea   there . 
```

It would seem to be right to use `parataxis` here, following the documentation example with "The guy, John said, left early in the morning", but I thought I would check here first. @tlynn747 does anything like this happen in Irish ?

**Comment by dan-zeman** [comment]
Is this related to the recent discussion about Erzya in https://github.com/UniversalDependencies/UD_Erzya-JR/issues/1?

**Comment by ftyers** [comment]
@dan-zeman ... related yes, this is the current analysis:

```
5-6     emezi   _       _       _       _       _       _       _       SpaceAfter=No
5       emezi   eme     ADP     pr      _       6       case    _       _
6       zi      i       PRON    prn     Case=Acc|Gender=Fem|Number=Sing|Person=3|PronType=Prs   9       parataxis       _       _
```

**Comment by dan-zeman** [comment]
So maybe the issue can be closed, or shall we wait whether @tlynn747 has anything to add?

(For the record, there are “inflected prepositions” in Irish, see http://universaldependencies.org/ga/pos/ADP.html. It seems that they keep it as one syntactic word and attach it via a language-specific relation, `obl:prep`: http://hdl.handle.net/11346/PMLTQ-IZ2L)

**Comment by ftyers** [comment]
I think it can be closed. The differing treatment of these contractions/inflected prepositions in Breton and Irish is something me and @tlynn747 need to discuss :)

**Comment by tlynn747** [comment]
Apologies! 

yes thanks for closing @dan-zeman . I agree, an in-depth discussion/ comparison of how they're dealt with across treebanks would help. Hopefully more time for this over the summer @ftyers 

As for parataxis. Yes that sort of thing happens in Irish - but rare examples in the treebank as of yet. Sent_id 159 holds an example " ......, says Pat McDonagh,......".  Most other examples are phrases/ sentences separated by punctuation like :, -, etc
