### ISSUE TITLE
Macedonian needs to be added to list of languages

### ISSUE THREAD

**Issue by BBW1** [UniversalDependencies/docs#437]
Macedonian is a Slavic language and the administrative language of the Republic of Macedonia. It's missing from the list of languages. Please add it.

**Comment by dan-zeman** [comment]
With pleasure - as soon as there are Macedonian data, or someone working on them. Do you want to volunteer?

**Comment by BBW1** [comment]
Ah, since some of the other languages only had placeholders, I didn't realize there had to be someone working on a language to add it. I'm quite new to the UD framework so I'm afraid not the best person to volunteer at this time.

**Comment by dan-zeman** [comment]
Allright. If you happen to know any Macedonian corpus linguists who might be interested in starting at least a small UD treebank, please point them to us. It would be great to have Macedonian on board, otherwise the Slavic group is already almost complete :-)
