### ISSUE TITLE
Link to language-specific documentation

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#438]
What is the best way to refer someone to a language-specific documentation? If we give a link to the index page, people have to search for the specific language in a long list, while Introduction pages don't have the standart list of links. Maybe we should add that list to Introduction pages?

**Comment by dan-zeman** [comment]
Are you looking for something like this?

http://universaldependencies.org/#uk

**Comment by msklvsk** [comment]
Great, thanks, even better! Shame I haven't noticed that.
