### ISSUE TITLE
Reasoning for “The dislocated elements attach to the same governor as the dependent that they double for”

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#439]
What is the reasoning for attaching [`dislocated`](http://universaldependencies.org/u/dep/dislocated.html) to “normal” element’s head instead the element itself, which at first glance seems to be the loss of information?

It’s just annotators keep making this mistake and we don’t know how to prove them they are conceptually wrong.

**Comment by jnivre** [comment]
Syntactically, the dislocated element is dependent on the head (usually the predicate). If the dislocated element is co-referential with another dependent of the head, the relation between these two elements is anaphoric and does not belong in the basic dependency  representation (but may be annotated in the enhanced representation). However, not all dislocated elements do have an anaphoric relation to another element (see, for example, the Japanese example in the guidelines), so attaching to the head is the only approach that generalises to all cases.

**Comment by msklvsk** [comment]
Thank you and sorry to have bothered you with a naive question.

**Comment by jnivre** [comment]
No need to apologise. It was a perfectly valid question (and one that was discussed when working out the guidelines). I am sorry if my answer made it seem like I thought otherwise. :)
