### ISSUE TITLE
Tokenisation with case suffixes following punctuation

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#443]
I'm looking at Crimean Tatar at the moment, but I think that this applies to quite a few other languages (Armenian example also below):

> 2015 s. yanvar 24-te, saba saat 09.25 rusiye terroristleri Mariupolniñ şarqiy civarına "Grad"lardan ateş açtılar, 30 insan elâk oldı, 100-ge yaqın adam yaralandı, olarnıñ içinde ballar da mevcut.

The question is how to tokenise the sequence "Grad"lardan. Here "Grad" is a name enclosed in quotes, and -lardan is the plural ablative.

One tokenisation I would like is (crh-1):

```
1 "
2 Gradlardan
3 "
```

e.g. just fix it in the input. An alternative would be (crh-2):

```
1 "
2-3 Grad"lardan
2 Gradlardan
3 "
```

This would maintain the original text better, but have punctuation as part of a multispan.

Here is a slightly more complicated example from Armenian meaning «former red army soldier»-'s (thanks to Marat Yavrumyan):

> «նախկին կարմիրբանակային»-ի
> «naxkin karmirbanakayin»-i

Here the -ի suffix is the genitive, but it is usually written without -, so do we go for (hye-1):

```
1 «
2 նախկին
3-4 կարմիրբանակային»-ի
3 կարմիրբանակայինի
4 »
```

Or (hye-2): 

```
1 «
2 նախկին
3-5 կարմիրբանակային»-ի
3 կարմիրբանակային
4 »
5 -ի
```

And make the relation between -ի something like `goeswith` ? In any case with hye-2 makes life easier for the tokeniser but harder for the parser and downstream applications. 

My opinion is that for consistency we should go with crh-2 and hye-2, and update the tokenisation guidelines to allow inflectional morphemes written after punctuation to be joined to their original word.

**Comment by jnivre** [comment]
Maybe I am missing something, but aren't crh-2 and hye-1 the combination that is consistent. To me, hye-2 looks like we would treat a bound morpheme as a word, but maybe I have misunderstood something.

**Comment by ftyers** [comment]
Oops, yes, you are right, crh-2 and hye-1... exactly. That was a typo. To be clear, these are the variants I think we should go for:

```
1 "
2-3 Grad"lardan
2 Gradlardan
3 "
```

```
1 «
2 նախկին
3-4 կարմիրբանակային»-ի
3 կարմիրբանակայինի
4 »
```

**Comment by dan-zeman** [comment]
Although I am not particularly fond of the crh-2/hye-1 solution, it seems to be the least evil. I should not have claimed at the EACL tutorial that tokenization is an easy task :-)

**Comment by jnivre** [comment]
Serves you right. ;) Maybe I shouldn't say this, but we (or at least I) have learned a lot about different languages and writing system since we designed the first version of the guidelines and CoNLL-U. Maybe for v3, we need to revisit some of the basic issues concerning tokenisation and word segmentation.

**Comment by myavrum** [comment]
If you say, that tokenization is not an easy task, then... :) As I see the main problem in hye-2 is that we cannot give a POS tag (for example X) and @goeswith for -ի in CoNLL-U (yes, -ի is a bound morpheme).
the "solution" in EANC http://eanc.net/ : pls search   »ին

**Comment by ftyers** [comment]
Also, it would mean putting `Case=Gen` on this bound morpheme (or leaving it off and losing the information). 

> «Ես որպես նախագահ տեր եմ լինելու ե՛ւ «այո»ին, ե՛ւ «ոչ»ին»,

Oh wow, this one is pretty gnarly... And I'm not sure about their solution, they don't seem to mark it at all. Here I would have "yes" and "no" as nouns and just tokenise it as:

> « Ես որպես նախագահ տեր եմ լինելու ե՛ւ « այոին » , ե՛ւ « ոչին » » ,

(The ՛ is the emphasis mark [right?], which could be a feature on the word, or you could tokenise it as `եւ · ՛`  )

**Comment by myavrum** [comment]
Dear colleagues, what about such a solution?
http://universaldependencies.org/hy/dep/goeswith.html

**Comment by martinpopel** [comment]
> http://universaldependencies.org/hy/dep/goeswith.html
> The head is in some sense the main part,

This contradicts [the universal guidelines on goeswith](http://universaldependencies.org/u/dep/goeswith.html) which say that "the head is always the first part". This is also covered by tests (e.g. in [Udapi](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py#L93)).

Also the link to the [tokenization page](http://universaldependencies.org/hy/overview/tokenization.html) does not work.

**Comment by myavrum** [comment]
tokenization -
https://github.com/UniversalDependencies/docs/blob/pages-source/_hy/tokenization.md
