### ISSUE TITLE
PronType of reflexive pronoun in Finnish

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#444]
Martin's ud.MarkBugs marks as a bug those pronouns which don't have the `PronType` feature. Two questions:

1) Should this be an actual bug? 
2) If it is a bug, what `PronType` should the pronoun `itse` in Finnish get? 

Some related (and unrelated languages for comparison):

In Estonian, `ise` gets `PronType=Prs`. 
In Hungarian, `maga` doesn't get a `PronType`
In English `myself` and friends get `PronType=Prs`. 
In Russian `себя` doesn't get a `PronType`.
In Czech, `se` gets `PronType=Prs`. 

@fginter @jmnybl any thoughts ?

**Comment by jmnybl** [comment]
I guess PronType=Prs would work also in Finnish, as Reflex is a feature and not a PronType. Typically "itse" does not inflect (minä itse, sinä itse, etc.), but if it's used as an object it gets possessive suffix which will have the person (itseni, itsesi, see for example: http://bionlp-www.utu.fi/dep_search/query?search=itseni&db=UD_Finnish-v2&case_sensitive=True&hits_per_page=10).

**Comment by jpiitula** [comment]
Sure it inflects: itselläni (adessive), itselleen (allative), itseään
(partitive), itsestään (elative).

**Comment by jmnybl** [comment]
Sorry, my mistake.
