### ISSUE TITLE
Object vs. oblique in Arabic

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#446]
Summary: nodes with prepositional children should not be `obj` in Arabic.

The point is, there is a relation labeled `Obj` in PADT (in the original Prague-style annotation) and it is used for various nominal arguments of verbs, including some prepositional phrases. This corresponds to the Prague broader definition of object as a nominal whose form is governed by a verb (http://ufal.mff.cuni.cz/pdt2.0/doc/manuals/en/a-layer/html/ch03s02x04.html). This actually corresponds to objects in traditional grammars of various languages (not sure about Arabic here) but it is clearly different from the definition in UD, where the label `obj` is used only for direct objects (http://universaldependencies.org/u/dep/obj.html). While it cannot be apriori excluded that even the direct object is marked by adpositions in some languages, it does not seem to be the case in Arabic. So I think the following solution should be applied:

* Do not convert every Prague `Obj` to UD `obj`. If it is a direct object (i.e. no preposition, accusative case?), it will become `obj`. Otherwise it will be `obl`.
* This means that some Prague objects will be merged with adjuncts (`Adv` in PADT), which will also end up as `obl` if they are nominal/prepositional phrases.
* Since the argument/adjunct distinction has already existed in PADT, it would be a pity to lose it in the conversion. So we may define a relation subtype such as `obl:iobj` or `obl:arg` to preserve the distinction. But if people want to ignore the subtype, they will still get `obl` as defined in UD. I think some UD treebanks have already taken an approach like this.

**Comment by jnivre** [comment]
I think obl:arg is a reasonable choice for people who want to encode (or preserve) the distinction between oblique arguments and other oblique dependents. I think obl:iobj is potentially confusing, given that iobj is a universal relation.

**Comment by ftyers** [comment]
+1 for `obl:arg`.

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_Arabic-PADT/commit/3fe42b9b2bd21b89cd3bb3c3d8cf6a914bc82e8e
