### ISSUE TITLE
Handling reduplication

### ISSUE THREAD

**Issue by vinbo8** [UniversalDependencies/docs#449]
What's the current standard for handling reduplication? Marathi has reduplication in quite a few contexts, I've marked all of these with `compound` for now but I don't know how valid that is. I'll try and enumerate some examples briefly (leaving the glosses out for the duplicated phrases):

Adjectival reduplication:

* Intensification: _lāl phula_. "Red flowers" `(red flower-PL)` vs. _lāl-lāl phula_. "(Very) red flowers" (also "many red flowers").

* Implying "distributions": _ardhā lāḍū doghānnī khallā_. "Both of them ate half a sweet" `(half-SG sweet both-PL-ERG eat-PERF)` vs. _ardhā-ardhā lāḍū doghānnī khallā_. "Each of them ate half a sweet (i.e. they ate the whole thing together)"

Adverbial reduplication:

* Lexicalised compounds: _haḷū_ "slowly" vs. _haḷū-haḷū_ "gradually", _parat_ "again" vs. parat-parat "repeatedly".

* Intensification: _to jorāt oraḍlā_. "He shouted loudly" `(he loudly shout-IMPF-3MSG)` vs. _to jor-jorāt oraḍlā_. "He shouted (very) loudly".

Verbal reduplication:

* Adverbialisation: _(malā) sāngūn-sāngūn kanṭāḷ ālā_. "(I) am tired of telling sb. sth. again and again" `(me-DAT tell-CVB-PERF tell-CVB-PERF boredom.M come-3MSG)`.

* Sequential/parallel actions: _bastā-bastā pāūs surū jhālā_. "While (we) were sitting, it started raining" `(sit-IMPF-PTCP sit-IMPF-PTCP rain.M start happen-3MSG)`; _baslyā baslyā pāūs surū jhālā_. "As soon as (we) sat down, it started raining)" `(sit-PERF-PTCP sit-PERF-PTCP rain.M start happen-3MSG)`. These can be expressed with converbs, but reduplication is more frequent in narrative contexts.

Pronouns: pluralisation; _kuṭhe?_ "where?"; _kuṭhe kuṭhe?_ "where? (multiple places)"

Echo words: _mula_ "children"; _mula bila_ "children etc.".

Any suggestions? Would a subtype of `compound` work for all of these?

**Comment by martinpopel** [comment]
See http://universaldependencies.org/tr/dep/compound-redup.html

**Comment by vinbo8** [comment]
Perfect, I hadn't noticed that. I'll subtype `compound`, then - cheers!

**Comment by dan-zeman** [comment]
Also see #238 and #307. Looks like we need a section on reduplication in the docs.

**Comment by jnivre** [comment]
We need a lot in the docs. Working out more complete guidelines and docs should definitely be our first priority once the dust settles after the shared task and the workshop.
