### ISSUE TITLE
Non-nominative subjects and verbal agreement

### ISSUE THREAD

**Issue by vinbo8** [UniversalDependencies/docs#452]
I believe the consensus for non-nominative subject constructions was that the subject ought to be the word that the verb morphologically agreed with. Ergative-absolutive alignment in Marathi forces the transitive verb to agree with the patient, which still ought to be marked with `obj` and not `nsubj`, though, unless I'm mistaken? So that leads to a situation like this:

_to khidkī ughaḍto_ `he window.F open-IMPF-1MSG` "He opens the window": clearly `nsubj(open, he)`.

_tyāne khidkī ughaḍlī_ `he-ERG window.F open-PERF-3FSG` "He opened the window": still remains `nsubj(open, he)`.

_tyālā khidkī āvaḍlī_ `he-DAT window.F like-PERF-3FSG` "He liked the window": does the relation here change to `nsubj(window, open)`?

---

Next, there are transitive verbs with default agreement and dative subjects, and certain verbal aspects that force dative subjects, like desiderative forms:

_malā kaḷta_ `I-DAT understand-IMPF-3NSG` "I understand": this seems similar to eg. German _mir ist kalt_ where there simply wouldn't be a subject, and an `obj(understand, I)`.

_malā basāyche āhe_ `I-DAT sit-DES-3NSG cop-3NSG` "I want to sit". Would this be similar, with `obj(sit, I)`? #248 has a reference to Russian genitive-inflected nouns being marked with `nsubj` - is this similar?

Note that this kind of construction doesn't exclude the possibility of having another argument with dative inflection:

_malā tyālā shāḷelā paṭhavāyche āhe_ `I-DAT him-ACC school-DAT send-DES-3NSG` "I want to send him to school".

**Comment by jnivre** [comment]
We probably need more discussion of how to deal with ergativity as well as quirky case, and we cannot assume that agreement is universally an acid test for subjecthood. My immediate reaction is that "he" should be "nsubj" in the first three examples, because Marathi does not have subject-verb agreement but rather agreement with highest nominative/absolutive (or something like that). I would not exclude that "nsubj" should be used for the following dative examples too, but I don't know the facts well enough.

**Comment by ftyers** [comment]
Subjects may certainly be in other cases than nominative, especially ergative in languages with ergative--absolutive alignment. From the [docs](http://universaldependencies.org/u/dep/all.html#al-u-dep/nsubj):
```
A nominal subject (nsubj) is a nominal which is the syntactic subject and 
the proto-agent of a clause. That is, it is in the position that passes typical 
grammatical test for subjecthood, and this argument is the more agentive, 
the do-er, or the proto-agent of the clause. 
```

So, in your first example, the subject could/should be "he" in all cases. 

Your second question is harder, and you might have to look for other diagnostics. In Russian currently stuff like _мне хочется думать_ "me-DAT wants-REFL to.think", gets `obl(хочется, мне)`. This is a fairly common cross-linguistic phenomenon, so perhaps it might be worthwhile doing a survey of the existing treebanks to see how things are done there?

**Comment by vinbo8** [comment]
How would you have a typical grammatical test for subjecthood that doesn't get into semantic role-labelling? It seems to me that the dative subject example in the first bit fails on two counts - the "subject"/agent is in a non-nominative, non-absolutive case, and the verb agrees with the object/patient. Are there any other non-semantic tests that would firmly establish "he" as a subject I ought to consider? Are semantic tests for this sort of stuff okay?

`obl` seems like it could work in that context, I'll have a look at other treebanks though.

**Comment by ftyers** [comment]
In addition, here are a few things to think about regarding subjecthood, the list is non-exhaustive and a bit vague, but should provide pointers for further thinking:

* Valency changing: if you have passive what happens?
* Position: Does it go in the "typical" place where a subject goes --- if this is relevant for the language in question
* Agreement: Does it undergo agreement typical to a subject?
* Control structures: Does it behave like a subject in control structures ?
* Coreference: Can it corefer with reflexive pronouns?

**Comment by jnivre** [comment]
The literature on quirky case (and quirky subjects in particular) contains discussion of other tests for subjecthood. I have to run now, but I will try to dig out some references.

**Comment by dan-zeman** [comment]
The semantic roles are actually needed, see Andrews (2007), cited in the docs (in Shopen et al., Language Typology vol. 1). Semantic roles are cross-linguistic. Based on them you identify primary transitive verbs in your language, and note the typical coding used to mark their arguments. Then you know how to recognize the S, A and P grammatical functions in Marathi. It might include nominative/ergative case marking, word order, cross-referencing on the verb etc. But it is already Marathi-specific, not universal. As a result, you will probably find out that nominative and ergative case lead to the `nsubj` relation in UD.

**Comment by jnivre** [comment]
Subject tests are described in:

Stephen Anderson. 1976. On the Notion of Subject in Ergative Languages. In Charles N. Li (ed.) _Subject and Topic_, 1--23. New York: Academic Press. URL: https://cowgill.ling.yale.edu/sra/notionofsubject.pdf

Annie Zaenen, Joan Maling, and Höskuldur Thráinsson. 1985. Case and Grammatical Functions: The Icelandic Passive. _Natural Language and Linguistic Theory_ 3: 441--483. URL: http://babel.ucsc.edu/~hank/114/IcelandicPassive.pdf
