### ISSUE TITLE
Inconsistent treatment of discourse connectives

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#453]
I am noticing that constructions of the form "S1, ADV S2" are not linked consistently. "X, so Y" uses `parataxis` to link X and Y, but this is not [documented](http://universaldependencies.org/u/dep/parataxis.html). `advcl` or `ccomp` is sometimes used with other connectives like "however" and "thus".

When discourse adverbials interrupt a clause, there is inconsistency in how it is linked to the clause ("after all" in "We are, after all, in this together" attaches as `obl`, while in "This is, after all, his business" it attaches as `advmod`).

**Comment by dan-zeman** [comment]
I was surprised to find out that _all_ [is usually tagged](http://hdl.handle.net/11346/PMLTQ-B2XW) `ADV` in _after all_. But if the tag is correct, then the `advmod` relation is correct and `obl` is wrong.

**Comment by dan-zeman** [comment]
What is the status of this issue? Are we waiting for a change in the data or in the documentation?
