### ISSUE TITLE
Treebank's name

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#463]
We have now several treebanks for many languages. Often one of this treebank has only the language's name, while the others have particular name. For instance for French we have now 6 treebanks:

1. French
2. French-FTB
3. French-PUD
4. French-ParTUT
5. French-Sequoia
6. French-Spoken

The treebank called French is the older one, but its is not necessary the best one. Is it possible to change the name of this treebank?

Same request for other languages.

**Comment by martinpopel** [comment]
Do I understand your suggestion that all treebanks (or only when there are multiple treebanks for one language) should have some specifier in names?
I understand the motivation. It would mean renaming also the GitHub repositories, but those have no web pages, so it is [doable](https://help.github.com/articles/renaming-a-repository/).

Leaving the names aside, I think it would be very valuable to merge several treebanks of the same language into one.
Of course, this is not always possible (if each treebank is primarily maintained in different format&style and exported to UD automatically) or suitable (e.g. if one treebank is spoken language with very different properties and extra/missing annotation).
Of course, this means extra work to make the treebanks consistent before merging and also closer cooperation between the maintainers of both treebanks.
However, I think that's the goal of UD and it pays off in the long term and users would appreciate it.
CoNLL-U now supports sentence, paragraph and document IDs, so there is no problem with different domains etc. - they can be encoded in the IDs (and domain-specific subcorpus can be extracted if needed).

**Comment by sylvainkahane** [comment]
**About treebank's names**

If two treebanks have been done by the same team it could be good that they have a similar specifier (cf. PUD or ParTUT). This includes languages with a unique treebank. Conversely non-related treebanks (such as Finninsh-FTB and French-FTB) should not have the same specifier.

**About the merging**

I see two problems.

First, a good corpus might be provided with good metadata. We need to know what is the genre: news, litterature, science, forum, chat, email, SMS, etc. Even for spoken languages we have significant differences between interview, discourse, free discussion, etc. I don't think that coprus with diffrent genres must be merged without keeping good traces of the origin of each sentence and the metadata associates.

Second, the problem mentionned by @martinpopel. The investigation we made on French UD treebanks shows A LOT of divergences in the annotation choices. And also significant differences in the quality. To come back to the first point, it can be more interesting to compare two treebanks provided by the same team (for instance two -ParTUT treebanks) than two treebanks on the same languages developped by two teams that have never collaborated.

**Comment by jnivre** [comment]
Thanks for bringing this up. The naming scheme has evolved organically over time and can definitely be improve. Maybe we can set this as a goal for the November release. When it comes to merging treebanks, I think we have to be pragmatic. When nothing prevents it, it should definitely be considered, but as you both point out there are sometimes reasons not to do it. Maybe we can provide guidelines for this as well.

**Comment by dan-zeman** [comment]
Fixed in UD 2.2.
