### ISSUE TITLE
CONLL-U mimetype

### ISSUE THREAD

**Issue by flammie** [UniversalDependencies/docs#464]
Does CONLL-U have a registered mimetype or suggested? Can one be registered? I'm sitting amidst CLARIN-D meeting and so I was just curious, might be helpful with some things, if it was not just text/plain.

**Comment by dan-zeman** [comment]
I don't think so. I don't see the benefit right now (given that there is no CoNLL-U-specific editor) and I also don't know what it involves to register a mime type, but if you want to volunteer…

**Comment by ftyers** [comment]
I think there are several groups working on editors, we have a project ongoing at the moment `ud-annotatrix`. It seems like a request can be logged here: https://www.iana.org/form/media-types , but it requires stuff like _Note: Registrations in the standards tree must be approved by the IESG or must correspond to a formal publication by a recognized standards body._

**Comment by flammie** [comment]
In this context, also web services generally rely on mimetypes to identify data or publicise what can be processed for example. I've also tried to make sense of the requirements and stuff, since the most recent ones discourage x- type ad hoc prefixes, I think the rationale was somewhere in RFC that it's lightweight to register new type so it's always good to do so, but I cannot find that just now.

**Comment by dan-zeman** [comment]
Tentatively closing as there does not seem to be enough interest and development in this direction. Feel free to reopen if there are any news.
