### ISSUE TITLE
NUM as nonverbal predicate

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#467]
I believe there's a type of nonverbal predication not mentioned in the docs (in addition to equation, attribution, location, possession, benefaction) — quantification.

Here is an example in Ukrainian:
![image](https://user-images.githubusercontent.com/473012/28240437-84c12d0a-698a-11e7-8b37-4d240f5c15f3.png)

```
Інструментів   для цього є   два : низькі ціни   та  обмеження   .
Of-instruments for this  are two : low    prices and regulations .
```

Also present in Czech:
![image](https://user-images.githubusercontent.com/473012/28240623-e4910a4a-698d-11e7-8111-f42e59125c19.png)

To mention:
- the predication is not existential (existence is assumed);
- there is no elided element behind the numeral;
- the copula can be omitted.

**Comment by dan-zeman** [comment]
Agreed. Although one could say that it is a special case of attribution.

**Comment by msklvsk** [comment]
One could say that. I’m just reporting a place where annotators were unsure it’s legal (in case you consider this is worth mentioning in the docs for clarity).

**Comment by dan-zeman** [comment]
Link: this is the page that should be extended: http://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses

**Comment by dan-zeman** [comment]
Added a short note in 4d75e648613471d7ca82e08321a8978dcef88a2b.
