### ISSUE TITLE
Status of obl:agent

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#469]
In the [Simple Clauses](http://universaldependencies.org/u/overview/simple-syntax.html) documentation and the [`obl` documentation](http://universaldependencies.org/u/dep/obl.html), there are English examples with `obl:agent`. However, though [this query](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Eobl%3Aagent%20_&db=UD_Russian-v2&case_sensitive=True&hits_per_page=50) returns a few results in the Russian v2 data, `obl:agent` is never used in the English v2 data. Is it a subtype that English intends to add? Or should the guidelines be modified?

**Comment by sebschu** [comment]
It says optional in the guidelines ;)

But no, I don't think we intend to add this to the English treebank. However, it should add this automatically when you convert to the enhanced representation (though, admittedly using a very crude heuristic, which works most of the time but will also turn obliques such as _by the table_ in _It was placed by the table_ into `obl:agent`, but these are very rare anyways).
