### ISSUE TITLE
Attachment of punctuation with parataxis

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#473]
For forms of [parataxis](http://universaldependencies.org/u/dep/parataxis.html) where there is a separating [punctuation](http://universaldependencies.org/u/dep/punct.html) mark (such as a comma or colon), I don't see a guideline stipulating whether the punctuation mark attaches to the first part or the second part.

Both occur in the English UD corpus:

- [attaches left](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Eparataxis%20%28_%20%21%3Epunct%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=10)
- [attaches right](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Cparataxis%20%28_%20%21%3Epunct%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=100)

What should the policy be? Should it be uniform or should it depend on the kind of parataxis (reported speech, side-by-side sentences, etc.)?

**Comment by martinpopel** [comment]
One of the [punctuation guidelines](http://universaldependencies.org/u/dep/punct.html) says the punctuation should be attached to the **subordinated unit** (i.e. not the governing unit).
Typically, the second part of parataxis is attached to the first part, so the punctuation should be attached to the second part.
However, the [parataxis guidelines](http://universaldependencies.org/u/dep/parataxis.html) allow also the first part of parataxis attached to the second part, so here the first part is the subordinated one and the punctuation should be attached to it.

I think the [punctuation guidelines](http://universaldependencies.org/u/dep/punct.html) are clear (after careful reading), so the attachment of punctuation can be almost fully [automatized](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py). The only exception is the [detection of the unit span](https://github.com/udapi/udapi-python/blob/3fe163a4c0feb5e844e325024b5f6e6da66c5764/udapi/block/ud/fixpunct.py#L145-L152).

**Comment by nschneid** [comment]
Ah, I read "subordinated unit" as a linguistic construction (subordination), which is not really operative in parataxis.

So you're saying the punctuation should attach to the dependent, and thus [these examples](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Eparataxis%20%28_%20%21%3Epunct%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=10) are incorrect?

**Comment by dan-zeman** [comment]
Yes. A frequent function of punctuation is to delimit a nested phrase. Then it should go with the phrase it delimits, i.e. be attached to its head. Commas (or brackets, colons etc.) around parataxis seem to fit well this pattern.

**Comment by martinpopel** [comment]
> Ah, I read "subordinated unit" as a linguistic construction (subordination), which is not really operative in parataxis.

Yes. Linguistically, parataxis is not (by definition) subordination, but UD attaches one part of parataxis to the other, similarly as in real (linguistically hypotactic) dependencies.
Maybe we can clarify the guidelines: "subordinated" -> "dependent" and provide examples (annotating all commas and brackets in [parataxis guidelines](http://universaldependencies.org/u/dep/parataxis.html)).

> and thus [these examples](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Eparataxis%20%28_%20%21%3Epunct%20_%29&db=UD_English-v2&case_sensitive=True&hits_per_page=10) are incorrect?

Yes. All the ten examples on the first page are wrong according to my understanding of the guidelines.
Note that the paired brackets in the 5th example and paired quotes in the 8th example should be attached to the same node (head of the phrase enclosed in the paired punctuation).

**Comment by nschneid** [comment]
Thanks for the clarification. I've added `punct` edges to the examples at [`parataxis`](http://universaldependencies.org/u/dep/parataxis.html)—hope I did it correctly. Also replaced "subordinated" with "dependent" at [`punct`](http://universaldependencies.org/u/dep/punct.html) and [other constructions](http://universaldependencies.org/u/overview/specific-syntax.html).

**Comment by msklvsk** [comment]
But what about question/exclamation marks or ellipsis closing `parataxis` at the end of a sentence? Should it still belong to the global root or can we attach it to parataxis root if, for example, only parataxis clause is exlamated?

**Comment by dan-zeman** [comment]
If it belongs to the parataxis, I would attach it to the head of the parataxis. I do not think we should attach something to the main predicate just because it is a particular symbol.
