### ISSUE TITLE
discourse vs. advmod

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#474]
A couple of discrepancies:

* **actually:** The [`discourse` doc page](http://universaldependencies.org/u/dep/discourse.html) lists *actually* as an example, but in the English treebank, all *actually* tokens are (actually) attached as `advmod`. Should the distinction be clarified in the guidelines?

* **of course:** In the English treebank, there are [4 tokens](http://bionlp-www.utu.fi/dep_search/query?search=_%20%3Ediscourse%20%28of%20%3Efixed%20course%29&db=UD_English-v2&case_sensitive=True&hits_per_page=50) where *of course* is attached as `discourse`. I'm guessing at least 2 of them should be `advmod`, which is how most *of course* tokens are handled, as well as all tokens of *however*. For the two sentence fragments where there is no verb, I think `discourse` is reasonable.

**Comment by nschneid** [comment]
cf. #306

**Comment by dan-zeman** [comment]
In UD 2.4 English EWT, _actually_ is still treated as `advmod`, except for one `parataxis`; see this query: http://hdl.handle.net/11346/PMLTQ-WZIF. @manning @sebschu : Should we modify the examples in the documentation or the data?

**Comment by dan-zeman** [comment]
UD 2.6 English EWT, still no change: [http://hdl.handle.net/11346/PMLTQ-0YVL](http://hdl.handle.net/11346/PMLTQ-0YVL).

**Comment by amir-zeldes** [comment]
In GUM 'actually' is also `advmod`. Are we sure we want this to be 'discourse'? There is a variety of sentence 'stance' adverbials which are a bit different from classic VP adverbs, but there are also different uses of actually (e.g. adnominal and often stressed "*actually* a rock"), and I'm not sure we'd get high agreement on this. I would be pretty OK with removing "actually" from the examples in the guidelines and keeping it as `advmod`, but I'm convinceable. FWIW, here's a frequency list of words labeled `discourse` in EWT vs. GUM with f>1 (some may be errors; I'd say other words similar to 'actually', like 'indeed' are not represented):

```
GUM
===
well	25
no	15
oh	15
yes	9
Yeah	8
mean	6
yeah	6
right	6
say	5
like	5
fucking	4
Hey	4
hey	4
man	4
ha	3
ho	3
Yep	3
please	2
=p	2
OK	2
No	2
ok	2
lol	2
you	2
Well	2
look	2
okay	2
sorry	2
```

```
EWT
===
please	330
yes	67
:)	59
well	58
no	41
like	26
lol	21
ok	16
hi	15
oh	15
hey	13
thanks	12
okay	10
yeah	10
anyway	9
:(	9
wow	9
sorry	9
:-)	8
:d	7
mean	7
right	7
(:	5
of	5
;)	4
^_^	4
say	4
yep	4
haha	4
p.s.	4
sure	4
though	3
anyways	3
=)	3
uh	3
huh	3
pls	3
plz	3
yea	3
dhin	3
hmmm	3
o	2
:p	2
^^	2
eh	2
er	2
lo	2
ps	2
so	2
ya	2
aye	2
btw	2
god	2
idk	2
thx	2
fine	2
hell	2
nope	2
hello	2
ummmm	2
```

**Comment by nschneid** [comment]
From a PDTB perspective, there are many *discourse adverbials*, which are a subtype of *discourse connectives*: therefore, actually, however, instead, indeed, in other words, for example, on the other hand, ...

But it looks like most of the ones listed above are greetings, please/thanks, yes/no, filled pauses, emoticons/laughter/swearing, etc. These are not really semantic connectives. So I'd be happy to use `advmod` for the adverbial connectives like "actually", "though", "anyway(s)".

Not sure about "(I) mean", "so", "well", "look", "say": These feel to me like they mainly have a floor-taking function (we could add "listen" and "now" too); the speaker is leaning in to the fact that they are speaking now, or emphasizing a point, and not necessarily choosing these words based on the content of what they are trying to communicate. "(I) mean" and "well" do feel like they have, or could have, a contrast-like quality though, where the speaker is objecting to or hedging what the other person has said. "I mean" also appears to have a use similar to "that is". (For "so" I am talking about the let-me-start-talking sense, not the causal sense.)

**Comment by amir-zeldes** [comment]
For multiword expressions with internals syntax, like "I mean", we've been using the parataxis guideline, which allows you to keep the clause-like analysis internally:

parataxis(mainverb,mean)
nsubj(mean,I)

I think this is better than using `discourse` on 'mean', which seems like more of a pragmatic than a syntactic statement.

**Comment by dan-zeman** [comment]
I think it is better to attach _actually_ (and other sentence "stance" adverbs) as `advmod`. In fact I thought that this is what UD does and didn't know that _actually_ is cited under `discourse` until I saw this issue.

Perhaps we should simply remove the example from the documentation of `discourse`. BTW the formulation with this example seems to date back at least to [Depling 2013](https://www.aclweb.org/anthology/W13-3721.pdf), two years before first release of UD :-) But the UD English data, since UD 1.0 in January 2015, treated _actually_ as `advmod` (with one exception, which is `parataxis`).

**Comment by amir-zeldes** [comment]
OK, given the apparent consensus on this, I went ahead and updated the documentation.
