### ISSUE TITLE
acl for secondary predication

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#476]
I find `acl`(_She, sad_) in _She entered the room sad_ the most confusing part in UD.

![image](https://user-images.githubusercontent.com/473012/28386065-17bdb600-6cd3-11e7-9a27-3a9e7397ef4c.png)

This relation seems more semantic than syntactic: _sad_ intuitively modifies _entered_ _(she entered **being sad**)_. And if it really is semantic, we should apply the same logic as for dislocated (see #439) and move it to the enhanced representation level.

Also, _If the nominal head is missing, the secondary predicate must be attached as `advcl` of the verbal predicate_, which will often happen for pro-drop languages, hurting parallelism even inside a language family, a very UD-unlike phenomenon. 
![image](https://user-images.githubusercontent.com/473012/28386208-7e2df602-6cd3-11e7-8faa-4506cc304202.png)

Moreover, in Slavic, _sad_ can have not only nominal case _(uk: сумн**а**)_, but also instrumental _(сумн**ою**)_, thus making a state more temporary and `acl` even more unusual, disagreed with the nominal.

We also find examples, where _sad_-alikes can be treated as `conj` to an adverbial clause or oblique:
(translated from uk)
- _Andrew sat in the middle, knowing what to expect from other convicts, and prepared for a fight_.

- ![image](https://user-images.githubusercontent.com/473012/28729131-0841922a-73d4-11e7-81e2-6b0264b3fcae.png)
```
    She     is-standing without    a-shawl    ,         gray-haired ,       lush-haired
```

I suggest to always analyze optional depictives as `advcl`(_entered, sad_) for the following reasons.
1. It intuitively belongs to a verbal predicate.
1. Semantics does not belong in the basic dependency representation.
1. We already use `advcl`(_entered, sad_) if the nominal head is missing, which would often be the case for e.g. Polish.
1. In Slavic, _sad_ can also be instrumental, a very “adverbial” case.
1. There are examples of coordination between optional depictives and adverbial clauses/obliques.
1. `xcomp` vs `advcl` for secondary predication would rhyme with `obj` vs `obl`.

**Comment by mcandito** [comment]
I fully agree with this proposal: syntactic handling of optional secondary predicates, and recovering the semantic link in enhanced dependencies
Marie

**Comment by jnivre** [comment]
I find this argumentation convincing as well. This should definitely be taken into account when working out the new and improved guidelines. I am not sure whether we should set up a working group specifically for secondary predication, or whether it can be subsumed under some other topic. I will add a note to the "brainstorming page" for now. (See my email on the UD list two days ago.)

**Comment by amir-zeldes** [comment]
+1
And I believe this is also the way the Stanford Dependencies handled adverbial `vmod`, so others have found such an analysis sensible before.

**Comment by jnivre** [comment]
I think it would be very useful to have a working group looking at this in the larger context of non-finite modification (and complementation). Examples like:

she entered the room sad
she entered the room crying
she entered the room holding a handkerchief
she entered the room (with) a handkerchief in her hand

**Comment by rafael75012** [comment]
Hello,
May I ask if we came to any decision?

**Comment by jnivre** [comment]
Unfortunately, nothing seems to have happened here. We need to follow up this and many other issues.

**Comment by dan-zeman** [comment]
Anyways, if there is a conclusion, it will be the next version of the guidelines, right? Shall I modify the milestone to "later"?

**Comment by jnivre** [comment]
Right.

**Comment by dan-zeman** [comment]
A [guidelines amendment](https://universaldependencies.org/changes.html#optional-depictives) from May 2022 (UD 2.10) approved the proposal to use `advcl` instead of `acl`, so I am closing this issue as completed.

(Still pending: Extend the enhanced UD guidelines to also capture the relation between the secondary predicate and the nominal in the matrix clause. But this would be a separate issue, and it would apply to other adverbial clauses, too.)
