### ISSUE TITLE
nmod:npmod and obl:npmod

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#478]
I figure it's worth reexamining [`nmod:npmod`](http://universaldependencies.org/docs/en/dep/nmod-npmod.html), which in v2 has split into `nmod:npmod` and `obl:npmod`.

Browsing the English corpus, I see the following:

__obl:npmod__ is used for:

* distance + cardinal direction: 50 <nummod km <obl:npmod west, a bit north
* duration + adjective: month <obl:npmod long, 3 years old
* duration + adverb: Four <nummod months <obl:npmod later, several years ago
* duration + preposition or subordinator: weeks <obl:npmod after <mark [its military withdrew]
* noun + verb compound: text <obl:npmod based, sky-high, ghost-written, ...
* noun + adjective compound: self <obl:npmod important, cost-effective, ...
* duration adverbial + verb: I remain devoted >obl:npmod time >amod full (full-time)
* extent/degree/quantity adverbial: a <det little <obl:npmod sooner, a lot more, rose >obl:npmod cents >nummod 60

__nmod:npmod__ is used for:

* rate with postmodifying "each": 90 seconds >nmod:npmod each, £ 15 each (`nmod:npmod(£, each)`)
* rate with "a(n)": 240 kilometers an hour (`nmod:npmod(kilometers, hour)`), 5 times a year
* rate with "every": 10 dollars every week (`nmod:npmod(dollars, week)`)
* distance + case-marked cardinal direction: miles to the west (`nmod:npmod(west, miles)`), 30 miles from Iran 's border
* duration + case-marked temporal reference point: several days before the elections (`nmod:npmod(elections, days)`)
* time + timezone: 3:29 p.m. >nmod:npmod EST, 3:30 Houston time, 10:30 my time
* extent/degree/quantity postmodifier of noun: thanks a lot (`nmod:npmod(thanks, lot)`)
* adjective + noun compounds: wrong <nmod:npmod doers
* noun + "the same" postmodifier: terms the same as (`nmod:npmod(terms, same)`)
  - the sentence occurs twice, once with `amod`, which seems better
* age postmodifier: Ronald Joseph Crawford , 42 , ...
  - this construction is elsewhere handled with `amod`, which seems better
* floating reflexives: the test >nmod:npmod itself
* name of event, location and other forms of metadata [why not `list`?]: Transmission...Conference >nmod:npmod Miami , Florida
* looks like a conversion error due to a missing word:  "need to know what kind food Argentina people eat": `nmod:npmod(kind, food)` (but this is apparently missing "of")

The above is not an exhaustive analysis, but it captures the vast majority of tokens.

**Comment by nschneid** [comment]
This seems like an odd basis on which to lump phenomena together. I think we should consider the following groups:

1. compound involving a noun and a non-noun
   - can these just be `compound`?
2. duration/extent/cost + unit of measure, direction, or rate
   - something like `:unit` or `:scale`?
3. duration/extent/cost modifier of relation like "after", "ago", "away"
   - `(nmod|obl):adv`? `:distance`?
4. degree expression like "a little", "a lot" modifying a noun or verb
   - `(nmod|obl):adv`? `:degree`?
5. adverbial of cost/extent modifying a verb
   - `obl:adv`?
6. floating reflexive
   - `nmod:refl`?
7. metadata in a time or other kind of value, esp. time + timezone
   - values need standardization (#455)

**Comment by dan-zeman** [comment]
So what is the current status of this issue? Are we waiting for a change of the data or of the documentation?

**Comment by nschneid** [comment]
See also some MWE examples at https://universaldependencies.org/en/dep/fixed.html
