### ISSUE TITLE
Partitive with preposition in French (and other languages)

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#480]
French, and some other languages, use a preposition to make a partitive e.g. "je voudrais de l'eau" and not "je voudrais l'eau".

In the French treebank, this use of "de" seems to be annotated as a determiner(!!)

```
# sent_id = fr-ud-train_00600
# text = La chambre n'avait pas de chauffage, résultat -> impossible de dormir le premier soir.
1       La      le      DET     _       Definite=Def|Gender=Fem|Number=Sing|PronType=Art        2       det     _       _
2       chambre chambre NOUN    _       Gender=Fem|Number=Sing  4       nsubj   _       _
3       n'      ne      ADV     _       Polarity=Neg    4       advmod  _       SpaceAfter=No
4       avait   avoir   VERB    _       Mood=Ind|Number=Sing|Person=3|Tense=Imp|VerbForm=Fin    0       root    _       _
5       pas     pas     ADV     _       Polarity=Neg    4       advmod  _       _
6       de      un      DET     _       Definite=Ind|Gender=Masc|Number=Sing|PronType=Art       7       det     _       _
7       chauffage       chauffage       NOUN    _       Gender=Masc|Number=Sing 4       obj     _       SpaceAfter=No
```

I looked in the French docs and there doesn't seem to be a description of this (e.g. no mention of "de" as a determiner in `DET.md` or `det.md`. 

Would it be possible to document the diagnostics for when it is a deteminer ? It seems to be when there is no other determiner.

**Comment by dan-zeman** [comment]
Isn't it just a confusion with the determiner _des_?

The _de_ seems like `ADP` to me but I don't speak French. @mcdm?

**Comment by sylvainkahane** [comment]
We are working on the guidelines for French, but we have now 6 UD treebanks for French  (including the French-Spoken coming soon) developped by at least 4 different teams. The treebank called just French (developped by Google) is the worst one and should not be taken as a reference (I already asked that its name be changed).

**Comment by sylvainkahane** [comment]
The question of _de_ is very complex.
There exists a weak form of the determiner _des_ used only before an ADJ:

```
des pommes 'apples'
*de pommes
de belles pommes 'beautiful apples'

```
But _des_ itself is a portmanteau of  _de + les_ 'of + the'. And _des_ cannot occur after the preposition _de_:

```
Je rêve de cette pomme 'I dream of this apple'
Je rêve de pommes 'I dream of apples'

```
This _de_ will be analyzed as an ADP but the determiner has disappeared and it could also be analyzed as a portmanteau 'de + des'.

The _de_ after a negation (_Je n'avais pas de chauffage._ 'I had no heating') is the most controversial one. It is often analyzed as a DET occuring only after a negation. But il could also be analyzed as an ADP, as in _J'avais trop de chauffage_ 'I had too much heating_. I really think that the latter is the best solution.

**Comment by ftyers** [comment]
Which treebank is the best one to use for reference ? 

Incidentally in Basque the negative is analysed as `Case=Par|Definite=Ind` _Derbietan ez dago faboritorik_, and in Finnish as `Case=Par`, _Sisällissodan uhka ei ole pelkkää retoriikkaa._

In Basque, certain grammars like de Rijks (2008) describe -rik as being a partitive determiner along the lines of _-a_ and _bat_

Coming back to French, in that case would you have a different analysis for _Je n'avais pas de chauffage_ and _J'avais trop de chauffage_ ?

**Comment by dseddah** [comment]
> Le 26 juil. 2017 à 00:14, Francis Tyers <notifications@github.com> a écrit :
> 
> Which treebank is the best one to use for reference ?

Good question, I’d say the Sequoia one for its consistency (regardless of the MWEs which are still discussed a lot I’ve heard). it comes from the conversion from its native annotation scheme to UD2 by Bruno Guillaume.
The native scheme is the FTB dependency scheme  (Candito et al, 2010) + manual correction.
It will be available also in an extended version of the enhanced++ scheme super soon.
 
While I’m here, there’s also a version of the French Treebank (Abeille et al, 2003) in the UD v2 format. 


Best,
Djamé
