### ISSUE TITLE
Attachment of "etc."

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#483]
In the English treebank it looks inconsistent: sometimes `advmod`, sometimes `conj`: [results](http://bionlp-www.utu.fi/dep_search/query?search=etc.&db=UD_English-v2&case_sensitive=True&hits_per_page=100)

Note that "X, Y, Z, etc." does not require a coordinating conjunction, but it nevertheless feels like coordination. So I lean toward `conj`.

**Comment by sylvainkahane** [comment]
Yes `conj`is the best solution. We analyze _et caetera_ 'and others' like _and things like that_, that is, the agglutination of a conjunct and a conjuction.

Such elements are called _lists completers_  (Jefferson 1990, Selting 2007).

**Comment by sylvainkahane** [comment]
The most problematic thing is the POS. A word like _etc._ do not behave as any other word. In particular it does not behave as an ADV and can never be an adverbial modifier. We decided to give it the POS CCONJ because it can only appear in coordination and is the agglutination of a CCONJ and something else.

**Comment by dseddah** [comment]
> Le 29 juil. 2017 à 12:11, sylvainkahane <notifications@github.com> a écrit :
> 
> The most problematic thing is the POS. A word like etc. do not behave as any other word. In particular it does not behave as an ADV and can never be an adverbial modifier. We decided to give it the POS CCONJ because it can only appear in coordination and is the agglutination of a CCONJ and something else.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Hi Sylvain and all,

how should «et cætera » be analyzed (pos and dep), eg.   « Aux armes et cætera »  (To arms et cætera) ?

or etc in case of doubling ?

« I’m very annoying etc etc but  … » (https://twitter.com/rtnjeanne/status/891221385929949184 )
or in case like

« J’ai mangé, c’était bon etc etc mais c’était pas le problème »  (I’ve eaten, it was good etc etc but that wasn’t the point)


Best,
Djamé

**Comment by sylvainkahane** [comment]
I would analyze all cases of _etc_ as CCONJ `conj`:

```
Aux armes et caetera
conj(armes, et)
fixed(et, caetera)

I’m very annoying etc etc but 
conj(annoying, etc1)
conj(annoying, etc2)

etc.
```

As your examples show, _etc_ is not restricted to lists of NPs. It can appear in coordination of every POS.

**Comment by dseddah** [comment]
> Le 29 juil. 2017 à 22:20, sylvainkahane <notifications@github.com> a écrit :
> 
> I would analyze all cases of etc as CCONJ conj:
> 
> Aux armes et caetera
> conj(armes, et)
> fixed(et, caetera)
> 
> I’m very annoying etc etc but 
> conj(annoying, etc1)
> conj(annoying, etc2)
> 
> etc.
> 
> As your examples show, etc is not restricted to lists of NPs. It can appear in coordination of every POS.

in  the second example  'etc etc’ I would have been inclined to consider it as a fixed expression with some discourse labels attached to annoying, 
‘etc etc’ doesn’t have the same distribution as etc., which from a rapid check seems to occur after at least 2 phrases (would « I have apples, etc. for dinner » be acceptable? - in French, I’d say no. No idea for English).
enforcing them to be conjuncts is like pushing some (maybe plausible) interpretation. On the other hand « etc etc » can commute with « and all », « and stuff » so maybe the conj analysis is correct but I think we’re missing 
something potentially useful for a higher analysis level.


Djamé

**Comment by Oneplus** [comment]
Hi @nschneid, so what's the conclusion? Should `etc.` be analyzed as `advmod` or `conj`?

Hi @ermanh , it seems Chinese guideline suggest to tag Chinese etc. marker -- `等` as a particle (PART). Should we update the guideline to make it more consistent with similar cases in English?

**Comment by nschneid** [comment]
> would « I have apples, etc. for dinner » be acceptable?

I think it is syntactically valid to say *I'll have fish etc. for dinner* (in a context where other items can be inferred from the explicit one). Perhaps there is a menu item with a long description, and *fish* is sufficient to identify it uniquely, so the *etc.* indicates everything else that comes with fish.

I take it the conclusion is `CCONJ` as the POS and `conj` as the relation for *etc.*, at least in English.

That would create a new case of the rare (see UniversalDependencies/UD_English#37) phenomenon of `CCONJ` tokens attaching as something other than `cc` or `cc:preconj`. But I can live with it.

**Comment by Oneplus** [comment]
@nschneid Great, thanks!

**Comment by wongtaksum** [comment]
What do you think is the best way to tag 等 in the Chinese treebank?
