### ISSUE TITLE
Dislocation with determiners

### ISSUE THREAD

**Issue by vinbo8** [UniversalDependencies/docs#485]
Marathi sentences often use what appears to be dislocation in narratives or formal text, but I'm not too sure whether the appropriate deprel in some of these instances is `dislocated` or `det`, particularly when they use determiners instead of pronouns. For instance:

_John hā bāget hotā_ `John.NOM this.MASC garden.LOC was` "John was in the garden" (this refers to John, not the garden).

or:

_Mulgā "John" yā nāvāne oḷakhlā jāto_ `Boy "John" this.OBL name.INST recognised goes` "The boy goes by the name John" (this refers to the name, not the boy).

The first seems like dislocation and not a simple determiner relation to me, and I'm not too sure about the second. What is a good way to handle this?

**Comment by MemduhG** [comment]
From what I understand the determiner is both in an abnormal place and has a different inflection than usual, and this serves some grammatical purpose. Please correct me if I am wrong.

Since this seems to appear more often in formal text, it seems to me that it isn't really similar to things where the `dislocated` relation would be used like "I ate it, the bread", which are grammatical oddities and discouraged when writing. Maybe some specific variant of the `det` relation could be used for it, e.g. `det:rev`.

**Comment by vinbo8** [comment]
The determiner isn't in an "abnormal" place as such. For instance (with an intransitive verb because that's simpler),

_John hā jhoplā_ `John-NOM this-NOM slept` "John slept"

is not the same as

_Hā John jhoplā_ `This-NOM John-NOM slept` "This John slept"

There's also a clear syntactic difference between the two determiner positions, because you can have:

_John hyālā sāṃg_ `John-NOM this-DAT tell-IMP` "Tell John"

_Hyā John-lā sāṃg_ `This-OBL John-DAT tell-IMP` "Tell this John"

where the determiner's case depends on its position.

Essentially, these two determiners are completely unrelated - it is possible to combine both to get something like:

_Hā John hyālā sāṃg_ `This-NOM John-NOM this-DAT tell-IMP`

In this case, it's clear that there ought to be a `det(John, hā)`. Should the other rel be `dislocated(John, hyālā)`? Another determiner doesn't seem to make any sense there.

**Comment by sylvainkahane** [comment]
I suppose that Marathi, as many other Indo-European languages, has words that can be both determiners and pronouns (cf. English _this, each, some, one_, …). It is traditional in European grammar to consider to different POSs, DET and PRON, for these words and UD has adopted this (debatable) tradition (See Hudson 2010 for pronouns as DET. See also Melcuk's paper on POS, where he proposes not to consider that "pronoun" is a POS.)

So if we consider your examples, UD's analysis will be:

> _John hyālā sāṃg_ `John-NOM this-DAT tell-IMP` 'Tell John'
> _John_ PROPN `dislocated`
> _hyālā_ PRON `nsubj`

and

> _Hyā John-lā sāṃg_ `This-OBL John-DAT tell-IMP` 'Tell this John'
> _Hyā_ DET `det`
> _John_ PROPN `nsubj`

**Comment by vinbo8** [comment]
Okay, that looks good - analysing it as a pronoun rather than as a determiner (though the lines are honestly very blurry) makes this look more acceptable. Thanks!
