### ISSUE TITLE
Multiple nsubj on one verb?

### ISSUE THREAD

**Issue by hajimes** [UniversalDependencies/docs#489]
Short story:
Does the UD2 spec allow two `nsubj` on one verb, where one `nsubj` is subclassified into a language-specific feature like `nsubj:obl` (oblique-like nominal subject)?

e.g. (in the Ainu language),

```
káni anakne k=ek
I (intensifier) I=come
"It is I who came."

káni/PRON anakne/ADV k=/PART ek/VERB
nsubj:obl(ek, káni)
advmod(káni, anakne)
nsubj(ek, k=)
root(ek)
```

Long story:
I have a problem regarding the annotation of the Ainu language (which were briefly discussed in my paper at the NoDaLiDa UD Workshop).

Ainu (and many languages outside Eurasia) has two different sets of word classes which can serve as arguments. Pronominal clitics ("k=" in the above example) are obligatory and have rigid word order, but pronouns and nominals ("káni" in the above example) are optional and have relatively free word order.

In linguistics, it seems that the treatment is divided between formalists and functionalists.
Chomskyan formalists adhere to syntactic constraints that the number of core arguments must be less than or equal to the valency of a verb; Eloise Jelinek (1984) claimed that in these types of languages, clitics are true arguments and pronouns/nominals are adjuncts, which are somewhat different from common adjuncts in that they must not conflict with canonical clitic arguments.
On the other hand, functionalists such as William Croft and Martin Haspelmath don't see any inconveniences to have many core arguments; a verb can simply have multiple `nsubj` (and of course multiple `obj` and `iobj`).

For example,

1st person

```
káni anakne k=ek
I (intensifier) I=come
Natural English trans.: "It is I who came."
Literal trans. according to formalists: "Speaking of me, I came."
Literal trans. according to functionalists: "I I came."
```

3rd person (an empty clitic on a verb unambiguously specifies the 3rd person)

```
kimunkamuy ek
bear come
Natural English trans.: "A bear came."
Literal trans. according to formalists: "He, as a bear, came."
Literal trans. according to functionalists: "A bear he came."
```

To mitigate these conflicting views, recently I come to think of using `nsubj:obl`, `obj:obl`, and `iobj:obl` (Perhaps `*:obl` is confusing and not a good name and we may need to come up with better one).

If we adopt functionalist theory, we can simply ignore the `:obl` parts and then one verb can have unlimited core arguments. On the other hand, if we adopt formalist thoery, we can regard pronouns and nominals as secondary core arguments (`nsubj:obl`, `obj:obl`, and `iobj:obl`), which are almost oblique-like but still different from common `obl` in that they must not conflict with true core arguments. So we can easily "switch" between major linguistic theories without any annotation changes. 

Is this approach compatible with UD2? I would be very grateful if you could give me any suggestions.

**Comment by sebschu** [comment]
I don't really know anything about Ainu, so I'm not sure if this would be a reasonable solution, but have you considered the [`dislocated`](http://universaldependencies.org/u/dep/dislocated.html) relation instead of `nsubj:obl`?

**Comment by jnivre** [comment]
Yes, nsubj + dislocated is the way this is dealt with in other languages. For example, French:

Lui il arrive. 
He (emph) he comes. 

nsubj(arrive, il)
dislocated(arrive, lui)

Perhaps the facts in Ainu are different, but this would be my first suggestion.

**Comment by hajimes** [comment]
Thank you very much for valuable suggestions.

The problem on this type of languages is that under some circumstances, secondary core arguments look like core arguments in major languages.

If we use `dislocated` (and its language-specific varints to retain meaningful semantics) for nominals and pronouns as suggested, we have

```
John kampi Mary kore
John book Mary give
"John gave Mary a book."

dislocated:nsubj(kore, John)
dislocated:obj(kore, book)
dislocated:iobj(kore, Mary)
root(kore)
```

On the other hand, with my own proposal,

```
John kampi Mary kore
John book Mary give
"John gave Mary a book."

nsubj:obl(kore, John)
obj:obl(kore, book)
iobj:obl(kore, Mary)
root(kore)
```

The two solutions are isomorphic (just label-name issues) so I think both are ok to some extent (aside from linguistic issues). Which label-name convention is reasonable under the UD theory?

**Comment by ftyers** [comment]
In Chukchi (also polysynthetic), the agreement morphemes are bound morphemes (not clitics) and then pronouns are extremely rare. 

I'd be curious about the reasoning for treating them as clitics (can they appear in full form unattached to the word (like "dámelo" "que me lo des") or do they attach phrasally "The king of Spain's". Do they always appear in the same place, and do they always attach to verbal stems or other verbal bound morphemes ? Can they be separated from the verbal stem by other non-bound morphemes? Are there any "empty" clitics ?

I'm just going to throw another suggestion out there, that could be worth considering, if you want to continue treating them as clitics would be to use `aux:agr` for auxiliary agreement and then use `nsubj` for the pronoun. Much like in other languages with verbal agreement, only with the agreement morphemes considered clitics. This goes slightly outside the TAMVE remit of `aux`, but not so far.

**Comment by jnivre** [comment]
Maybe I am missing something, but why can't you not simply have:

John kampi Mary kore
John book Mary give
"John gave Mary a book."

nsubj(kore, John)
obj(kore, book)
iobj(kore, Mary)
root(kore)

Compare French:

Jean parle
nsubj(parle, Jean)

il parle
nsubj(parle, il)

Jean il parle
nsubj(parle, il)
dislocated(parle, Jean)

It is only when we have two separate "realisations" of the argument (that are both independent words and not morphological agreement features) that we invoke "dislocated".

**Comment by hajimes** [comment]
@ftyers

Thank you for making issues clear and providing suggestions.

> I'd be curious about the reasoning for treating them as clitics

The story is actually very complicated. Among a set of 12 Ainu pronominal morphemes, 2 morphemes are clearly free morphemes, but other 10 morphemes are partly clitic-like but partly affix-like. Furthermore, the former are enclitics (or suffixes) but the latter are proclitics (or prefixes), so some Ainu linguists think they are a different set of pronominal morphemes.

Free morphemes: "=an" 1PL.INCL.INTR (first person inclusive for intransitives) and "=as" 1PL.EXCL.INTR.

```
cis a cis a
he.weep too he.weep too 
"He continued to weep"

cis=an a =an a
weep=we too we too
"we, including you, continued to weep"
```

On the other hand, proclitics or prefixes like "ku=" (1SG) tend to be fused into verbs and they also interact with the phonotactics of the verbs (e.g, "ku=" + "arpa" -> "k=arpa": "u" in "ku=" is deleted; "ku=" + "iták" -> "kú=itak": the accent position denoted by "´" changed). It is therefore possible to claim that they are affixes (though they have some properties which are not shared by other verbal affixes).

There are still other considerations and Bugaeva (2011) proposed more fine-grained classification; "=an" and "=as" in the above are independet words (not clitics), some from 10 are clitics, and the rest is affixes.

That said, the above tendencies are actually only limited for verbal constructs. If they are used with nominals and noun phrases, even "prefixes" behave like clitics. As long as they precede head nominals, they can appear anywhere in noun phrase constructs.

```
Shibatani, 1990, p. 73

kurasno poro e=setaha (head-initial)
black big you=dog

e=kurasno poro setaha (phrase-initial)
you=black big dog
```

Both denote "your black big dog". It can appear even in phrase-middle positions.

```
Shibatani, 1990. p. 75

pon a= kor yupi
little I have elder.brother
"My little elder brother"
```

So I want to be simple and to say all of them are simply clitics, rather than to get headaches by complex if-then-else.

> if you want to continue treating them as clitics would be to use aux:agr for auxiliary agreement and then use nsubj for the pronoun.

I thank you for your thoughtful comments. I made the proposal in this post because I have read several papers on the Pronominal Argument Hypothesis from the Chomskyan school (notably from Eloise Jelinek and Mark Baker) which claimed in these polysynthetic languages clitics/affixes are true arguments, not auxiliary agreement markers. But I'm not sure if their hypothesis is sound.

I think it's good to have a language-specific relation `aux:agr` as you suggested, because Ainu also has auxiliary verbs which are very similar to those of major languages, so we need to distinguish these common `aux` from pronominal auxiliaries `aux:agr` (clitics, affixes, whatever). I'll try to examine this possiblity.

**Comment by hajimes** [comment]
@jnivre

Thank you for your practical advice.

Typologically speaking, having two sets of arguments (affixes/clitics for obligatory true core arguments, nouns/pronouns for optional arguments) is a cross-linguistic phenomenon which can be seen in many languages, especially highly common in polysynthetic languages. Perhaps we might want to encode this typological fact. Or perhaps we might not, because I understand UD is for descriptive annotations, not necessarily for theoretical researches on typology.

I think your realization-based approach is a great idea for annotation, since if we focus on one language, it will greatly reduce annotation ambiguity.

In French, how do we annotate dislocation if it has non-subject alignment? I think it's convenient to have subtypes of dislocation for natural language understanding.

```
káni k=arpa wa (Sato, 2008, p. 24)
I I=go (intensifier)
"I'll go."

dislocated:nsubj(arpa, káni)
nsubj(arpa, k=)
advmod(arpa, wa)
root(arpa)
```

```
káni hem oca en=kore yan (Sato, 2008, p. 24)
I too tea me=give please
"Please give me a cup of tea, too."

dislocated:iobj(kore, káni)
advmod(káni, hem)
obj(kore, oca)
iobj(kore, en=)
advmod(kore, yan)
root(kore)
```

But at least in Ainu it is possible to guess the type of dislocation by using pronominal clitics (not always, but in many cases). So perhaps we can overburden context processors for discourse and don't need such subclassification at the syntatic annotation level, if you want to minimize the expansion of language-specific features.

**Comment by jnivre** [comment]
What you suggest looks very reasonable to me. I think we need to review more systematically the different types of (multiple) realisation of arguments across languages and possibly revise our guidelines in the process. As you say, the motivation for UD is mostly practical, and we do not aspire to be a linguistic theory, but we also want to avoid to do things that do not make linguistic sense.

**Comment by hajimes** [comment]
@sebschu @jnivre @ftyers 
I'm sincerely thankful to your comments! I'll try to examine both the `dislocated` approach and the `aux` approach more carefully and rethink my annotation scheme whether they improve annotation consistency for Ainu.

**Comment by wongtaksum** [comment]
Dear all,
     So have we reached a consensus here?  
     In the case of:
John kampi Mary kore
John book Mary give
"John gave Mary a book."
, where word order is not free, I suppose.

Shall we use:
nsubj(kore, John)
obj(kore, book)
iobj(kore, Mary)
root(kore)

or 

dislocated:nsubj(kore, John)
dislocated:obj(kore, book)
dislocated:iobj(kore, Mary)
root(kore)

or

nsubj:obl(kore, John)
obj:obl(kore, book)
iobj:obl(kore, Mary)
root(kore)
???

I am confused by the Japanese example of dislocated in the guideline.  In the guideline, the noun marked by the topic marker "wa" is defined as a dislocated word.  However, in the Japanese treebank, this is not the case!!!  In this case, nsubj is used instead!!

If the above is too complicated.  Let's use an example in English:
1. Apple, I like it.
2. Apple, I like.

In the first case, clearly you would use dislocated, but what about in the second case?  "Apple" is a core argument but it is not in a typical object position.

@kimgerdes  You might be interested in this thread.

**Comment by jnivre** [comment]
For the English example 2, we should definitely just use "obj". Topicalisation may be less common in English than in other languages, but it doesn't change the syntactic relation. In general, I would be very restrictive with using "dislocated" when there is not a double realisation (despite the Japanese example in the guidelines), and I would advise against subtypes like nsubj:obl (at least until I have heard more argument). From what I have heard so far, I would still propose:

nsubj(kore, John)
obj(kore, book)
iobj(kore, Mary)
root(kore)

**Comment by wongtaksum** [comment]
Oh Thank you very much for your comments!

**Comment by murawaki** [comment]
I happened to look into the grammar of Fijian and found that multiple nsubj's are a fairly regular phenomenon although Fijian is definitely not a polysynthetic language.
- A verb is preceded by an obligatory subject pronoun.
- The predicate can be followed by a subject NP with a noun (double nsubj's).
- The predicate can be followed by a subject NP with a cardinal pronoun, mainly for emphasis (double nsubj's).
- The predicate can be followed both by a subject NP with a cardinal pronoun and by a subject NP with a noun (triple nsubj's).
For more information, see [Section 4.2 of Dixon (1988)](https://books.google.com/books?id=zCFhkgbYSJUC&pg=PA33&lpg=PA33&hl=en). 

Also relevant is WALS's [Feature 101A: Expression of Pronominal Subjects](https://wals.info/chapter/101) by Matthew S. Dryer. Languages like Fijian are classified as "Subject pronouns in different position". For some reason, Dryer treats Ainu's obligatory subject markers as affixes. Dryer suggests that this type is an amalgam of two subtypes, only one of which matters here. But they are no rarer than languages like English, suggesting the need for a principled solution.

**Comment by Stormur** [comment]
> I happened to look into the grammar of Fijian and found that multiple nsubj's are a fairly regular phenomenon although Fijian is definitely not a polysynthetic language.
> 
>     * A verb is preceded by an obligatory subject pronoun.
> 
>     * The predicate can be followed by a subject NP with a noun (double nsubj's).
> 
>     * The predicate can be followed by a subject NP with a cardinal pronoun, mainly for emphasis (double nsubj's).
> 
>     * The predicate can be followed both by a subject NP with a cardinal pronoun and by a subject NP with a noun (triple nsubj's).
>       For more information, see [Section 4.2 of Dixon (1988)](https://books.google.com/books?id=zCFhkgbYSJUC&pg=PA33&lpg=PA33&hl=en).
> 
> 
> Also relevant is WALS's [Feature 101A: Expression of Pronominal Subjects](https://wals.info/chapter/101) by Matthew S. Dryer. Languages like Fijian are classified as "Subject pronouns in different position". For some reason, Dryer treats Ainu's obligatory subject markers as affixes. Dryer suggests that this type is an amalgam of two subtypes, only one of which matters here. But they are no rarer than languages like English, suggesting the need for a principled solution.



The obligatory subject pronoun looks like a particle or affix rather than a true subject and could have the relation `expl` rather than `nsubj`, which could be assigned to the postponed subject noun phrase. This could be the case especially if verb+particle form an inseparable unit (contrary e.g. to Germanic languages). Incidentally, a similar thing happens also in many dialects in Northern Italy, where such pronominal particles are really just a part of the conjugation alongside the verbal ending and the true subject: e.g. Milanese _ti [**te** seet]_ vs. Italian _tu [ _ sei]_ 'you are'. _te_ is derived from the second person personal pronoun and is obligatory, whereas _ti_ 'you' is not.

The cardinal pronoun for emphasis might be treated as a `dislocation`.

In sum, the only "true" subject (and then `nsubj`) seems to be the optional noun phrase after the verb; the other elements seem to be either obligatory or strictly limited in form and function.

**Comment by murawaki** [comment]
Thank you for the suggestion. No one has recommended ``expl`` in this thread but it looks better for cross-linguistic compatibility than ``aux``.

I think the obligatory subject pronouns are words (clitics) rather than affixes. According to Dixon, a tense-aspect maker and/or a discourse marker can be inserted between a subject pronoun and a verb, and the order of these elements are mostly, but not completely, fixed.
