### ISSUE TITLE
XML or JSON for pos/features/deprels?

### ISSUE THREAD

**Issue by hajimes** [UniversalDependencies/docs#493]
Does the UD project provide the list of items under data serialization formats such as XML and JSON (other than  auto-generated `stats.xml` for each language)? 

Something like:
```
{
  "upostag": [
    {
      "id: "adp",
      "name": "adposition"
    }
  ],
  "feat": [
  ],
  "deprel": [
    {
      "id": "nsubj",
      "name": "nominal subject",
      "functional_category": "core arguments",
      "structural_category": "nominals"
    },
    {
      "id": "advcl",
      "name": "adverbial clause modifier",
      "functional_category": "non-core dependents",
      "structural_category": "clauses"
    }
  ]
}
```

**Comment by martinpopel** [comment]
I am not aware of any XML/JSON with this info. You can create it from [the guidelines](http://universaldependencies.org/) and [lists of language-specific labels](https://github.com/UniversalDependencies/tools/tree/master/data).

**Comment by hajimes** [comment]
@martinpopel 
Thanks for your clear answer!

**Comment by arademaker** [comment]
Hi @hajimes you may find some information at http://www.acoli.informatik.uni-frankfurt.de/resources/olia/. One of my students is working on UD 2.0 modeling, possible extending the ideas of olia for consistency checking.

**Comment by hajimes** [comment]
@arademaker 
Thank you for introducing interesting work. I found several xml/owl files for UD 1.3 at the web site. Linguistic infrastructures based on ontological modeling sound promising and I hope UD 2.0 version will come soon.
