### ISSUE TITLE
Copula in Chinese

### ISSUE THREAD

**Issue by Oneplus** [UniversalDependencies/docs#497]
Hi all,

We've been working on creating a UD treebank of simplified Chinese. We found that the part-of-speech of `是` (shi4) was annotated differently between UD_Chinese and UD_Chinese-CFL. It seems in UD_Chinese-CFL which, we believe, was more recently created and more consistent with the guidelines. `是` (shi4) was annotated as `VERB` when either it's used as a copula or not. However, the UD_Chinese differs `AUX` from `VERB` and it's more consistent with UD_English.

So we would like to know the reason of UD_Chinese-CFL annotating all the 是 (shi4) as `VERB`.

**Comment by jnivre** [comment]
Great to hear that there is more interest in developing Chinese treebanks in UD. You are quite right about the relation between UD_Chinese-CFL and UD_Chinese. The latter has unfortunately not been maintained actively since it was first created by Google.

Regarding your other question, I think @ermanh should be able to answer. It sounds like a "bug" to me, since the "cop" relation requires the "AUX" tag in v2.

**Comment by ermanh** [comment]
Thanks @jnivre, and hi again @Oneplus, yes, this is a known discrepancy between the overall UD guidelines vs. the UD Chinese guidelines that we wrote up regarding the copular usage of 是. Part of it is my fault for not noticing the discrepancy while adapting v2, but part of it was also a decision to keep a unified POS tag for the verb regardless of its many uses, which we unfortunately didn't have time to dissect carefully.

I'm not officially a member of the team managing the UD_Chinese-CFL data anymore (EDIT: or the UD Chinese guidelines themselves, though I do occasionally fix typos I had previously made if I see them, and I'm always happy to answer questions about specific decisions that were made); the main contact person now for both the UD_Chinese-CFL data and the Chinese guidelines is Sam @wongtaksum. If it is a must to use the "AUX" tag with the "cop" relation, perhaps both the data and the UD Chinese guidelines could be fixed and updated before the upcoming release (seems like a simple script should do?).

**Comment by martinpopel** [comment]
> seems like a simple script should do

[Yes](https://github.com/udapi/udapi-python/blob/3fe163a4c0feb5e844e325024b5f6e6da66c5764/udapi/block/ud/convert1to2.py#L113-L116)

**Comment by Oneplus** [comment]
@ermanh Thank you for the clarification. I believe `AUX` is the better tag.

**Comment by jnivre** [comment]
Whether or not it is the better tag, it is the one required by the guidelines. :)

**Comment by Oneplus** [comment]
@jnivre Sure, we will adopt the `AUX`.

**Comment by wongtaksum** [comment]
Guys, thank you for your contributions!
So, according to the guideline, every copula uses AUX with cop?  If so, I will update the data tomorrow.

**Comment by jnivre** [comment]
Yep!
