### ISSUE TITLE
Leaving out inflectional information

### ISSUE THREAD

**Issue by vinbo8** [UniversalDependencies/docs#498]
Is it acceptable to leave out inflectional information when it clearly does not reflect morphologically in certain instances? Eg. Indo-Aryan adjectives typically do not agree with anything in the oblique case. Is it a better idea to add contextual gender/number/person or just leave all of them out if the adjective is in the oblique?

**Comment by jnivre** [comment]
I don't think we have a clear policy on this, and I therefore suspect that different treebanks have different practices, but I would say it is okay to leave them out.

**Comment by dan-zeman** [comment]
I agree with @jnivre that this is not standardized (and not easily standardizable). I think the features should in the first place describe the word itself. If it is an adjective and if adjectives do not inflect for person (which, I believe, is the case not only in Indo-Aryan but in many other languages), then there is no reason to include the feature, regardless whether the case is oblique or not.

Disambiguation by context should be needed only if a word class inflects for a feature but this particular word happens to have ambiguous form for several values of the feature. Then I would show the value of the feature, but disambiguated by context.

If it is a feature like gender, where the adjective may have forms for different genders (I suppose it can), but it has always just one form in the oblique, then I think it is really up to you whether you want to disambiguate in the oblique or not. Both approaches are used, even within one language for different phenomena.

**Comment by sylvainkahane** [comment]
If the lexeme can have different forms in a given language, I cannot guess what is the form that is used in positions where the agreement is blocked. So I think the features concerning the whole paradigm of the lexeme are needed in every position. And/or maybe an additional feature is needed to say that the agreement is blocked in this position and the default form is used.

**Comment by ftyers** [comment]
My opinion is that the analysis/features should give enough information to correctly produce the surface form (ideally unambiguously -- but some of the extra information, e.g. paradigm for words that have ambiguous lemmas --- e.g. _lie_ --- could be in the `MISC` column)

**Comment by vinbo8** [comment]
Having `Case=Obl` is enough morphological information to generate the surface form, so that's probably what I'll do for now. @sylvainkahane, I don't think I understand what you mean by not being able to guess what the form is - could you elaborate?

**Comment by sylvainkahane** [comment]
@vinit-ivar If you have only one form with `Case=Obl`, it's ok, you can guess what the form is knowing the lemma and the morphosyntactic features. Same recommendation than @ftyers.
