### ISSUE TITLE
Morphological features in English

### ISSUE THREAD

**Issue by xsway** [UniversalDependencies/docs#499]
I guess it's rather an improvement plea than a question. As I understood from the documentation, morphological features in English treebanks were added automatically and consequently they are quite sparse and incomplete. 

I found, for example, that only singular forms of verbs/auxiliaries are annotated with the number feature (`Number=Sing`) but not the plural ones.

It would be great to see some better coverage in this case and in general.

[I don't have a good idea whether people use the English UD treebank widely? Or maybe instead someone uses the PTB/CONLL treebanks and convert them to UD? If such a convertion tool is available somewhere I would be very grateful to know!]

Thanks!

**Comment by dan-zeman** [comment]
Is this something that applies to multiple English treebanks? (There are 5 at the moment.) Or would it be more suitable to move the issue to a particular treebank repository?

**Comment by amir-zeldes** [comment]
At least EWT and GUM get their morphology automatically from CoreNLP, with the exception of Polarity=Neg, which is added on top.

I can also answer the question by @xsway : yes, there are automatic conversion tools - you can convert PTB brackets to UD using CoreNLP, and you can convert non UD-English (Stanford Dependencies) into UD as well, though in both cases, conversion of names depends on NER or gold entity annotation. EWT was originally converted from constituent brackets, and GUM was converted from Stanford Dependencies using DepEdit: https://corpling.uis.georgetown.edu/depedit/ 

Hope this helps!
