### ISSUE TITLE
coordinating conjonctions between sentences - discourse

### ISSUE THREAD

**Issue by CatalinaMaranduc** [UniversalDependencies/docs#500]
In the Gospels of 1648 there are many sentences that begin with a coordinating conjunction that establishes a relationship with the previous sentences.
I have noticed that in the Romanian treebank in UD similar cases are considered the root of the sentences and the true nucleus of the sentence is subordinated to them and has the relation ”discourse”.
Ex:
sent_id = train-2964
4      dar	dar	CCONJ	Ccssp	Polarity=Pos	0	root	_	_
5	n-	nu	PART	Qz-y	Polarity=Neg|Variant=Short	7	advmod	_	SpaceAfter=No
6	am	avea	AUX	Va--1	Person=1	7	aux	_	_
7	știut	ști	VERB	Vmp--sm	Gender=Masc|Number=Sing|VerbForm=Part	4	discourse	_	
(1 but 6 did 5 not 7 know)
It does not result from the general explanations of the relationship ”discourse” a same interpretation.
In my annotation, these conjunctions have the relationship ”discourse” and are subordinated to the root.
Example.
Matt. 11.16
1 | Dar | dar | CCONJ | Ccssp | Polarity=Pos | 4 | discourse
-- | -- | -- | -- | -- | -- | -- | --
2 | cui | cine | PRON | Pw3-so | Case=Dat,Gen\|Number=Sing\|Person=3\|PronType=Int,Rel | 4 | iobj
3 | voi | vrea | AUX | Vaip1s | Mood=Ind\|Number=Sing\|Person=1\|Tense=Pres | 4 | aux
4 | închipui | închipui | VERB | Vmn | Mood=Inf\|VerbForm=Fin | 0 | root
5 | ruda | rudă | NOUN | Ncfsry | Case=Acc,Nom\|Definite=Def\|Gender=Fem\|Number=Sing | 4 | obj
6 | aceasta | acesta | DET | Dd3fsr---o | Case=Acc,Nom\|Gender=Fem\|Number=Sing\|Person=3\|Position=Postnom\|PronType=Dem | 5 | det
(1 But 2 who 3 will 4 compare 6 this 5 generation)
how is it right?
I have just transposed 520 phrases in UD format, if I have to change this annotation mode, I can do it.

**Comment by jnivre** [comment]
The verb should definitely be the root here, but the relation to the initial conjunction should normally be cc, not discourse. See: http://universaldependencies.org/u/dep/cc.html

**Comment by CatalinaMaranduc** [comment]
ok

**Comment by CatalinaMaranduc** [comment]
But if the first word is a subordinating conjunction, it should be
annotated as ”mark”, it is not a ”cc” ?

**Comment by dan-zeman** [comment]
@CatalinaMaranduc : Yes, I think it should.

**Comment by CatalinaMaranduc** [comment]
ok, thank you.
