### ISSUE TITLE
le président Macron and President Trump: flat?

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#503]
in discussion #501 we concluded that English has two constructions N N:

- N2 N1 for _pizza boy_ or _Michigan Lake_
- N1 N2 for _Fort Alamo_ or _Mount Rushmore_

And that both constructions could be analyzed with `compound(N1,N2)`.

My first question is: why this analyses does not apply to _President Trump_? Do you really think that _President Trump_ is headless? (I mean the expression, not the real guy.) In other word why do we want `flat(President,Trump)` rather than `compound(President,Trump)`? (cf. _President Obama_ in [flat page](http://universaldependencies.org/u/dep/flat.html)).

My second question is: what to do for other languages? For instance, we do not have an N2 N1 construction in French. The head is always the first noun: _le lac Michigan, le mont Rushmore_, etc. And _le président Macron_ (with the determinant _le_ necessarily). So I have no hesitation to consider that _président_ is the head and I'm not in favor of the relation `flat` which is for headless constructions. The relation should be `appos` if we follow the guide (cf. _the French actor Gaspard Ulliel_ in [appos page](http://universaldependencies.org/u/dep/appos.html)).

**Comment by dan-zeman** [comment]
I do not see it as a problem if two expressions with the same meaning have different analyses in two languages. If there are grammatical clues in one language that are not so obvious (or non-existent) in the other language then perhaps we can say that the two languages use different strategiees to encode the same construction.

**Comment by nschneid** [comment]
I think occupational titles like *President*, *King* fall somewhere between person-honorifics like *Mr.* and location-types like *Fort*. I would definitely not want to say that *Mr.* is a head, because *Mr.* must always precede a name.

**Comment by XinyingChen** [comment]
It is not that straightforward in Chinese...

I agree that intuitively President somehow feels like Mr., however, in
Chinese (with relatively fix word order), we can only put Mr. behind a name
while President can fall behind as well as infront of a name. So they are
not really equivalent in those structures.

Meanwhile, it can be a problem for using flat to annotate *President Trump*,
since it means there would be two ways of annotates in Chinese (and no
specific cretiria for identifying the 'correct' one). In a way, it would
lower the coherence of Chinese corpus.

So, maybe headless annotation flat is a 'real' problem, but I am not sure
about the good solution for now....

2017-11-08 3:11 GMT+01:00 Nathan Schneider <notifications@github.com>:

**Comment by jnivre** [comment]
The thing about "flat" is that you have to remember that it literally means what it says, that is, that none of the elements is (a clearly discernible head). So, if there is variation between X Y and Y X, but there is no clear indication that either X or Y is the head, then think of the flat annotation as just a bracketing [X Y] and [Y X], not as structures with different heads X -> Y and Y -> X.

**Comment by sylvainkahane** [comment]
I agree with @dan-zeman that we can have different analyses in different languages. The universal part of the guide must be very clear about that. Because most examples are in English, it is not always clear whether the examples that are given concern a specific construction of English or a universal recommendation. It is the case with the [flat page](http://universaldependencies.org/u/dep/flat.html), where it is said "Titles/honorifics are also analyzed using the `flat` relation.". If we agree on @dan-zeman's remark, this must be reformulated by something like that: "For instance, titles/honorifics are analyzed using the `flat` relation in English because in this language there are no clear arguments to decide where is the head. In other languages such as …, titles/honorifics can be analyzed using …"

@XinyingChen Can you give the data for Chinese?

**Comment by jnivre** [comment]
I also agree with @sylvainkahane and @dan-zeman. This is one of the aspects of the documentation that needs to be improved. We will start this work for real once we are done with release v2.1.

**Comment by dan-zeman** [comment]
Related: #400
