### ISSUE TITLE
relation subtype descriptions are not available

### ISSUE THREAD

**Issue by evelinacs** [UniversalDependencies/docs#504]
Visiting any of the links on the language-specific relations page (http://universaldependencies.org/ext-dep-index.html) results in a 404 http error.

**Comment by jnivre** [comment]
Thanks for reporting this. We'll look into it. As announced on the UD mailing list, we are in the process of reorganising the entire documentation. Bear with us. :)

**Comment by CatalinaMaranduc** [comment]
I will use the universally specific UD relationship that the other treebank
uses for Romanian.
I just notice that advcl:tmod is no longer used, it has been replaced by
advcl:tcl and has not been deleted from the list.
Also note the absence of nsubj:pass in the list, used in the two Romanian
treebanks.

Cătălina Mărănduc

**Comment by jnivre** [comment]
This page has not been updated to v2 and will probably be replaced by a completely different structure eventually. Sorry for the inconvenience.

**Comment by dan-zeman** [comment]
Fixed, thanks @spyysalo! Blue links work. Red links do not work because nobody has written the target page so far.
