### ISSUE TITLE
Ellipsis in relative clauses

### ISSUE THREAD

**Issue by prokopidis** [UniversalDependencies/docs#505]
Hi,

The guidelines for ellipsis focus on constructions that involve some type of coordination. In Greek (and, I believe, in other languages as well) there are constructions that could be seen as relative clauses with an elided predicate:

```
1. Πολλά νησιά,     μεταξύ  των οποίων  η Σίφνος,   έχουν... 
Many  islands-nom,  among   which       Sifnos-nom, have...
```

```
2. Επισκέφτηκαν πολλά νησιά,        μεταξύ  των οποίων  τη Σίφνο 
They-visited    many islands-acc,   among   which       Sifnos-acc
```

```
3. Έφυγαν από την εταιρεία, πολλοί  εκ των οποίων   για τα καλά 
They had left the company,  many    of whom         for good
```

In the examples above, a variation with a coordinating conjuction is often used: 

```
4. Πολλά νησιά,     μεταξύ  των οποίων  και η Σίφνος,   έχουν... 
Many  islands-nom,  among   which       and Sifnos-nom, have...

```

Example 3 is a variation of one of the English examples in the guidelines: `They had left the company , many for good`. The original example is analyzed by promoting `many` to `conj` and by annotating `for good` as an `orphan`. 

But, due to the presense of the relative pronoun in examples 1-4, an analysis could be to promote one of the dependents (following the `nsubj > ... > advcl` order) to `acl:relcl` and to attach the others with the `orphan` relation:

```
2.  Επισκέφτηκαν πολλά νησιά,   μεταξύ των οποίων τη Σίφνο 
They-visited many islands-acc,  among  which      Sifnos-acc
acl:relcl(νησιά, Σίφνο)
orphan(Σίφνο, οποίων)
```

Any thoughts? Also, I am not sure whether in the first example, one can assume an elided copula and thus have:

```
1.  Πολλά νησιά,        μεταξύ  των οποίων  η Σίφνος,   έχουν... 
    Many  islands-nom,  among   which       Sifnos-nom, have...
nsubj(οποίων, Σίφνο)
acl:relcl(νησιά, οποίων)
```

**Comment by jnivre** [comment]
We had a discussion in another thread about whether gapping is possible in comparative constructions, and it seemed to be in some languages but not in others (perhaps). So I suppose the same could be true of relative clauses. The question is whether they can all be expanded to full relative clauses, which would increase the plausibility of the analysis.

**Comment by prokopidis** [comment]
Thank you. In the second of the examples above, the most obvious way to construct a full relative clause would be to repeat the verb of the main clause. But such a sentence would never be observed in actual texts.

**Comment by sebschu** [comment]
Gapping is definitely possible in relative clauses in some languages (for example, in Dutch, see example (17) in our [UDW paper](https://nlp.stanford.edu/~sebschu/pubs/schuster-lamm-manning-udw2017.pdf)). 

But I'm also not sure whether these are really examples of gapping. In the English translation of example (3), "many of whom" would be the subject of an elided "left" and "for good" an oblique modifier, so there are clearly two arguments/modifiers of an elided predicate. But for the other examples, it's not clear to me which grammatical roles "among which" and Sifnos would take. 

Have you thought about how you would analyze these sentences in the enhanced representation with additional nodes? As Joakim already said, it's only really plausible to assume that there is gapping if you could expand the relative clause to something that has an overt predicate.

**Comment by sylvainkahane** [comment]
One of the constructions is possible in French:

> nous avons visité plusieurs îles, parmi lesquelles Sifnos

The ellipsis analysis has only a diachronic value. Today it is quite fixed and _parmi lesquel(le)s_ works as _including_ in English.

**Comment by prokopidis** [comment]
It is possible to "reconstruct" the relative clauses with overt predicates that have roles for "among which" and "Sifnos" for all examples:

```
1. Πολλά νησιά,     μεταξύ  των οποίων  συγκαταλέγεται	η Σίφνος,   έχουν... 
Many  islands-nom,  among   which	is included    	Sifnos-nom, have...
nsubj(συγκαταλέγεται, Σίφνος)
obl(συγκαταλέγεται, οποίων)
```

```
2. Επισκέφτηκαν πολλά νησιά,        μεταξύ  των οποίων  επισκέφτηκαν	τη Σίφνο 
They-visited    many islands-acc,   among   which	they-visited	Sifnos-acc
obj(επισκέφτηκαν, Σίφνος)
obl(επισκέφτηκαν, οποίων)
```

But example 1 is very formal and rare compared to the construction without the predicate. On the other hand, the repetition of the verb in example 2 would not be actually observed in real life, which I guess is needed for the expansion criterion to hold.  

So, what are the alternatives for similar constructions? Perhaps handling them as special cases of coordination and attaching the relative phrase to the second conjunct as a fixed phrase or as an nmod?

**Comment by jnivre** [comment]
At least one of them seem to parallel to the French example brought up by @sylvainkahane, so it would be interesting to hear how it is analysed in French.

**Comment by dan-zeman** [comment]
> would not be actually observed in real life, which I guess is needed for the expansion criterion to hold.

I don't think it is needed. Or at least there is some flexibility (is it still just highly improbable, or is it already ungrammatical?)

**Comment by prokopidis** [comment]
Well, I looked at a sample of 100 sentences from newspaper articles containing the string `μεταξύ των οποίων/among which`. When the non-relative dependent is a subject, there are a few instances where an overt verb (translated as either `is included` or `stands out`: `... διεθνείς παρατηρητές, μεταξύ των οποίων ξεχωρίζει το Κέντρο Κάρτερ/ ... international observers, among which the Carter Center stands out`).  

But when the non-relative dependent is not a subject, I found no cases where an overt verb is observed. And yet, I think that I would classify such a sentence as very odd or unacceptable, not ungrammatical.
