### ISSUE TITLE
obl:tmod in Chinese

### ISSUE THREAD

**Issue by Oneplus** [UniversalDependencies/docs#508]
Hi folks,

As mentioned in Chinese guidelines (http://universaldependencies.org/zh/dep/obl-tmod.html), the temporal noun in a prepositional phrase is attached with `obl:tmod` when it acts as a temporal modifier, even there is a preposition (在 zai4) before it.

However, it's not consistent with UD_English. In UD_English, obl:tmod is only used when there is no preposition ahead. See that in http://bionlp-www.utu.fi/dep_search/query?search=tonight&db=UD_English-v2&case_sensitive=True&hits_per_page=50

![image](https://user-images.githubusercontent.com/745499/32975126-317a87dc-cc3f-11e7-82c5-7a8ea37d6043.png)

![image](https://user-images.githubusercontent.com/745499/32975130-3d75422a-cc3f-11e7-8b01-672a95908157.png)

In the first example, there is no preposition modifies `tonight`, thus, `obl:tmod` is used. But in the second example, there is a preposition `around`, so even `tonight` works as a temporal modifier, it's still labeled as `obl`.

So, maybe it's a better practice to use `obl` for the temporal noun with a leading preposition.

An additional question is that if the temporal noun is modified by a postposition (like 里 li3), should we use `obl` or `obl:tmod`.

**Comment by dan-zeman** [comment]
I don't see why preposition should make a difference. If you see a pattern in data, it does not necessarily mean that the pattern is a rule. It is also possible that there is an annotation error.

The English documentation has not been updated to UD v2 and the relevant page was named nmod-tmod until now. I just renamed the page and replaced `nmod` with `obl`. The second example clearly shows that preposition can occur in `obl:tmod`: http://universaldependencies.org/en/dep/obl-tmod.html

**Comment by ermanh** [comment]
Second @dan-zeman here. The "obl" relation itself is not limited to whether a case marker or adposition is present or not, so I don't see why a subrelation would have a limitation on that as well. Temporal modifiers that are NOUN should be treated with obl:tmod regardless of whether an adposition is there or not.
