### ISSUE TITLE
Appos and directionality

### ISSUE THREAD

**Issue by kristiank** [UniversalDependencies/docs#510]
All examples I can find in the documentation that pertains to version 2 has the ``appos`` arrows going to the right. Is this a requirement of version 2?

I ask, because we got it as a requirement for annotating, but the traditional notion of appositional modifiers in our language is wider and the head can be on either side (cf jnivre's comment on #180). This would impose choosing the first pariticipant as head and I could live with it, but it seems strange to impose a restriction on the directionality of a dependency.

**Comment by martinpopel** [comment]
The rule that appos should be left-headed is encoded in UDv2 svalidation rules [here](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py#L93) and [here](http://universaldependencies.org/svalidation.html#appos-is-right-headed).
The [guidelines](http://universaldependencies.org/u/dep/appos.html) say "immediately following the first noun", which implies the direction is required. And also "the two halves of an apposition can be switched", which somehow explains that the required direction is just a matter of annotation consistency (not a linguistic reason), similarly to `list` or `conj`.
Note that as as @manning [says](https://github.com/UniversalDependencies/docs/issues/180#issuecomment-298368643) in the old (pre-UD2) discussion #180, some of the examples, called "fixed apposition" in some traditional grammars, should be annotated with `flat` in UDv2.

**Comment by jnivre** [comment]
I can see the point about directionality, and the truth of the matter is probably that "appos" is not a pure dependency relation. The idea is that an apposition (in this narrow sense) is an elaboration, a non-restrictive modifier in the form of a co-referential noun phrase, and it follows that the elaboration must follow the first referential noun phrase. It can always be debated whether this is an appropriate concept, but it is what we have for v2 (as in v1), although we are aware that its application is still not consistent across languages.

As @martinpopel points out "flat" may be an alternative in case of titles and similar, but if it is clear that the second nominal is the head, then "nmod" is the relation to use.

**Comment by kristiank** [comment]
Thank you for elaborating on this. Perhaps it would be a good idea to add something on the non-purity of the "appos" dependency relation in the docs. I find that other non-linguistic relations do this very nicely in the docs, and I guess this kind of conventions is what often is forgotten when some kind of linguistic truth is started to be searched for instead, not realising they both are simply conventions in the first place. This is at least what happened to me. Thank you again, this Issue can be closed.

**Comment by olesar** [comment]
A note about "_immediately_ following the first noun": What about hesitation markers, particles, reparanda, punctuation marks that pop up between two nominals?And it seems that most of examples in the guidelines likeSam , my brother , arriveddo not suit the definition as well. Olga

**Comment by sylvainkahane** [comment]
There are some constructions, which I think must be formalized with `appos`, where the second conjunct is not adjacent to the first one (and the tree is not projective):

> I gave many exercises to my students: one on coordination, one on apposition, etc.
> A few things must be changed: the light, the paint, etc.

Here I think we would like:

> appos(exercises,one)
> appos(things, light)

**Comment by jnivre** [comment]
Agreed. I think the word "immediately" should be removed from the definition.

**Comment by martinpopel** [comment]
First, I would suggest to keep this issue about directionality of appos and start a new issue about the word "immediately" in the appos guidelines (if there is more discussion on the topic). I think now we all agree that appos is always left-headed, so @kristiank can close this issue and possibly start a PR which adds a sentence about "non-purity" to the guidelines.

@olesar: as obvious from the guidelines, punctuation is not considered as breaking the "immediately" nature. I don't know why the word "immediately" is needed (what are the counter-examples). I agree hesitation markers etc. should be allowed.

@sylvainkahane: I think the sentence "A few things must be changed: the light, the paint, etc." should be included in the guidelines.

**Comment by kristiank** [comment]
@martinpopel Where do I find the guidelines texts to edit?

**Comment by martinpopel** [comment]
@kristiank: I've included the link to appos guidelines in my first post: http://universaldependencies.org/u/dep/appos.html
There is an "edit page" button on top of the page, which brings you to GitHub editing, where you can suggest a change as a Pull Request (or commit directly if you have the rights to do so and if there is no controversy about the edit).
