### ISSUE TITLE
Lemma of English possessive clitic

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#515]
There is a spelling rule that if a noun has been pluralized with *-(e)s*, then it is made possessive by adding *'*, and if not, by adding *'s*. Because this is merely a spelling rule, I think both should have *'s* as the lemma.

The English treebanks are currently inconsistent on this: [UD_English-LinES](/UniversalDependencies/UD_English-LinES) has *'s* as the lemma if the token is *'* ([query](http://bionlp-www.utu.fi/dep_search/query?search=%27%26PART%26L%3D%27s&db=UD_English-LinES-dev&case_sensitive=True&hits_per_page=50)), while the others keep the surface form as the lemma.

**Comment by dan-zeman** [comment]
+1 for making _'s_ the lemma of both forms.

Has the inconsistency been fixed and can we close the issue?

**Comment by amir-zeldes** [comment]
In GUM this is already the case (also normalizing over various apostrophe glyphs):

https://corpling.uis.georgetown.edu/annis/#_q=cG9zPSJQT1MiIF89XyBsZW1tYQ&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by nschneid** [comment]
> Has the inconsistency been fixed and can we close the issue?

Yes, e.g. "-s" in http://bionlp-www.utu.fi/dep_search/query?search=Jack%20%3E%20-s&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=10

Incidentally, I had been searching http://bionlp-www.utu.fi/dep_search/query?search=Jack%20%3E%20-s&db=UD_English-dev&case_sensitive=True&hits_per_page=10, but that is not up to date—maybe it does not reflect the renaming of UD_English to UD_English-EWT.
