### ISSUE TITLE
displaying letters with diacritics

### ISSUE THREAD

**Issue by wongtaksum** [UniversalDependencies/docs#518]
http://universaldependencies.org/zh/pos/ADJ.html

Like in this page, the letter í in the words  qūbiécí  and  xíngróngcí looks very different.  Does anybody know the reason?

**Comment by dan-zeman** [comment]
They look pretty much the same on my screen:
![pinyin-diacritics](https://user-images.githubusercontent.com/663752/34437058-409a755c-ec9b-11e7-921b-99dfc48a03bb.png)

I have also checked how they are encoded and all three are identical, i.e., "LATIN SMALL LETTER I WITH ACUTE" (unlike the _ó,_ which is not "LATIN SMALL LETTER O WITH ACUTE" but a combination of two characters, "LATIN SMALL LETTER O" and "COMBINING ACUTE ACCENT"). But they should look the same anyways.

**Comment by wongtaksum** [comment]
![default](https://user-images.githubusercontent.com/29035987/34440236-c9e54014-ecee-11e7-8f50-25f8541bf19a.png)
but on my screen they are entirely different....

**Comment by martinpopel** [comment]
The words appear multiple times on the page. @dan-zeman's screeshot captures the first occurrence, while @wongtaksum's screenshot captures the second, where í in qūbiécí is written with a single Unicode character 'LATIN SMALL LETTER I WITH ACUTE' (U+00ED), but in xíngróngcí it is written using a decomposition into 'LATIN SMALL LETTER I' (U+0069) and 'COMBINING ACUTE ACCENT' (U+0301). Modern browsers should render both correctly. @wongtaksum should report it as an issue to his browser's (or font or OS) vendor.

**Comment by dan-zeman** [comment]
I see. This is a different occurrence of the two words. Here, the first word really uses the single character for _í_ while the second word employs the combining diacritics. Apparently your system does not know how to render the glyphs correctly. They still look the same on my screen (Microsoft Windows 10, Chrome browser). But you can see below that the encoding differs. I would suggest that you normalize all accented pinyin letters and always use the dedicated single Unicode character, not the combining diacritics.

<pre>
q         113   0071    L       LATIN SMALL LETTER Q
ū         363   016B    L       LATIN SMALL LETTER U WITH MACRON
b          98   0062    L       LATIN SMALL LETTER B
i         105   0069    L       LATIN SMALL LETTER I
é         233   00E9    L       LATIN SMALL LETTER E WITH ACUTE
c          99   0063    L       LATIN SMALL LETTER C
í         237   00ED    L       LATIN SMALL LETTER I WITH ACUTE
           32   0020    Z       SPACE
o         111   006F    L       LATIN SMALL LETTER O
r         114   0072    L       LATIN SMALL LETTER R
           32   0020    Z       SPACE
形      24418   5F62    L       CJK UNIFIED IDEOGRAPH-5F62
容      23481   5BB9    L       CJK UNIFIED IDEOGRAPH-5BB9
詞      35422   8A5E    L       CJK UNIFIED IDEOGRAPH-8A5E
           32   0020    Z       SPACE
/          47   002F    P       SOLIDUS
           32   0020    Z       SPACE
x         120   0078    L       LATIN SMALL LETTER X
i         105   0069    L       LATIN SMALL LETTER I                                                                                                                    ́
          769   0301    M       COMBINING ACUTE ACCENT
n         110   006E    L       LATIN SMALL LETTER N
g         103   0067    L       LATIN SMALL LETTER G
r         114   0072    L       LATIN SMALL LETTER R
o         111   006F    L       LATIN SMALL LETTER O                                                                                                                    ́
          769   0301    M       COMBINING ACUTE ACCENT
n         110   006E    L       LATIN SMALL LETTER N
g         103   0067    L       LATIN SMALL LETTER G
c          99   0063    L       LATIN SMALL LETTER C
i         105   0069    L       LATIN SMALL LETTER I                                                                                                                    ́
          769   0301    M       COMBINING ACUTE ACCENT
</pre>

**Comment by wongtaksum** [comment]
I have modified.  It looks fine on the preview.  Hope everything is fine after commit.

**Comment by wongtaksum** [comment]
The issue has been solved!  Thank you!
