### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by wongtaksum** [UniversalDependencies/docs#521]
At the top of the docs pages, there is a line, like for Mandarin Chinese:

home zh/zh edit page issue tracker

The link for zh/ah is supposed to be http://universaldependencies.org/zh/zh but now it is a dead link.

This is the same for other languages like English.

**Comment by wongtaksum** [comment]
Another similar issue is that on the CCONJ pages of many languages, if not all, only link to [u] is found at the bottom of page:

CCONJ in other languages: [u]

**Comment by wongtaksum** [comment]
The third issue is all.html is only available to [u] but not other languages
http://universaldependencies.org/u/dep/all.html

**Comment by dan-zeman** [comment]
The zh / zh issue should now be fixed, I have removed the link from the page layout.
