### ISSUE TITLE
Broaden the use of `compound` in UD_English?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#525]
[`compound`](http://universaldependencies.org/u/dep/compound.html) sounds like it should include adjectival compounds, yet *nuclear free*, *ill - fated*, *tip top*, etc. are analyzed as `amod(ADJ, ADJ)` in UD_English.

cf. #478: `obl:npmod` includes some noun-verb compounds and `nmod:npmod` includes some adj-noun compounds. I think it would make sense to include these under `compound` as well.

**Comment by dan-zeman** [comment]
What is the status of this issue? Any pending changes to the English guidelines or data?
