### ISSUE TITLE
Aspect in Tagalog

### ISSUE THREAD

**Issue by kasteph** [UniversalDependencies/docs#527]
In Tagalog, we can have a sentence: `Kailangan ko ang kuwalta`.
```
# sent_id = schachter-otanes-65-9
# text = Kailangan ko ang kuwalta.
# text_en = I need the money.
1   Kailangan   kailangan   VERB    VBP    Mood=Ind|VerbForm=Fin                   0    root    _   _
2   ko          ko          PRON    PRP    Number=Sing|Person=1|Case=Erg           1    nsubj   _   _
3   ang         ang         DET     DT     Definite=Def|PronType=Art|Case=Abs      4    det     _   _
4   kuwalta     kuwalta     NOUN    NN     Number=Sing                             1    obj     _   _
5   .           .           PUNCT   .      _                                       1    punct   _   _
```
I want to annotate the `Aspect` feature of `kailangan` to be `neutral` or `infinitive` as suggested [here](http://www.hawaii.edu/filipino/Grammar_Topics/Grammar_2-1.html) (`kailangan` is a root verb cf. [this table](http://www.seasite.niu.edu/Tagalog/Grammar%20Activities/Grammar%202/Verbal%20Focus/Verbalfocus-fs.htm)). This also agrees with my intuition as a native speaker since it is an action that has not been done or will be done, it just is. Could this be annotated as `Hab` (for habitual aspect) or should there be a new value for the `Aspect` feature?

**Comment by dan-zeman** [comment]
If the aspect-neutral forms are used (among others) to denote habitual actions, then `Aspect=Hab` is probably a good choice. I would advise against introducing a new value `Aspect=Neut`. The more UD-like way of saying that this form does not subscribe to any particular aspect would be simply omitting the `Aspect` feature.

**Comment by kasteph** [comment]
Thanks @dan-zeman. I will annotate these cases with `Aspect=Hab` unless there will be a new value added in the future for Aspect 😃
