### ISSUE TITLE
annotation of "se" and "dont" in French

### ISSUE THREAD

**Issue by ioan2** [UniversalDependencies/docs#530]
Hello,

This issue is close to issue #461, since the annotation of the reflexive pronoun "se" has been discussed, but no decision seems to have been taken.
In fr-ud-train.conllu V2, "se" has been annotated 1487 times as an "obj" relation and 574 times as "expl". I would like to understand the motivation for this. In traditional French grammar there is an distinction between "verbes pronominaux" and "verbe exclusivement pronominaux". The first are verbs which can be used as reflexive, the latter are always with an reflexive pronoun. However checking (some) of the examples I do not think that this is the distinction here (e.g. examples with the verb "se voit":  "se" is attached to "voit" 10 times as "obj" and 4 times as "expl"
- sent_id = fr-ud-train_05555 "Le gouvernement de Bourassa se voit donc obligé ..."
-  sent_id = fr-ud-train_06271 "... elle se voit traitée ..." (obj)

If there is a semantic distinction, it is very subtle, but for dependency analysis I would prefer a distinctive feature or XPOS, but not a different dependency relation

A similar problem is the attachment of "dont": whereas I agree totally when it is attached as "nmod" in sentences like
- sent_id = fr-ud-train_00061: "....cependant un certain nombre d'artefacts caractéristiques du viatique funéraire royal de la XVIIIe dynastie ont pu être retrouvés et dont le tombeau de Toutânkhamon..."

There are case where "dont" is attached (correctly, in my view) to a verb, but using the "iobj" relation
-  sent_id = fr-ud-train_00537: "Professionnalisme et qualité, voilà les mots qui conviennent pour l'accompagnement dont j'ai bénéficié."
There are more examples like this (sentences 543, 824, 852, 964). I think iobj is not the correct relation, since "dont" can be rephrased as "dont j'ai bénéficié" --> "j'ai bénéficié de l'accompagnement" which is no "iobj" but rather "obl" (or something different :-)
Is there a reason why "dont" is "iobj" in these cases?

Best regards
Johannes

**Comment by dseddah** [comment]
Hi,
Can I ask if you noticed the same patterns in the other French treebanks (the se was annotated manually in the Sequoia and the FTB treebanks for example) ?

Djamé

**Comment by ioan2** [comment]
Hi Djamé,
not yet, but I will check as sson as I can

Johannes

**Comment by gossebouma** [comment]
I counted nsubj + verb + _se_ in UD_French, UD_French-Sequoia and UD_French-ParTUT (v2.1). By checking for nsubj I hope I avoided including occurrences of _se_ in passives. French-PUD and French-FTB do not have lemmas so I skipped those. 

Here is an overview of the number of distinct verb lemmas occurring with _se_ as obj, with _se_ as expl, and the number of roots that occur with both se/expl and se/obj.

| treebank | obj | expl | overlap |
|------------|------|------|-----------|
|sequoia| 10|107|2|
|french|251|163|16|
|Partut|28|24|4|

It seems there are interesting differences (ie only sequioa has overall preference for expl), but i leave that to you 

[Here](https://github.com/gossebouma/expletives.git) is some code to produce more detailed statistics if you like.

**Comment by ioan2** [comment]
Hi
I just checked UD_French-Sequoia for "dont" and there are instances of "iobj" as in UD_French:

- sent_id = emea-fr-dev_00024: "...la perfusion dépend de la manière dont le SCA doit être traité: "
- sent_id = Europar.550_00003: "...les producteurs de viande de boeuf et de mouton, dont on attend aujourd'hui qu'ils vendent leurs produits..."

Johannes

**Comment by perrier54** [comment]
Regarding the annotation of _"se"_, there is a very simple criterion for deciding between EXPL, OBJ and IOBJ:

- If it is possible to replace _"se"_ with _"le",_ without changing the meaning of the verb, put OBJ.
- f it is possible to replace _"se"_ with _"lui"_, without changing the meaning of the verb, put IOBJ.
- In other cases, put EXPL.

Some examples: 
_Il se lave (he is washing himself)_ -> OBJ
_Il se lave les mains (he is washing his hands)_ -> IOBJ
_Il se souvient (he remembers)_ -> EXPL
_Ce livre se vend bien (This book is sold well)_ -> EXPL 
_Il se fait huer (he gets booed)_ -> EXPL (_il le fait huer_ has a causative meaning but not _Il se fait huer_)

Even if the criterion is simple, in some bordeline cases, it is difficult to choose. The two examples of @ioan2 are borderline cases:
    _sent_id = fr-ud-train_05555 "Le gouvernement de Bourassa se voit donc obligé ..."
    sent_id = fr-ud-train_06271 "... elle se voit traitée ..."_ (obj)
In my opinion, _"se voir + predicate"_ has not the same meaning as _"voir + obj +predicate"_; Thus, the dependency is EXPL in both examples. 

The problem for _"dont"_ is different. It comes from the unclear status of IOBJ in UD (see [my comments on this issue](https://github.com/bguil/UD-French-discussion/issues/14), unfortunately in French).

**Comment by ioan2** [comment]
I agree with this differentiation for OBJ/EXPL, and I checked the first 10 examples of "se" in fr-ud-train.conllu, and I think 8 of them which are OBJ should be EXPL in this case

**Comment by dan-zeman** [comment]
I am tentatively closing this issue. If actual annotation in UD_French-GSD still contains bugs w.r.t. attachment of _se_, please open an issue in the repository of that treebank.
