### ISSUE TITLE
relative pronouns that head a relative clause

### ISSUE THREAD

**Issue by gossebouma** [UniversalDependencies/docs#531]
When validating my first attempt at enhanced dependencies for Dutch, the following (abbreviated, translated) gives an error:

He became chairman, which he still is

Basic dependencies:

acl:relcl(chairman,which)
nsubj(which,he)
cop(which,is)

The underlying treebank analyzes the relative pronoun as a predicative complement of the copula is, which seems reasonable. Conversion to enhanced, however, requires that we add a ref(chairman,which) relation (OK), **and** that we make _chairman_ a dependent of whatever _which_ was a dependent of in the relative clause. The problem that arises now is that the predicative complement *is* the head of the relative clause, so my script ends up adding a relation acl:relcl(chairman,chairman). 

Note that the problem is not so much that this is a cycle (allowed in enhanced) but that it is a direct reflexive relation (apparently not allowed). I am not sure how to remedy this. Is there a better linguistic analysis (I seem to remember there are cases where the copula is allowed to be the head, but this one seems different)? Or should we relax the validation rules?

**Comment by jnivre** [comment]
It seems to me that what we want to infer in this case is that "he" is an nsubj of "chairman", and possibly that "is" is a cop of "chairman". Hence, when the relative pronoun is the root of the relative clause, we should NOT add a relation from its head to its co-referential element, but relations from the co-referential elements to its dependents, possibly excluding functional relations. The acl:relcl should remain the same as in basic dependencies. Does this make sense?

**Comment by dan-zeman** [comment]
I agree with Joakim.

And I think that this is an excellent example that should be added to the guidelines.

**Comment by gossebouma** [comment]
It does make sense, but I was afraid someone would suggest this, as it complicates things quite a bit. 

For now, I will do the minimal modifications to avoid the self-reference (ie NOT add acl:relcl(chairman,chairman). 

I will think a bit more about  part 2 of the proposal (add relations from the antecendent noun to all other dependents in the relative clause), as that adds quite a bit of complexity (ie check for each word whether its head happens to be a pronoun heading an acl:relcl, find its antecedent and modify the parent index to the index of that antecedent) for just 1 case so far...

**Comment by jnivre** [comment]
It seems to me that the case with the relative pronoun being the root of the relative clause should only occur precisely when it is a nominal predicate. Therefore, we can perhaps simplify the rule to say that, if the relative pronoun is the root of the relative clause then we should add an nsubj relation from the antecedent to the nsubj of the relative pronoun.

**Comment by dan-zeman** [comment]
http://universaldependencies.org/u/overview/enhanced-syntax.html#relative-clauses
