### ISSUE TITLE
Typographical error correction and missing punctuation

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#534]
The treebank we are converting Latvian UD data from contains PDT inspired typographical error correction system, and we are currently working on how to incorporate the most of this information in the UD treebank.

While regarding misspelled words it feels that I understand how it is intended to be in UD, I would like to have some discussion/clarification about punctuation.

The thing is, Latvian has rather strict rules regarding where punctuation and especially commas should be used or not used (every clause-like thing is being separated from the rest of sentence with commas), and thus, original treebank contains both some cases where original text has completely unnecessary comma and some cases where mandatory comma is missing. Original treebank annotates such cases as mistakes and builds the syntax structure for corrected sentence.

In the case of having unnecessary comma we figured out, for UD we would just attach it with `punct` to previous token and add some warning about it being an error in `MISC` column. Is there some preferred flag I should put in the `MISC` about this? Maybe I should use some subrelation for punct, e.g., `punct:unneeded` or something like that?

In case of missing comma I feel heavily tempted to make null node in the enhanced graph for it (again with some additional information in `MISC` column), but this seems to be veeeeeeeery free take on quidelines, so I better ask first :)

Is there some unofficial standards how other UD treebanks indicate typographical errors, if any?

**Comment by jnivre** [comment]
I don’t think we have any general guidelines for how to deal with typographical errors, but it should definitely be kept outside the morphological and syntactic annotation, so MISC sounds right. In particular, null nodes should never be used for punctuation (nor any other items that do not take dependents of their own). That would be clear violation of the guidelines.

**Comment by dan-zeman** [comment]
Related: https://github.com/UniversalDependencies/docs/issues/330

**Comment by lauma** [comment]
For version v2.2 we ended up with flags in Misc column to indicate (a) wrong wordform, (b) missing comma after the wordform or (c) that the comma is unmotivated.

If some guidelines are formed in future, we can tweak our representation.
