### ISSUE TITLE
Appositions and their introducing elements

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#536]
Looking at the discussion and the guidelines, I found no satisfying way to define what an apos is but, more fundamentally, what the deprel of an element introducing an apposition is. 

1) The `appos` deprel seems to be much more restrictive than the PDT `Apos` construction: "a nominal immediately following the first noun that serves to define, modify, name, or describe that noun". But this ignores a big gray area of other appositions:

Italian: 
_dovrà essere compreso in le **frontiere** "storiche e naturali" di la Croazia , **cioè quelle tracciate da Pavelic**_
"it shall be comprised inside the "historical and natural" borders of Croatia, i.e. those drawn by Pavelic"

Here, do we have `appos(frontiere-6,tracciate-18) / appos(borders,drawn)` ? In the treebank we have `nmod(frontiere-6,quelle-17)` and `acl(quelle-17,tracciate-18)`.

Latin:
_**dupliciter** possunt considerari [...] ; **vel secundum habitudinem materiae [...] , vel secundum habitudinem instrumenti [...]**_
"they can be considered twofoldly [...] ; either according to the condition of the matter [...], or according to the condition of the instrument [...]"

Here, everything after the semi-colon is an explanation of _dupliciter_/"twofoldly" , so it should be an `appos`, introduced by `;` : `appos(dupliciter-1,habitudinem-7)`, but _dupliciter_ is an adverb. 

In other discussions about the subject, in the first  case the apposition seems to be treated as an `acl` (as seen in the reported treebank). However, I am arguing here that it is not a modifier, but it stays on the same level of _frontiere_ (borders). Further, this should induce us to interpret the second case as an `nmod` or an `amod`, which it can not be. I feel that the apposition is closer to a `parataxis` than to a `*mod` in spirit.
In any case, browsing through some treebanks I noticed that `appos` is already very commonly treated in a broader sense than those seen in the guidelines, more akin to the PDT `Apos`. Could this be a point for discussion? E.g.:

Greek:
_οι τοπικές αρχές θα πρέπει [...] να **σκέφτονται** εγωιστικά , **δηλαδή να σκέφτονται μόνο το άμεσο συμφέρον τους**_  / _i topikì arhès tha prèpi na skèftonde egoistikà, dhiladhì na skèftonde mòno to àmeso simfèron tus._
"local authorities will have to think egoistically, that-is to think only about their-own immediate interest."
`appos(σκέφτονται-7,σκέφτονται-12)` and  `dep(σκέφτονται-12,δηλαδή-10)`, but I am not sure of `nsubj(δηλαδή-10,αρχές-3)`.

2) The status of the particle connecting an element to its apposition (as in the first example) is very unclear. In the treebanks, I have found wildly different interpretations for the same word meaning "that is": Latin _scilicet_, Italian _cioè_, Greek _δηλαδή_/_dhiladhì_, Czech _tj_ = _to je_. 
_cioè_ is often treated as `advmod` because it is basically an adverb, but its function is different here, since it does not modify the element, but just introduces ; other times it is labelled `cc` and the head of the apposition `conj` of its parent; _tj._ is sometimes also a `cc`; the Greek treebank prevalently resolves to use `dep`, maybe the most correct choice given the guidelines. I think it can not be a `mark`.
In our Latin IT-treebank we are leaning towards the compromise of using `dep:cc`, with the ratio that the apposition more closely resembles a co/ordination, in that both elements are on the same level.

In the end I am proposing to discuss a broader re-definition of the deprel `appos`, and a choice or probably a new deprel for particles introducing an apposition.

**Comment by jnivre** [comment]
The UD notion of apposition is quite restrictive and (at least according to the current guidelines), should only be used for a non-restrictive co-referential noun phrase. In this sense, it can be thought of as a subtype of nmod, conceptually but not formally. For other types of non-restrictive modifiers and parentheticals, other relations should be used. If the head word is a predicate, "acl" is often appropriate, but if the relation is very loose "parataxis" may be more suitable.

**Comment by Stormur** [comment]
I understand that `appos` is a very narrow subclass of `nmod`. I'm OK using other types of deprels for other non-restrictive modifiers, even if it is not fully coherent with the source data we are converting into UD, but still I'm uncertain with regard to the introducing element, for example `scilicet` in Latin. We resolved for now to label it as `advmod:cc`, since it clearly can not be a `mark`, as it does not introduce a subordinate clause; it is hardly a typical `advmod`, because it does not necessarily depends on a predicate or modifier word, and it does not modify it; and it is not a typical `cc`, since the construction is not treated as a conjunction. Further, we want to avoid confusion with a possible `advmod:appos`, coming from an apposition in the original source treated as an `advmod` in UD.

But we are not particularly satisfied with this solution, and we would like to advocate for a new specific deprel.

**Comment by amir-zeldes** [comment]
We had adnominal cases of "i.e." in UD_English-GUM and went with appos from noun to noun, and attached "i.e." to the second noun as advmod. I'm not sure if this is a good solution for clausal cases, but for NPs it looked pretty much like normal apposition (coreference, and if we interpret i.e. as modifying the second noun, then adjacency as well).

**Comment by jnivre** [comment]
I think advmod sounds reasonable for the introducing element. Keep in mind that UD is a coarse-grained system that cannot capture all the fine distinctions that you can have in a language-specific system.

**Comment by Stormur** [comment]
I would like to come back to this issue after I think I have gained a better insight into the problem.

I think that the best fit for an apposition-introducing element like _scilicet_, _cioè_ or _δηλαδή_ as described in the previous discussion is the part of speech `CCONJ` and, consequently, the deprel `cc` in relation to the introduced element.

While choosing to use the special deprel `advmod:cc` in our Latin treebank and retaining the `ADV` part of speech, we were already acknowledging this fact, while at the same time probably relying to much on the description of traditional grammars.

Now, this consideration might have consequences for the annotation in UD. First of all, let's observe that constructions like in the Italian sentence:

_dovrà essere compreso in le **frontiere** "storiche e naturali" di la Croazia ,_ cioè _**quelle** tracciate da Pavelic_
"it shall be comprised inside the "historical and natural" **borders** of Croatia, i.e. **those** drawn by Pavelic"

are of a co-ordinative nature. The apposition does not really modifies its head, it just explains it, so both elements are on the same semantic and syntactic level. Still, it is true that we have a different kind of co-ordination than in

_I'm eating **apples** and **pears**._

So, with regard to appositions and co-ordinations, I would like to advance the following proposal(s):

- introduction of a feature `ConjType` for conjunctions, in the same vein as `PronType` and `NumType`. Some possible values with Latin examples: copulative (and it might be combined with negative polarity: _nec_ "and not" ): _et_ "and"; correlative: _cum ... tum_ "as ... as"; disjunctive: _aut_ "or (opposition)"; adversative: _sed_ "but"; declarative: _nam_ "for"; **explicative: _scilicet_** "that is"; conclusive: _igitur_ "therefore".  

This would have the advantage to be at the same time facultative and to better solve the problem of these complex appositions, and to open interesting interlinguistic comparisons.

There could be the possibility to either allow an element with deprel `cc` depending on another element labeled with `appos` instead of `conj`, or to simply reduce all these structures to normal `conj-cc` coordinations with `ConjType=Expl`. In the example above:

... , `amod(frontiere,storiche)`, `conj(storiche,naturali)`, `cc(naturali, e)`, `nmod(frontiere,Croazia)`, ..., `conj(frontiere,quelle)`, `cc(quelle,cioè)`, `acl(quelle,tracciate)` ...
_e_: `CCONJ`, `ConjType=Cop`  ; _cioè_: `CCONJ`, `ConjType=Expl`.

It might be thinkable to duplicate this subtype on the deprel if there is no (explicit) connecting element. The Latin example:

_**dupliciter** possunt considerari [...] ;_ vel _**secundum habitudinem** materiae [...] ,_ vel _**secundum habitudinem** instrumenti [...]_
"they can be considered **twofoldly** [...] ; either **according to the condition** of the matter [...], or **according to the condition** of the instrument [...]"

... `advmod(considerari,dupliciter)`, ... , `conj:expl(dupliciter,habitudinem)`, `cc(habitudinem,vel)`, ... , `conj(habitudinem,habitudinem)`, `cc(habitudinem,vel)`, ...
Both _vel_: `CCONJ`, `ConjType=Disj`.

In both examples we observe that the involved elements all indeed have the same syntactic role.

At the same time, it could be thinkable to remove the present deprel `appos`, which has some controversial interpretations, if it is to be intended just as a "non-restrictive co-referential noun phrase [...] as a subtype of nmod" (as @jnivre said) and to replace it simply with `nmod`, removing its directional constraint ("a nominal modifier _following_  a noun") and possibly at the same time introducing a subtype for restrictiveness, of which currently, as far as I know, there is none. The actual `appos` might then correspond to `nmod:nonres`.

Maybe these changes could improve the actual chaotic situation where `conj`, `acl`, `nmod`, `appos`, `parataxis` are used quite arbitrarily, in combination with many different subtypes (see e.g. `parataxis:appos` in Italian, `appos:conj` in French, `conj:appos` in Naija or `nmod:appos` in Latin).
