### ISSUE TITLE
Gender for nouns in UD_Arabic

### ISSUE THREAD

**Issue by ioan2** [UniversalDependencies/docs#538]
Hello,
I have just realised that nouns do not have a Gender value in ar-ud-train.conllu nor ar-ud-dev.conllu, neither has the taglist conversion table (http://universaldependencies.org/tagset-conversion/ar-padt-uposf.html). However, adjectives, numerals, pronouns and verbs to have Gender information.
Is this a bug or something missing in the underlying original (PADT?) treebank.
I could provide a script which deduces gender of nouns from dependent adjectives, numerals (to a certain degree) and/or noun suffixes (final ta marbuta (ة,  ـة ) for singulars or ـات  for plurals)

Regards
Johannes

**Comment by dan-zeman** [comment]
It is missing in the original PADT (ElixirFM) tagset. Apparently the tags cover inflectional gender but not lexical gender. I am not sure that guessing gender is a good idea because otherwise the source tags have been manually checked.
