### ISSUE TITLE
filling the MISC field in ranges for Sanskrit compounds

### ISSUE THREAD

**Issue by EricaBiagetti** [UniversalDependencies/docs#539]
In the Sanskrit Treebank every form has a feature <code>Gloss</code> in the MISC field, in which a translation of the form (and *not of the lemma*) is provided.
The problem arises for compounds words, which happen to be very common in Classical Sanskrit: in Sanskrit compounds the first element lacks morphological inflection and surfaces as the stem, this will be recognized with a feature<code>Compound=Yes</code> in the UPOSTAG field.

~~~ sdparse
6-7	प्रबोधनार्थम	_	_	_	_	_	_	_	_
6	प्रबोधन	प्रबोधन	NOUN	_	Compound=Yes	7	nmod	_	Translit=prabodhana|LTranslit=prabodhana|Gloss=awakening
7	अर्थम्	अर्थ	NOUN	_	Case=Acc|Gender=Masc|Number=Sing	3	nmod	_	Translit=artham|LTranslit=artha|Gloss=goal
~~~

Since the function of प्रबोधन / *prabodhana* "awakening" as the head-modifier is not suggested by inflection and since the meaning of the compound as a whole should be recovered in some way, I'm wondering whether it would be possible to fill the MISC filed in the range 6-7, as follows:
~~~ sdparse
6-7	प्रबोधनार्थम	_	_	_	_	_	_	_	Gloss=goal-of-awakening
6	प्रबोधन	प्रबोधन	NOUN	_	Compound=Yes	7	nmod	_	Translit=prabodhana|LTranslit=prabodhana|Gloss=awakening
7	अर्थम्	अर्थ	NOUN	_	Case=Acc|Gender=Masc|Number=Sing	3	nmod	_	Translit=artham|LTranslit=artha|Gloss=goal
~~~

Alternatively, it could be possible to add a feature <code>Comp_Gloss=goal-of-awakening</code> to the head of the compound:
~~~ sdparse
6-7	प्रबोधनार्थम	_	_	_	_	_	_	_	_
6	प्रबोधन	प्रबोधन	NOUN	_	Compound=Yes	7	nmod	_	Translit=prabodhana|LTranslit=prabodhana|Gloss=awakening
7	अर्थम्	अर्थ	NOUN	_	Case=Acc|Gender=Masc|Number=Sing	3	nmod	_	Translit=artham|LTranslit=artha|Gloss=goal|Comp_Gloss=goal-of-awakening
~~~
I specify here that, although it goes against UD guidelines, we are thinking about splitting almost every compound in Sanskrit. In case this way of proceeding will be accepted, we'll provide detailed documentation for such a decision; motivations for this will be based on Indian grammatical tradition and will try to give an account for the syntactical complexity of compounds in Classical Sanskrit.

**Comment by dan-zeman** [comment]
The Gloss attribute can be put on the line of the multi-word token. This line must have underscores in most columns but the MISC column is an exception (http://universaldependencies.org/format.html#words-tokens-and-empty-nodes).
