### ISSUE TITLE
punct having dependents

### ISSUE THREAD

**Issue by tzshi** [UniversalDependencies/docs#540]
From http://universaldependencies.org/u/dep/punct.html , it says `punct` "can never have dependents". 
However, there are many cases in the current version that they do have dependents. 

I checked English, French, German, and Czech. All of these treebanks found such instances. 
I used Grew to identify: http://match.grew.fr/?custom=5acf06b85566b&corpus=UD_English

Most cases should be due to annotation error, but some cases might worth discussion, such as in French (first sentence that showed up using Grew):
`Il critique le plan marocain en soulignant qu'une autonomie devrait donner davantage aux Sahraouis que le droit de « collecter leurs propres ordures ménagères (...).`
`(...)` contains three PUNCT, and all of them are attached to `critique`. Arguably, the way of attaching `(` and `)` to `...` might be preferred against attaching all three tokens to `critique`.

The current validation tool doesn't include this on http://universaldependencies.org/svalidation.html , so it might be worth adding this as an automatic check.

**Comment by dan-zeman** [comment]
I think that cases like _(...)_ should be an exception, although the current guidelines do not mention it. In case of paired punctuation (brackets, quoatation marks) within one sentence, where the only contents is punctuation, the rule might be that the paired symbols are still attached as dependents of the symbol inside. But it is also possible that the punctuation inside is tokenized into multiple tokens. Then it is not clear to me whether we should also allow that one symbol inside the brackets is attached to another symbol. (So far I have seen only simple cases such as _(!)_.)

I think punctuation errors are a good candidate for addition to the validation tests.

**Comment by martinpopel** [comment]
Udapi has a svalidation tool which highlights these cases and several more punctuation-related bugs (e.g. non-projectivities), see [ud.MarkBugs](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py#L134).
It has even a tool which fixes punctuation bugs -- [ud.FixPunct](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py).
I agree there are exceptions where you have to break some of the UD rules, e.g. if `(...)` is the whole sentence, insisting on "punctuation has no dependents" would break the single root property.
Even if it is not the whole sentence, ud.FixPunct prefers to keep the paired punctuation attached to the same parent even if the parent is a punctuation itself, see [this rule](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixpunct.py#L196-L199).

**Comment by olesar** [comment]
Other examples:* * *- - - - -that can be used as separators between text sections.

**Comment by dseddah** [comment]
Hi,
what's the policy in term of punctuation used as interjection eg.  
he said "the sky was yellow" (!!!) 


best,
Djamé

**Comment by dan-zeman** [comment]
@dseddah : No official policy so far, as far as I know. Otherwise this is what this issue is mainly about :-)
