### ISSUE TITLE
Veni, vidi, vici - parataxis or conj?

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#541]
As the title suggests, I found a contradiction in the documentation regarding the treatment of the Latin sentence

`Veni, vidi, vici`
`I came, I saw, I won`

In the [documentation](http://universaldependencies.org/u/dep/conj.html), it is listed as an example of asyndetic co-ordination, so deprels are `conj` there; in slide 26 of the [UD tutorial](http://universaldependencies.org/eacl17tutorial/consist.pdf) it is used as example of side-by-side sentences, so of `parataxis`. 

What is the correct interpretation? Reading the documentation, I would actually be inclined towards parataxis, but the border between the two cases, when predicates are co-ordinated, looks really blurred to me. Is it thinkable to restrict asyndetic co-ordination to non-verbs only?

**Comment by amir-zeldes** [comment]
+1 for parataxis here, but I think you can also have conj for verbs with zero VP coordination, i.e. if they share a subject:

```
She went to work, made some coffee.
```

Here conj would let you recover the subject deterministically, but parataxis wouldn't. In the Latin pro-drop cases this doesn't really make a difference, but if there's a shared subject I would go with conj (that's what we did in UD_English-GUM anyway).

**Comment by nschneid** [comment]
To me the clearest case of `conj` without a coordinating conjunction is seen in headlinese:

    Budget's oil provisions divide Congress, White House

The comma is just a terse substitute for "and". A full sentence paraphrase might be *The budget's oil provisions divide Congress and the White House.*

**Comment by dan-zeman** [comment]
I would not restrict asyndetic coordination to non-verbs (and I would not restrict parataxis to verbs).

This boundary indeed is blurred and I suspect that different UD'ers have different opinions here but unlike some of the more prominent issues, we haven't tried to sort it out and come up with more detailed guidelines.

I am personally not fond of `parataxis` competing with `conj`. I would always prefer `conj` if the construction remotely resembles the more prototypical examples of coordination; therefore, _veni, vidi, vici_ is coordination for me.

**Comment by nschneid** [comment]
> I would always prefer conj if the construction remotely resembles the more prototypical examples of coordination; therefore, veni, vidi, vici is coordination for me.

I think I have the opposite instinct: for me, the so-called "comma splice" is prototypical [parataxis](http://universaldependencies.org/u/dep/parataxis.html):

    I lost my wallet, hopefully somebody will find it.

This can be paraphrased either as separate sentences or with a coordinating conjunction.

@dan-zeman, would you think `conj` could apply there? If so, maybe we should consider renaming `parataxis` to `parenthetical`.

**Comment by amir-zeldes** [comment]
I agree with @nschneid and I think the example with Congress + White House is also `conj` because it is also a case of structure sharing (they're part of the same argument structure). In the wallet example, both clauses are fully independent.

**Comment by dan-zeman** [comment]
@nschneid : Yes I would think `conj` could apply there and I believe we would find such examples of `conj` in UD Czech because it was converted from data where such things are annotated as coordination. (And because the source corpus distinguishes parentheticals, but not parataxis in the broader UD sense.)

But I'm also pretty sure that other people who participated in shaping the guidelines would disagree with me. Definitely do not take my opinion as the "official" position on this.

Renaming `parataxis` to `parenthetical`, with the appropriate narrowing down of the definition, would have to wait for UD v3 guidelines, but I think I'd support it.

**Comment by sylvainkahane** [comment]
We have to face this problem everytime when we work with spoken copora. You have no punctuation and you have to decide when a sentence ends or not. We use the following criteria for coordination:

> A coordination occurs only in a governed position. No governor, no coordination.

I think it is a good criteria, easy to apply.

Example: _Veni, vidi, vici_. No governor, I can't use conj. So I use `parataxis`. If it was a spoken data, I would have considered that I have three sentence and three roots.

Note also that `parataxis` has many uses and in our treebank of spoken French, we use several subtypes of `parataxis`, but it is another topic. In this case we use `parataxis:conj`.

**Comment by dseddah** [comment]
> Le 12 avr. 2018 à 18:00, sylvainkahane <notifications@github.com> a écrit :
> 
> We have to face this problem everytime when we work with spoken copora. You have no punctuation and you have to decide when a sentence ends or not. We use the following criteria for coordination:
> 
> A coordination occurs only in a governed position. No governor, no coordination.
> 
> I think it is a good criteria, easy to apply.
> 
> Example: Veni, vidi, vici. No governor, I can't use conj. So I use parataxis. If it was a spoken data, I would have considered that I have three sentence and three roots.
> 
> Note also that parataxis has many uses and in our treebank of spoken French, we use several subtypes of parataxis, but it is another topic. In this case we use parataxis:conj.

talking about parataxis, would you make the same analysis for 

No. Way!

?

or

IM. POS. SI. BLE !

without the period I would have gone with goes_with for the second case  but here it could  be parataxis:goes_with (if it doesn’t exist yet, I’m voting for it)



Djamé

**Comment by nschneid** [comment]
> No. Way!

> IM. POS. SI. BLE !

I would treat the punctuation here as only adding stylistic/pronunciation emphasis, not changing the morphological or syntactic structure. These don't seem like parataxis to me.
