### ISSUE TITLE
two or more words not split by space

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#544]
UD has relations such as *goeswith* to label words written separately in text that is not well edited.
However, there might be the opposite case in not-well-edited/crawled texts and especially web texts (media, blogs..) when two or more words are written together:
If therearesuch beings, then, theremight be a miracle...

Are there any guidelines on their tokenization (at least in those languages where the space splits 'words')?

If we treat them as several tokens, what kind of relation can be used? What kind of label in the 10th column can be used?

If we treat them as one token, how to label its POS, lemma and features?

**Comment by martinpopel** [comment]
@dan-zeman in [Typos.pdf](https://github.com/UniversalDependencies/docs/files/428471/Typos.pdf) suggests, we should just use `SpaceAfter=No` in the "*thecar*" example.

However, I would say tokens boundaries can be only on whitespace or punctuation, so *therearesuch* must be one token.
Obviously, we would like to annotate it properly, so we should split it to multiple words via a multi-word token.

We should also mark that this case is a typo or a not-well-edited text, not a typical grammatical contraction.
We could use `Typo=Yes`, but [Typo](http://universaldependencies.org/u/feat/Typo.html) is a feature and multi-word tokens must have the FEATS column empty (cf. #435).
I think it makes no sense to mark the typo with any of the words ("there", "are", "such" -- all three are correct).
So we should probably use the MISC column (which is allowed non-empty even with multi-word tokens).
See also #330.

**Comment by dseddah** [comment]
> Le 14 avr. 2018 à 22:57, Olga Lyashevskaya <notifications@github.com> a écrit :
> 
> UD has relations such as goeswith to label words written separately in text that is not well edited.
> However, there might be the opposite case in not-well-edited/crawled texts and especially web texts (media, blogs..) when two or more words are written together:
> If therearesuch beings, then, theremight be a miracle...
> 
> Are there any guidelines on their tokenization (at least in those languages where the space splits 'words')?
> 
> If we treat them as several tokens, what kind of relation can be used? What kind of label in the 10th column can be used?
> 
> If we treat them as one token, how to label its POS, lemma and features?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Hi,
what we’re doing in our own UGC TB is to treat them like regular contraction and spaceafter=no   but it’s only a workaround bc the spaceafter here is not mandatory at all (it’s just to make sure we could train a proper tokenizer at some pont)

1-2 thereis
1 there ….	spaceafter=no
2 is

what’s more difficult is case like  "the reis » or french c t (for c’était, it was). Here you would need a 2 indices mapping (for n-m mapping). as far as I know, it’s not possible in UD.



Djamé

**Comment by olesar** [comment]
Djamé @dseddah, thank you for bringing the "the reis" (instead of the "there is") case, it is very common in my data. Typo.pdf does not include such cases.

**Comment by dseddah** [comment]
if you think about it, we can even imagine cases where disambiguation such sequence would be impossible, so only lattices input would be viable.

**Comment by dan-zeman** [comment]
In the meantime, the abovementioned PDF document has been converted to MarkDown and added as a [recommendation in the guidelines](https://universaldependencies.org/u/overview/typos.html), so I am closing this issue.
