### ISSUE TITLE
UGC, verbs out of NPP and UD "Home Alone'd"

### ISSUE THREAD

**Issue by dseddah** [UniversalDependencies/docs#545]
Talking about UGC, I just saw this on twitter

"When he was 8, he Home Alone'd a Nazi" 

https://twitter.com/CharmingGrump/status/984899840189476864

How should we annotate "Home Alone'd"  ?

1-3 Home Alone'd
1 Home    ?         3   goeswith     
2 Alone    ?         1    flat 
3 'd                     V    ....    
 

Djamé

**Comment by nschneid** [comment]
Ha, nice example of zero-derivation of a verb!

I don't think the past tense marker should be a separate syntactic word here—just treating "Home" as goeswith and "Alone'd" as a verb seems fine.

**Comment by dseddah** [comment]
Yeah, we could but we're loosing the game play with the movie title by treating it as if the poster would have written "googled". He intentionally separated Home Alone and the past marker.
Let say someone writes
"I love those Home Alone-based  stories!"  it should be expected that we can retrieve all references of Home Alone according to some patterns.   For example in that example, the -based would be analyzed as a punct and some adjectives (or maybe past participles) attached to a compound or a flat phrase. Why not trying to keep the same analysis pattern?

**Comment by nschneid** [comment]
It feels odd to separate a bound morpheme. My understanding of the POS categories is that they all are intended for words with free morphemes or clitics. "'d" is not really a verb; rather, "Home Alone'd" is a verb derived from a proper name (and "Home Alone" could similarly be used as a present-tense verb, without any overt verbal morphology).

UD is a lexicalist framework—it doesn't normally decompose subword morphology, and I don't see why special punctuation should change that.

**Comment by bulbulistan** [comment]
>
> Yeah, we could but we're loosing the game play with the movie title by
> treating as if the poster would have written "googled". He intentionally
> separated Home Alone and the past marker.
>
Well, I don't know about intentionally: if you were to ask the user why, do
you think they could offer a halfway coherent explanation? More likely they
saw a similar usage somewhere else and think this is how it should be done.
And let's not get bogged down by orthography (which is also why we have
goeswith): whether written separately, together or with a hyphen, what we
have here is a verb [hoʊməloʊn] with a past suffix. This isn't any
different from verbs like double-book.

**Comment by dseddah** [comment]
> Le 15 avr. 2018 à 21:34, bulbulistan <notifications@github.com> a écrit :
> 
> >
> > Yeah, we could but we're loosing the game play with the movie title by
> > treating as if the poster would have written "googled". He intentionally
> > separated Home Alone and the past marker.
> >
> Well, I don't know about intentionally: if you were to ask the user why, do
> you think they could offer a halfway coherent explanation?
> More likely they
> saw a similar usage somewhere else and think this is how it should be done.

Actually, i did ask him. I let you know if he answers something.
> And let's not get bogged down by orthography (which is also why we have
> goeswith):

Let’s not get started with the orthography, I’m in the « let’s handle this at the token level » camp.
« goeswith » is a workaround to avoid the need of a proper tokenization layer.

> whether written separately, together or with a hyphen, what we
> have here is a verb [hoʊməloʊn] with a past suffix. This isn't any
> different from verbs like double-book.

what bothers me is not the morphological analysis itself, it’s the fact that looking for that kind of pattern
is almost difficult in our treebanks. I know it’s not the point of the UD initiative, of course, and frankly, we have
enough in our plates for not adding a « named entity»-morphology interface in our framework.

Djamé

**Comment by bulbulistan** [comment]
>
> Let’s not get started with the orthography, I’m in the « let’s handle this
> at the token level » camp.

You can't have it both ways: if you want to deal with the token level, you
have to deal with the orthography, because that is the major reason we have
"home alone'd" but "double-booked". And that's still a relatively new
thing, until recently you'd even get "work'd" and "explain'd" (I wonder how
diachronic treebanks of English handle this).
Here, however, UD rules apply: we are dealing with syntactic words and so
there is a world of difference between "you'd" and "Home Alone'd" - in the
former, "'d" is a syntactic word, in the latter, "'d" is quite clearly a
suffix.


> > whether written separately, together or with a hyphen, what we
> > have here is a verb [hoʊməloʊn] with a past suffix. This isn't any
> > different from verbs like double-book.
>
> what bothers me is not the morphological analysis itself, it’s the fact
> that looking for that kind of pattern
> is almost difficult in our treebanks.
>
If you're talking about the pattern where an affix is attached to a
multi-word expression/multi-token word, I agree, that is a problem, though
perhaps not an urgent one.

**Comment by dseddah** [comment]
> Le 15 avr. 2018 à 22:24, bulbulistan <notifications@github.com> a écrit :
> 
> >
> > Let’s not get started with the orthography, I’m in the « let’s handle this
> > at the token level » camp.
> 
> You can't have it both ways: if you want to deal with the token level, you
> have to deal with the orthography, because that is the major reason we have
> "home alone'd" but "double-booked ».

I’m not sure I’m following why do you think I want anything « both ways » ?

> And that's still a relatively new
> thing, until recently you'd even get "work'd" and "explain'd" (I wonder how
> diachronic treebanks of English handle this).
> Here, however, UD rules apply: we are dealing with syntactic words and so
> there is a world of difference between "you'd" and "Home Alone'd" - in the
> former, "'d" is a syntactic word, in the latter, "'d" is quite clearly a
> suffix.

just to make myself clear, I wasn’t discussing the fact that ‘d is a suffix,
I was asking how best to analyse this new verb so that we can keep
track of its compositional nature.

This is important for everyone working on non-canonical texts and I think
 that being more flexible in that aspect could be actually helpful.

**Comment by dseddah** [comment]
so quick follow-up, the poster answered this to my questions  
(sorry to disturb you but we're discussing your use of "Home Alone" in "home alone'd" in a linguist mailing list (https://github.com/UniversalDependencies/docs/issues/545 … ) may I ask why you added the quote ? was it to separate clearly the movie from the past tense marker?
or is it just a common pattern  like "googled" or smthg? )
----------->
 I wanted to ensure it was separate, but in my circles it's somewhat of a common pattern. I believe it started on Deadspin, as a way of signifying say, a sports team choked in a manner of another, such as Oilers'd. Or a announcer speaking in a particular manner.
https://twitter.com/CharmingGrump/status/985629292263436288)

**Comment by bulbulistan** [comment]
>
> I’m not sure I’m following why do you think I want anything « both ways » ?
>
You said "Let's not get started with the orthography" and at the same time
described yourself as positioned in the "« let’s handle this
at the token level » camp." Tokenization, however, strongly depends on
orthography, as I illustrated with my examples.


> just to make myself clear, I wasn’t discussing the fact that ‘d is a
> suffix,
> I was asking how best to analyse this new verb so that we can keep
> track of its compositional nature.
>
And I believe the consensus so far is that separating out the 'd as V is
probably not the best way to go. Also, and that's only my opinion, the 'd
should not be a separate token.
Is there anything that goeswith plus the V PoS-tag cannot handle?

This is important for everyone working on non-canonical texts and I think
> that being more flexible in that aspect could be actually helpful.
>
Absolutely.

**Comment by bulbulistan** [comment]
Thank you. So there is no actual linguistic analysis behind it, is there?
It looks to me like a mere convention of genre/social group (or perhaps
scribal practice)...

**Comment by dan-zeman** [comment]
@nschneid :
> I don't think the past tense marker should be a separate syntactic word here—just treating "Home" as goeswith and "Alone'd" as a verb seems fine.

Since `goeswith` implies ill-edited text, and since the space between _Home_ and _Alone'd_ is not an error, I would favor `compound` over `goeswith`.

**Comment by nschneid** [comment]
> Since `goeswith` implies ill-edited text, and since the space between *Home* and *Alone'd* is not an error, I would favor `compound` over `goeswith`.

I'm not sure what the "correct" spelling would be of such a liberal verbalization of a multiword name. (Can't think of analogous examples that are more conventional.) Orthographically it might be preferable to hyphenate and omit the apostrophe: *Home-Aloned*. The advantage of `goeswith` is it gives us a way to say that it is morphologically a single word and only one POS tag is really applicable (here, `VERB`).

If we went with `compound`, which word would be the head, and what would be the POS tags?

Given that neither *Home* nor *Alone* is independently a verb here, I guess another option would be to analyze it internally as a flat named entity (`flat(Home, Alone)`, with both words tagged as `PROPN`), but give the head word verbal morphological features and treat it like a verb with respect to the rest of the sentence. Seems like a recipe for confusion though.

See also #525 regarding `compound`.

**Comment by dan-zeman** [comment]
I don't think it can be `PROPN` if it has acquired verbal morphology. If we went with `compound`, then I would make _Alone'd_ the head, and I would tag it `VERB`. Superficially similar to _ill-suited_, although there are significant differences, the main being that _Alone_ alone would not become a verb.

**Comment by nschneid** [comment]
This issue is similar to #443
