### ISSUE TITLE
Sanskrit relative-correlative nonverbal clauses with no copula

### ISSUE THREAD

**Issue by EricaBiagetti** [UniversalDependencies/docs#547]
In reviewing Sanskrit sentences one problem is how to handle clauses which lack a fine verb form and which are indeed very usual in Sanskrit.
UD guidelines show how to annotate nonverbal clauses with no linking word and clauses with no copula. What is less clear to me, is how to proceed in cases such as the following, with a relative-correlative clause lacking the verb _asti_ "to be".

- यस्यार्थाः स पुमान् लोके / _yasyārthāḥ sa pumān loke _
 "He who has wealth is a man of the world"

```
1-2	यस्यार्थाः	_	_	_	_	_	_	_	Translit=yasyārthāḥ|Gloss=whose-wealth
1	यस्या	यद्	PRON	_	Case=Gen|Gender=Masc|Number=Sing|Poss=Yes|PronType=Rel	3	acl	_	Translit=yasyā|LTranslit=yad|Gloss=of-which
2	अर्थाः	अर्थ	NOUN	_	Case=Nom|Gender=Masc|Number=Plur	1	nsubj:cop	_	Translit=arthāḥ|LTranslit=artha|Gloss=wealth
3	स	तद्	PRON	_	Case=Nom|Gender=Masc|Number=Sing|PronType=Dem	4	nsubj:cop	_	Translit=sa|LTranslit=tad|Gloss=he
4	पुमान्	पुंस्	NOUN	_	Case=Nom|Gender=Masc|Number=Sing	0	root	_	Translit=pumān|LTranslit=puṁs|Gloss=man
5	लोके	लोक्	NOUN	_	Case=Loc|Gender=Masc|Number=Sing	4	nmod	_	Translit=loke|LTranslit=lok|Gloss=world
```
In the original analysis (to be found in the branch compounds_review [https://github.com/UniversalDependencies/UD_Sanskrit-UFAL/tree/EricaBiagetti-compounds_review](url)) the relative pronoun _yasya_ is given the deprel as `acl`, while its subject _arthāḥ_ is linked to it by means of the deprel `nsubj:cop`.

My question is whether in such cases wouldn't be better to have the `nsubj` as `acl:relcl` and to leave the relative pronoun with the deprel that it has in the context (here `nmod:poss`, being in the gen). In this way relative pronouns would be treated as in "standard" relative clauses, where the deprel `acl:relcl` is taken by the verb.

The new analysis would figure as following:
```
1-2	यस्यार्थाः	_	_	_	_	_	_	_	Translit=yasyārthāḥ|Gloss=whose-wealth
1	यस्या	यद्	PRON	_	Case=Gen|Gender=Masc|Number=Sing|Poss=Yes|PronType=Rel	2	nmod:poss	_	Translit=yasyā|LTranslit=yad|Gloss=of-which
2	अर्थाः	अर्थ	NOUN	_	Case=Nom|Gender=Masc|Number=Plur	4	acl:relcl	_	Translit=arthāḥ|LTranslit=artha|Gloss=wealth
3	स	तद्	PRON	_	Case=Nom|Gender=Masc|Number=Sing|PronType=Dem	4	nsubj:cop	_	Translit=sa|LTranslit=tad|Gloss=he
4	पुमान्	पुंस्	NOUN	_	Case=Nom|Gender=Masc|Number=Sing	0	root	_	Translit=pumān|LTranslit=puṁs|Gloss=man
5	लोके	लोक्	NOUN	_	Case=Loc|Gender=Masc|Number=Sing	4	nmod	_	Translit=loke|LTranslit=lok|Gloss=world
```

I would be glad if anyone could give his opinion about it.

**Comment by dan-zeman** [comment]
The problem I see in your analysis is that _artha_ should not be be the head of the clause _yasyā artha_ “whose wealth”. It is a clause with non-verbal predicate, type 4 Possession in [this section of the guidelines](http://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses). The possessed noun, _artha_ “wealth” is the subject of the clause, and the wh-word _yasyā_ “whose” is the predicate. That is why I think the original analysis is correct.

**Comment by EricaBiagetti** [comment]
Yes, I was looking at the clause from the 'relative clause' point of view and didn't think about the possessive being the head of it. Thank you!
