### ISSUE TITLE
Conll shared 2008-2009 format to conll-U conversion

### ISSUE THREAD

**Issue by vishu0047** [UniversalDependencies/docs#548]
Hi..

I am working on parser training where I have to convert  conll data into conll-U format.
I didn't fine any script or steps on UD tool directory if any one have solution for this .please help me.
current structure of my training data:

bc/cctv/00/cctv_0001   0   0      What   WP  (TOP(SBARQ(WHNP(WHNP*        -   -   -   Speaker#1   *   -
bc/cctv/00/cctv_0001   0   1      kind   NN                      *)       -   -   -   Speaker#1   *   -
bc/cctv/00/cctv_0001   0   2        of   IN                   (PP*        -   -   -   Speaker#1   *   -
bc/cctv/00/cctv_0001   0   3    memory   NN                 (NP*)))   memory  -   1   Speaker#1   *   -
bc/cctv/00/cctv_0001   0   4         ?    .                     *))       -   -   -   Speaker#1   *   -

**Comment by dan-zeman** [comment]
This does not look like the CoNLL 2009 format. (I do not know how CoNLL 2008 looked but I suspect it should be same as 2009.)

You are right, there is no script for this conversion in the tools repository. One problem of such a script would be that it would need to know a lot about the source language and treebank (its tag set, dependency relation labels, guidelines for structural annotation). You cannot have a single conversion script that covers all languages.

If you can take care of the conversion between annotation guidelines yourself, the bare conversion of the storage format should not be too difficult. The CoNLL 2009 format is similar to CoNLL-U in that it has one line per token, empty lines after sentences, and various atributes in TAB-separated columns. The main difference is that there is a variable number of columns, while you need always exactly 10 columns in CoNLL-U. Also, some of the columns have different semantic and you may need to move stuff around. But the first column in both formats is the numeric ID of the token/node, and this is apparently not your case.
