### ISSUE TITLE
tool or mapping to convert Ontonote5.0 data to core nlp .conll-U format

### ISSUE THREAD

**Issue by vishu0047** [UniversalDependencies/docs#549]
I am trying to train new parser model using Ontonotes 5.0 data set. I checked UD tool section but there was no tool committed to do the conversion. I to do the conversion using DDR (deep dependency) format but the dependency label for DDR are not same as UD dependency.
1       With    with    IN      _       4       case    _       _
2       their   their   PRP$    _       4       poss    _       _
3       unique  unique  JJ      _       4       attr    _       _
4       charm   charm   NN      _       14      ppmod   _       _
5       ,       ,       ,       _       14      p       _       _
6       these   these   DT      _       11      det     _       _
7       well    well    RB      _       9       adv     _       _
8       -       -       HYPH    _       9       p       _       _
9       known   know    VBN     _       11      attr    _       _
10      cartoon cartoon NN      _       11      com     _       _
11      images  image   NNS     _       14      nsbj    _       _
12      once    once    RB      _       13      com     _       _
13      again   again   RB      sem=tmp 14      adv     _       _
14      caused  cause   VBD     _       0       root    _       _
15      Hong    hong    NNP     _       16      com     _       _
16      Kong    kong    NNP     _       20      nsbj    _       _
17      to      to      TO      _       20      aux     _       _
18      be      be      VB      _       20      cop     _       _
19      a       a       DT      _       20      det     _       _
20      focus   focus   NN      _       14      comp    _       _
21      of      of      IN      _       23      case    _       _
22      worldwide       worldwide       JJ      _       23      attr    _       _
23      attention       attention       NN      _       20      ppmod   _       _
24      .       .       .       _       14      p       _       _

Is UD have any tool or mapping for above??

**Comment by amir-zeldes** [comment]
Hi @vishu0047 , you should be able to use CoreNLP/Stanford Parser to convert the OntoNotes constituent parses to dependencies. I've done it before and I don't remember having any problems. Just use: `edu.stanford.nlp.trees.EnglishGrammaticalStructure -treeFile FILE.parse`
