### ISSUE TITLE
The open compound noun "hot dog" is not recognized.

### ISSUE THREAD

**Issue by Mark-Patterson** [UniversalDependencies/docs#551]
The Stanford Core NLP ver. 3.9.1 uses UD and parses the UD for the sentence:
"He ate a hot dog for lunch."  

to mean that he ate a dog that was hot: amod(dog-5, hot-4) 

![hot dog](https://user-images.githubusercontent.com/38922196/39540887-0dc92c8a-4e12-11e8-96c5-6d32f6a05ae3.jpg)

Contrast this with "He ate ice cream for lunch." which is correctly identifies "ice cream" as an open compound noun:  compound(cream-4, ice-3)

**Comment by dan-zeman** [comment]
In general, this is probably not the proper place to post questions about the Stanford Core NLP.

However, if it contains a statistical parser that has been trained on the UD English EWT treebank, then it is not surprising that the parser does not recognize _hot dog_ as a compound. The phrase _hot dog_ does not occur in the treebank, so the parser must look at other sources of information, such as the POS tags. And the most probable relation to connect an adjective with the following noun is `amod`.

**Comment by Mark-Patterson** [comment]
The phrase _hot dog_ should be added to the UD English EWT Treebank and identified as an open compound noun.

**Comment by dan-zeman** [comment]
Sorry, this is not how treebanks usually work. The treebank is a collection of sentences that have been written by real people and found on the web. Of course you will find sentences with _hot dog_ on the web, but it is not possible to manually annotate and add to the treebank all sentences from the web. No matter what you do, there will be always millions of phrases that exist in the language but are not represented in the treebank.

**Comment by Mark-Patterson** [comment]
Thanks for your replies Dan!  I'm just getting up to speed.  I'm amazed that with something as fluid as language that the UD Treebank has not been designed to be extensible.

**Comment by nschneid** [comment]
You are welcome to contribute a new corpus to the UD project, provided it contains full-sentence annotations according to the standard: http://universaldependencies.org/contribute.html

If you're interested in multiword expressions in particular (such as compounds with idiosyncratic meanings), you may be better off consulting WordNet or another lexical resource.

**Comment by nschneid** [comment]
BTW, the plural form "hot dogs" *does* occur in EWT, and is annotated with `amod`.
