### ISSUE TITLE
Preposition stranding in relative clause/question: ellipsis or nonprojectivity?

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#552]
[This query](http://bionlp-www.utu.fi/dep_search/query?search=PRON%20%3E%40R%20ADP&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=100) reveals about 50 EWT instances with the nonprojectivity analysis, where the stranded preposition is a dependent of the relativizer. In other cases similar sentences are treated as ellipsis. Which analysis is correct?

## that-RC

"a thing that you pay for" has the nonprojective analysis:

    obl(pay, that)
    case(that, for)

Whereas the ellipsis analysis is seen e.g. in "outcomes that they had little to do with"

    obl(had, that)
    obl(do, with)

## wh-clause

This inconsistency also happens with wh-initial (free relative?) clauses:

"I have no idea what you're talking about": nonprojective

    acl(idea, talking)
    obl(talking, what)
    case(what, about)

"what you are referring to": ellipsis

    acl:relcl(what, referring)
    obl(referring, to)

## wh-question

"what are you having problems with?": nonprojective

    nmod(problems, what)
    case(what, with)

"what did you guys vote for?": ellipsis, with pronoun attached as `obj` instead of `obl`

    obj(vote, what)
    obl(vote, for)

See also UniversalDependencies/docs#454 & UniversalDependencies/UD_English-EWT#523.

**Comment by dan-zeman** [comment]
When the pronoun is present in the clause, it is not ellipsis and the preposition should be attached to the pronoun despite the nonprojectivity.

**Comment by jnivre** [comment]
Quite right.

**Comment by nschneid** [comment]
OK—I couldn't find this in the guidelines, so it should probably be added somewhere!

Looks like there are at least several dozen sentences with a pronoun that need to be corrected.

What about "anyplace you want to spend more time at"? "Anyplace" is tagged as `ADV`.

**Comment by dan-zeman** [comment]
Not sure about _anyplace_. I think it is not totally unheard of that a preposition combines with a word that lies in the gray zone between nouns and adverbs and is possibly tagged `ADV`. But one would have to search for examples. And the English-specific guidelines should probably mention the cases mentioned in this issue.

**Comment by amir-zeldes** [comment]
Since 'place' is also a noun, maybe this is NOUN in context? The same could be said about home/NOUN vs. home/ADV depending on context.
