### ISSUE TITLE
xcomp erroneously used for iobj/dobj constructions

### ISSUE THREAD

**Issue by Mark-Patterson** [UniversalDependencies/docs#553]
In "I threw him the ball.", "ball" is erroneously identified as an xcomp of "threw" with "him" erroneously identified as the nsubj of ball.  "ball" should have been the dobj of "threw" and "him" should have been the "iobj" of "threw".

![i threw him the ball](https://user-images.githubusercontent.com/38922196/39970514-c7db514c-56ba-11e8-852f-f22a2d534190.jpg)

(photo from Stanford CoreNLP 3.9.1 which relies on Universal Dependencies)

**Comment by jnivre** [comment]
This is not a UD issue, it is an issue for the Stanford CoreNLP parser. I think you should contact the Stanford NLP team instead.
