### ISSUE TITLE
Gender/number for 'double agreement' possessives

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#554]
Some languages, e.g. Coptic, German, have possessive determiners that mark both the gender/number of the possessor and the possessed. In German, for example, these currently take the gender (and number) of the possessed, just like articles (an example is below). Do we want a feature to encode the gender/number of the possessor as well?

```
6	er	er	PRON	PPER	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	7	nsubj	_	_
7	kam	kommen	VERB	VVFIN	Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin	4	conj	_	_
8	einfach	einfach	ADV	ADV	_	7	advmod	_	_
9	mit	mit	ADP	APPR	_	11	case	_	_
**10	seinen	sein	PRON	PPOSAT	Case=Dat|Gender=Neut|Number=Plur|Poss=Yes	11	det:poss	_	_**
11	Geräten	Gerät	NOUN	NN	Case=Dat|Gender=Neut|Number=Plur	7	obl	_	_

```

("he just came with **his** instruments" - the possessor, 'his', takes the gender Neut and number Plur from 'instruments', but the possessor is a Masc+Sing)

**Comment by ftyers** [comment]
This is what subfeatures are for, e.g. `Number[psor]`, e.g. consider this example from German:
```
11	ihr	_	PRON	DTP$	Case=Acc|Gender=Neut|Gender[psor]=Fem|Number=Sing|Number[psor]=Sing|Person=3|Person[psor]=3|PronType=Prs	16	nmod:poss	_	_
```
The `Gender` comes from the agreement, and the `Gender[psor]` comes from the possessor.  The example you give is from `UD_German-GSD`:

```
# sent_id = dev-s60
# text = Meine Mutter ist bettlägerig und er kam einfach mit seinen Geräten zu ihr nach Hause!
```

It seems that `-GSD` doesn't encode `psor`, but `-PUD` does. This should definitely be standardised (and I would say we should include the psor info).

**Comment by amir-zeldes** [comment]
OK, great - I agree it should be standardized, and I can add it to the Coptic treebank. Is the notation with square brackets standardized somewhere? And the name 'psor'? I did't see this in the documentation for the gender feature etc.

**Comment by amir-zeldes** [comment]
Just discovered this:

http://universaldependencies.org/u/overview/feat-layers.html

It seems to still be marked as udver1. If this standard is acceptable to everyone maybe we could link it more prominently, and also from the pages for Gender and Number?

**Comment by jnivre** [comment]
Layered features are described briefly at http://universaldependencies.org/u/overview/morphology.html, so they are definitely part of v2. The other page needs to be updated, but I will leave this to Dan, who has a better overview of the documentation of features.

**Comment by amir-zeldes** [comment]
OK perfect, thanks!

**Comment by dan-zeman** [comment]
Reopening until I will have fixed the page.

**Comment by dan-zeman** [comment]
I have modified the guidelines, layered features are now accessible from the main TOC. I have also verified that the page about layered features is v2-compliant. Closing the issue.
