### ISSUE TITLE
Should we ban duplicite DEPS?

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#555]
As reported by @bguil in https://github.com/UniversalDependencies/UD_Dutch-Alpino/issues/2 (and also for other treebanks, e.g. UD_Polish-LFG), the enhanced dependencies in the DEPS column sometimes contain duplicite entries, i.e., there are two or more relations where both the parent index and the relation label are identical.

I think it is not explicitly mentioned as an error in the current guidelines (http://universaldependencies.org/format.html#syntactic-annotation) but I don't see what valid purpose it could serve; probably it is just a bug in conversion software. Should we extend the [validator](http://quest.ms.mff.cuni.cz/cgi-bin/zeman/unidep/validation-report.pl) to report such duplicities as errors?

**Comment by martinpopel** [comment]
I vote for banning these duplicates and extending the validator. Just to be sure: we will forbid just exact duplicates and we will allow cases where the two dependencies differ in sdeprel ("language-specific" subtype of dependency relation)?

**Comment by dan-zeman** [comment]
@martinpopel : Yes, that's what I meant by saying "both the parent index and the relation label are identical" :-)

**Comment by dan-zeman** [comment]
There is a [prototype of a new validator](https://github.com/UniversalDependencies/tools/commit/4424c7a96fa968ec3eb0fd8d975f50005a28dd2c) (ported to Python 3), which should not allow duplicate enhanced relations. It does not affect release 2.3 but it should be in effect for 2.4.
