### ISSUE TITLE
Coordination between packs of uncoordinated modifiers

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#556]
_The square was filled with **French** and **old Italian** cars._

_French_ here is `conj` to _old Italian_ as a whole. What is the proper way annotate that? Currently we use `conj`(French, old) with `flat:conjpack`(old, Italian).

**Comment by nschneid** [comment]
I guess another option would be to treat this as ellipsis: "The square was filled with French (CARS) and old Italian cars." "French" would be promoted to be the head of the first conjunct, giving `conj(French, cars)`, `amod(cars, old)`, `amod(cars, Italian)`.

Cf. "She saw three monkeys and he saw two".

**Comment by msklvsk** [comment]
The problem with ellipsis is that _“old Italian”_ is perceived (at least in my mind) as a single unit, that is, conjoined are car ‘specifications’, like _“curly black or straight brown”_ can be used to describe someone’s hair preferences.

It happens quite often, especially in legal text with _“or other alike”_ endings e.g.: 
_“…tests on animals related to surgical or other harmful effect”_.

Those are homogenous modifiers, but what really bugs me is something like this:
 _“I eat burgers, tacos, Chinese, often ribs, but never a salad.”_
_Often_ modifies _eat_ for _ribs_ only, but to describe the syntax via ellipsis we have to put inside the sentence a phantom copy of _eat_ with all its modifiers. This makes me wonder if _“old Italian”_ logic can be generalized to also pack heterogeneous modifiers like _often_ and _ribs_ together and connect them as a single `conj`.

**Comment by nschneid** [comment]
I don't have a strong opinion and will defer to others on this, but my hunch is that this is the sort of thing where dependency syntax has inherent limitations and we'll have to make compromises. (I feel that way about coordination generally!)

**Comment by martinpopel** [comment]
I think this should be handled in enhanced deps rather than in basic deps, but I don't have an exact proposal now.

A side note: in "*curly black*" it is clear that *curly* depends on *black*. I can imagine "*old Italian*" meaning *old-Italian-style* with a non-compositional semantics (i.e. not every car which is old and Italian can be called "old-Italian-style car") and I am not sure how to annotate this (just let *old* depend on *Italian*, but keep it tagged as adjective, or use `flat`/`compound`). However, I guess that in our case "*old Italian*" is fully compositional and it means just "old and Italian".

**Comment by msklvsk** [comment]
Just found an example of packing unrelated to coordination! (Should be `flat:pack` after all?) 

<img width="279" alt="image" src="https://user-images.githubusercontent.com/473012/42702851-649268b6-86d3-11e8-9242-53bde9a2ff2a.png"> 

_The-leaves [are] entire linear._

(_Entire_ and _linear_ are the terms for the form of leaf’s edge and body respectively and do not depend on each other.)

**Comment by dan-zeman** [comment]
I would probably analyze the two adjectives as asyndetic coordination, i.e., conj(цілісні, лінійні). If they were used attributively instead of predicatively, there would be another option: simply attach them both as `amod`s.
