### ISSUE TITLE
Elided existential predicates

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#559]
Consider the following example from a weather report (ukr).
```
На дорогах   ожеледиця .
on the-roads ice-crust
```
This is not the _“she is in the kitchen“_ type of predication, rather the verb for existence (_is_, _lies_) is omitted. That would make its subject, _ice-crust_, _ожеледиця_, the root. Now does this mean `orphan`(_ожеледиця_, _дорогах_)?

> If the elided element is a predicate and the promoted element is one of its arguments or adjuncts, we use the orphan relation when attaching other non-functional dependents to the promoted head.

These constructions are quite frequent and often there are many adjuncts to become orphans.

NB: It really isn’t a nonverbal predication (that would be _ожеледиця — на дорогах_), neither it is a plain noun phrase.

**Comment by ftyers** [comment]
If this isn't the equivalent of _ожеледиця — на дорогах_, which would be:
```
root(дорогах)
case(дорогах, на)
nsubj(ожеледиця)
```

Is this like a "shipping forecast"[1] / "list" construction ? Could you have a copula verb there in the past?(if so the "на дорогах" is already the predicate)


1. https://en.wikipedia.org/wiki/Shipping_Forecast#Broadcast_format

**Comment by dan-zeman** [comment]
I suppose that the past tense of the existential sense would be

_На дорогах була ожеледиця. / Na dorohach bula oželedycja._ = “There was ice crust on the roads.”

and the past tense of the locative sense would be

_Ожеледиця була на дорогах. / Oželedycja bula na dorohach._ = “The ice crust was on the roads.”

I would argue that the difference between the two sentences is only pragmatic (unlike in English, where the syntax is different, too). Therefore their trees should be isomorphic:

`root`(_дорогах_)
`nsubj`(_дорогах_, _ожеледиця_)
`cop`(_дорогах_, _була_)

Now if we switch back to the present tense, the copula disappears but it was a leaf node, there are no consequences. The rest stays the same.

**Comment by ftyers** [comment]
@dan-zeman that would be my suggestion too, and follows how it works in Russian.

**Comment by sylvainkahane** [comment]
In weather forecasts, it is very common to have nominal sentences. For instance in French, to have something like:

```
Sur les routes, verglas persistant aujourd'hui.
On the roads, persistent ice today.
```
It doesn't really make sense to test the past tense for a weather forecast. I have no intuition concerning Russian, but I wouldn't be surprised that nominal sentences are also frequent in weather forecasts in Russian. If this is the case, 'ice crust' would be the root and 'on the roads' would be an `obl:mod`. In any case, it would be my analysis for French.

**Comment by dan-zeman** [comment]
@sylvainkahane : I think that the difference from French is that in Russian (and, I suppose, Ukrainian too), this is not some special case of  weather forecasts. The language works this way in other contexts too (_there is food in the fridge_ vs. _the food is in the fridge_).

(And I don't see anything nonsensical about converting a weather forecast to the past tense. For example, one can ask whether what they forecasted became real.)

**Comment by msklvsk** [comment]
In the past tense, you must add a verb indeed, only it would not be copular, but existential, I believe. It is more natural to use _lay_, but you can use _was_ as well:
_На дорогах **була** ожеледиця._ — and I would analyze it as `nsubj`(_була_, _ожеледиця_).

This isn’t an extremely condensed sentence, and this phenomenon is widespread, not exclusive to forecasts (thanks @ftyers for an interesting read!)

Let me show it to you on another example: _“My room has two windows“_
```
В  моїй кімнаті двоє вікон .
in my   room    two  windows
```
`orphan`(_вікон_, _кімнаті_)

If you were previously speaking about some particular windows you bought and now you say you’ve installed two of them in your room, that would be

```
Двоє вікон    —    в  моїй кімнаті .
two  windows [are] in my   room
```
`nsubj`(_кімнаті_, _вікон_)

You can in theory drop the dash: _“Двоє вікон в моїй кімнаті.“_, but now it’s ambiguous with a noun phrase _“two windows in my room“_. Nobody would say _“В моїй кімнаті двоє вікон.“_ in this case unless it’s some extreme poetry an you strongly emphasize _“В моїй кімнаа́аті“_.

_“В моїй кімнаті двоє вікон.”_ — existential — _“My room has two windows“_
_“Двоє вікон — в моїй кімнаті.”_ — locational — _“The two windows are in my room“_

Now I see @dan-zeman already pointed that out. Doesn't the different word order count for syntax? 

It is absolutely natural to say _На дорогах **є** ожеледиця._ — the present tense of existential sense. 
Now if you make it past tense, it should remain existential. Unless you abolish all existential to-be in a treebank.

**Comment by dan-zeman** [comment]
@msklvsk :
> Doesn't the different word order count for syntax?

In languages with a fixed word order (English) it does, because word order is part of the syntax. For example, people might question whether _food_ is `nsubj` in _there is food in the fridge_, because subjects are supposed to precede the verb in English declarative sentences.

But as far as I know, in Slavic languages the word order is pragmatic rather than syntactic. Not entirely, because position of some things like clitics is restricted, but for most part it is independent of syntax. So for example, looking at all verbs that have both the subject and the object in UD Ukrainian, you have

<pre>
SVO	1387
OVS	173
OSV	143
SOV	127
VOS	46
VSO	25
</pre>

Neither the subject nor the object (nor the verb) change their syntactic function if you switch between these word orders.

**Comment by sylvainkahane** [comment]
@dan-zeman I know that the copula is absent in Russian in the present tense and for this reason it is much more difficult in Russian to decide whether nominal sentences exist or not in weather forecasts. Nevertheless, it is possible to construct examples where a copula would be quite inappropriate. Something like: 'Ice crust in the morning and heavy rain in the afternoon. No wind. Sun sporadically.'

You said also "I don't see anything nonsensical about converting a weather forecast to the past tense". But you cannot forecast the past ;-)
It is a particular genre, like cooking recipes for instance. If you change the tense, you’re no longer in that genre. And the particular syntactic construction (if there is one) is linked to the genre (like the infinitive form in cooking recipes in French).

**Comment by msklvsk** [comment]
uk | tense | to-be | sense | en
---------|----------|---------|---------|---------
 На дорогах **є** ожеледиця. | present | optional | existential | There is ice crust on the roads.
 На дорогах ожеледиця. | present | dropped | existential | There is ice crust on the roads.
 На дорогах **була** ожеледиця. | past | mandatory | existential | There was ice crust on the roads.
 Ожеледиця **—** на дорогах. | present | dropped | locational | The ice crust is on the roads.
 Ожеледиця **була** на дорогах. | past | mandatory | locational | The ice crust was on the roads.

**Comment by dan-zeman** [comment]
So I suppose the question is whether the difference between _є_ and other forms of _бути_ is enough to distinguish copulative and existential _to be_ according to [the guidelines](http://universaldependencies.org/u/overview/simple-syntax.html#nonverbal-clauses): “If there is an overt word used in existential constructions (category 6), which is different from the copula in equational constructions (either a different lemma or with different syntax), then it should be regarded as the head of existential clauses, taking a subject (and often a locative obl).”

**Comment by msklvsk** [comment]
In this issue, I'm pointing out that present tense existential to-be-s (which are currently allowed in UD) are often dropped in some Slavic languages.

The distinction between existential and locational senses is clear without a context in most cases (drop or no drop), and, most importantly, it's parser-trainable.

If we don't treat dropped to-be existentials as elided roots, we create an asymmetry with non-dropped cases, inluding the past tense. If we then analyze all the past tense as locationals, we still have an asymmetry with overt present tense cases.

So yes, it’s either orphans, or asymmetry, or ban existentials entirely.

**Comment by dan-zeman** [comment]
I would be in favor of not distinguishing existence from location, that is, I would treat all occurrences of Slavic _to be_ as either `cop` or `aux`.

**Comment by msklvsk** [comment]
I would argue for the opposite. This is a valuable distinction and is very much encoded in language. How about a test: we create a task-specific dataset of sentences by marking sentences in the existing data and annotating new ones if required. We then train one of the shared task winning parsers and measure how accurately can it distinguish existentials vs locationals. Is there an accuracy percentage that will prove it is a syntax matter?

P.S. Those orphans won’t be orphans in enhanced representation. Parsers already [can reconstruct](https://nlp.stanford.edu/pubs/schuster2018gapping.pdf) and will only become better at it.

**Comment by dan-zeman** [comment]
One reason why my preference is with not distinguishing the usages is that I'd like to avoid the asymmetry. (And orphans too.)

As for the definition what is syntax: I don't think there is a single and clearcut definition. But I never thought of syntax as everything that can be predicted by a software tool. Even if that tool has "parser" in its name.

Technically, the distinction can be made of course. And it can be sometimes useful. I just doubt that it still falls under the scope of UD - remember that UD cannot annotate everything. And I doubt that it is in line with the current guidelines; if it isn't, then it also undermines parallelism across treebanks. If it would go against the guidelines but you still want to distinguish the two usages, you can encode it in a relation subtype or in the MISC column.
