### ISSUE TITLE
Ellipsis in clauses and confusion with copula

### ISSUE THREAD

**Issue by GPPassos** [UniversalDependencies/docs#560]
Currently in [the documentation on ellipsis in clauses](http://universaldependencies.org/u/overview/specific-syntax.html#ellipsis-in-clauses), it is said that 

> In more complicated cases where a predicate is elided but no aux or cop is present, simple promotion (without orphan deprels) could lead to very unnatural and confusing relations. For example, in the following sentence, you would be the subject of coffee, suggesting that the second clause contains a copular construction rather than an elided predicate.

The example is the following:
```
# visual-style 6 5 nsubj color:red
1 I      I      _ PRP _ 2 nsubj _ _
2 like   like   _ VBP _ 0 root  _ _
3 tee    tee    _ NN  _ 2 obj   _ _
4 and    and    _ CC  _ 6 cc    _ _
5 you    you    _ PRP _ 6 nsubj _ _
6 coffee coffee _ VBP _ 2 conj  _ SpaceAfter=No
7 .      .      _ .   _ 2 punct _ _
```

However, we now have a specific order for promoting dependents:
> In such cases, we promote dependents in the following order: nsubj > obj > iobj > obl > advmod > csubj > xcomp > ccomp > advcl and for the non-promoted dependents, we use the special relation orphan to signal a non-standard dependency. 

Even disregarding `orphan` analysis, this confusion with copula is now impossible, because an `obj` would never be promoted if a `nsubj` is present. Thus it seems a strange example to have.

Should a `csubj` example be used instead? For instance, something like this:
```
# text = Dialogue makes peace but fighting, only chaos.
1	Dialogue	Dialogue	PROPN	_	Number=Sing	2	nsubj	_	_
2	makes	make	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
3	peace	peace	NOUN	_	Number=Sing	2	obj	_	_
4	but	but	CCONJ	_	_	8	cc	_	_
5	fighting	fight	VERB	_	VerbForm=Ger	8	csubj	_	SpaceAfter=No
6	,	,	PUNCT	_	_	8	punct	_	_
7	only	only	ADV	_	_	8	advmod	_	_
8	chaos	chaos	NOUN	_	Number=Sing	2	conj	_	SpaceAfter=No
9	.	.	PUNCT	_	_	2	punct	_	SpaceAfter=No
```
![image](https://user-images.githubusercontent.com/13408995/43216169-9b042444-9014-11e8-81fe-8147ed358d5c.png)

Perhaps someone can come up with a better sentence?

**Comment by dan-zeman** [comment]
The promotion hierarchy has been introduced as part of the `orphan` analysis. If you disregard `orphan`, you should disregard the hierarchy too. The main point is that nsubj(coffee, you) in that example is unnatural beyond the extent we are willing to tollerate. It is irrelevant which nominal you decide to promote: obj(you, coffee) is as unnatural.

I am quite fine with the example that is there now. But I do not mind if there are more examples. If anything is added, perhaps the obj(you, coffee) should appear there first, to demonstrate that no promotion hierarchy is better than the others, if we do not introduce orphans.

**Comment by GPPassos** [comment]
I see. I thought the example a bit misleading as `nsubj(coffee, you)` is not the only alternative for promoting without the `orphan` relation (it is actually the worst alternative possible, due to copula).

I agree that `obj(you,coffee)` appearing first would make it clearer. Perhaps it is just a matter of adding it and slightly changing the wording.

**Comment by dan-zeman** [comment]
Okay, what about this.
http://universaldependencies.org/u/overview/specific-syntax.html#ellipsis-in-clauses
