### ISSUE TITLE
Doubt on propagation of conjuncts in Enhanced Dependencies

### ISSUE THREAD

**Issue by GPPassos** [UniversalDependencies/docs#561]
The documentation of enhanced dependencies presents 3 cases: conjoined verbs and verb phrases, conjoined subjects and objects, and conjoined modifiers.

Does it mean that only these 3 cases are allowed (so, for instance, it would be forbidden to propagate an `amod` to two conjoined nominals in "_young boys and girls_", or the dependency relation in conjoined function words) or are these 3 cases merely examples?

**Comment by dan-zeman** [comment]
We do not have examples with all parts of speech but coordination can apply to all parts of speech, and so does propagation of conjuncts.

**Comment by GPPassos** [comment]
Thanks! May I submit a PR making this explicit?

**Comment by dan-zeman** [comment]
Yes, please do.

**Comment by msklvsk** [comment]
By the way, conjoined modifiers are the most tedious part to implement enhanced dependencies for. If conjuncts are heterogeneous (e.g. adjectives mixed with noun phrases and/or clauses), you have to predict their relation, and there are dozens of combinations. Maybe it’s also worth to mention explicitly in the docs (that you have to predict).
