### ISSUE TITLE
How should we treat akkadian determinatives?

### ISSUE THREAD

**Issue by vaporizedcamel** [UniversalDependencies/docs#564]
Note: Question was originally asked in the email conversation with Dan Zeman

I would like to ask for an advice on the clf dependency. In Akkadian there are plenty of what assyriologists call determinatives. It would be the best to cite Huehnergard (2011) to make the case clear:

"_Some signs, again physically indistinguishable from syllable signs, are used as graphic indicators of the class of objects to which the item denoted by a given noun belongs; they are called determinatives.
Determinatives may be used to denote the material out of which an object is made or that a given noun denotes a proper name, a female, a city, a country, a river, a kind of animal (e.g., a fish, a bird), a part of the body, a profession, a month name, etc.
Most determinatives stand before the nouns they classify, although a few follow their nouns. They are represented in transliteration according to their Sumerian pronunciation (as with logograms), with lower case Roman letters (usually in smaller type), written as superscripts, i.e., above the line. All determinatives also occur as logograms, but not all logograms occur as determinatives; in fact, the number of determinatives is quite small, about two dozen._"

The problem is complex and it might be unavoidable to compromise.

There are a few reasons - first is that determinatives could be read as nouns. For example, KUR szu-me-ri could be read as 'mat šumeri' (the land of Sumer), or just 'šumeri'. DINGIR.AMAR.UTU is usually transliterated as 'dMarduk', but could be transcribed as 'ilu Marduk' (god Marduk) as well.

But - a single cuneiform 𒁹 (https://en.wiktionary.org/wiki/%F0%92%81%B9) sometimes means 1 (one), sometimes sixty, or it means 'šumma' (if), preposition 'ana', or denotes that following string of signs is a personal name - and it will be marked in transliteration as mPersonal_Name. It has no noun value when denoting a personal name.

Yet another case: GIŠ.GU.ZA in Sumerian, will be transliterated to Akkadian GIŠkussû - a chair or a throne - GISZ denotes an object that is made of wood. It is unlikely it was read aloud as 'wooden throne'. But this is the problem with the cuneiform script - we can't be certain. Also, determinatives are not obligatory, their role is rather to disambiguate the meaning.

I struggle to decide which POS tag should determinatives have (DET, NOUN, or some other?), and is the clf relation adequate in that case? I would really appreciate some recommendation, as determinatives are very common in Akkadian and it would be the best for me to annotate them correctly from the start.

One more excerpt from Huehnergard:
![image](https://user-images.githubusercontent.com/41971325/44552600-186c8e80-a72b-11e8-9366-59d388c1c377.png)
![image](https://user-images.githubusercontent.com/41971325/44552623-24585080-a72b-11e8-8a1e-52824ca66845.png)

Reference:
Huehnergard, J.
A Grammar of Akkadian
2011

**Comment by dan-zeman** [comment]
Here is a copy of my e-mail reply; hopefully we get opinions of other people here :-)

I suspect that determinatives may be different from classifiers used in Chinese and other languages, although they share the trait that they semantically categorize the neighboring noun. Is it correct to assume that they are just part of the writing system? That is, if you were sitting in Babylon and hearing the king pronouncing the proclamation, there would be no segment of his utterance directly corresponding to the determinative? If that is the case, then I am not sure that the determinative should be treated as a separate syntactic word (tree node). It may be just a part of the written representation of the noun.

**Comment by sylvainkahane** [comment]
I agree with @dan-zeman that it can be the simplest solution.
But if you want to describe the writing system and you consider that these constructions are compositional in this system, it is justified to treat determinatives as a separate nodes. I think that determinatives belong to a distributional class different from NOUN. If you do not have use DET for something else in Akkadian, you could use it for the class of determinatives. And `clf` seems ok if the determinative is optional. If it is not, maybe `det` is better.

**Comment by vaporizedcamel** [comment]
Thank you for your answers, I will follow your advice and merge determinatives with neighbouring nouns.
