### ISSUE TITLE
Directional particle/adverb + spatial PP

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#570]
In English-EWT, there is an inconsistency for phrases like "go **back to** the city" and "drive **down from** the city", with a spatial adverb/particle followed by a spatial preposition. Sometimes the adverb/particle ("back", "down", "away", "out", tagged as `ADV`) is treated as the head of the subsequent PP, and in other cases they are sisters.

For example:

* [down/ADV heading PP](http://bionlp-www.utu.fi/dep_search/query?search=down%26ADV%20%3E%20%28_%20%3E%20ADP%29&db=UD_English-EWT-dev&case_sensitive=False&hits_per_page=100)
   - "I would like to come down to Austin"

         advmod(come, down)
         obl(down, Austin)
         case(Austin, to)

* [down/ADV sister to PP](http://bionlp-www.utu.fi/dep_search/query?search=down%26ADV%20%3C%20%28_%20%3E%20%28_%20%3E%20ADP%29%29&db=UD_English-EWT-dev&case_sensitive=True&hits_per_page=100)
   - "I walk down in the basement"

         advmod(walk, down)
         obl(walk, basement)
         case(basement, in)

   - "The bus trip down from Sao Paulo"

         advmod(trip, down)
         nmod(trip, down)
         case(Sao, from)

In most of these cases it seems either the particle or the PP can be omitted, so I think I favor the sister analysis.

**Comment by nschneid** [comment]
Another consideration is that the particle + PP combination can be a predicate complement: "He is back from the trip."

I guess the possible analyses are (a) make "back" the head of "from the trip", (b) make "trip" the head of both "back" and "from", (c) make "from" the head of "back", or (d) treat this as one of the exceptional uses of the copula where it is the head of the clause, so both "back" and "from" can attach to it.

**Comment by amir-zeldes** [comment]
+1 for sisters in the first batch. For 'he's back from the trip' I'd say 'back' is the head, since we can't say 'he's from the trip'. If this is accepted I'd say 'from the trip' modifies 'back' (otherwise the analysis is not analogous to 'he's back', which I would think is desirable).

**Comment by dan-zeman** [comment]
So what is the status of this issue? Does it wait for a modification of the data or the guidelines?
