### ISSUE TITLE
New tool for viewing CoNLL-U

### ISSUE THREAD

**Issue by pebbe** [UniversalDependencies/docs#571]
There is a new web-based tool for viewing Universal Dependencies.

Live site: http://www.let.rug.nl/kleiweg/conllu/

Sources available here: https://github.com/rug-compling/conllu-viewer

**Comment by dan-zeman** [comment]
Added to [http://universaldependencies.org/tools.html#conll-u-viewer](http://universaldependencies.org/tools.html#conll-u-viewer).
