### ISSUE TITLE
Question: How to handle scansions in UD?

### ISSUE THREAD

**Issue by mcolburn** [UniversalDependencies/docs#575]
I am using UD to annotate some Christian hymns from the 8th century, written in Greek.  These hymns were (and still are) chanted. The earliest known manuscript uses non-terminal punctuation marks as scansions.  A scansion marks the boundary between metrical units.   They are not grammatical.  That is, the scansions do not necessarily coincide with the boundary of syntactic units (phrases or clauses).  Later versions use an asterisk for the scansion, and sometimes there are both punctuation marks and scansions, side by side.  As a made up example, it could be 

> And, he said to * them, Come, * see for yourself!

In which case, the commas are marking grammatical boundaries and the asterisk is marking a metrical boundary.  

So, my question is, what POS and what syntactic relation should be used to annotate a scansion?  Keeping in mind that in some cases non-terminal punctuation marks (e.g. colon, comma) are used as scansions and in some cases asterisks are used.

**Comment by amir-zeldes** [comment]
We sometimes have things like that in UD_Coptic, and we're never sure if they're real 'punctuation', or 'breathing pause marks' or something else, so we just make them PUNCT and use the udapi punctuation attachment guidelines. In fact, annotators don't do anything with them manually: anything tagged PUNCT is auto-attached at the end.

**Comment by mcolburn** [comment]
Interesting!  Do you attach them to the word they follow or the word that follows them?

**Comment by amir-zeldes** [comment]
We use the general UD punctuation guidelines (or better to say, udapi does), so this is what we aim to produce: http://universaldependencies.org/u/dep/punct.html

In other words, if this thing happens to appear in the middle of a coordination, it acts like comma punctuation inside coordinate phrases, if it appears at clause level, attach to clause root, etc.

**Comment by kajad** [comment]
We used the same PUNCT/punct principle in the Spoken Slovenian Treebank for the annotation of non-lexical tokens, such as markers of pause, laughter, yawning etc.

**Comment by sylvainkahane** [comment]
For UD_Naija, which is a spoken corpus, we have both syntactic and prosodic tags in our transcription and we treat both as PUNCT. It doesn't cause any problem.

Btw, @mcolburn it is far to be clear that ponctuation in written texts is only syntactic. Many writers have an expressive ponctuation, which can be view as a transcription of prosodic breaks.

**Comment by mcolburn** [comment]
Thank you all for your interesting and useful comments!  The consensus seems to be to use PUNCT as both the POS and Syntactic tag.  And, that is what I will do.
