### ISSUE TITLE
Demonstrative ADVs doubling for advcl: chained or parallel?

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#578]
```
uk:   Дах           сконструйований так , що   його      можна    розсувати .
en:   The-roof [is] designed        so  , that it   [is] possible to-open   .
                                    Dem        Acc
```

Is it `advcl`(_so_, _possible_) or `advcl`(_designed_, _possible_)?

On one hand, we connect _as_ parallel to `advcl` in comparatives:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/473012/46952196-d9a3e680-d092-11e8-8a23-0a909fe23fb7.png">

But on the other, we chain here:
 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/473012/46954493-6b165700-d099-11e8-90f5-0d180e84712a.png">

```
to-do     that   ,   what he-considered as    more-preferable
```

**Comment by dan-zeman** [comment]
I would not make _так_ “so” a sibling of the subordinate clause. In the English example, the first _as_ is part of the constituent _as often_, which in Czech would also have two words _(tak často)_ and I suspect the same may be the case in Ukrainian _(так часто)_. But as the Slavic examples show, we can also have just the demonstrative adverb in a similar position while I don't think it is possible with English _as_.

I would analyze the subordinate clause in the Ukrainian example as an `advcl` modifying the demonstrative adverb _так_ “so”.
