### ISSUE TITLE
Quantifier determiners and possessive determiners in Chinese

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#582]
I wondered why quantifiers like 所有 (all), 全部 (all) have been put into DET category, but not possessives pronouns like in 我爸爸 (me + dad : "my dad"), 我的狗 "me + part. 的 + dog : "my dog").
First, these two quantifiers are similar to pronouns as well, they can be object of a verb
我吃了所有 (me + eat + asp. part. + all : 'I ate it all")
我吃了全部 (me + eat + asp. part. + all : 'I ate it all")
我忘了一切 (me + eat + asp. part. + all : 'I forgot everything")

Possessives pronouns and quantifiers placements are similar : 
我很旧的车 : me + very + old + part. 的 + car : PRON + ADJ + part. 的 + car : my old car
所有很旧的车 : all + very + old + part. 的 + car : PRON + ADJ + part. 的 + car : all old cars

**Comment by dan-zeman** [comment]
我 _(wǒ)_ “I” is `PRON`. I think we came to the guideline that if it is the same word (pronoun) that is used in possessive constructions, then we leave it as `PRON` and do not attempt to retag it as `DET` based on context. The possessive function can still be expressed by a subtype of the dependency relation, such as `nmod:poss`.

**Comment by rafael75012** [comment]
Indeed I found the following statement (http://universaldependencies.org/u/pos/DET.html)

> In others [languages], they [possessives] are more like a normal personal pronoun in a specific case (often the genitive), or a personal pronoun with an adposition; they are tagged PRON

Just a remark : doesn't it influence parallelism between languages? For example this pair of translation, completely different analyses for the same thing
My dog : det(dog, my)
我的狗 : nmod(狗, 我); case(我, 的)

**Comment by dan-zeman** [comment]
It does influence the parallelism. But it also highlights the different strategies that the two languages employ to express the same idea. I think UD is an attempt to find a balance between these conflicting objectives. If you give absolute priority to the parallelism, you will end up with a purely semantic representation.

**Comment by wongtaksum** [comment]
I doubt whether these are grammatical...
?我吃了所有 (me + eat + asp. part. + all : 'I ate it all")
?我吃了全部 (me + eat + asp. part. + all : 'I ate it all")
These sentences do not sound natural in colloquial Mandarin...

**Comment by rafael75012** [comment]
My informant told me that, although it is not very natural, but it's grammatical
There are also these interesting examples : 
这 是 我 的 所有 (this + is + I + part. de + all : literally this is my everything;   'this is everything I have')
他 给 了 她 所有 (he + give + asp. part. + she + all : 'he gave her his all')

**Comment by wongtaksum** [comment]
All of these seem to be Europeanized usages... bad Chinese...

**Comment by rafael75012** [comment]
Sorry but those examples are clearly attested https://www.chinlingo.com/articles/600461/ and have all been confirmed by informant. You could also check them on Baidu and ask some chinese native speakers.

And, it is not the main point of my post...

**Comment by rafael75012** [comment]
@dan-zeman, I see
I am simply not sure that there really exists a linguistic difference between the two cases mentioned ("quantifiying determiners" and "possessives") so that it would justify to annotate them with different relations

In the lists of quantifiying determiners (1), there is some adjective-like words (整 / zhěng “whole”, 多 / duō “many”, 少 / shǎo “few”, 許多 / xǔduō “many”) and some pronoun-like words (有的 / yǒude “some”, 有些 / yǒuxiē “some, 一切 / yīqiè “all”, 所有 / suǒyǒu “all”, 全部 / quánbù “all”).

Here is how the pronouns-like listed above are tagged in the "Contemporary Chinese Dictionary" (现代汉语词典). I know this is not an evidence, but I take it to be sufficiantly evocative to raise some attention
I also added the example provided in the corresponding entry of the dictionary 

> 有的 / yǒude “some” : `pronoun`
> 十个 指头，有的 长，有的 短
> shígè + zhǐtou + yǒude + cháng + yǒude + duǎn
> 10 + CL. + finger + some + be.long + some + be.short
> _Ten fingers, some are long, some are short_
> 

> 有些 / yǒuxiē “some” : `pronoun`
> 今天 来 参观 的 人 有的 是 从 外地 来 的
> jīntiān + lái + cānguān + de + rén + yǒude + shì + cóng + wàidì + lái + de
> today + come + visit + DE + people + some + be + from + outside.of.the.city + come + DE
> _Among the people who came to visit today, some were from outside of the city_
> 

> 一切 / yīqiè “all” : `pronoun`
> 人民 的 利益 高于 一切
> rénmín + de + lìyì + gāoyú + yīqiè
> people + DE + interest + be.above + everything
> _The interests of the people are above everything else_
> 

> 所有 / suǒyǒu “all” : `noun`, `adjective`
> 把 所有 力量 都 贡献 给 祖国
> Bǎ + suǒyǒu + lìliang + dōu + gòngxiàn + gěi + zǔguó
> BA + all + power + all + contribute + to + motherland
> _Giving all the power to the motherland_
> 

> 全部 / quánbù “all” : `noun`
> 全部 力量
> quánbù + lìliàng
> all + strength
> _All strength_
> 

For the two words 所有 / suǒyǒu and 全部 / quánbù, examples given by the dictionary are more adjective-like, I provided pronoun-like behaviour of these two words in posts above.

(1) http://universaldependencies.org/zh/pos/DET.html

**Comment by wongtaksum** [comment]
Other than 所有、全部、一切, could you find more examples?
