### ISSUE TITLE
Clarifications on pronominal adverbs

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#583]
Hi,

On this page (http://universaldependencies.org/u/overview/morphology.html#pronominal-words) we can read

(1)
> pronominal adverbs (_where_, _when_, _how_)
> Pronominal adverbs are tagged `ADV`. Their pronominality is encoded using the PronType feature. Their typical syntactic function is to modify verbs.

**Indirect interrogatives**
In French_Sequoia
(a) _Nul ne sait où la piste conduisait ensuite_  `ccomp`(_sait_, _conduisait_); `obl:arg`(_conduisait_, _où_-`ADV`)
(b) _Je sais où ils sont_ `ccomp`(_sais_, _sont_); `obl:arg`(_sont_, _où_-`ADV`)

In English_EWT
(c) _I don't know where this stands officially_ `ccomp`(_know_, _stands_); `advmod`(_stands_, _where_-`ADV`)

**Relatives**
In French_Sequoia
(d) _la laiterie Besnier où il comptait de nombreux amis_ `acl:relcl`(_laiterie_, _comptait_); `iobj`(_comptait_, _où_-`PRON`)

In FrenchSpoken
(e) _énormément de fois où on ira_ `acl:relcl`(_fois_, _ira_); `advmod`(_ira_, _où_-`PRON`)

In English_EWT
(f) _other locations where Muslims are dominant_ `acl:relcl`(_locations_, _dominant_); `advmod`(_dominant_, _where_-`ADV`)

-- "where" (fr. "où") should be annotated `ADV` everywhere, right? And we shouldn't have the alternation into `PRON` like in (d, e)?

-- If we don't want to make the distinction between argumental and non-argumental oblique, like it seems to be the case in English, so no problem, the relation is systematically `advmod` (notice `iobj` in (d)), and it makes sense as "where" is `ADV`.

But if, as in French, you have the distinction between argumental and non-argumental obliques?
I guess the choice of `obl:arg` in (a, b) is accurate. However having an `ADV` depending on an `obl`, isn't it problematic? And their function is not to modify anymore, contrary to what is stated in (1)

**Comment by dan-zeman** [comment]
If the dependent is an adverb (and not a nominal), the universal part of the relation type should not be `obl`. It should be `advmod`.
