### ISSUE TITLE
Clarification on PP copula objects 

### ISSUE THREAD

**Issue by omriabnd** [UniversalDependencies/docs#584]
I was wondering if you could clarify UD's treatment of copulas with a PP object.

My initial understanding was that they should be no different than copulas clauses with an NP object. I was relying on this: (http://universaldependencies.org/u/overview/simple-syntax.html)
> the verb “to be” is used in all of (1-6), and a copula analysis is therefore used consistently, except for equated clauses (1b) and existentials (6), where the verb must be treated as the head of the clause.

However, it seems that some examples (which are not equated clauses or existentials) take the copula to be the head. Examples (head is boldfaced):
1. "... **est** sans précédent ..." (French-PUD, sent_id=n01001011)
2. "... as it **is** with Kerry ..." (English-EWT, #sent_id = weblog-blogspot.com_alaindewitt_20040929103700_ENG_20040929_103700-0068)

Could you clarify when in such cases the copula (rather than the prepositional object) should be the head?

Many thanks,
Omri

**Comment by dan-zeman** [comment]
I suppose that your usage of the term _object_ is not in the UD sense. So it is actually the (nonverbal part of) predicate what you are referring to, right?

I believe that your French example is an annotation error. _Sans précédent_ should be treated as a nonverbal predicate, hence it should be the head of the adverbial clause in that sentence.

Now, I don't think that whenever there is a single adpositional phrase with a _be_-verb, you can grab it and say it's a predicate. Most of the time you probably can (and should) but the English example you found seems to be a good counterexample. You could say _It is bad/good/the same with Kerry_ and the adjective would be the predicate while _with Kerry_ will be an oblique modifier. I think it is the case of the phrase _as it is with Kerry,_ except that the nonverbal predicate has been elided here. Therefore the copula has been promoted to the predicate position. The phrase _with Kerry_ could be a predicate in a different context, for instance in _I am with Kerry now._

**Comment by omriabnd** [comment]
> I suppose that your usage of the term object is not in the UD sense. So it is actually the (nonverbal part of) predicate what you are referring to, right?

Yes. Thanks for clarifying!
