### ISSUE TITLE
Website font doesn’t support Cyrillic italics

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#585]
**[update]** Upstream bug: https://github.com/adobe-fonts/source-sans-pro/issues/87.

The website font, Source Sans Pro, is actually missing italic glyphs for Cyrillic.

As seen on [Google Fonts](https://fonts.google.com/specimen/Source+Sans+Pro?selection.family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&selection.subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese):
<img width="690" alt="image" src="https://user-images.githubusercontent.com/473012/47947647-0b3cfe80-df29-11e8-95e1-002b9d33dd85.png">

(To be fair, it has an **_л_**.)

## Google Chrome fallbacks in [the docs](http://universaldependencies.org/contributing.html#style-guidelines) to Arial:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/473012/47947667-7be41b00-df29-11e8-8a1a-22335130acd6.png">

## While Safari has gaps!
<img width="633" alt="image" src="https://user-images.githubusercontent.com/473012/47947676-9918e980-df29-11e8-86bb-e7491ac76467.png">

**Comment by dan-zeman** [comment]
Oh dear. This issue would ideally be for @spyysalo but I am not sure that he is reachable at present.

**Comment by fginter** [comment]
I can also give it a stab, but am at EMNLP now, and don't have a computer with me so it will take till next week.

**Comment by fginter** [comment]
If you can propose a substitute font that would be great. I don't have Safari so it's hard to test.

**Comment by fginter** [comment]
https://github.com/UniversalDependencies/docs/blob/pages-source/css/style.css 

this is the place but I don't dare mess with it right now because I cannot test

**Comment by dan-zeman** [comment]
Agreed that the best thing is to test (also) in Safari but in fact the first problem is that the current font lacks the Cyrillic italic glyphs. So e.g. in Chrome/Windows, you can see the letters but they are visually different from the Latin ones, so it is obvious that a substitution is needed.

**Comment by fginter** [comment]
sure thing. but messing with the font settings from my mobile phone is a recipe for disaster, so I fix this one I am at a computer. If anyone wants to recommend a new font, now is the time. How about comic sans? 😁

**Comment by dseddah** [comment]
you're kidding but Comic Sans is one of the best fonts for dyslexic people. (really, apparently it's super readable)

**Comment by bulbulistan** [comment]
Roboto or Montserrat would be my first choice.

**Comment by msklvsk** [comment]
Top 5 popular Google fonts, rendered in Chrome on a retina Mac
<details>
  <summary>Click to expand</summary>
 
# Open Sans
<img width="645" alt="image" src="https://user-images.githubusercontent.com/473012/47958684-c4a6dd00-dfd8-11e8-8878-ef7095162c26.png">

# Roboto
<img width="645" alt="image" src="https://user-images.githubusercontent.com/473012/47958690-06378800-dfd9-11e8-90bf-4fe86a59620c.png">

# Montserrat
<img width="641" alt="image" src="https://user-images.githubusercontent.com/473012/47958700-35e69000-dfd9-11e8-9abc-808f27b28e6f.png">

# PT Sans
<img width="648" alt="image" src="https://user-images.githubusercontent.com/473012/47958707-51519b00-dfd9-11e8-97c6-f7c1ade47827.png">

# Noto Sans
<img width="637" alt="image" src="https://user-images.githubusercontent.com/473012/47958766-dab59d00-dfda-11e8-84de-523ef5278f4d.png">
</details>

**Comment by dan-zeman** [comment]
Noto Sans seems to have a problem with rendering the back apostrophes around `nsubj` (looks like a grave accent above n).

**Comment by dan-zeman** [comment]
@msklvsk could you please check whether these fonts also have italic glyphs for Greek and Armenian? (I just added examples of both to the [Style Guidelines](http://universaldependencies.org/contributing.html#style-guidelines).)

**Comment by msklvsk** [comment]
Actually, none of them have Armenian at all. If we choose to switch to any of those, Armenian will remain as it currently is for your platform. Only two of them have Greek. Noto Sans is disqualified.

<details>
  <summary>Click to expand</summary>

### Open Sans
<img width="368" alt="image" src="https://user-images.githubusercontent.com/473012/47963200-62c69180-e031-11e8-857c-da6d87f4678a.png">

### Roboto
<img width="379" alt="image" src="https://user-images.githubusercontent.com/473012/47963188-3b6fc480-e031-11e8-9541-a21600c6eadc.png">

### Montserrat
<img width="367" alt="image" src="https://user-images.githubusercontent.com/473012/47963232-a91bf080-e031-11e8-8d43-bfd58557b32b.png">

### PT Sans
<img width="370" alt="image" src="https://user-images.githubusercontent.com/473012/47963246-d5d00800-e031-11e8-9a9c-fd39ea29ba21.png">

</details>

**Comment by dan-zeman** [comment]
Ok, out of this selection, OpenSans seems to have better coverage than the rest, although it misses italics+bold.

**Comment by msklvsk** [comment]
For my last screenshots, I just took first 4 faces. All the fonts have bold italics, see _**Which**_ in the previous comparison.

**Comment by fginter** [comment]
Better now? Note: you may need to hard-reload to get rid of cached css.

**Comment by msklvsk** [comment]
It must be personal, but Open Sans puts some strain on my eyes. Even dorky Roboto is a smoother read. I wonder if anyone feels the same. If you don’t mind platform differences, you can also use respective system fonts like GitHub does.
