### ISSUE TITLE
Space in MISC

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#588]
The CoNLL-U [format specification](http://universaldependencies.org/format.html) states quite clearly that fields other than FORM and LEMMA must not contain space characters.

The validator script has been more permissive and allowed the space also in MISC (see [here](https://github.com/UniversalDependencies/tools/blob/b13b2ab096aa93718ce5fdf80923871f2d589bd7/validate.py#L265-L271)).

At least one treebank (Romanian Nonstandard) contains spaces in MISC. It is not essential there and an underscore would do equally good (or even better) job, but the validator allows it, so it is there.

We should get rid of the inconsistency between the validator and the specification. So the question is: do we want to modify the specification and allow spaces in MISC, or modify the validator and disallow it? One potential use case that I can see (other than the one currently present in Romanian) is that the MISC column of some treebanks contains transliterations of the form and lemma. If the word contains spaces, then it would be natural that its transliteration also contains spaces.

**Comment by Stormur** [comment]
Is it maybe possible to allow spaces in MISC and to agree on a standard separator for elements in that column, like ; ?

**Comment by foxik** [comment]
BTW, two other treebanks have spaces in MISC, uk_iu and cop_scriptorium. Both uses the space in the sense you suggested -- they include either FORM (which can have spaces) or original version of the form.

The point that convinced me to allow spaces is the fact that FORMs can have spaces. But then if you include FORM in the MISC column, you can get invalid CoNLL-U unless you escape the space somehow, which seems wrong. My preference is therefore to allow spaces (anyway I will allow it in UDPipe, as we have treebanks now with them).

**Comment by foxik** [comment]
@Stormur The standard separator for MISC is `|`, see http://universaldependencies.org/format.html#miscellaneous.

**Comment by amir-zeldes** [comment]
+1 for allowing space - since space is not a separator, I think this shouldn't cause problems.

cop-scriptorium has a MISC annotation called Orig, containing each word form as it appeared in a manuscript, before normalization. This may contain spaces on rare occasions, and the annotation value comes from a preexisting resource, so we'd like to keep it this way.

**Comment by gossebouma** [comment]
A related issue: in the enhanced DEPS field period (.) is not allowed, while it is in LEMMA. Adding the lemma of a case dependent tot obl and nmod thus sometimes leads to inconsistencies: e.g. Dutch has phrasal prepositions like _ten opzichte van_ (_with respect to_), often abbreviated as  _t.o.v._  The lemma for this token is _t.o.v._ in the underlying treebank, which I preserve in LEMMA, but in DEPS I am forced to respell it as _ten_opzichte_van._ 

I am not sure anything would ever depend on this, but it seems more transparent to have the same validation rules for both LEMMA and enhanced DEPS.

**Comment by msklvsk** [comment]
@gossebouma That can be another argument [against](https://github.com/UniversalDependencies/docs/issues/566) bringing forms into `DEPS` at the first place.
