### ISSUE TITLE
reparandum for repeated words in poorly edited texts

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#594]
Is it permited to use role `reparandum` for poorly proofread texts where verb is ungrammatically repeated, e.g. _yesterday he was was here_. If not, what would be more appropriate?

In Latvian corpus we have a sentence _Zālē bija aizņemtas bija gandrīz visas vietas_ (all seats were taken in the hall) from relatively reputable news source. In this sentence the ungrammaticaly repeated verb "bija" (were) even isn't next to the previous instance of it. Latvian has rather free word order, so either _bija aizņemtas gandrīz visas vietas_ or _aizņemtas bija gandrīz visas vietas_ both are completely fine.

**Comment by dan-zeman** [comment]
It sounds acceptable to me. But it would be also possible to attach both occurrences to the same parent and use the `dep` relation for the second copy. I think I have seen something like that in one of the UD treebanks.

**Comment by lauma** [comment]
Untill now I assumed that `dep` means incomplete or someway wrong annotation, and, thus, should be used as a last resort.

**Comment by dan-zeman** [comment]
I would say that this case is a last resort :-) The `dep` relation definitely should be used as little as possible. But an ungrammatical sentence is something where I would start at least considering `dep` as a possible solution.

**Comment by colinbatchelor** [comment]
In the speech subcorpus I'm annotating at the moment I'm using `dep` where the transcriber has been unable to work out what the speaker said and written `[?]`. Occasionally I can guess the part of speech from context but it seems safest just to say `dep`. Is that reasonable?

**Comment by dan-zeman** [comment]
In situations where you cannot guess a different relation from context, `dep` sounds reasonable to me.

**Comment by amir-zeldes** [comment]
@colinbatchelor we do the same for damaged manuscript parts in the Coptic treebank (by convention, `dep` governed by the root, or local root if there is a projectivity problem)
