### ISSUE TITLE
The expl relation in German

### ISSUE THREAD

**Issue by EmanuelUHH** [UniversalDependencies/docs#601]
The official documentation for German states that: 

> The following main types are not used alone and must be subtyped: expl.

What is the reasoning behind this? Constructions with an expletive "it" are perfectly grammatical in German and there are several examples across the German treebanks where expl is actually used sensibly as a main type.

**Comment by dan-zeman** [comment]
Good catch. It looks like the claim has been copied along from another language. And overlooked.
