### ISSUE TITLE
Definition of 'mark'

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#602]
The [`mark` definition](http://universaldependencies.org/u/dep/mark.html) begins: "A marker is the word introducing a finite clause subordinate to another clause."

Why does this specify a *finite* clause given that infinitive "to" is considered a marker? At the very least I think there should be clarification about infinitive markers.

**Comment by dan-zeman** [comment]
I suppose it is a relict from some version of the Stanford Dependencies. I think finite and non-finite subordinate clauses had different relations there (not sure what they did with the infinitive marker though).

**Comment by gossebouma** [comment]
An additional question is whether it is OK to have more than one mark dependent, as in Dutch:

een zondag om nooit te vergeten
a sunday TO never TO forget 

where both 'om' and 'te' (comparable to EN 'to') are mark dependents of the verb 'vergeten'. It causes an issue when converting to Enhanced UD. The current treebank has 

mark(vergeten,te)
mark(vergeten,om)
acl:te(zondag,vergeten)

but perhaps the concatenation

acl:om_te(zondag,vergeten) 

is better?

**Comment by dan-zeman** [comment]
According to the German example in the documentation (coincidentally very similar to your Dutch one), it obviously is OK.
