### ISSUE TITLE
French : périphrase "qu'est-ce que" and "est-ce que"

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#603]
Hi, 

Seems there is no consistent annotation of "qu'est-ce que" and "est-ce que" in French treebanks.

- Qu'est-ce que

Sequoia uses `dislocated` for attributive construction

> 1	Qu'	que	PRON	_	PronType=Int	0	root	_	SpaceAfter=No
> 2	est	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	1	cop	_	SpaceAfter=No
> 3	-ce	ce	PRON	_	Number=Sing|Person=3	1	nsubj	_	_
> 4	qu'	que	SCONJ	_	_	5	mark	_	SpaceAfter=No
> 5	Aclasta	Aclasta	PROPN	_	_	1	dislocated	_	_
> 6	?	?	PUNCT	_	_	1	punct	_	_
> 

Spoken treats "qu'est-ce que" as an MWE? But without parsing it internally with `fixed`?

> 1	qu'	qu'	PRON	_	_	2	advmod	_	_
> 2	est	être	AUX	_	_	7	obj	_	_
> 3	-	-	PUNCT	_	_	4	punct	_	_
> 4	ce	ce	PRON	_	_	2	nsubj	_	_
> 5	qu'	que	SCONJ	_	_	4	obj	_	_
> 6	vous	vous	PRON	_	_	7	nsubj	_	_
> 7	lisez	lire	VERB	_	_	0	root	_	_
> 8	en	en	ADP	_	_	10	case	_	_
> 9	ce	ce	DET	_	_	10	det	_	_
> 10	moment	moment	NOUN	_	_	7	obl:mod	_	_
> 

GSD uses `advcl:cleft`

> 6	qu'	que	PRON	_	_	0	root	_	SpaceAfter=No
> 7	est	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	6	cop	_	SpaceAfter=No
> 8	-ce	ce	PRON	_	Number=Sing|Person=3|PronType=Dem	6	nsubj	_	_
> 9	qu'	que	SCONJ	_	PronType=Rel	11	mark	_	SpaceAfter=No
> 10	on	on	PRON	_	Gender=Masc|Number=Sing|Person=3	11	nsubj	_	_
> 11	fait	faire	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	6	advcl:cleft	_	_
> 

- Est-ce que

GSD uses `ccomp`

> 1	Est	être	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	SpaceAfter=No
> 2	-ce	ce	PRON	_	Number=Sing|Person=3|PronType=Dem	1	nsubj	_	_
> 3	que	que	SCONJ	_	_	6	mark	_	_
> 4	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	5	det	_	_
> 5	Congolais	Congolais	PROPN	_	_	6	nsubj	_	_
> 6	ont	avoir	VERB	_	Mood=Ind|Number=Plur|Person=3|Tense=Pres|VerbForm=Fin	1	ccomp	_	_
> 7	moins	moins	ADV	_	_	6	obj	_	_
> 8	de	de	ADP	_	_	9	case	_	_
> 9	besoins	besoin	NOUN	_	Gender=Masc|Number=Plur	7	obl:arg	_	_
> 10	?	?	PUNCT	_	_	1	punct	_	_
> 

Spoken treats "est-ce que" as a MWE, but without analyzing it internally? And links it with `mark`, but then I don't see to what this `mark` corresponds

> 1	est	être	VERB	_	_	7	mark	_	_
> 2	-ce	ce	PRON	_	_	1	nsubj	_	_
> 3	que	que	SCONJ	_	_	1	dep	_	_
> 4	vous	vous	PRON	_	_	7	nsubj:pass	_	_
> 5	vous	vous	PRON	_	_	7	dep:iobj	_	_
> 6	êtes	être	AUX	_	_	7	aux:pass	_	_
> 7	fixé	fixer	VERB	_	_	0	root	_	_
> 8	aussi	aussi	ADV	_	_	7	advmod	_	_
> 9	un	un	DET	_	_	10	det	_	_
> 10	cadre	cadre	NOUN	_	_	7	obj	_	_

**Comment by jheinecke** [comment]
We annotated about 600 of questions following primarily GSD. However for pratical reasons (we want to parse questions without risking errors in _est-ce que_/_qu'est-ce que_ etc, we put them as a single word on one line: _est-ce que_ only means that the sentence is a closes questions, _qu'est-ce que_, _qui est-ce qui_ etc. can be regarded as "long form" of wh-words _qui_, _que_. From a linguistic view point, this can be seen as ugly, bad or wrong, but from a parsing point of view (UDpipe, trained on GSD + 80% of the questions) and had a LAS of 93% for the 20% other questions (5-fold cross evaluation).

**Comment by dseddah** [comment]
Hi, good news about your question data set, the more the merrier :)
 It's a pity though we didn't synchronize, the next UD release will include 2300 French questions from the French QuestionBank [1], following the FTB/Sequoia original annotation scheme and converted to UD by Bruno Guillaume 


Best,
Djamé
[1] https://hal.archives-ouvertes.fr/hal-01457184v2

**Comment by jheinecke** [comment]
We can always do it at a later stage :-)
BTW, we annotated the questions, because in FTQ the questions are rather long. We needed short , quiz like questions well parsed: "Qui est-ce que le président de la France", "Combien de buts a marqués Pelé". Without our annotations GSD was 10points lower (LAS 82%) on these type of questions.

**Comment by dseddah** [comment]
Yes, that's exactly the same kind of questions, the vast majority coming from a TREC multilingual task that was also used for the English Question Bank.

**Comment by rafael75012** [comment]
In Guillaume et al. (2019) "Conversion et améliorations de corpus du français annotés en Universal Dependencies", a proposition has been made for the annotation of "qu'est-ce que".

> Dans une clivée comme (4), la subordonnée n’est pas un argument du foyer de cette clivée, mais pour la distinguer d’une subordonnée ordinaire qui modifie une proposition principale, nous utilisons la relation `advcl:cleft` de la tête du foyer vers la tête de la subordonnée. Une clivée peut avoir une forme interrogative.
_Qu’est-ce qui va augmenter ?_

What about updating https://universaldependencies.org/fr/dep/advcl-cleft.html with a corresponding example?
