### ISSUE TITLE
HTTPS support for universaldependencies.org domain

### ISSUE THREAD

**Issue by josalmi** [UniversalDependencies/docs#604]
GitHub has supported HTTPS for custom domains for a while now: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

universaldependencies.org website should be updated to new A-records from GitHub and after certificate is generated https could be enforced from the settings.

**Comment by dan-zeman** [comment]
Why should we use a secure protocol on a site where people do not submit their passwords?

**Comment by josalmi** [comment]
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

HTTPS also brings faster loading times: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#faster-site-load-times

**Comment by foxik** [comment]
HTTP only sites are being marked as "not secure" by browsers, see https://www.blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/ . If I understand correctly, a more aggressive version (with red color) is planned in general.

I believe we should start offering HTTPS eventually.

**Comment by fginter** [comment]
Yes, absolutely, let's do it. Right now, that option is unavailable because there's some sort of mixup with the DNS setup. I'll see if I can provide @jnivre with updated instructions. I believe Joakim will need to adjust the config before GitHub lets us turn HTTPS on.

**Comment by jnivre** [comment]
Okay. Just tell me what I need to do and I'll try to do it. :)

**Comment by fginter** [comment]
instructions in email :)

**Comment by fginter** [comment]
...waiting for the certificate to be issued, will take 24h

**Comment by fginter** [comment]
I think this works as of few minutes ago.

**Comment by jnivre** [comment]
Great, Thanks!
