### ISSUE TITLE
Governor of discourse markers

### ISSUE THREAD

**Issue by sylvainkahane** [UniversalDependencies/docs#605]
Currently, the guidelines say about the `discourse` relation:  "These discourse elements are attached to the head of the most relevant nearby clause, which is why they are grouped with non-core clausal dependents even though they are normally not dependents of the predicates as such."
But some discourse markers are inside phrases which are not clauses and to attach them to the head of a clause causes non-projective links. This is particularly pregnant in spoken corpora, especially with fillers such as _uh/er_.
I propose to treat them as (simple) punctuations, because they often work like them, punctuating a phrase: "2. A discourse marker preceding or following a dependent unit is attached to that unit. 3. Within the relevant unit, a discourse marker is attached at the highest possible node that preserves projectivity."
This rule can be simplified and reformulated like this: ""A discourse marker must be attached to the foot of its roof. The roof of a given postion is the smallest dependency covering it. It is the root dependency when the position is not covered."
This should also apply for `parataxis` I think.

**Comment by kajad** [comment]
In the Spoken Slovenian Treebank, we also followed a general rule of attaching such nodes - i.e. discourse markers (labeled as `discourse`, e.g. _well_), clausal discourse markers (`parataxis:discourse`, e.g. _you know_) and filled pauses (`discourse:filler`, e.g. _uh_) - to the highest relevant unit preserving projectivity, either a predicate or any other constituent. 

However, different types of sentential parentheticals appearing in clause-medial positions (`parataxis`, but also `advcl`, e.g. _as far as I know_) have usually been attached to the predicate, regardless of their non-projectivity. 

Perhaps the same solution should be applied in both cases, but we considered non-projectivity to be less problematic than arbitrary clause attachment at the time.
