### ISSUE TITLE
Broken link in PROPN part-of-speech page

### ISSUE THREAD

**Issue by venkatasg** [UniversalDependencies/docs#606]
The following link in the References section for Proper Nouns(PROPN): [Loos, Eugene E., et al. 2003. Glossary of linguistic terms: What is a proper noun?](
http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/WhatIsAProperNoun.htm) is broken. The link is 
http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/WhatIsAProperNoun.htm.

Perhaps the new link is [this](https://glossary.sil.org/term/proper-noun)?

**Comment by dan-zeman** [comment]
Thanks! Replaced with the link you found.
