### ISSUE TITLE
Data split for larger treebanks

### ISSUE THREAD

**Issue by akoehn** [UniversalDependencies/docs#612]
We are preparing a UD release of the HDT, but the [guidelines for the repository layout](https://universaldependencies.org/release_checklist.html#data-format-and-repository) only talk about smaller treebanks.

Our train set would be nearly 200mb, twice the maximum file size for files in github.  Should we simply split the file and add a merge script or are there better recommendations?

An alternative would be to have a test-dev-train split within the size limits and label the additional data as "extra".

**Comment by dan-zeman** [comment]
As long as the whole treebank fits into one repository, we can use the same solution as for [UD_Czech-PDT](https://github.com/UniversalDependencies/UD_Czech-PDT). Split the train file into several smaller files of acceptable sizes, name them `de_hdt-ud-train-?.conllu` where the question mark stands for one or a few letters/digits that distinguish the files. I will then hardcode an exception in the script that checks the treebank files and their names. At release time, the files will be merged using `cat de_hdt-ud-train-*.conllu > de_hdt-ud-train.conllu`, i.e., there will be a single train file in the released package. No merge script is needed from you but

- think about the `?` character if you want to achieve a particular file order;
- you may want to document this in the README file (note that the same README file is visible in your repository on Github and will appear in the treebank folder in the release package)

**Comment by akoehn** [comment]
Okay, I will mention that when we ask for a repository (hopefully soon, we aim for the next UD release).
