### ISSUE TITLE
'contigo' in Spanish treebanks

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#614]
Currently in the treebanks where it appears, the Spanish *contigo* "with you" appears with different labels for morphology:

AnCora:
```24      contigo tú      PRON    PRON    Number=Sing|Person=2|PrepCase=Pre|PronType=Prs  23      obj     _       SpaceAfter=No```

GSD:
```40      contigo tú      PRON    _       Case=Com|Number=Sing|Person=2|PronType=Ind      39      case    _       _```

PUD:
```No examples```

This should probably be standardised.

**Comment by dan-zeman** [comment]
`PronType=Ind` resulted from a bug. All three treebanks now use `PronType=Prs` for _conmigo, contigo, consigo_. They also use the comitative case, although we may want to treat it as a multi-word token instead, and split it to _con tí_.
