### ISSUE TITLE
The ambiguity of pronouns

### ISSUE THREAD

**Issue by EmanuelUHH** [UniversalDependencies/docs#615]
The documentation for amod explicitly states that it is for modifiers of a noun, but in phrases like "something else" it is commonly used to attach the adjectival modifier to a pronoun. I have two questions related to this:

1.) How strongly does "noun" imply the use of both nouns and pronouns? 
While they are used the same way, they are also clearly distinguishable, which I'd take as reason to mention both. (But maybe that would be completely unnecessary effort and I'm just being pedantic.)

2.) Is it correct to annotate English structures like "something else" as amod(something, else) and their German equivalent "etwas anderes" as det(anderes, etwas)? 
I found it surprising how similar the structures are semantically despite their noticeable syntactic difference and was very intrugued when I learned about the ambiguity between pronouns and determiners (mentioned for example in the respective POS documentation pages). It feels weird to me to annotate what seems like the exact same phrase so differently depending on the language, particularly since the UD strives to make cross-linguistic comparisons easier, and I'd like to understand better why these structures are supposed to look like that. Where should I look, apart from the Glossary of linguistic terms cited in the documentation?

**Comment by gossebouma** [comment]
The Dutch data for "iets anders" follows the English analysis, ie with something/iets as the head. I would think this is the preferred analysis, as it seems wrong to label something/etwas/iets as a determiner (it cannot be used as determiner in combination with other nouns). Note that the "iets ADJ+s" construction is productive: iets vreemds (something strange), iets lekkers (something sweet), etc. A Dutch grammar describes this as genitive s that is being attached to an adjective. http://ans.ruhosting.nl/e-ans/06/04/02/01/body.html

**Comment by sylvainkahane** [comment]
In French, these constructions have also been analyzed with theb ADJ depending on the pronoun but it is interesting to note that in french, as in Dutch and in German, the ADJ has also a genitive case marker, the preposition DE:

> quelque chose **de** bizarre 'something strange'

**Comment by EmanuelUHH** [comment]
A genitive? That's very interesting indeed. 
In German, the adjective in these constructions "etwas ADJ+es" is nominalised, i.e. "something strange" would become "etwas Seltsames". Sadly the few examples I've found in UD treebanks were very inconsistent, but in annotations specific to German I've often seen attributive pronouns subordinated to the nominalised adjective as a determiner, which kind of makes sense to me. "Etwas", being an attributive indefinite pronoun, is also permissible as det according to both https://universaldependencies.org/u/pos/DET.html and https://universaldependencies.org/de/dep/det.html (although that last page might not be completely up do date?).
I still see how "something" would be the head in other languages, which is why I'm interested in arguments for annotating it this way or that.

**Comment by dan-zeman** [comment]
Ad question 1: I think `amod` is a modifier within a nominal phrase, which can be also headed by a pronoun, hence an `amod` attached to a pronoun can be correct. Maybe we should mention it somewhere in the documentation.

Ad question 2: where did you see _etwas anderes_? I did not find a single occurrence, neither in UD 2.3 German GSD, nor in German PUD. There are a few other examples of _etwas *es_, see http://hdl.handle.net/11346/PMLTQ-5ATQ. They are indeed annotated inconsistently. I tend to agree that _etwas_ should be the head and the following word should be its modifier. I would have expected the second word to be an adjective but in fact, most cases are written with a capital first letter and tagged as `NOUN` (or even `PROPN`, wrongly). In that case they are `nmod`, not `amod`. (But the current annotation uses various wrong relations, such as `compound` or `appos`.)

**Comment by dan-zeman** [comment]
_Etwas *es_ made consistent in the dev branch of UD_German-GSD. I am tentatively closing this issue, although I am aware that it was not just about German GSD. Feel free to reopen if more discussion is needed.

**Comment by EmanuelUHH** [comment]
> where did you see etwas anderes? I did not find a single occurrence, neither in UD 2.3 German GSD, nor in German PUD.

That was part of the problem - sorry if my wording was somewhat ambiguous. I meant to say that the few examples I found were only for "etwas ADJ+es", not actually for "etwas anderes".

> I would have expected the second word to be an adjective but in fact, most cases are written with a capital first letter and tagged as NOUN (or even PROPN, wrongly). In that case they are `nmod`, not amod.

The nominalisation of adjectives is the main reason I thought that `amod` seemed weird even though the structures are highly similar. I like your solution a lot; `nmod`allows us to maintain the same dependency structure while highlighting in what way the modifiers are different.

> I am tentatively closing this issue, although I am aware that it was not just about German GSD. Feel free to reopen if more discussion is needed.

The question regarding the desired annotation was the most important thing for our current project, although I remain interested in discussion on the subject (particularly regarding the linguistic theory behind it). Thank you. :)
