### ISSUE TITLE
Preverbal Particles

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#619]
A need an advice for the annotation of preverbal particles in Welsh, espacially in the case of auxiliaries:
"the car is red" is "y mae 'r car yn goch" in Welsh

```
1  y     y    AUX  preverbal _  2  aux
2  mae   bod  AUX  aux       _  6  aux 
3  'r    y    DET  art       _  4  det
4  car   car  NOUN noun      _  6  nsubj
5  yn    yn   PART pred      _  6  case:pred
6  goch  coch ADJ  adj       _  0  root
```

I do not see a better way to attach the first word _y_ . However the validation scripts do not allow dependants on auxiliaries. Does anybody see a better way ?
_y_ can be replaced with the negation particle or with an interrogative particle (_nid ydy 'r car yn goch_ "the car is not red", _a ydy 'r car yn goch_ "is the car red?"). 
For other werbs the affirmative particle appears as _mi_ or _fe_, but ih the current version I attached them using `aux` too. If somebody has a better idea, I'd be gratefull

**Comment by dan-zeman** [comment]
The guidelines actually [suggest](https://universaldependencies.org/u/pos/PART.html) that negative particles are tagged `PART`, not `ADV` (but still attached `advmod`). I am not sure whether we wanted to modify this in v2 but we didn't. This is about words whose sole function is the negation, not to negative adverbs of location or time (_nowhere, never_) which are definitely `ADV`.
