### ISSUE TITLE
Validator: X is not a copula in language Y

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#622]
Where can I update copula/auxilliary verb list used by validator for Latvian?

After legthy discussions here locally we worked out that Latvian has 4 auxilliaries: _būt_, _kļūt_, _tikt_, _tapt_ (rare), and we have written this down in the language documentation. However, validator gives warnings `'k\u013c\u016bt' is not a copula in language [lv]` and `'tikt' is not a copula in language [lv]`. Should I add some kind of file, e.g., `auxverbs.lv`, in data folder?

**Comment by lauma** [comment]
The argument about _kļūt_ being copula went something like this:
* _kļūt_ can't be used outside of copular constructions, i.e., saying just _viņš kļūst_ 'he becomes' is incomplete and ungrammatical, and this missing part uses the nominal case or preposition _par_ as it is in copular predicates not acusative or dative as for objects.
* When _būt_ is used in existencial or locational meaning, it can have passive forms (_vai tur ir būts?_), however not in copular use. As _kļūt_ is used only in copular constructions, it has no passive forms at all (the only instance of passive form _kļūts_ in our 10 million corpus is a typo). I think, together with obsolete _tapt_ they are the only verb-ish things in Latvian lacking passive forms. This is the closest thing Latvian has of having incomplete form system for any subclass of verbs.
* The difference why someone would choose _būt_ or _kļūt_ for their copular construction seems to fall into the TAME categories: _viņš bija gudrs_ = 'he was smart', _viņš kļuva gudrs_ ~ 'he was smart, but not all the time, only starting from some point in time'.

I hope my explanation is any good. TAME categories are not much researched in local context and copular verbs in Latvian do not have very obivous formal differences to distinguish them (above mentioned lack of passive is the closest thing we could find in rather vast verbal paradigm), thus, for a while we considered that maybe there are no UD-sense copulas in Latvian at all, but it felt like it is not what was meant in UD guidelines :)

**Comment by lauma** [comment]
Argument about _tapt_ is basically the same as for _kļūt_, and as people don't feel any difference between _kļūt_ and _tapt_, the last one is rapidly vanishing from the contemporary use. In some distant past there probably was some TAME-ish diference between them. Or _kļūt_ wasn't a copula back then. I don't know for sure.

Meanwhile _tikt_ is used for constructing passive voice (it is an analytical form in Latvian) and the difference between _būt_ and _tikt_ again seem to fall into TAME categories: _vāze bija sasista_ 'vase existed in broken state (in some point of past)' and _vāze tika sasista_ 'vase was broken [by someone] (in the same point of past)'.

**Comment by dan-zeman** [comment]
Thanks, Lauma, for the explanation. I think that some of your arguments would apply to the English _to become_ as well. And the fact that a verb is incomplete without its argument/complement is quite common (cf. transitive verbs). Some verbs require an `obj`, some require an `xcomp`.

Anyways, the three verbs have now been added and the validator will recognize them.
