### ISSUE TITLE
Validator: not an auxiliary verb in language

### ISSUE THREAD

**Issue by liljao** [UniversalDependencies/docs#626]
I have recently made a change in the Norwegian Nynorsk treebank, analyzing the passive auxiliary "verte" as AUX rather than the previous (and incorrect) analysis as VERB. The validator now throws an error, is there somewhere to add this verb to an existing list?

**Comment by dan-zeman** [comment]
At present the list is hardcoded. I added _verte_ now.

**Comment by olesar** [comment]
Please add the following verbs and clitics to the auxiliary list for orv (Old Russian):
'учати', 'имати', 'яти', 'бы', 'бъ', 'ся'
cf. the current version: 'orv': ['быти', 'не быти']

**Comment by hanneme** [comment]
And could you also correct  'не быти' to  'не.быти'? That would remove a swathe of validation errors for Old_Russian-TOROT.

**Comment by dan-zeman** [comment]
@hanneme : See my [comment](https://github.com/UniversalDependencies/docs/issues/668#issuecomment-549026195) in #668.

**Comment by dan-zeman** [comment]
@olesar : For 'бы', 'бъ', I think you should include them under lemma _быти_, then the validator will not report them. (I see this elsewhere in your data and also in TOROT.)

**Comment by dan-zeman** [comment]
@olesar : I don't think 'ся' is an auxiliary verb, although I can see some possible argumentation in its favor. But I think that the annotation of _ся_ in TOROT better preserves parallelism with genetically related languages.

**Comment by dan-zeman** [comment]
And finally, may we also discuss _учати, имати, яти_? I am no expert on Old Russian so I may be misled but I am not convinced that the occurrences I saw in the treebank are really auxiliaries.

**Comment by olesar** [comment]
That is what I was asked many times by people doing Old Russian research, to represent periphrastic Future II tense. We reduced the list to what all these people believe to be a grammatical marker.

02.11.2019, 17:34, "Dan Zeman" <notifications@github.com>:And finally, may we also discuss учати, имати, яти? I am no expert on Old Russian so I may be misled but I am not convinced that the occurrences I saw in the treebank are really auxiliaries.

**Comment by olesar** [comment]
'бы', 'бъ' cannot be a form of быти in 1600-1700s texts, just as in the modern Russian.  As for ся/сь reflexive marker, I changed aux to expl:pv (in parallel to Polish and Czech) to distinguish between the reflexive ся  and the expletive particle се (=modern себе).

**Comment by hanneme** [comment]
In TOROT we take those to be biclausal, basically because they don't seem
entirely conventionalised. So in имамъ приити we would take имамъ to be the
head and приити its xcomp dependent. The only auxiliaries we allow are быти
and не быти.

lør. 2. nov. 2019 kl. 19:21 skrev Olga Lyashevskaya <
notifications@github.com>:

**Comment by dan-zeman** [comment]
> 'бы', 'бъ' cannot be a form of быти in 1600-1700s texts, just as in the modern Russian.

But the file `orv_rnc-ud-test.conllu` actually contains _бъ_ lemmatized as _быти_. I found it only twice (on lines 1360 and 3109), so perhaps it is an error.

Also, shouldn't this be annotated the same way in both the treebanks? In TOROT I grepped 94 instances:
<pre>grep -n -P '(бы|бъ)\tбыти' *.conllu | wc -l</pre>
while none is lemmatized as itself.

**Comment by dan-zeman** [comment]
If _учати, имати, яти_ are Future II auxiliaries, what distinguishes them from full verb usages? I see only one occurrence of _учати_ tagged as `AUX` while there are 19 occurrences of this lemma tagged as `VERB`. I browsed several of the `VERB` occurrences and they do occur with an infinitive of another verb, which is attached to them as `xcomp`. Even the `AUX` occurrence is not attached as `aux` to the infinitive; it is made a head of an `advcl`, and the infinitive is attached to it as `xcomp`. So the most consistent step appears to be to just re-tag the one occurrence as `VERB`.

**Comment by olesar** [comment]
I re-tagged auxiliaries other than быти, бы, бъ, but re-tagging учати, имати, яти is a temporary decision as more data will move to ud.Thanks for noticing the deprel error!

**Comment by hanneme** [comment]
> Also, shouldn't this be annotated the same way in both the treebanks? In TOROT I grepped 94 instances:
> 
> grep -n -P '(бы|бъ)\tбыти' *.conllu | wc -l
> while none is lemmatized as itself.

I actually agree with Olya that these are no longer real forms of быти in the late Middle Russian period, but rather particles. The TOROT annotation is deliberately archaising – we keep taking бы as an aorist of быти even in the latest of our texts, simply in order to increase retrievability. This is part of an overarching policy difference between the two treebanks, I'm afraid: TOROT is deliberately conservative and RNC is deliberately oriented towards the modern structures.

**Comment by dan-zeman** [comment]
After adding the conditional particles to the list of auxiliaries UD_Old_Russian-RNC is valid.
