### ISSUE TITLE
Bugs in Slovak

### ISSUE THREAD

**Issue by vladob54** [UniversalDependencies/docs#628]
Some Slovak participles (mapped to adjectives in UD) produce verbal lemma, most likely due to errors in the Slovak treebank.  How can I correct it?

**Comment by dan-zeman** [comment]
This treebank is special in that

- it is converted from a different annotation style AND
- there is currently no mechanism of editing the source data

Therefore I think the corrections should be incorporated in my conversion procedure. I could use a simple list with lines of the form

<tt>'pomätená' => 'pomätený',</tt>

which I would apply when I see an adjective with current lemma ending in "-ť" (<tt>grep -P 'ť\tADJ' *.conllu | wc -l</tt> currently gives me 27 hits, but some of them are instances of a different problem, e.g. it should actually be tagged `VERB`).

For passive participles with the hard inflection I could probably just use a regular expression on a lowercased version of the word form (s/(ý|á|é|ého...)$/ý/), and maybe a similar approach would work for the active present participles (prijímacej      prijímať        ADJ     AAfs2x), I just can't produce the paradigm out of my head and would have to look it up somewhere.

**Comment by dan-zeman** [comment]
I have fixed a subset of the problematic cases for release 2.4 in https://github.com/UniversalDependencies/UD_Slovak-SNK/commit/f947c75718e8aebf0c4558a1b2bc39011afe3f43. Only words that look like participles and have `VerbForm=Part` were modified. There are still other words that are tagged `ADJ` and their lemma ends in _-ť_:

<pre>
1       Nestoja stáť    ADJ     VLepcm- Animacy=Anim|Aspect=Imp|Gender=Masc|Number=Plur|Polarity=Neg|Tense=Past|VerbForm=Part   0       root    0:root  _
2       Trúfa   trúfať  ADJ     VLescf+ Aspect=Imp|Gender=Fem|Number=Sing|Polarity=Pos|Tense=Past|VerbForm=Part 6       obj     6:obj   _
7       tuhnú   tuhnúť  ADJ     VLepcf+ Aspect=Imp|Gender=Fem|Number=Plur|Polarity=Pos|Tense=Past|VerbForm=Part 3       amod    3:amod  _
1       Plávajú plávať  ADJ     VLepcf+ Aspect=Imp|Gender=Fem|Number=Plur|Polarity=Pos|Tense=Past|VerbForm=Part 0       root    0:root  _
4       neuveriteľné    uveriť  ADJ     AAns1x  Case=Nom|Degree=Pos|Gender=Neut|Number=Sing     0       root    0:root  SpaceAfter=No
19      unavení unaviť  ADJ     AAmp1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Plur        17      conj    0:root|17:conj  _
22      sklamaní        sklamať ADJ     AAmp1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Plur        17      conj    0:root|17:conj  SpaceAfter=No
2       presvedčený     presvedčiť      ADJ     AAms1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Sing        0       root    0:root  SpaceAfter=No
10      prijímacej      prijímať        ADJ     AAfs2x  Case=Gen|Degree=Pos|Gender=Fem|Number=Sing      11      amod    11:amod _
2       prijímacej      prijímať        ADJ     AAfs6x  Case=Loc|Degree=Pos|Gender=Fem|Number=Sing      3       amod    3:amod  _
2       neuveriteľné    uveriť  ADJ     AAnp4x  Case=Acc|Degree=Pos|Gender=Neut|Number=Plur     3       amod    3:amod  _
5       nadšený nadchnúť        ADJ     AAms1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Sing        0       root    0:root  SpaceAfter=No
6       sklamaný        sklamať ADJ     AAms1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Sing        0       root    0:root  SpaceAfter=No
4       pomätená        pomiasť ADJ     AAfs1x  Case=Nom|Degree=Pos|Gender=Fem|Number=Sing      0       root    0:root  SpaceAfter=No
12      zahĺbený        zahĺbiť ADJ     AAms1x  Animacy=Anim|Case=Nom|Degree=Pos|Gender=Masc|Number=Sing        11      amod    11:amod _
5       plávajú plávať  ADJ     VLepci+ Animacy=Inan|Aspect=Imp|Gender=Masc|Number=Plur|Polarity=Pos|Tense=Past|VerbForm=Part   2       amod    2:amod  _
</pre>
