### ISSUE TITLE
Validator complains about asterisks “* * *” grouped with `flat`

### ISSUE THREAD

**Issue by msklvsk** [UniversalDependencies/docs#630]
There are three asterisks separated by space. We glued them with `flat`. Should we group with a different relation? or should the validator be changed?

**Comment by nschneid** [comment]
`goeswith`? Are they acting as a single unit?

**Comment by dan-zeman** [comment]
Depends on what UPOS tag you use with them. You can connect them with `flat` if their tag is `SYM`. If they are `PUNCT` then you must attach each of them separately to the common parent, using the `punct` relation.

**Comment by msklvsk** [comment]
@nschneid Yes, they are a single unit, they separate sections of a book. But `goeswith` implies an error, and there is none.

@dan-zeman They do not have a common parent because they are in a separate sentence. I wanted to avoid `SYM` and used `PUNCT` instead. Now I guess I should make them `SYM`.

**Comment by dan-zeman** [comment]
Do you mean the sentence consists solely of the three asterisks and nothing else? If that's the case then you can make the first asterisk the head, attach it to node 0 via a `root` relation, and attach each of the other two asterisks to the head asterisk via a `punct` relation.
