### ISSUE TITLE
subject/object pronoun

### ISSUE THREAD

**Issue by eduarddrenth** [UniversalDependencies/docs#636]
Dear all,

How would one encode a subject pronoun like "I" and an object pronoun like "me" in UD?

See https://en.wikipedia.org/wiki/Object_pronoun

**Comment by dan-zeman** [comment]
<pre>
1	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	2	nsubj	2:nsubj	_
3	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	2	obj	2:obj	_
</pre>

**Comment by eduarddrenth** [comment]
Hi, does this mean that object/subject will be in the v2.4 release? As new values of PronType (nsubj and obj)?

**Comment by dan-zeman** [comment]
No. `nsubj` and `obj` have been in UD since 2.0 (resp. 1.0) and they are dependency relations, not values of `PronType`. The feature that distinguishes the pronoun forms is `Case=Nom` (nominative ~ subject) vs. `Case=Acc` (accusative ~ object).

**Comment by eduarddrenth** [comment]
ok, thanks
