### ISSUE TITLE
encode base form?

### ISSUE THREAD

**Issue by eduarddrenth** [UniversalDependencies/docs#637]
Would it be a good idea to be able to encode the "base form" of a word, independent from it's POS?

For verbs the baseform would be VerbForm.Inf, for other POS like ADJ (i.e. good) and NOUN (i.e. NOUN) one cannot, as far as I can see, encode a base form.

Perhaps "LEMMA" would be a good term?

**Comment by dan-zeman** [comment]
Maybe you want to read the UD documentation. Lemmas are mentioned at many places, for instance, here: https://universaldependencies.org/u/overview/morphology.html#lemmas. Not all UD treebanks contain lemmas but most of them do; it is the value of the LEMMA column in the CoNLL-U format.

**Comment by eduarddrenth** [comment]
Thanks. I do read and strive to use UD, I think it's great and very usable, I concentrate on /u/pos and /u/feat and did not stumble upon LEMMA there. Perhaps me being an ICT expert and not a linguist didn't help either.
