### ISSUE TITLE
"X's own" construction in English

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#638]
Nonverbal "own" is consistently tagged as `ADJ`, though it is a special adjective that must follow a possessive. But the dependency structure is inconsistent in EWT: 

* possessive + own + head noun : "their own choice", "the Republican Right 's own tactics" - `nmod:poss` for possessive and `amod` for "own" are both daughters of the head noun
* P + posessive + own, no head noun: "do research projects on their own", "have children of our own" - `nmod:poss(own, POSSESSIVE-PRON)`
* "Winter defied his own board", "her own small territory" - `nmod:poss(own, POSSESSIVE-PRON)`
   - Just 2 examples; I think these are errors.

Could there be a validation rule that throws an error for the structure `amod(NOUN, own) + nmod:poss(own, *)`?

**Comment by nschneid** [comment]
Some clear errors in English-LinES: PPs attaching as `amod` in "a world of their own" and "powerful magic of their own"

**Comment by nschneid** [comment]
A special case in English-GUM—"a BART station all its own":

amod(station, own)
nmod:poss(own, its)
det:predet(its, all)

Perhaps my suggested validation rule should be limited to cases where the noun occurs to the right of the possessive and "own".

**Comment by amir-zeldes** [comment]
I'm not sure, but I think the GUM case might be correct: if 'all its own' were acting as a possessive determiner, we wouldn't get 'a' (*a its own Bart station), so this analysis posits it as a heavy adjectival modifier that gets right dislocated due to its weight. So basically in transformational terms:

hypothetical:
a [all-its-own] Bart station

right dislocation:
a t1 Bart station [all its own]1

But I'm open to alternatives.

**Comment by manning** [comment]
"own" is a weird word, but I agree with the original post that we should take the first two bullets as correct analyses and the two examples in the 3rd bullet as errors – which I might just run off and correct right now. 

FWIW, there is useful discussion of "own" in section 16.7 of Huddleston and Pullum (2002) – it gets a whole section. Additional notes there include that there are a few expressions where "own" occurs without a possessive like "She scored an own goal" and that "own" can be modified like an adjective in case like "a house of her very own".

**Comment by sylvainkahane** [comment]
It seems like superlatives in French:

> le plus beau livre 'the most beautiful book'
> **le** livre le plus beau, lit. the book the most beautiful

@amir-zeldes When _le plus beau_ is extraposed, a new determiner fills the empty place. Similar with the demotion of a subject: when the subject is extraposed, an expletive subject is introduced:

> To do that is dangerous
> **It** is dangerous to do that

**Comment by amir-zeldes** [comment]
@sylvainkahane - Yes, I think this supports the argument that it is not a possessive in the right dislocated construction, as the article is normal with adjectives anyway, so it just stays there with heavy ones:

A similar book - regular amod
A similar book to the one I read - regular amod, extraposed argument
A book similar to the one I read - extraposed amod + argument, but still amod
