### ISSUE TITLE
Sentence-starting hashmarks

### ISSUE THREAD

**Issue by DavidNemeskey** [UniversalDependencies/docs#642]
While not common, sentences can begin with the hash mark character, or, more likely, a hashtag. This may confuse CoNLL-U parsers. I think it made more sense if comments started with the hash mark AND space characters -- something that never occurs on a token line, since the field delimiter is the tab character.

Incidentally, all the example comments on the [CoNNL-U page](https://universaldependencies.org/format.html) already adhere to the hash mark + space rule.

**Comment by dan-zeman** [comment]
I don't see any possible confusion in the current specification. A line that starts with "#" is a comment line. A natural language sentence can start with "#" but when the sentence is encoded in CoNLL-U, this hash mark will never occur as the first character of a line. On the text metadata comment line, this will be the second hash mark:

<pre># text = # ...</pre>

And on the line describing the first token, the first column contains the numeric node ID:

<pre>1   #   #   SYM   _   _   0   root   _   _</pre>

**Comment by DavidNemeskey** [comment]
Oh, I completely forgot about the numeric node ID! This must be because we are using a CoNLL-U-like format, which lacks that column. So I guess this problem does not affect the regular CoNLL-U format.
