### ISSUE TITLE
Which roles can become orphan?

### ISSUE THREAD

**Issue by lauma** [UniversalDependencies/docs#643]
Is there something like a conclusive list which roles must become orphan in case when the predicate they are dependant of is elided? https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis says following:
> "If the elided element is a predicate and the promoted element is one of its arguments or adjuncts, we use the orphan relation when attaching other non-functional dependents to the promoted head."

Would that mean that all roles from blocks Nominals, Clauses, Modifier words listed  in https://universaldependencies.org/u/dep/index.html are eligible to become `orphan`, i.e., full list would look like this?
* Nominals: core arguments - `nsubj` `obj`, `iobj`
* Clauses: core arguments - `csubj`, `ccomp`, `xcomp`
* Nominals: non-core dependents - `obl`, `vocative`, `expl`, `dislocated`
* Clauses: non-core dependents - `advcl`
* Modifier words: non-core dependents - `advmod`, `discourse`
* Nominals: nominal dependents - `nmod`, `appos`, `nummod`
* Clauses: nominal dependents - `acl`
* Modifier words: nominal dependents - `amod`

The inclusion of `discourse` in this list seems to be excessive, but what about others?

Having such complete list would be very helpfull, when building validation or convertion tools for UD data.

**Comment by dan-zeman** [comment]
No, I do not think such a list exists, at least not with the intention to strictly exclude everything else. You could say that the obliqueness ranking that is mentioned [in the guidelines](https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis-in-clauses) lists dependent types that were foreseen to become orphans: `nsubj > obj > iobj > obl > advmod > csubj > xcomp > ccomp > advcl`.

I also do not think that `discourse` should be included, and I am not sure about `expl`. The relations `vocative` and `dislocated` probably should be included.

On the other hand I am pretty sure that dependents of nominals are excluded: `nmod`, `appos`, `nummod`, `amod`, `acl`. If the modified noun is elided, one of the “orphans” should be promoted as the new head of the noun phrase, and the other orphans are attached to the promoted one via the same relation as if they were attached to the elided noun. They are not attached via `orphan`. The promotion occurs regardless whether the noun phrase is a predicate or not.

**Comment by lauma** [comment]
Thanks! I will tune the convertor code used for Latvian to follow these prelaminary guidelines.

**Comment by dan-zeman** [comment]
Unless there are objections I propose to add `dislocated` and `vocative` to the end of the obliqueness hierarchy [in the guidelines](https://universaldependencies.org/u/overview/specific-syntax.html#ellipsis-in-clauses).

**Comment by jnivre** [comment]
+1
