### ISSUE TITLE
Nominalizations of verb particle constructions

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#648]
In EWT, nominalizations like "set up", "check - out", and "take - out" (with or without a hyphen) are analyzed as N+N compounds headed by the second word. This seems odd because etymologically, the first word is clearly a verbal head.

True noun-noun compounds are normally right-headed (with a couple exceptions in the corpus). Should these particles be an exception? Should they even be classified as nouns?

**Comment by amir-zeldes** [comment]
In GUM we have the first word as the head with `compound:prt` pointing to the particle:

https://corpling.uis.georgetown.edu/annis/#_q=cG9zPSJOTiIgXz1fICJzZXQiIC4gInVwIg&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by nschneid** [comment]
> In GUM we have the first word as the head with `compound:prt` pointing to the particle:

Along with tagging the second word as RP.

This is reminiscent of #462—the question of whether to treat compositional structure differently when a verb is nominalized.

**Comment by nschneid** [comment]
Also in EWT: "Giving __a hand up__" (currently "up" is incorrectly attached as `case` to the following noun)

**Comment by nschneid** [comment]
@omriabnd mentions "to go __belly up__"

**Comment by amir-zeldes** [comment]
+1 for deciding deprel based on function, not the POS tags of the attached tokens
