### ISSUE TITLE
Consistency of corpora in one language VS consistency of parallel corpora

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/docs#652]
These two objectives may be sometimes contradictory, two examples:
 * The English possessives *my*, *its* are tagged `PRON` in all English corpora except **UD_English-ParTUT** where they are tagged `DET` (to be more parallel to other **ParTUT** annotation?)
 * The French possessives *mon*, *son* are tagged `DET` in all French corpora except **UD_French-PUD** where they are tagged `PRON` (to be more parallel to other **PUD** corpora?)

I would prefer to improve intra-language annotation (and then for the examples above, to change annotations in **UD_French-PUD** and **UD_English-ParTUT**).

**Comment by dan-zeman** [comment]
Intra-language consistency should have higher priority. Which of course does not exclude the possibility that 5 English treebanks find out they were wrong, and change their annotation to that used in English ParTUT :-)

PUD is a separate story. Most PUD treebanks were annotated in Google, following Google UD-like annotation guidelines, but not UD directly. A small group of people (incl. me) then converted them to UD and tried to address at least the most striking errors. It is not surprising that some annotation decisions are consistent across PUD and deviate from other UD treebanks of the given languages, but it was not the goal. Everyone, if you find an abandoned PUD treebank in a language you speak, feel free to adopt it and make it consistent with the rest of UD, and primarily with the other UD treebanks for that language.
