### ISSUE TITLE
Tokenization of punctuation inside words

### ISSUE THREAD

**Issue by MathieuDehouck** [UniversalDependencies/docs#655]
Hello,

I am currently annotating a bit of Walloon data following the UD guidelines.
I haven't asked for the Walloon github yet as it is still in the early stage.

Yet, I am facing a tokenisation difficulty. (Truly more than one but heh)

How are we supposed to tokenize words containing punctuation around specific morphemes.

An english example would be something like:
I was trying to fall asleep when my neighbour (re)started to make noise.

I am interested in the tokenization of (re)started.

In walloon, there are a lot of verbs starting in "ri" and I have instances like "(ri)cnoxhît" that means something like recognized and know, maybe like (ac)know(ledge).

Thank you,

**Comment by dan-zeman** [comment]
Maybe the easiest approach would be to keep _(ri)cnoxhît_ as one token and to provide normalized spelling without the brackets in the lemma. But it is also possible to split the prefix, i.e., create four tokens _( ri ) cnoxhît_; only you then also must find a relation type to connect the prefix with the main part of the verb. This problem has been discussed in #224, and the tentative conclusion seems to be that `dep` can be used in these cases.

Also related are issues #443 and #609.

**Comment by sylvainkahane** [comment]
As in a pun, we have two readings of the same word: _ricnoxhît_ and _cnoxhît_. We cannot annotate this properly without introducing a double annotation. I don't think it is good idea to try to annotate writing tricks. We try to annotate the syntax. I suggest to annotate the main reading (_ricnoxhît_) and to possibly encode the other one in a special feature such as `pun=cnoxhît`.

**Comment by amir-zeldes** [comment]
Not sure if this helps in this situations, but in English-GUM we generally annotate as:

1. The form that agreement implies - "friend(s)" gets xpos=NNS if it has plural agreement in context, or NN if it is singular
2. Failing evidence for that distinction, we take the longest form (so friend(s) defaults to NNS, the lemma of (re)blog would be "reblog", etc.)

I agree with @sylvainkahane that fully representing this would require some kind of double annotation, so all we are trying to do with the above is have a guideline for a single analysis, if one is desired.

**Comment by MathieuDehouck** [comment]
Thank you for those insights.

I think I will stick with the one word analysis and lemmatise it as the longest form, in this case ricnoxhî.

This issue might or not be closed, since looking at the three links provided by mr Zeman, there is, it seems, no clear definitive answer.
