### ISSUE TITLE
Subdivided measurement notation: 5'2 or 5'2" meaning "5 feet, 2 inches"

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#659]
*5'2* occurs in English-EWT. How should this be tokenized, tagged, and parsed?

(Similar notation can be used for minutes + seconds, as well as degrees + subdivisions of degrees.)

**Comment by dan-zeman** [comment]
We do not have strict cross-linguistic rules for tokenization. So the tokenization should be made consistent within a corpus and, if possible, a language, although this particular example is not specific to English.

You could treat it as one token (_5'2_ would be similar to _5.2_). Then the question is whether it is OK to tag it `NUM`. I think there has been another thread with a similar issue for dates and times.

If you split it then I think it should be three _(5'2)_ resp. four _(5'2")_ tokens. Then obviously the numbers are `NUM` and the feet/inch symbols are `SYM`. Relations `nummod(', 5)` and `nummod(", 2)` do not seem controversial, either. What remains is the relation between feet and inches. I think `flat(', ")` would be suitable, although I can imagine `conj` as well.

**Comment by amir-zeldes** [comment]
We've had this with degrees in GUM and tokenized the circular 'degree' symbol as the head, with nummod to the amount of degrees. This looks similar to me. I haven't seen the feet and inches case, but I think conj makes the most sense to me there.
