### ISSUE TITLE
Cusco Quechua Directional Suffix

### ISSUE THREAD

**Issue by fjagiell** [UniversalDependencies/docs#660]
Hello,

We are wondering in the conversion of the Squoia treebank for Cusco Quechua what to make the directional suffix +Dir in UD annotation. We considered making it an aspect though it co-occurs with Inchoative aspect at DW-s384. The current idea for annotating it is "Motion=Dir" or "Aktionsart=Dir".

Please let us know if this is a good start or if there is another approach we should take.

Thank you,
Trey Jagiella

**Comment by ftyers** [comment]
@fjagiell could you paste the relevant sentence here (with the translation), people may not know where to find the Squoia treebank. Btw, [this](https://core.ac.uk/download/pdf/16105757.pdf) is a potentially interesting discussion, they propose a '+/- Motion' feature on verbs in Quechua.

**Comment by fjagiell** [comment]
The sentence is "Kirguizistán -pi internet -manta ñawpaq ka -q seminario -qa ancha yachaqari -qkuna -paq hina -m ka -rqan ." The Spanish translation is "El primer seminario de internet en Kirguizistán fue una experiencia muy constructiva ." Since I do not speak Spanish, this is what Google translate is outputting from Spanish to English: "The first internet seminar in Kyrgyzstan was a very constructive experience." Seems like a decent translation.

**Comment by ftyers** [comment]
Ok, so that is:

```
# sent_id = DW-s384
# text = Kirguizistán -pi internet -manta ñawpaq ka -q seminario -qa ancha yachaqari -qkuna -paq hina -m ka -rqan . 
# text[spa] = El primer seminario de internet en Kirguizistán fue una experiencia muy constructiva .
1	Kirguizistán	_	Root	Root	NP	2	s.arg	_	_
2	-pi	_	Cas	Cas	+Loc	16	loc	_	_
3	internet	_	Root	Root	NRootES	4	s.arg	_	_
4	-manta	_	Cas	Cas	+Abl	8	mod	_	_
5	ñawpaq	_	Root	Root	NRoot	6	pred	_	Gloss=antes
6	ka	_	Root	Root	VRoot	8	mod	_	Gloss=ser
7	-q	_	NS	NS	+Ag	6	ns	_	_
8	seminario	_	Root	Root	NRootES	16	subj	_	_
9	-qa	_	Amb	Amb	+Top	8	topic	_	_
10	ancha	_	Root	Root	NRoot	11	mod	_	Gloss=muy,mucho
11	yachaqari	_	Root_VDeriv_VDeriv	Root_VDeriv_VDeriv	VRoot|+Dir|+Inch	13	s.arg.claus	_	Gloss=saber
12	-qkuna	_	NS_Num	NS_Num	+Ag|+Pl	11	ns	_	_
13	-paq	_	Cas	Cas	+Ben	14	p.arg	_	_
14	hina	_	Root	Root	Part_Sim	16	comp	_	_
15	-m	_	Amb	Amb	+DirE	16	ev	_	_
16	ka	_	Root	Root	VRoot	0	sntc	_	Gloss=ser
17	-rqan	_	Tns_VPers	Tns_VPers	+NPst|+3.Sg.Subj	16	s.subj	_	_
18	.	_	$.	$.	_	16	punc	_	_
```

So the relevant word here is `yachaqariqkunapaq`, and the tree looks something like:
![Captura de 2019-10-23 02-09-46](https://user-images.githubusercontent.com/449545/67347510-381f6280-f53a-11e9-954d-881dc993f8a3.png)

If I understand correctly:
```
11	yachaqari	_	Root_VDeriv_VDeriv	Root_VDeriv_VDeriv	VRoot|+Dir|+Inch	13	s.arg.claus	_	Gloss=saber
12	-qkuna	_	NS_Num	NS_Num	+Ag|+Pl	11	ns	_	_
13	-paq	_	Cas	Cas	+Ben	14	p.arg	_	_
```
* yachaqari is a root with two derivations, this `motion` derivation and an inchoative derivation "start to X"
* to this is attached some kind of nominalising suffix (agentive plural?) 
* to which is attached the benefactive case
* the whole expression is a `p.arg` (postpositional argument == adverbial clause?) to `hina-m`

Given that those things are the case, I might suggest something like:

```
11	yachaqariqkunapaq	_	VERB	_	Aspect=Inch|Case=Ben|Motion=Dir|VerbForm=Vnoun	12	advcl	_	Gloss=saber
```

But questions remain:
* What is the `+Ag|+Pl`
* Should 'Inchoative' be an aspect?
* What kind of nominaliser is `NS_Num` ?

**Comment by fjagiell** [comment]
Since it appear the agentive +Ag, is not a case but rather a type of nominalizer. Is there an annotation the already exists in UD or should we create something along the lines of Nominalizer=Ag?

**Comment by dan-zeman** [comment]
I am not aware of an existing UD feature suitable to capture this. (Although you may want to use something like `VerbForm=Vnoun` in addition to `Nominalizer=Ag`.)

**Comment by ftyers** [comment]
In UD_Finnish-TDT there is `Derivation=`, e.g.

```
UD_Finnish-TDT/fi_tdt-ud-train.conllu:71154:11	heräämisen	herääminen	NOUN	N	Case=Gen|Derivation=Minen|Number=Sing	12	nmod:poss	_	_
```

And in Komi:
```
UD_Komi_Zyrian-Lattice/kpv_lattice-ud-test.conllu:745:3	жалиттӧг	жалитны	VERB	V	Derivation=Tog|Polarity=Neg|VerbForm=Conv	4	advcl	_	_
```

Of course the question is then what happens if there is more than one nominaliser in the same token? @fjagiell are there any examples of more than one nominaliser for a single token?
