### ISSUE TITLE
The info page for Maltese UD

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/docs#662]
Two issues with https://universaldependencies.org/mt/index.html:
1. It claims to pertain to v1, that is incorrect.
2. The formatting is broken.
Is there something I can do to fix it?

**Comment by dan-zeman** [comment]
The Markdown header must contain the line

udver: '2'

You had "2.4" instead of "2" there, which does not work. 2.4 is release number of data, not version of guidelines.

**Comment by dan-zeman** [comment]
See also here:
https://universaldependencies.org/contributing_language_specific.html
and here:
https://universaldependencies.org/contributing.html

The second link has some info on Markdown syntax which may help with the broken formatting.

**Comment by bulbulistan** [comment]
I fixed the second table, looks ok in https://github.com/UniversalDependencies/docs/blob/pages-source/_mt/index.md.
