### ISSUE TITLE
Predicate ellipsis (and comparison) with orphaned SCONJ

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/docs#663]
In Maltese, we have a few examples of this type of ellipsis:
![23b_04J03-18](https://user-images.githubusercontent.com/18728008/67517003-f4476d00-f6a1-11e9-8b20-bf053e48ded1.png)
Gloss: _one favors more DOM_DEF- singer /than/ DEF- song_
Translation: "One favors the singer more than the song."

The problem here is the word 'milli' (glossed as /than/) which is a subordinating conjunction and thus generally to be attached as `mark`, which I did above and it does not seem right. Does anybody have a suggestion what to do in cases like this? Thank you.

**Comment by dan-zeman** [comment]
case(kanzunetta, milli)
obl(aktar, kanzunetta)

See also https://universaldependencies.org/u/overview/specific-syntax.html#comparatives

**Comment by bulbulistan** [comment]
Thank you.
