### ISSUE TITLE
+Cont (Continuative) in Cusco Quechua

### ISSUE THREAD

**Issue by fjagiell** [UniversalDependencies/docs#665]
Hello,

In trying to determine the way to convert +Cont (Continuative), we are thinking of making it listed as a feature Aspect=Cont. Given the example below, does this seem a plausible representation within the UD framework?

Thank you!

Spanish Translation: A muchas empresas peruanas aún les falta aprovechar este servicio que ofrece la Cámara .
English Translation: Many Peruvian companies still have not take advantage of this service offered by the Chamber.
```
# sent_id = ahk1968-2008_qu-s265
# text = Perú -manta achkha empresakuna -m mana -raq kay Cámara ni -sqa -pa yanapa -ku -y -nin haywari -ku -sqa -n -man taripa -nku -raq -chu 
1	Perú	_	Root	Root	NP	2	s.arg	_	_
2	-manta	_	Cas	Cas	+Abl	4	mod	_	_
3	achkha	_	Root	Root	NRoot	4	mod	_	Gloss=mucho
4	empresakuna	_	Root_Num	Root_Num	NRootES|+Pl	22	subj	_	_
5	-m	_	Amb	Amb	+DirE	22	ev	_	_
6	mana	_	Root	Root	Part_Neg	22	neg	_	_
7	-raq	_	Amb	Amb	+Cont	6	mod	_	_
8	kay	_	Root	Root	PrnDem	10	det	_	_
9	Cámara	_	Root	Root	NRootES	10	flm	_	_
10	ni	_	Root	Root	VRoot	12	s.arg.claus	_	Gloss=decir
11	-sqa	_	NS	NS	+Perf	10	ns	_	_
12	-pa	_	Cas	Cas	+Gen	13	poss.subj	_	_
13	yanapa	_	Root_VDeriv	Root_VDeriv	VRoot|+Rgr_Iprs	17	obj	_	Gloss=servir,ayudar
14	-ku	_	VDeriv	VDeriv	+Rflx_Int	13	mod	_	_
15	-y	_	NS	NS	+Inf	13	ns	_	_
16	-nin	_	NPers	NPers	+3.Sg.Poss	15	s.poss.subj	_	_
17	haywari	_	Root_VDeriv	Root_VDeriv	VRoot|+Inch	21	s.arg.claus	_	Gloss=alcanzar
18	-ku	_	VDeriv	VDeriv	+Rflx_Int	17	mod	_	_
19	-sqa	_	NS	NS	+Perf	17	ns	_	_
20	-n	_	NPers	NPers	+3.Sg.Poss	19	s.poss.subj	_	_
21	-man	_	Cas	Cas	+Dat_Ill	22	iobj	_	_
22	taripa	_	Root_VDeriv	Root_VDeriv	VRoot|+Rep	0	sntc	_	Gloss=encontrar
23	-nku	_	VPers	VPers	+3.Pl.Subj	22	s.subj	_	_
24	-raq	_	Amb	Amb	+Cont	22	mod	_	_
25	-chu	_	Amb	Amb	+Intr_Neg	22	s.neg	_	_
```
![image](https://user-images.githubusercontent.com/46580428/67809082-705cfe80-fa6e-11e9-804b-7c1df2c1128d.png)

**Comment by ftyers** [comment]
It appears that this suffix can also be used with nouns (from "The Cusco Quechua Reportative Evidential and Rhetorical Relations "):

```
(9) b.  Lima-man-raq-si yawar-ni-n-pis ri-n.     
Lima-ILLA-CONT-REP blood-EUPH-3-ADD go-3  
   ‘Her blood even went to Lima.’ 
```

and from Wiktionary, [-raq](https://en.wiktionary.org/wiki/-raq):

```
    Aqha kanraqchu?
    Chicha there.is-CONT-QST?
        "Is there still chicha?"
```

**Comment by dan-zeman** [comment]
If it is aspect, perhaps you could use `Aspect=Prog`, which already exists in UD. I think I have seen the terms continuous/continuative and progressive used for similar things.

[https://universaldependencies.org/u/feat/Aspect.html#Prog](https://universaldependencies.org/u/feat/Aspect.html#Prog)

**Comment by ftyers** [comment]
@dan-zeman I think `Aspect=Prog` is taken by another morpheme already, e.g. [*-chka*](https://en.wiktionary.org/wiki/-chka). Although I'm not sure of the precise semantic/syntactic/morphotactic differences between the two ... e.g. not sure if *-chka* can also go on nouns, like *-raq*. @fjagiell can you check?

**Comment by fjagiell** [comment]
From what I have seen, the -chka is only going on verbs, while -raq is primarily nouns but limited to them.

**Comment by dan-zeman** [comment]
Note that it is not necessary to invent a new feature for every suffix if the suffixes do not apply to the same word. And even if they do apply to the same word, one should ask what are the differences in usage of the suffixes by speakers. Is it really a different aspect meaning, or is it something else, e.g., colloquial register?
