### ISSUE TITLE
Speaker information and quotation attribution

### ISSUE THREAD

**Issue by amir-zeldes** [UniversalDependencies/docs#667]
I'm wondering if anyone has a good way of representing speaker information for **part** of a sentence. We're already using comments like these for whole sentences:

```
# sent_id = GUM_interview_gaming-4
# text = Heaven Sent Gaming is basically me and Isabel, I'm Mario J. Lucero.
# s_type=decl
# speaker=MarioJLucero
1	Heaven	heaven	PROPN	NNP	Number=Sing	2	compound	_	_
2	Sent	send	PROPN	NNP	Number=Sing	3	compound	_	_
3	Gaming	gaming	PROPN	NNP	Number=Sing	6	nsubj	_	_
4	is	be	AUX	VBZ	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	6	cop	_	_
5	basically	basically	ADV	RB	_	6	advmod	_	_
6	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	0	root	_	_
7	and	and	CCONJ	CC	_	8	cc	_	_
8	Isabel	Isabel	PROPN	NNP	Number=Sing	6	conj	_	SpaceAfter=No
9	,	,	PUNCT	,	_	12	punct	_	_
10	I	I	PRON	PRP	Case=Nom|Number=Sing|Person=1|PronType=Prs	12	nsubj	_	SpaceAfter=No
11	'm	be	AUX	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	12	cop	_	_
12	Mario	Mario	PROPN	NNP	Number=Sing	6	parataxis	_	_
13	J.	J.	PROPN	NNP	Number=Sing	12	flat	_	_
14	Lucero	Lucero	PROPN	NNP	Number=Sing	12	flat	_	SpaceAfter=No
15	.	.	PUNCT	.	_	6	punct	_	_
```

But for some sentences, especially in fiction, even though we have speaker information, we can't represent it as a sentence annotation for the whole sentence:

```
# sent_id = GUM_fiction_rose-27
# text = "You 're ashamed of me," he guessed, and Rachel kissed him and smiled and didn't say anything.
# s_type=decl
1	"	''	PUNCT	``	_	4	punct	_	SpaceAfter=No
2	You	you	PRON	PRP	Case=Nom|Person=2|PronType=Prs	4	nsubj	_	_
3	're	be	AUX	VBP	Mood=Ind|Tense=Pres|VerbForm=Fin	4	cop	_	_
4	ashamed	ashamed	ADJ	JJ	Degree=Pos	10	parataxis	_	_
5	of	of	ADP	IN	_	6	case	_	_
6	me	I	PRON	PRP	Case=Acc|Number=Sing|Person=1|PronType=Prs	4	obl	_	SpaceAfter=No
7	,	,	PUNCT	,	_	4	punct	_	SpaceAfter=No
8	"	''	PUNCT	''	_	4	punct	_	_
9	he	he	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3|PronType=Prs	10	nsubj	_	_
10	guessed	guess	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	0	root	_	SpaceAfter=No
11	,	,	PUNCT	,	_	14	punct	_	_
12	and	and	CCONJ	CC	_	14	cc	_	_
13	Rachel	Rachel	PROPN	NNP	Number=Sing	14	nsubj	_	_
14	kissed	kiss	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	10	conj	_	_
15	him	he	PRON	PRP	Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs	14	obj	_	_
16	and	and	CCONJ	CC	_	17	cc	_	_
17	smiled	smile	VERB	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	14	conj	_	_
18	and	and	CCONJ	CC	_	21	cc	_	_
19	did	do	AUX	VBD	Mood=Ind|Tense=Past|VerbForm=Fin	21	aux	_	SpaceAfter=No
20	n't	not	PART	RB	Polarity=Neg	21	advmod	_	_
21	say	say	VERB	VB	VerbForm=Inf	14	conj	_	_
22	anything	anything	NOUN	NN	Number=Sing	21	obj	_	SpaceAfter=No
23	.	.	PUNCT	.	_	10	punct	_	_
```

Even though we know who the speaker of tokens 1-8 is, we have no good way of expressing it in conllu. This is complicated by the fact that a single sentence might have multiple speakers in different parts. Any thoughts on how to represent speaker information for sentence parts would be appreciated!

**Comment by nschneid** [comment]
CoNLL-U doesn't place any formal constraints on values in these extra comments, right? Maybe

    # speaker=Narrator,1-8:QuotedGuy

**Comment by martinpopel** [comment]
We use a special extension of CoNLL-U which allows to add JSON-formatted attributes in the CoNLL-U comments.
See [this file](https://github.com/udapi/udapi-python/blob/master/udapi/core/tests/data/babinsky.conllu) for an example.
We use it for Named Entity Recognition and Linking, but it could be used for marking any sets of nodes and extra information which would be cumbersome to store in the MISC field.
"Note that the utterance", Martin says, "may be split into several parts, so we cannot use a plain range such as 1-8 in general".

[Udapi](https://github.com/udapi/udapi-python) supports this JSON extension, i.e. it deserializes any comments with name "json_*" (for sentence-level attributes) and "doc_json_*" (for document-level) attributes when [loading CoNLL-U](https://github.com/udapi/udapi-python/blob/master/udapi/block/read/conllu.py) and serializes when [writing](https://github.com/udapi/udapi-python/blob/2c39b23/udapi/block/write/conllu.py#L39-L42).

**Comment by amir-zeldes** [comment]
That's interesting, thanks! I think the split speech case could be handled the same as the multiple speakers case, in which case something like @nschneid 's suggestion works:

```
# text = "Note that the utterance", Martin says, "may be split into several parts, so we cannot use a plain range such as 1-8 in general"
# speaker = MartinPopel[1-6]; Narrator[7-10]; MartinPopel[11-33]
...
```

In practice we don't notate the narrator (='no speaker'), but format-wise this seems the simplest. I'll keep the json in mind though, that could come in handy for more complex annotation layers we have in parallel.

**Comment by ftyers** [comment]
Wouldn't it also be possible to put it in the `Misc` column ? e.g. for every token have a `Speaker=MartinPopel` or `Speaker=Narrator`? And if *n* people were saying the same thing at the same time you could have `Speaker=MartinPopel,Narrator`

**Comment by amir-zeldes** [comment]
@ftyers Token-wise annotations are also possible, but seem a little spammy - I'm just a little worried there will be such a monster of text on each line that basic annotations might become unreadable. For GUM we have a huge amount of annotations, but they mostly live in other files, so it's really a question of how much to inject into the conllu files and how to represent it in the least annoying way :)
