### ISSUE TITLE
New validation rules and UD_Old_Russian-TOROT

### ISSUE THREAD

**Issue by hanneme** [UniversalDependencies/docs#668]
I very belatedly had a look at the validation page, and see that UD_Old_Russian-TOROT is no longer valid. We haven't changed the contents in dev at all since the last release, so this must be due mostly to new validation rules for orphans, which rightly uncover some problems with our conversion. Unfortunately I won't have the time to fix the conversion script before the data freeze, so I wonder what happens if I do nothing. Do I understand it correctly that the May release (warts and all) would be included in the November release? If not I could probably manage to weed the sentences with errors out of our files before the data release (there are many errors, but limited to a handful of sentences).

I also notice that не.быти must have been taken out of the list of Old Russian copulae, probably because of the incorporated negation? But it must have been in last time, as the treebank came out as valid then, and dev is unchanged.

**Comment by jnivre** [comment]
If you haven't changed anything since the last release, your treebank will be regarded as a "legacy treebank" and will be included in the release. More information here: https://universaldependencies.org/validation-rules.html

**Comment by dan-zeman** [comment]
Well, actually, legacy treebanks are 2.3 and older, so we have a problem with Old Russian, which only appeared in 2.4. The "orphan-parent" error is an exception: the test was introduced after 2.4, so even 2.4 treebanks are considered legacy if this is their only error.

**Comment by jnivre** [comment]
Oops, sorry. Thanks for correcting me, Dan.

**Comment by hanneme** [comment]
The vast majority of errors are the orphan ones, but as I mentioned I also get an error for sentences with 'не.быти' as aux-lemma. This must mean that 'не.быти' is out of the copula list, I think, probably because you would want me to do the negation as a feature rather than operating with a separate lemma? I would probably just be able to fix this before the data freeze, if that would allow the treebank to be released.

**Comment by dan-zeman** [comment]
I will try to look at the auxiliaries tonight when I get to the hotel. In the meantime, @hanneme and @olesar, could you please edit the template and create the language-specific documentation, which is another complaint by the validator? Thanks!

**Comment by dan-zeman** [comment]
@hanneme : The validator actually contains the negated copula as a separate lemma, but (per your e-mail request from 29 April) it is spelled with a space, not with a period:

<pre>
orv: ['быти', 'не быти']
</pre>

So maybe we can change the lemma in the treebank now? @olesar, does this occur in your Old Russian corpus too? If so, how is the lemma spelled there? I could not find examples.

In the long run, as I mentioned in an e-mail to @hanneme in April, I think it would be better to include the negative forms under the lemma _быти_ and distinguish them with the feature `Polarity=Neg`.

**Comment by hanneme** [comment]
Sure, I'll change it in the treebank now, and next time around I'll do it with the polarity feature instead.

**Comment by olesar** [comment]
hi, we only have быти as a lemma for нѣсмь etc.

**Comment by hanneme** [comment]
I changed the lemmas to не быти now, but apparently it needs to be on a list of exceptions allowed to contain whitespace. 

[Line 11737 Sent 127082]: [L4 Format invalid-word-with-space] 'не быти' in column LEMMA is not on the list of exceptions allowed to contain whitespace (data/tokens_w_space.LANG files).

**Comment by olesar** [comment]
@hanneme, you can add the file tokens_w_space.orv here https://github.com/UniversalDependencies/tools/tree/master/data

**Comment by dan-zeman** [comment]
I have created the exception file and the "invalid-word-with-space" errors have disappeared. So the remaining item that keeps both the Old Russian treebanks red is the language-specific documentation. Could you provide it for this release please? See [http://universaldependencies.org/contributing_language_specific.html](http://universaldependencies.org/contributing_language_specific.html) for instructions.

**Comment by hanneme** [comment]
Thank you! I've started on the language-specific documentation now, but I
can of course only speak for TOROT – @olesar should also have a look.

Best wishes,

Hanne

søn. 3. nov. 2019 kl. 05:51 skrev Dan Zeman <notifications@github.com>:

**Comment by hanneme** [comment]
I'm now done with the TOROT part of the documentation (it's quite brief and I aim to expand it for later releases). I changed the file name to index.md but left the instructions in for the benefit of @olesar

**Comment by dan-zeman** [comment]
Great, thanks!
