### ISSUE TITLE
Features  in Language that are not in UD

### ISSUE THREAD

**Issue by fjagiell** [UniversalDependencies/docs#670]
Hello,

There are several features in the Cusco Quechua Squoia treebank we are converting, which do not have features in UD v2 according to https://universaldependencies.org/v2/features.html . These features are focus (FOC), topic (TOP), different subject (DS), and same subject (SS). These features are all referred to on the page linked above but there is no specific UD annotation for them. Would it be preferable to keep the features as listed in the parentheses or come up with something else that generally fits in more with the UD style?

Thank you!

**Comment by ftyers** [comment]
@fjagiell could you give example sentences for each of the features you are asking about. In addition to the original trees and translations?

**Comment by fjagiell** [comment]
For +Top:
Spanish: La DW-AKADEMIE es el centro internacional de la Deutsche Welle para el desarrollo de medios , asesoría de medios y capacitación periodística . 
English: DW-AKADEMIE is the international center of the Deutsche Welle for media development, media consulting and journalistic training.
 ```
# sent_id = DW-s28
# text = DW-AKADEMIE ni -sqa -qa Deutsche Welle -p tiqsimuyu chawpi -n -mi KAN . 
1	DW-AKADEMIE	_	Root	Root	NP	2	flm	_	_
2	ni	_	Root	Root	VRoot	12	subj	_	Gloss=decir
3	-sqa	_	NS	NS	+Perf	2	ns	_	_
4	-qa	_	Amb	Amb	+Top	2	topic	_	_
5	Deutsche	_	FLM	FLM	_	6	nme	_	_
6	Welle	_	FLM	FLM	_	7	s.arg	_	_
7	-p	_	Cas	Cas	+Gen	9	poss	_	_
8	tiqsimuyu	_	Root	Root	NRoot	9	mod	_	Gloss=globo,tierra,mundo
9	chawpi	_	Root	Root	NRoot	12	pred	_	Gloss=centro,mitad
10	-n	_	NPers	NPers	+3.Sg.Poss	9	s.poss	_	_
11	-mi	_	Amb	Amb	+DirE	12	ev	_	_
12	KAN	_	DUMMY	DUMMY	_	0	sntc	_	_
13	.	_	$.	$.	_	0	punc	_	_
```

**Comment by fjagiell** [comment]
For +Foc
Spanish: Sólo pasado este plazo se puede sacar dinero sin intereses .
English: Only after this period can you get money without interest.
```
# sent_id = DW-s120
# text = Kay plazo pasa -pti -lla -n -mi qullqi -qa mana interés -niyuq hurqu -sqa ka -nman . 
1	Kay	_	Root	Root	PrnDem	2	det	_	_
2	plazo	_	Root	Root	NRootES	3	subj	_	_
3	pasa	_	Root	Root	VRootES	15	sub	_	_
4	-pti	_	NS	NS	+DS	3	ns	_	_
5	-lla	_	Amb	Amb	+Lim_Aff	3	mod	_	_
6	-n	_	NPers	NPers	+3.Sg.Poss	4	s.poss.subj	_	_
7	-mi	_	Amb	Amb	+DirE	15	ev	_	_
8	qullqi	_	Root	Root	NRoot	15	subj	_	Gloss=plata
9	-qa	_	Amb	Amb	+Top	8	topic	_	_
10	mana	_	Root	Root	Part_Neg	11	neg	_	_
11	interés	_	Root	Root	NRootES	12	s.arg	_	_
12	-niyuq	_	NDeriv	NDeriv	+Poss	13	mod	_	_
13	hurqu	_	Root	Root	VRoot	15	pred	_	Gloss=sacar
14	-sqa	_	NS	NS	+Perf	13	ns	_	_
15	ka	_	Root	Root	VRoot	0	sntc	_	Gloss=ser
16	-nman	_	VPers_Mod	VPers_Mod	+3.Sg.Subj|+Pot	15	s.subj	_	_
17	.	_	$.	$.	_	0	punc	_	_
```

**Comment by fjagiell** [comment]
The previous should have read for +DS
For +SS:
Spanish: Cuando pensamos en los últimos 40 años , tenemos muchas razones para llenarnos de orgullo . 
English: When we think about the last 40 years, we have many reasons to be proud.
```
# sent_id = ahk1968-2008_qu-s4
# text = Kay ñawpaq 40 watakuna -ta yuyaymana -spa -qa , achkha imaymanakuna -m kapu -wa -nchik kusi -ku -na -nchik -paq -qa . 
1	Kay	_	Root	Root	PrnDem	4	det	_	_
2	ñawpaq	_	Root	Root	NRoot	4	mod	_	Gloss=antes
3	40	_	Root	Root	NRootNUM	4	qnt	_	_
4	watakuna	_	Root_Num	Root_Num	NRoot|+Pl	5	s.arg	_	Gloss=año
5	-ta	_	Cas	Cas	+Acc	6	obj	_	_
6	yuyaymana	_	Root_VDeriv	Root_VDeriv	VRoot|+Rem	13	sub	_	Gloss=recordar,pensar
7	-spa	_	NS	NS	+SS	6	ns	_	_
8	-qa	_	Amb	Amb	+Top	6	topic	_	_
9	,	_	$.	$.	_	0	punc	_	_
10	achkha	_	Root	Root	NRoot	11	mod	_	Gloss=mucho
11	imaymanakuna	_	Root_Num	Root_Num	NRoot|+Pl	13	subj	_	Gloss=toda_clase_de,todos
12	-m	_	Amb	Amb	+DirE	13	ev	_	_
13	kapu	_	Root_VDeriv	Root_VDeriv	VRoot|+Rgr_Iprs	0	sntc	_	Gloss=ser
14	-wa	_	VPers	VPers	+1.Obj	13	s.obj	_	_
15	-nchik	_	VPers	VPers	+3.Subj_1.Pl.Incl.Obj	13	s.subj_obj	_	_
16	kusi	_	Root	Root	VRoot	20	s.arg.claus	_	Gloss=alegrar
17	-ku	_	VDeriv	VDeriv	+Rflx_Int	16	mod	_	_
18	-na	_	NS	NS	+Obl	16	ns	_	_
19	-nchik	_	NPers	NPers	+1.Pl.Incl.Poss	18	s.poss.subj	_	_
20	-paq	_	Cas	Cas	+Ben	13	purp	_	_
21	-qa	_	Amb	Amb	+Top	16	topic	_	_
22	.	_	$.	$.	_	0	punc	_	_
```
I cannot find anything with +Foc so we can ignore that one.

**Comment by amir-zeldes** [comment]
If we introduce a feature `Focus=Yes`, it could also be used for the Coptic focus marker (`xpos=CFOC`). I imagine `Topic=Yes` could be used for Japanese and similar languages.

**Comment by dan-zeman** [comment]
> Would it be preferable to keep the features as listed in the parentheses or come up with something else that generally fits in more with the UD style?

If it is in the FEATS column, it must fit with the UD style. So it cannot be just "FOC" but it can be "Focus=Yes". Sometimes you may find inspiration for features that are not universally defined but they are used in one or more treebanks, here: [https://universaldependencies.org/ext-feat-index.html](https://universaldependencies.org/ext-feat-index.html). We now have a `FocType` feature in Wolof but none of the languages use simple `Topic=Yes` or `Focus=Yes`. Not even Japanese or Tagalog.
