### ISSUE TITLE
Writing direction of each language

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/docs#675]
I cannot find in corpora descriptions or in language descriptions the writing direction.

I need this information for a correct display in the [Grew-match](http://match.grew.fr) tool.
It is now available on the 2.5 data and the following languages are displayed from right to left:
 * Arabic
 * Assyrian
 * Hebrew
 * Persian
 * Urdu
 * Uyghur

All other languages are displayed from left to right. Can someone confirm that is correct?

Maybe, this information should be recorded in the `Machine-readable metadata` part of the README.

**Comment by dan-zeman** [comment]
This sounds good to me.

**Comment by dan-zeman** [comment]
As for listing it in the README it may a bit overkill, although it is possible that some language in the future will have two treebanks, each using a different writing system.

**Comment by ftyers** [comment]
You could also use the information from CLDR, e.g. https://github.com/unicode-org/cldr/blob/master/common/supplemental/supplementalData.xml 

```
<language type="mn" scripts="Cyrl" territories="MN"/>
<language type="mn" scripts="Mong Phag" territories="CN" alt="secondary"/>
```
= Mongolian Cyrillic / Mongolian Mongolian script. Cyrl is LTR, Mongolian is TTB.

I second making the script(s) part of the machine-readable metadata. I could definitely see an arabizi treebank etc. Although I wonder if it should be more on a per-sentence basis

**Comment by dan-zeman** [comment]
In fact you can have even mixed sentences where some tokens are LTR and some are RTL. Not sure what that means for a tree visualizer, though. I think a tool should analyze the text, learn what the prevailing script is, then look it up in the Unicode tables and decide. We do not have to copy the Unicode standard in our metadata.

**Comment by dan-zeman** [comment]
I am inclined to close this issue now because there does not seem to be a coherent proposal for the next steps (although there is a number of possible options). If anyone volunteers to design and implement a change, feel free to reopen.
