### ISSUE TITLE
Multiple values for a single feature

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#677]
We're working with Mapudungun at the moment and are coming across some issues with how to encode the category of `Aspect`. We have the example *miawkelayaymi* `miaw-ke-la-ya-y-m-i` "you must not wander":
 
The gloss is:
```
wander-HAB14-neg10-IMP9-ind4-23-sg2       wander-HAB-NEG-IMP-IND-SG2
```
HAB = habitual
IMP = imperfective

The prohibition is habitual, but the action of ambulation is imperfective.

Some options:
* `Aspect=Imp|Aspect[neg]=Hab`
* `Aspect=HabImp`
* `Aspect[1]=Hab|Aspect[2]=Imp`

Any other suggestions?

**Comment by dan-zeman** [comment]
I think I'd support something along the lines of

`Aspect=Imp|Aspect[neg]=Hab`

although I suspect that there might be other candidate labels for the `neg` layer. It depends on the nature of other possible examples of double aspect.

**Comment by elejalea** [comment]
I also work in this Mapudungun project. We have not regarded all the existing uses so far. Probably there would appear a verbal form with both positive aspects. So there will be no distinction between them. That is why Fran suggests the third option
> Aspect[1]=Hab|Aspect[2]=Imp

**Comment by ftyers** [comment]
Well, it's one of the suggestions, it's a bit "un-UD" as these subcategories should ideally refer to something that is not a position indicator. I remember in previous discussions about Turkic that these kind of position indicators were unpreferred. I included it for completeness, because I have a feeling that at some point we will need to revisit it. 

Are there any examples of three or more Aspect markers in a single word? And is it possible to somehow pick out all of the examples of double aspect? It might be easier to come up with ideas if we have a more complete typology of the situations in which it can occur.

**Comment by jheinecke** [comment]
I think, this is an example where we must distinguish  between Aspect and Aktionsart. Where as Aspect is the view onto the event  as perfective or imperfective (ongoing) and expressed by the speaker, Aktionsart describes the type of the action (punctual, inchoative, terminative, telic, atelic... the list seems endless depending on the linguists) and is verb inherent. Some Aktionsart changes with some aspect can change the Aktionsart, so a punctual verb like "cough" becomes iterative when used with the imperfective Aspect. 
For instance, French _attraper_ ("to hunt down") has a telic Aktionsart, whereas chasser_ ("hunt") is atelic. Both can be combined with imperfective or perfective Aspect (roughly expressed in French using Passé Composé (perfective) or Imparfait (imperfective). Aktionsart is marked by morphems as it looks in Mapudungun, I think we need different features for this
