### ISSUE TITLE
git clone command line: minor issue

### ISSUE THREAD

**Issue by savary** [UniversalDependencies/docs#680]
I think there is a minor issue at the UD page on format validation (https://universaldependencies.org/release_checklist.html#validation)
There is

$ git clone git@github.com:UniversalDependencies/tools.git

When I run it I get: _fatal: Could not read from remote repository._
I think it should be

$ git clone https://github.com/UniversalDependencies/tools.git

**Comment by akoehn** [comment]
The clone works if you save your public ssh key in your github profile, so it is not strictly an error (and using ssh is superior to https for git in my opinion).  OTOH, the https URL is also usable without a github account.

**Comment by dan-zeman** [comment]
I agree with Arne. Cloning a Github repository without a Github account may be useful in other contexts, but a maintainer of a UD treebank needs the account anyway.
