### ISSUE TITLE
Sentence-level features?

### ISSUE THREAD

**Issue by DavidNemeskey** [UniversalDependencies/docs#681]
CoNLL-U is a great format for representing the training data and output of syntactic parsers and token classifiers. However, reading the specification, I did not find anything about sentence (paragraph, document)-level features. Examples that come to mind are sentiment, topic, genre... Is there an official way in CoNLL-U(+) to record these properties?

I am asking this because we have a pipeline that outputs CoNLL-U, and I would like to add sentiment classification to it. My idea is to use comments (since I already use `newdoc`, `newpar`, `text`, etc.), so something like `# sentiment = positive` would work perfectly fine. However, it would be nice if there was an official way to declare these features, similar to e.g. how columns are declared in U Plus. Such as: `# global.sentence_features = sentiment`.

**Comment by dan-zeman** [comment]
Sentence-level comments are the (only) means to store annotation that pertains to one or more sentences. UD does not aspire to replace projects like TEI-XML and to address every possible type of corpus annotation, so you are on your own. Nevertheless, if you produce a dataset that provides a new annotation layer for a substantial number of UD treebanks, it may be useful for the community if you let us know and we link back to the resource from the UD website.

**Comment by arademaker** [comment]
We have some open discussions about extensions for the CoNLL-U. See #562, #412 and #344.

**Comment by arademaker** [comment]
The main reference for TEI is https://tei-c.org, right @dan-zeman ?

**Comment by dan-zeman** [comment]
> The main reference for TEI is https://tei-c.org, right @dan-zeman ?

Seems so :-)
