### ISSUE TITLE
Wrong flag

### ISSUE THREAD

**Issue by abrarum** [UniversalDependencies/docs#682]
Hi. I was just surfing about the semantics and universal dependencies and found out that the developer has used a wrong flag against the language Urdu. The flag should be of Pakistan instead of India.

ref: https://universaldependencies.org/

Thanks.

**Comment by bulbulistan** [comment]
Speaking of, the Iraqi flag for Akkadian is also a bit off, especially considering that e.g. Coptic does not display the flag of Egypt, nor does Classical Chinese fly the PRC flag. The Assyrian royal seal is probably the closest thing to a flag that could be used here, e.g. https://research.britishmuseum.org/research/collection_online/collection_object_details/collection_image_gallery.aspx?partid=1&assetid=894662001&objectid=370305 (the image is available under CC BY-NC-SA 4.0).

**Comment by dan-zeman** [comment]
> language Urdu. The flag should be of Pakistan instead of India

Yeah both would work (as Urdu is used in both countries) but at present the only data we have in UD comes from India. The disclaimer on the title page says that the flags are just a visual enhancement, not a political statement of any sort. In the [language specific documentation](https://universaldependencies.org/ur/index.html) there is enough space for multiple flags and both flags are present.

**Comment by Delta-Sigma** [comment]
I'm sorry but I would ask you to reconsider the idea of the origin of data coming from somewhere. I understand it's not a political statement, but surely this is not a contentious issue? If data for French was coming from Canada, or for German from Switzerland, should there be Canadian and Swiss flags respectively for French and German?
