### ISSUE TITLE
Locative vs prepositional cases in Russian 

### ISSUE THREAD

**Issue by omagolda** [UniversalDependencies/docs#685]
It seems like on the morphological tagging in Russian the tag `Case=Loc` is used for both the prepositional case and the locative case. The actual locative case is rarer and does not exist for many nouns, but it still can create some problems.

For example, both "гробе" and "гробу" are marked as locative, although the former is prepositional.

Did I miss anything that justifies this treatment? (I'm not native in Russian)

**Comment by olesar** [comment]
What kind of tag do you suggest for 'the prepositional case'? According to UD, `Case=Loc` are typically applied for non-locational meanings as well.

Currently, the conversion script treat both forms as locative. The arguments are the following:

The locative case is one of the four so called 'secondary' cases (Genitive 2/Partitive, Accusative 2, Locative 2, Adnumeral) which are attested for a limited number of nouns in the modern Russian.  The rest of nouns have no separate form for the non-locative, partitive, adnumeral, etc. uses. 
In particular, all -e forms can be used in the locative construction whereas about 20 -u forms cannot be used in non-locative prepositional constructions. 

As for the feminive nouns, it would be even more problematic to distinguish between Locative and Prepositional cases. Feminine forms are distinguished only by the place of stress, and the distribution of forms is pretty the same. A very limited number of forms with the final stress cannot be used in non-locative prepositional constructions. What is more, some feminine nouns of such type are actually attested in the non-locative PPs, [example](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&dpp=&spp=&spd=&text=lexform&mode=accent&sort=gr_grsphere&ext=10&accent=1&req=%EE%20%ED%EE%F7%E8%27&docid=36558&sid=5).

Historically, these forms were in pretty free or dialect-based variation.
