### ISSUE TITLE
Mappings from Spanish ANCORA POS tags to UPOS?

### ISSUE THREAD

**Issue by johann-petrak** [UniversalDependencies/docs#697]
The documentation for this Spanish corpus 
  https://universaldependencies.org/treebanks/es_ancora/index.html
mentions that POS tags have been converted automatically to UPOS from that corpus - but 
I was unable to find code or mapping file from the original ancora tags (e.g. sp000) to the corresponding UPOS tags. Does this exist somewhere?

**Comment by dan-zeman** [comment]
Yes. The conversion table that was used for this conversion is [here](https://universaldependencies.org/tagset-conversion/es-conll2009-uposf.html). The tags may differ from the original form in which the AnCora treebanks were distributed. The UD version was created by converting the version of AnCora that was used in the CoNLL 2009 shared task.

**Comment by johann-petrak** [comment]
Oh ok, thanks, this is what was confusing me then: the original set of the ancora tags is very different and I was hoping to find a direct mapping!
Thanks!
