### ISSUE TITLE
WH-questions

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#705]
Oddly enough I don't see any discussion of wh-questions in the current UDv2 documentation. (cf. #454)

I am particularly interested in "where" and "when" questions, because there are inconsistencies between English treebanks on both POS and deprel of the WH-word:

[EWT](/UniversalDependencies/UD_English-EWT):
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/985263/81327408-3302aa80-9069-11ea-9c8e-e9686696a4c0.png">

[GUM](/UniversalDependencies/UD_English-GUM):
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/985263/81327449-43b32080-9069-11ea-8c8b-c8d2e98165a3.png">

Which is correct?

**Comment by nschneid** [comment]
(Discovered this investigating UniversalDependencies/UD_English-EWT#88)

**Comment by amir-zeldes** [comment]
I think EWT is correct here. This must be an artifact of the SD to UD conversion, but should be relatively easy to correct for questions since we have manual sentence type annotations. Thanks for reporting, I've opened an issue here: https://github.com/amir-zeldes/gum/issues/57
