### ISSUE TITLE
Q&A discourse as a genre

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#712]
I am wondering whether it makes sense to introduce a separate genre label for texts presenting "question and answer" sessions posted online? Or would it be better to assign "topic" labels such as "legal" or "medical" (or even "web" as a media marker of discourse)?

**Comment by dan-zeman** [comment]
The set of genre keywords is just a rough approximation and we never attempted or intended to create a complete taxonomy of genres. Using the `web` label sounds like a reasonable solution to me.
