### ISSUE TITLE
Inflected prepositions (deoc'h) 

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#718]
in sentence `apertium.vislcg.txt:21:280` (and others) _deoc'h_ (inflected preposition meaning to-you (PL) is annotated as a MWE:

```
3-4    deoc'h  _       _       _       _       _       _       _       _
3      deoc    da      ADP     pr      _       4       case    _       _
4      h       indirect        PRON    prn     Case=Acc|Number=Plur|Person=2|PronType=Prs      1       obl     _       _
```
which is not correct, since _c'h_ is considered as a single letter (for the phoneme /x/). I doublt whether inflected prepositions can be analysed as MWE at all, even though historically the were two distinct words (and in other Celtic languages, like Welsh, the inflected forms can be followed by a pronoun: _amdano fo_ "for+3SGMASC him")
For Breton I would propose either an annotation as in sentence `apertium.vislcg.txt:22:295` 

```
3-4     dezhañ  _       _       _       _       _       _       _       _
3       dezhañ  da      ADP     pr      _       4       case    _       _
4       _       indirect        PRON    prn     Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs  1       obl     _       _
```
(but what is the point having a MWE when the second part is empty) 
or as in Welsh, Irish and Scottish Gaelic (i.e. ADP with morphological features indicating Number and Person)

Welsh:
```
8       amdanyn am      ADP     cprep   Number=Plur|Person=3    9       case    _       _
9       nhw     hwy     PRON    indep   Number=Plur|Person=3|PronType=Prs       7       obl     _       SpaceAfter=No
```

Irish:
```
24      againn  ag      ADP     Prep    Number=Plur|Person=1    23      obl:prep        _       _
```

```
15      orm     ar      ADP     Prep    Number=Sing|Person=1    12      obl:prep        _       SpaceAfter=No
```

Scottish-Gaelic:
```
4       dhuibh  do      ADP     Pr2p    Number=Plur|Person=2    3       obl     _       _
```

**Comment by dan-zeman** [comment]
I am transferring this issue to the docs repository, as its importance exceeds the Breton treebank and language.

**Comment by ftyers** [comment]
The first part (e.g. splitting *deoc'h* as *deoc'* + *h*) is a bug in my conversion script and I should fix it. 

The second part, splitting or not splitting I think is more open to interpretation. In Breton, they are typically pretty compositional so I've analysed them as contractions of preposition and pronoun, much like in Spanish *contigo*. In Breton they are not emphatic forms. 

One of the reasons I don't like the `ADP` analysis is that the end result of this contraction (in UD) is a pronoun, not an adposition, e.g. the head of `case(PRON, ADP)` is the `PRON`. Of course then the question would be "do we encode the preposition that is contracted then as a feature?" ... `Prep=Da`, that might be a bit ugly. 

Anyway, I'm glad this has come up and I think it is useful to think about.

**Comment by ftyers** [comment]
> But MWT would be bad if the pronoun followed, (_deoc'h chw'i_) because than you had something like
> `1-2 deoc'h`
> `1 da`
> `2 chw'i`
> `3 chw'i`
> 
> I see these prepositions similar to prodrop verbs like in Spanish: _quiero_ "I want" is not analysed as a MWT of _yo_ and _quiero_ neither.

Can you give an example of this, is it like "clitic" doubling?

**Comment by jheinecke** [comment]
Since in the majority of cases in Breton, the pronoun is not repeated after an inflected preposition, 
I'm not 100% sure whether the presence of the pronoun is emphatic or not, but there is evidence. Some examples

* _Gloar **deoc’h-c’hwi**, maro evidom_ "glory **to you**, [who] died fo us"
* _Bonjour **deoc'h c'hwi** plac'hig_ "bonjour **to you**, little girl"
* _Deoc'h-c'hwi bremañ_
* _Ganeoc'h-c'hwi pechañs e c'hellimp ranniñ ..._ "With you we hope to share ..."
* _Hiziv c'hoazh e vez savet ganeomp-ni asambl_

Jules Gros (1984) Le Trésor du Breton Parlé, p.120 mentions these cases as emphatic: 
* _**Din-me** a roi anezañ da gentañ_ "c'est **à moi** que tu le donneras d'abord"
* _**Dit-te** na lavarin ket_ "**[à] toi**, je ne te le dirai pas"


I wonder whether there are important difference between speakers coming from different dialect background, since the "standard" of Breton is debatable (cf. Iwan Wmffre (2007), Breton Orthographies and Dialects: the Twentieth-century Orthography War in Brittany, vols.1–2, Bern: Peter Lang (Series: Contemporary Studies in Descriptive Linguistics) (xxviii + 782 pp) 

To resume, we have two cases in at least Welsh, Breton and Irish

* inflected preposition + pronoun
* inflected preposition

If we chose an MWE annotation, we would have two pronouns if the pronoun is not dropped. In this case, how can we attach the second (independent) pronoun ?


e.g. Welsh _amdani hi_ "about her":

```
1-2	amdani	_	_
1	am	am	ADP	2	case
2	hi	hi	PRON	0	root
3	hi	hi	PRON	?	?
```


But since in prodrop languages (like Spanish) we do **not** analyse _quiero_ as

```
1-2	quiero	_	_
1	yo	yo	PRON	2	nsubj
2	quiero	querer	VERB	0	root
```

so why should we do the following:

```
1-2	amdani	_	_
1	am	am	ADP	2	case
2	hi	hi	PRON	0	root
```

Of, course, in the Spanish case, the dependent (_yo_, nsubj) is dropped, in the case of Celtic
the head (_hi_) is dropped, so it is really the same thing.

In Arabic-PADT and Hewbrew the prepositions with pronominal clitics are annotated as MWE. 
But these prepositions are not inflected as the Celtic ones but simple prepositions with clitics and in both languages no additional pronoun can follow:

```
7-8	فيه	_	_
7	في	فِي	ADP		8	case
8	ه	هُوَ	PRON	6	obl
```

```
11-12	بينها	_	_
11	بين	بَينَ	ADP		12	case
12	ها	هُوَ	PRON	10	obl
```

```
2-3	לו	_	_
2	ל_	ל	ADP	3	case
3	_הוא	הוא	PRON	1	obl
```

and Amharic
```
1-2	ከኔ	_	_	_	_	_	_	_	_
1	ከ	ከ	ADP	ADP	_	2	case	_	Translit=kä|LTranslit=kä
2	እኔ	እኔ	PRON	PRON	_	7	nmod	_	Translit='əne|LTranslit='əne
```



But in any case I agree at least for the Celtic languages the inflected pronouns should be annotated in a similar way. 
Currently only the Breton treebank annotates inflected pronouns as MWEs.

The Irish treebank tags the inflected prepositions as ADP with morphological features for Number and Person (and Gender in the case of 3SG), if depending from a verb the deprel is `obl:prep`

```
3	liom	le	ADP	Prep	Number=Sing|Person=1	1	obl:prep
```

```
10	dúinn	do	ADP	Prep	Number=Plur|Person=1	5	obl:prep
```


Welsh is annotated similarly to Irish (except the deprel is only `prep`):

```
15  gennym  gan     ADP     cprep   Number=Plur|Person=1    14      obl
```

Unlike Irish and Scottish Gaelic, In Welsh (and to a lesser extend in Breton) the pronoun can follow the inflected preposition

```
8   wrthot  wrth    ADP     cprep   Number=Sing|Person=2    9       case
9   ti      ti      PRON    indep   Number=Sing|Person=2|PronType=Prs       5       obl
```

Scottish Gaelic again follows the Irish and Welsh scheme:

```
4	aca	aig	ADP	Pr3p	Number=Plur|Person=3	2	obl
```

```
2	dhomh	do	ADP	Pr1s	Number=Sing|Person=1	1	obl
```

**Comment by nschneid** [comment]
> Of, course, in the Spanish case, the dependent (_yo_, nsubj) is dropped, in the case of Celtic
> the head (_hi_) is dropped, so it is really the same thing.

With pro-drop it is straightforward to omit the pronoun because verbs are heads. But adpositions normally are not heads, which makes things awkward for Celtic and Semitic.

How's this as as summary of options:

1. When there is an inflected preposition + separate pronoun, the options are
     1. Treat it as a PP, i.e., a `case` relation headed by the separate pronoun
     2. Treat the separate pronoun as a special emphatic modifier (e.g. whatever we do for *you __yourself__*)
2. How to analyze the preposition?
     1. Multiword token analysis (ADP+PRON), like in Arabic and Hebrew
         * Straightforward with 1(ii): separate pronoun is modifier of internal pronoun
         * With 1(i), we have doubling of the pronoun—does it form a phrase, and if so, which is pronoun the head of the other?
     2. Single-word ADP token with pronominal features, no internal `case` relation
         * Always with 1(ii), or when there is no separate pronoun with 1(i), ADP is promoted to `obl` as it has no overt object
     3. (goes with 1(i)): (ii) if there is no separate pronoun, (i) otherwise

I don't love 2(iii) because it makes tokenization context-dependent.

Yet another option is to treat the inflected preposition instead as a case-marked pronoun, with the case specified as a morphological feature (as @ftyers noted). But I take it this construction applies to prepositions more widely than just (say) Accusative, Dative, and Genitive prepositions. I would prefer to keep feature values as abstract morphosyntactic categories rather than lexical items.

It seems important to decide whether to go with the "emphatic modifier" analysis (always, or in some dialects). Do non-prepositional pronouns allow such emphasis?

**Comment by amir-zeldes** [comment]
+1 for options 1(ii) and 2(i), which is also what we do in Coptic. Coptic 'double' cases are also movable/sometimes floating quantifiers (things like "for-you all-of-you"); we've used 1(ii) partly because of that, so it seems like the best option if you have similar constructions.

**Comment by jheinecke** [comment]
1(ii) and 2(i) might work for Breton, where the presence of the overt pronoun is more likely to be emphatic, but in Welsh it is definitely not emphatic. It's more a question of style. In more formal text, the overt pronoun is more likely to be dropped, in less formal text it is not dropped (apart form some fixed expressions). So even though I think 1(ii) and 2(i) is the best options, The annotation should not imply any emphasis. So how an phrase like _aros amdanat ti_ "waiting for you(SG)"  could be annotated:

1)  attaching the overt pronoun to the MWE pronoun:
```
1	aros	VERB	....	0	root
2-3	amdanat	_	....	_	_
2	am	ADP	....	3	case
3	ti	PRON	....	1	obl
4	ti	PRON	....	3	nmod	// overt pronoun

```

or 2) attaching the overt pronoun as (second) `obl` to the verb:

```
1	aros	VERB	....	0	root
2-3	amdanat	_	....	_	_
2	am	ADP	....	3	case
3	ti	PRON	....	1	obl
4	ti	PRON	....	1	obl	// overt pronoun

```

@nschneid I could find examples of _you yourself_ in the English treebanks, so what exactly you thought for this case. @amir-zeldes could you point me to an exemple in the Coptic treebank ? Thanks a lot!

**Comment by amir-zeldes** [comment]
Sure, there's lots of them all over the place. We basically have two analyses, depending on whether it's just a dislocated mention of the same pronoun (not adding an argument/adjunct) or if it's adding some flavor, like a quantifier or other modifier (which we don't see as just dislocation, since it has a separate function):

  * Floating "on-them all-of-them" - note "on-them" is `ejn + ntoou` which fuses into `ejo:u`, and "all-of-them" is a possessed quantifier, lit. "their-all", which is `te:r + ntoou` = `te:rou`. Both are dependents of the verb (token 51) in this example: https://github.com/UniversalDependencies/UD_Coptic-Scriptorium/blob/master/cop_scriptorium-ud-dev.conllu#L6313-L6318
  * Dislocated full pronoun on top of a fused PP pronoun: `ntof` is the extra full pronoun 'he' (emphatic or topicalized), and then in this example we also get "to him", which is the mention mandated by the argument structure of "come upon", so "him (ntof), they came upon him (ero+f)", where `erof = e+ntof` "to him". Example: https://raw.githubusercontent.com/UniversalDependencies/UD_Coptic-Scriptorium/master/cop_scriptorium-ud-train.conllu (look at lines 27121-27130, github is not letting me hyperlink it)

**Comment by nschneid** [comment]
In EWT the emphatic reflexives like "they themselves" are `nmod:npmod` (though the `npmod` subtype is problematic in general and should probably be revised).

**Comment by jheinecke** [comment]
Thanks for the English and Coptic examples. Hower I couldn't find a solution which fits the Celtic languages. Would `expl` fit?

Welsh _arhosodd amdanat [ti]_ "He waited for you(SG)"

```
1	arhosodd	VERB	0	root
2-3	amdanat		_	_	_
2	am		ADP	case	3
3	ti		PRON	obl	1
[4	ti		PRON	expl	1]
```
The advantage is that the structure of the (remaining) phrase is identical with or without overt pronoun.
The only case where this does not work are be a isolated inflected pronouns + overt pronoun:
_ganddo fo!_ "with him"

```
1-2	ganddo	_	_	_
1	gan	ADP	case	1
2	fo	PRON	root	0
3	fo	PRON	expl	??
```

Back to Breton: 
@ftyers More examples of inflected prepositions + pronoun are also mentioned in the _Atlas linguistique de la Basse-Bretagne_(ALBB, http://sbahuaud.free.fr/ALBB/), sheets 106, 107, 208-214, 159, 320 especially for the Leon dialect. At least some dialects have the pronoun frequently (see also Francis Favereau (1997): _Grammaire du breton contemporain_, § 766).

**Comment by amir-zeldes** [comment]
I think `dislocated` fits both of the cases above, unless I'm missing some nuance about the meaning of the construction. It doesn't add an argument, so the extra pronoun is a postposed realization which does not itself fulfill one of the core grammatical relations in the sentence, as in the relation description: https://universaldependencies.org/u/dep/dislocated.html

**Comment by ftyers** [comment]
I quite like `dislocated` for this as well. I think it is (or should be?) also used for "clitic" doubling in Romance languages, e.g. *a mí me gusta*, *le dio a ella* etc. Although it seems that this isn't exactly followed at least in the Spanish treebanks, https://github.com/UniversalDependencies/UD_Spanish-GSD/issues/6 https://github.com/UniversalDependencies/UD_Spanish-AnCora/issues/2 and a post from 2014 (has it been that long!) suggests using `expl` for this: https://github.com/UniversalDependencies/docs/issues/129

**Comment by jnivre** [comment]
I completely agree. Using dislocated + a core relation is the preferred solution for non-obligatory cases of "clitic doubling".

**Comment by sylvainkahane** [comment]
I'm not sure it is comparable to clitic doubling. In case of clitic doubling, the clitic can double any NP. In this case, as Johannes confirmed me, the "doubling" occurs only with pronouns. In other words we have only three possible configurations:

```
ADP NOUN
ADP=PRON ("=" means cliticization)
ADP=PRON1 PRON2
```
"ADP=PRON NOUN" is not allowed. Moreover "ADP=PRON1 PRON2" forms a phrase and we cannot consider that ADP=PRON1 and PRON2 occupy two different positions.

It seems to be a very local phenomenon (what we call microsyntax or even morphosyntax) compared to clitic doubling which generally comes from macrosyntactic phenomena such as dislocation. I think we can consider that's a reduplication of the pronoun due to the weakness of the pronoun realization as a clitic. What I suggest is:

```
PRON1 -case-> ADP
PRON1 -compound:redup-> PRON2
```

**Comment by ftyers** [comment]
(An aside @jheinecke I've fixed the stuff with *c'h* and in passing fixed some other weird tokenisation stuff: https://github.com/UniversalDependencies/UD_Breton-KEB/commit/4daa27b974e67991ff40d4e402e70a01fbe78d05, thanks for the bug report!)
