### ISSUE TITLE
Use of linguistic examples from papers that are behind paywall 

### ISSUE THREAD

**Issue by utkuturk** [UniversalDependencies/docs#724]
Hi everybody, 

We are annotating a treebank, however there are set of examples that we found in published papers. One is from Lingue e Linguaggi, which have following sentence in their website: This work is licensed under a Creative Commons Attribuzione - Non commerciale - Non opere derivate 3.0 Italia License.

The other one is from Language Typology and Universals under De Gruyter Motion, which have this kind of website for copyright issues: https://www.copyright.com/openurl.action?rwr=27&issn=2196-7148&WT.mc.id=deGruyter

I have the consent of the writers, which may or may not mean anything. I am not using anything apart from the linguistic examples, and I shuffled the order of the examples. I will explicitly cite the papers every time I will write about the treebank.

Is it okay for me to use these sentences? Unfortunately, there is not much data available online apart from papers and some facebook groups in this Language. For example, it does not have Wikipedia.

**Comment by ftyers** [comment]
@utkuturk I've emailed you offline about this.

**Comment by utkuturk** [comment]
@ftyers Thank you!
