### ISSUE TITLE
participles versus adjectives in English

### ISSUE THREAD

**Issue by jonorthwash** [UniversalDependencies/docs#725]
From [UD documentation of `cop`](https://universaldependencies.org/u/dep/cop.html):

> If the copula is accompanied by other verbal auxiliaries for tense, aspect, etc., then they are also given a flat structure, and taken as dependents of the lexical predicate:
> 
> > Sue has been helpful
> 
> The motivation for this choice is that this structure is parallel to the flat structure which we give to auxiliary verbs accompanying verbs. In particular, in languages such as English, it is often very difficult to decide whether to regard a participle as a verb or an adjective. Perhaps the following sentence is such a case:
> 
> > The presence of troops will be destabilizing .
> 
> While a part of speech has to be decided in such cases, it would be unfortunate if the choice of part of speech also changed the dependency structure. Note, however, that the exact distribution of the copula construction is subject to language-specific variation.

I'm trying to make this justification make sense in my mind.

In "The presence of the troops will be destabilising" the last word is an adjective in the "default" reading and not a verb, but it is technically ambiguous.  The meaning changes if it's a participial form of a verb, cf. unambiguous cases:

- "The presence of the troops will be destabilising to the economy." (adj)
versus
- "The presence of the troops will be destabilising the economy for years to come." (verb)

These two readings *absolutely should* have different structure (and POS tags).  It's not "unfortunate" if the two parses are different—it exactly reflects what's going on here!

Does it matter if it's hard to know which was intended, or to know which to annotate it as?  This is a recurring problem when applying UD to a new language, and a constant issue for annotators even of languages with clear annotation standards.  The current solution feels to me like "this is hard so we decided to make the problem go away by pretending it doesn't exist".

But perhaps I'm missing something here.  Could someone clarify?

**Comment by dan-zeman** [comment]
I am not sure if the cited motivation is the only one or even the main one. For me, copular sentences have a multi-word predicate, consisting of a copula and a non-verbal element (say, adjective). Auxiliaries further modify the predicate and add features such as tense, aspect or voice. So they should be attached to the head node of the predicate, which is the adjective. That should be enough to justify the decision.

(BTW, in Czech I tag most participle types always as adjectives (with `VerbForm=Part`) and then I am happy that the only consequence in predicative use of the participle is that one of the auxiliaries becomes a copula. The difficulty of figuring out whether the predication was meant as action or state does exist in Czech.)

**Comment by nschneid** [comment]
Right, another way to put it is that UD prefers content heads wherever possible, so copulas are almost never heads. If the lexical predicate is analyzed as ADJ then the "be" form will attach to it as `cop`; if it is tagged as VERB then "be" will attach as `aux`.

On a practical level the PTB guidelines which underlie the original English tagging decisions are liberal about interpreting -ing forms as verbs (VBG). So it may be difficult in practice to implement the ADJ/VERB distinction you are arguing for.

**Comment by jonorthwash** [comment]
@dan-zeman:

> I am not sure if the cited motivation is the only one or even the main one. For me, copular sentences have a multi-word predicate, consisting of a copula and a non-verbal element (say, adjective). Auxiliaries further modify the predicate and add features such as tense, aspect or voice. So they should be attached to the head node of the predicate, 

Yes, that is my understanding of how things are supposed to work currently in UD.

> which is the adjective. 

It should be clear in most contexts whether an "-ing" form in English is a verb form or an adjective.  Why must it always be an adjective?

> That should be enough to justify the decision.

What do you mean here?  (I.e., which decision?)

@nschneid:

> Right, another way to put it is that UD prefers content heads wherever possible, so copulas are almost never heads. If the lexical predicate is analyzed as ADJ then the "be" form will attach to it as `cop`; if it is tagged as VERB then "be" will attach as `aux`.

This sounds like an entirely reasonable approach to me, and exactly what I'm advocating for.

> On a practical level the PTB guidelines which underlie the original English tagging decisions are liberal about interpreting -ing forms as verbs (VBG). So it may be difficult in practice to implement the ADJ/VERB distinction you are arguing for.

I don't follow this.  In my mind, a given annotator simply has to make a decision, and usually this isn't a difficult one—at least not for a native speaker with some understanding of the distinction.  So I don't see how it would be "difficult in practice to implement" the distinction.

**Comment by nschneid** [comment]
I meant that, with respect to English, it would be a lot of work to change the criteria for VERB vs. ADJ if it meant revisiting all the data that has been annotated so far. Are you proposing something different from the policy in the [PTB annotation manual](https://repository.upenn.edu/cis_reports/570/) pp. 14-16 & 19-20? That is the main way English treebanks distinguish verbs from nouns/adjectives.

**Comment by nschneid** [comment]
Ohhh @jonorthwash is your question why the following specifies `cop` without committing to a POS? I.e. it can be read as implying that it could be `cop` headed by a VERB?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/985263/92331216-168c7400-f043-11ea-8dc4-520993ebf802.png">

I interpreted the sentence about structure as referring to the tree structure, not the deprel, and that it should be `aux` if "destabilizing" is tagged as a VERB.

**Comment by jonorthwash** [comment]
> Ohhh @jonorthwash is your question why the following specifies `cop` without committing to a POS? I.e. it can be read as implying that it could be `cop` headed by a VERB?

My question is more about why the structure necessarily has to be parallel for the two readings.  The two readings are very different in a number of ways, and more generally, requiring a single structure for ambiguous text would be a horrible thing to impose on any syntactic representation.  If they happen to be the same here, fine, but that should be a post facto note about a given set of ambiguous sentences, not part of the guidelines for how to annotate them.

I also wonder about "the motivation for this choice is that this structure is parallel to the flat structure which we give to auxiliary verbs accompanying verbs".  Does this mean that part of the design of `cop` is that they should be involved in tree structure in similar ways to `aux`?

And yes, if there's any implication that "be" should always be `cop` in sentences like this, then I'm concerned about that as well.  Perhaps it just needs clarification.  And in my opinion, this is a poor example of "it is often very difficult to decide whether to regard a participle as a verb or an adjective".

> 
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/985263/92331216-168c7400-f043-11ea-8dc4-520993ebf802.png">
> 
> I interpreted the sentence about structure as referring to the tree structure, not the deprel,

Yes, I interpret it that way (at least upon reading it now).

> and that it should be `aux` if "destabilizing" is tagged as a VERB.

That's not part of how I'm interpreting it.  Perhaps it could be clarified.

**Comment by dan-zeman** [comment]
@dan-zeman:

>> which is the adjective.

@jonorthwash:

> It should be clear in most contexts whether an "-ing" form in English is a verb form or an adjective. Why must it always be an adjective?

I was talking about copulas, not about English "-ing" forms. Adjective was an example of a non-verbal part of a predicate, introduced a few lines above. It could also have been a noun, a proper noun or a pronoun.
