### ISSUE TITLE
egomet: emphasis as a feature + particles and PronType=Emp

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#741]
This issue may be indirectly related to #709 and #732.

I was wondering if **emphasis** did not deserve its own feature, orthogonal to the existing `PronType=Emp`, in the same way that we do not have `PronType=Poss`.  

In particular, I observed the following for some particular "strengthened" pronominal forms in Latin (nothing new, however). Here we have e.g.
* _ego_ 'I' - basic form 
* _egomet_ '~ I myself, I indeed, I!' - strengthened form 

This _-met_ element is ambiguous between the status of a clitic and an affix, but the fact that it is so extremely selective (it appears only on personal pronouns, on _ipse_ 'self', and on some personal possessives, and not on all forms) and that it can apparently never be split, at least in Classical Latin (*_ego autem met_), seems to align it with inflection. So we might say that Latin has an emphatic inflection of some kind of some personal (pronouns and possessives) elements:
* _egomet_, _tumet_ 'you indeed', ...
* _tute_, _tete_, _tutin_; _tutemet_ all 'you!, you indeed' (with cumulation of emphatic elements)
* _meapte_ 'my own indeed', _suopte_ 'his/hers/its own indeed', ... ; _mepte_ 'me myself'

Since they are both personal and emphatic, theoretically I should choose a label like `PronType=Emp,Prs`, but I understand that this feature should select only one value. So I would like to propose a distinct feature `Emphatic=Yes|No`:

egomet    _ego_    PRON    `Case=Nom|Emphatic=Yes|Number=Sing|Person=1|PronType=Prs`

Now, some prefer to detach _met_ from _ego_, but with this feature it would make no difference: like non is a `PART` that bears `Polarity=Neg` and "passes" it to another word, so, in this case, _met_ would be a `PART` bearing `Emphatic=Yes` and passing it to the given personal pronoun/possessive. This would avoid a rather awkward, and _ad hoc_ defined, `PartType=Emp` feature (what we are using now; currently used by the treebank of _myv_jr_, which I can't identify).  
Probably, this could also be of help for Chukchi, where the particle _ъм_ could take `Emphatic=Yes` and attach to its word.
Also, this feature is very likely not limited to nominals, and it might also arise in different ways, e.g. as part of inflections, and it is surely distinct from definiteness or evidentiality.

Now, two issues arise:
* what should be the relation between _ego_ and _met_?
    * `advmod` seems to be out of place here, first of all because of its restriction to `ADV`s, and further because such particles are not adverbs, and are not restricted to modifier words. Could `aux` be sensible? Is there the need for a new relation for "external affixation"?
* I think that the value `Emp` of `PronType` should be relabelled (and redefined). Probably some of these elements could still be eligible for `Emphatic=Yes`, but I have the impression that the intended feature is better described as "specifying", or, as in Latin grammars, "determinative".

**Comment by dan-zeman** [comment]
> The `PronType` "feature should select only one value"

No, it is not required, and in fact, some treebanks systematically use `PronType=Int,Rel` for wh-words that can be both interrogative and relative. But I think that the expected semantics of the comma is "either-or", not "and at the same time also", hence I agree that `PronType=Emp,Prs` does not seem good fit.

`Emphatic=Yes` may be a reasonable language-specific solution for Latin and other languages where emphasis is inflection (Chukchi??) But the currently existing [PronType=Emp](https://universaldependencies.org/u/feat/PronType.html#Emp) is a lexical feature of pronouns/determiners whose main function is best explained as emphasis. They are not personal pronouns at the same time. The reason why `Poss` is orthogonal is that it can occur either with personal pronouns/determiners, or with interrogative/relative pronouns/determiners.

**Comment by Stormur** [comment]
(By the way, I discovered that these emphatic personal forms had been also discussed in #711)

>> The PronType "feature should select only one value"

> No, it is not required, and in fact, some treebanks systematically use PronType=Int,Rel for wh-words that can be both interrogative and relative.

I think that we (Latin IT-TB) might be the major culprits here... :slightly_smiling_face: 
It is true that at the moment we are using this formula in cases where we cannot resolve this ambiguity (e.g. _quis_ 'who?/anyone' -> `PronType=Ind,Int`) by means of automatic conversion. But it is also true that our interpretation of the comma has been rather "both at the same time", so that we are actually using it also for so-called "double pronouns" (which are arguments in a relative and in a higher clause at the same time), e.g. `PronType=Ind,Rel`. We are probably going to address these notational quirks in the future. However, the fact is that the guide lines don't seem to mention thie possibility of a double `PronType` explictly...

> The reason why Poss is orthogonal is that it can occur either with personal pronouns/determiners, or with interrogative/relative pronouns/determiners.

That is exactly why I was advocating for an `Emphatic` feature. 
I think this phenomenon comes up in many other languages and in many other ways, for example, apart from Chukchi:
* in Latin (and other languages) the particle _o_ which is preposed to vocatives (_O Romule!_ '(Oh) Romulus!') can be seen as a bearer of emphasis (it is not necessary to invocations);
* in Mongolian there is a "case" classically called a "vocative", but which might be better interpreted as emphasis. For example, to call someone called Бат _Bat_ one shouts Бат аа! _Bataa!_, to call the mom, ээж _eej_, instead ээж ээ! _eejee!_, following vowel harmony. But also, to say 'it's a lie!/you lie!' you can say худлаа! _khudlaa!_ from худал _khudal_ 'lie (noun)'. I can conceive to annotate all these forms as `Emphatic=Yes` (and with no other features, by the way). Such forms are also often used to form terms of endearment. Then there is холоо _kholoo_ 'very far (emphatic)' from хол _khol_ 'far', and so on. 
* ... I am sure there are many other examples! We might have a bias because this feature is apparently not so codified into European languages.

> But the currently existing PronType=Emp is a lexical feature of pronouns/determiners whose main function is best explained as emphasis.

Now this lets me wonder in which `PronType` the Latin words _ipse_ '~self' or _idem_ 'the same' actually fall. Does it make sense for _ipsemet_ to be at the same time `Emp` and `Emphatic=Yes`? Their role seems to be that of pinpointing something exactly rather than emphasising it: _Non omnes **eadem** delectant_ 'Not everybody likes the same things'. They also do not appear to function as demonstratives or personal pronouns... My thought was that emphasis is just a "secondary effect" of this kind of specification, so that `Emp` does not fit, as doesn't `Dem` or `Prs`. Then what are they?

**Comment by Stormur** [comment]
Well, I just found out that some treebanks already mark emphasis in a direct way (shame on me for not having spotted them before):

* Polish PDB straight uses `Emphatic=Yes`. At the moment it is not documented, so at least for me, as an ignorant of Polish, it would be interesting to know how it works there. It seems to happen for adverbs, determinants, particles and pronouns: _czyż_, _jakże_, _czymże_, _cóż_, _gdzież_, _któż_, _ileż_, _skądże_, _tyleż_.
* The feature `Form` with, among others, value [`Emp`](https://universaldependencies.org/ga/feat/Form.html#emp-emphatic) (i.e. _emphatic_) is used for Irish and Scottish Gaelic (it is also attested, but not documented, for Korean). So, we have pairs like _dom_ 'to me' and _domsa_ 'to me (emph.)', which is strongly reminding of Latin, e.g. _mihi_ 'to me' and _mihimet_ 'to me (emph.)'! But it seems to be pertain to verbs, too.
