### ISSUE TITLE
Converb vs. Coverb in Mongolic and Turkic

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/docs#747]
What is the difference between `VerbForm=Conv` and `VerbForm=Coverb` in Buryat? Similarly, Kazakh and Uyghur have `VerbForm=Cov` (in addition to `Conv`), which may possibly mean the same thing.

Skribnik (2011) lists over 10 different types of converbs for standard Buryat. One of them is the imperfective -zhA, which seems to match the "coverb" [in our Buryat data](https://universaldependencies.org/treebanks/bxr_bdt/bxr_bdt-feat-VerbForm.html): _байжа_.

Should we cover all these forms under `VerbForm=Conv` and then distinguish their subtypes in a language-specific feature?

-----
Elena Skribnik. 2011. Buryat. In: _The Mongolic Languages._ Routledge

**Comment by ftyers** [comment]
Probably `VerbForm=Conv` and `VerbForm=Converb` are the same.

`VerbForm=Coverb` is different, this is a form that is used with auxiliaries. In [this article](http://journals.linguisticsociety.org/proceedings/index.php/tu/article/view/4587/4237) this is the equivalent of the "infinitive". But that label is not available in UD. 

In general following the classification above:

* VN → `VerbForm=Vnoun`
* VADJ → `VerbForm=Part`
* VADV → `VerbForm=Conv`
* INF → `VerbForm=Cov`

**Comment by Stormur** [comment]
They are not intended to be the same; there are slight differences, and in my experience this is complicated by sometimes conflicting terminologies... even if, to me, such differences appear quite arbitrary or too much language-specific. Therefore, I am of the advice that all "adverbial forms" of verbs should be conflated into one single feature; other distinctions should happen through tense, mood, aspect, or syntactic relations. 

If I remember well, one of the distinctions made in this field is if a verb in a given form can appear as a full predicate, or if it needs another "finite" verb; this involves also "participles". Boundaries are very blurry here, and traditional Western terminology does not help. Also, probably this distinction overlaps with that between regular and modal verbs in other languages, or also auxiliaries, as @ftyers points out, but then UD should already have all needed labels, no? This is surely complicated by the fact that at least in Mongolian nearly _every_ word form seems to accept some kind of nominal inflection.

As an example, the descriptive grammar of Mongolian (not limited to Khalkha) by Janhunen (2012) does not use the term _coverb_, only _converb_, alongside _participle_. A main distinction is made between those converbs which admit different subjects than the main predicate ("disjunct") and those which don't ("conjunct"), among other of more morphological nature. There appears also the imperfective -ж/ч form you mention for Buryat. 

So, there should be no need for _coverbs_, at least not in Mongolic! Just my 2 cents, let's call an Altaicist! :slightly_smiling_face: 

---

>VerbForm=Coverb is different, this is a form that is used with auxiliaries. In this article this is the equivalent of the "infinitive". But that label is not available in UD.

Is the feature `VerbForm=Inf` not usable here?

**Comment by coltekin** [comment]
In Turkish, infinitives are syntactically very similar to other forms of verbal nouns. So, we mark them with `VerbForm=Vnoun`. I expect this to be similar in other languages. Unless their distribution is (substantially) different than verbal nouns, my suggestion would be using `Vnoun`.

**Comment by ftyers** [comment]
Turkish does not have "infinitives" of this type (unless you count e.g. the `-A` in `-Abil`). @jonorthwash any thoughts on this?

**Comment by Stormur** [comment]
Now, this makes me wonder if all values for verbal nouns, like `Vnoun`, `Inf` or `Sup` (_supine_, which I don't know if it exists outside of Latin), shouldn't be just conflated into just one value. All these labels just seem to arise from language-specific grammatical traditions. 

I mean, my point is that these objects are all substantially the same; if there are syntactic differences, then this should appear from relations and syntactic trees, rather than from labels, and morphology (presence/absence of declension, aspect, tense, mood...) is already marked by other features. In the same vein, I would also conflate `Ger` and `Gdv` into the more universal `Part`.

**Comment by dan-zeman** [comment]
> `VerbForm=Coverb` is different, this is a form that is used with auxiliaries. In [this article](http://journals.linguisticsociety.org/proceedings/index.php/tu/article/view/4587/4237) this is the equivalent of the "infinitive".

Great, in that case we can use the existing `VerbForm=Inf` and we do not need a new label.

**Comment by jonorthwash** [comment]
> in Mongolian nearly _every_ word form seems to accept some kind of nominal inflection

Can you point out a postposition, conjunction, or verb form other than a verbal noun or adjective that accepts nominal morphology in any Mongolic language?

**Comment by jonorthwash** [comment]
> Turkish does not have "infinitives" of this type (unless you count e.g. the `-A` in `-Abil`). @jonorthwash any thoughts on this?

There is an infinitive use of -(y)Ip with dur- (these are still written separately so are a slightly stronger case than the -(y)A forms you mention), e.g. in _çay içip durdum_.

@coltekin, the Turkish "-mAk infinitive" is a verbal noun by UD criteria.  The term infinitive is reserved for verb forms that pattern with auxiliaries.  (A case could be made with forms like _çay içmek istiyorum_, but I think this still could be a verbal noun, especially if it can answer the question _ne istiyorsun?_)

**Comment by jonorthwash** [comment]
> > `VerbForm=Coverb` is different, this is a form that is used with auxiliaries. In [this article](http://journals.linguisticsociety.org/proceedings/index.php/tu/article/view/4587/4237) this is the equivalent of the "infinitive".
> 
> Great, in that case we can use the existing `VerbForm=Inf` and we do not need a new label.

It sounds like maybe you're merging converbs and infinitives?  If so, I would express that these are very easily distinguished in Mongolic languages most of the time and probably shouldn't be merged in UD annotation.

**Comment by coltekin** [comment]
Do I understand correctly that the forms in question are ones that require an auxiliary? If so, I see the point of `Inf` (and not `Vnoun` as in _-mAk_). The example from Turkish would be _yap-a bilirim_ 'do-A abil-PRES-P1S' (I can do it), or _iç-e durdum_. I'd mark the _-(I)p_ version, _iç-ip durdum_, as `Conv`, even though this specific example looks like _iç-e durdum_, its syntax is the same as other uses of _-(I)p_. These type of free auxiliaries are rare in Turkish (auxiliary becomes a suffix, as in _yapabilirim_, in typical use). In the first example above, it makes sense to mark the first verb _yap-a_ as `VerbForm=Inf`. I think this also fits the definition/example in the UD documentation for `Inf`.

Now I wonder if the correct morphological tag for the non-finite forms like _iç-iyor olacağım_ or _iç-miş oldum_ should also be `Inf`. The first words (verbs) in these constructions do not have a particular suffix like _-A_ above, but they are incomplete (as a finite or non-finite verb/head of a subordinate clause) without the auxiliary _ol-_.

**Comment by ftyers** [comment]
I wouldn't say "require" an auxiliary, as there are no "infinitives" that are not also some other class (see Table 2 in [this article](http://journals.linguisticsociety.org/proceedings/index.php/tu/article/view/4587/4237)).

These *-iyor* examples are interesting, and could be related to other copula-as-auxiliary constructions that we discuss in the paper.

Going with `VerbForm=Inf` for these "Coverbs" is fine by us (and corresponds to what we call them in the paper).

**Comment by jonorthwash** [comment]
> there are no "infinitives" that are not also some other class

...  *in Turkish*. 

> These _-iyor_ examples are interesting, and could be related to other copula-as-auxiliary constructions that we discuss in the paper.

They are _exactly_ that. 

@coltekin, 

> I'd mark the _-(I)p_ version, _iç-ip durdum_, as `Conv`, even though this specific example looks like _iç-e durdum_, its syntax is the same as other uses of _-(I)p_

No, its syntax is entirely different.  In verbal adverb (`Conv`) uses of _-(y)Ip_ in Turkish, anything can come between the non-finite form and the main predicate.  Also, in terms of the semantics, there are two separate events, not one as with the infinitive use.  For example (feel free to correct details, but I think the point stands):

* _Eve gidip, yeni kardeşlerimle Moğolistan'da aldığım çayı içtik._

I'm not positive about Turkish off the top of my head (and can't check easily as I'm typing this on my phone), but in other Turkic languages I know, the two verbs can even have different subjects.

In _içip durdum_, you can't put many things between them (maybe _de_ and the like?), and they form a single predicate/event and _must_ share a subject and all other arguments.

**Comment by dan-zeman** [comment]
> > > `VerbForm=Coverb` is different, this is a form that is used with auxiliaries. In [this article](http://journals.linguisticsociety.org/proceedings/index.php/tu/article/view/4587/4237) this is the equivalent of the "infinitive".
> > 
> > Great, in that case we can use the existing `VerbForm=Inf` and we do not need a new label.
> 
> It sounds like maybe you're merging converbs and infinitives?  If so, I would express that these are very easily distinguished in > Mongolic languages most of the time and probably shouldn't be merged in UD annotation.

No, I don't think so. The Buryat data currently has both `VerbForm=Conv` and `VerbForm=Inf`. The latter was previously labeled `VerbForm=Coverb`, the former is unchanged. But I cannot judge whether the distinction between the two is made correctly in the data.
