### ISSUE TITLE
Number=Count in Slavic and universally

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/docs#749]
We currently use `Number=Adnum` in the Old Russian-RNC treebank and get 
```
Wrong value 'Adnum'. The correct UD label for the special form of noun after numeral is 'Number=Count'.
```
during validation. 

We would also be glad to annotate a number of forms as `Number=Count` in (modern) Russian.

However, we see that this value is defined in the universal documentation the following way:
```
Attested in Bulgarian and Macedonian. It is known variously as “counting form”,
“count plural” or “quantitative plural” (Sussex and Cubberley 2006, p. 324).
It is a special plural form of nouns if they occur after numerals.
(The form originates in the Proto-Slavic dual but it should not be marked
`Number=Dual` because 1. the dual vanished from Bulgarian and 2. the form is
no longer semantically tied to the number two.)
```

The problem is, that adnumeral forms such as _шаг'а, шар'а, ряд'а_ in Russian are not parallel to Bulgarian and Macedonian and do not originate in the Proto-Slavic dual. The dual forms comparable to  Bulgarian and Macedonian were reanalysed as Genitive singular forms in Russian when the paradigm structure changed. They are no longer associated specifically with the counting contexts. At the same time, forms such as _шаг'а_ are used exclusively with numerals.

The Old Russian forms are only partially tied to dual forms as well. 

That said, I would suggest to change the universal definition and mention neither plural nor dual in the main part. I would define `Number=Count` as a special inflectional form that occur after numerals.   
(Btw we consider assigning `Number=Count` to some adjectives as well in this construction in Old Russian, so should we mention nouns in the definition?).

**Comment by dan-zeman** [comment]
I have modified the documentation of `Number=Count` to make it less Bulgarian-specific. Would [this](https://universaldependencies.org/u/feat/Number.html#Count) work?

**Comment by dan-zeman** [comment]
BTW, is the apostrophe part of the spelling of the count form in _шаг'а, шар'а, ряд'а_?
