### ISSUE TITLE
Voice=Pass in Livvi

### ISSUE THREAD

**Issue by rueter** [UniversalDependencies/docs#750]
This is related to the issue #746 .
Unlike Finnish and Estonian, which have traditionally spoken of ```passive``` voice when dealing with their morphologically distinct impersonal ```Person=0```, the Livvi language, elsewhere Olonets-Karelian, does not have a morphologically distinct impersonal person. Instead, Livvi has a single morphological form for the third person plural, which is a cognate of the Estonian and Finnish impersonal.

With this in mind, I decided to look at where ```Voice=Pass``` was used in the olo-kkpp-ud-test.conllu document.
I came across the ```Voice=Pass``` where I would have expected ```Number=Plur|Person=3```
```
5	saneltah	sanella	VERB	VERB	Tense=Pres|VerbForm=Fin|Voice=Pass	0	root	_	_
```

```
# sent_id = vepkar-1820.17
# text = Omis ruadonerolois nuorižon hyväkse saneltah Karjalan Rahvahan Liiton aktivistat.
# text_en = Activists from the 'Karelian National Union' speak of their own work for the benefit of youth. (rough translation: Jack Rueter)
1	Omis	oma	ADJ	ADJ	Case=Ela|Number=Plur	2	amod	_	_
2	ruadonerolois	ruadonero	NOUN	NOUN	Case=Ela|Number=Plur	5	obl	_	_
3	nuorižon	nuorižo	NOUN	NOUN	Case=Gen|Number=Sing	5	obl	_	_
4	hyväkse	hyvä	ADP	ADP	Case=Tra|Number=Sing	3	case	_	_
5	saneltah	sanella	VERB	VERB	Tense=Pres|VerbForm=Fin|Voice=Pass	0	root	_	_
6	Karjalan	Karjala	PROPN	PROPN	Case=Gen|Number=Sing	7	nmod:poss	_	_
7	Rahvahan	Rahvas	NOUN	NOUN	Case=Gen|Number=Sing	8	nmod:poss	_	_
8	Liiton	Liitto	NOUN	NOUN	Case=Gen|Number=Sing	9	nmod:poss	_	_
9	aktivistat	aktivistu	NOUN	NOUN	Case=Acc|Number=Plur	5	nsubj	_	SpaceAfter=No
10	.	.	PUNCT	PUNCT	_	5	punct	_	SpaceAfter=No

```
I assume, @flammie , that we would want reference to ```Number=Plur|Person=3``` in Livvi, especially when there is a dependency nsubj(saneltah, aktivistat).
Are there any instances where we would want ```Voice=Pass``` if there is no morphological distinction between the two uses?

**Comment by flammie** [comment]
good catch thanks, it's an oov so the analysis is handwritten from the scratch and probably deosn't appear elsewhere in corpus
