### ISSUE TITLE
Amharic treebank tiny

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/docs#758]
Greetings,

Would like to request a bigger treebank for Amharic or how can one contribute to this existing treebank?

https://universaldependencies.org/treebanks/am_att/index.html

Thanks

**Comment by ftyers** [comment]
@yosiasz I think the general idea is to create new treebanks as opposed to expanding an existing one. In any case you can then combine them at training time. The first step would be to find some free/open-source text (perhaps the [Amharic Wikipedia](https://am.wikipedia.org/wiki/%E1%8B%8B%E1%8A%93%E1%8B%8D_%E1%8C%88%E1%8C%BD)? And then select some sentences and annotate them. You could ask the Stanford people how many tokens they would like.

I would be more than happy to assist in the process. You could also get in contact with the people who published [the paper](https://www.aclweb.org/anthology/L18-1350.pdf) and see if they would be interested in participating.

**Comment by yosiasz** [comment]
thanks very much @ftyers I will look at the paper. For now we have our own resources.

**Comment by yosiasz** [comment]
@ftyers so this is what I am thinking. I am a native speaker and have development experience. I want to do the creation of the next treebank in an automated fashion. Start small and keep building on it. Vet the output, clean up any issues, fix the automation code, rerun. wash, rinse , repeat. I don't see doing this manually which could take a very long time. What do you think of this approach? here are a some resources I could use to build a corpus of data to automate the creation of a new treebank. I could going about this totally in the wrong way. if so could you please provide me some guidance. 

https://am.wikipedia.org/
https://amharic.voanews.com/

**Comment by ftyers** [comment]
I have a few thoughts:

* The UD project only consists of manually-verified treebanks, and conversions of such, so we wouldn't want to include "parse banks" (e.g. output of automatic parsers that has not been manually verified). Of course you are welcome to do a parsebank project yourself.
* Treebanking iteratively using a rule-based parser is a completely reasonable idea, e.g. write a parser, run it on text, fix rules and iterate. Constraint grammar is one possibility for that, but you could also do something ad hoc. 
* Treebanking can take less time than you think, having the guidelines in place helps a lot, and you already have an Amharic treebank that you can consult. 

If you are interested in coming up with a project plan, feel free to [get in contact with me](http://xixona.dlsi.ua.es/~fran/email.html). I'd be happy to discuss a way forward.

**Comment by yosiasz** [comment]
Agreed. The automation part is just to create a conllu file with the basic headers info that does not need to be created manually that will then be manually verified.

**Comment by ftyers** [comment]
You could start out with something like [this](https://dpaste.com/BAU4883P8) using a [rough script](https://dpaste.com/H3Y3N32BX) based on [this](https://github.com/fgaim/HornMorpho/). Probably the tokenisation/segmentation would need to be fixed, but that probably needs to happen after the morphological disambiguation.

**Comment by yosiasz** [comment]
Amazing! thanks will take a look

**Comment by yosiasz** [comment]
ok, started on the script, couple of issues with l3. Once I sort that out going to feed this baby bigger and bigger corpus of data and see what we can come up with. I don't think I will even need stanza anymore. I could just go straight from this new treebank to spaCy.   thanks much!

**Comment by ftyers** [comment]
Note, the script won't give you a treebank, it will just give you the tokenisation (roughly) and the undisambiguated morphology. There is still the annotation step for syntactic structure. For that you could use something like [UD Annotatrix](https://jonorthwash.github.io/ud-annotatrix/) or [CoNLL-U Editor](https://github.com/Orange-OpenSource/conllueditor). 

But yes, once the treebank is prepared it should be possible to just input it into spaCy, or any other tool supporting CoNLL-U. I have been getting some good results from [UDpipe2](https://github.com/ufal/udpipe/tree/udpipe-2).

**Comment by yosiasz** [comment]
yes I get that. It wont give me a finished treebank but it will give me the basic entries  that I dont have to enter manually. I could populate a shell conll-u file with 100K entries in an seconds then go back in and add annotations manually.

**Comment by yosiasz** [comment]
@ftyers where is this l3 python module found in?

**Comment by ftyers** [comment]
@yosiasz I got it from [here](https://github.com/fgaim/HornMorpho/). Btw, we might want to take this discussion to email to avoid the inbox spam for the other developers. :)
