### ISSUE TITLE
amod guidelines examples

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#760]
[`amod`](https://universaldependencies.org/u/dep/amod.html) gives the example of "3 million dollar loan". Shouldn't this be `compound` rather than `amod`?

**Comment by amir-zeldes** [comment]
agreed, this looks like an error to me.

**Comment by nschneid** [comment]
b40441a also clarifies that the quantity in relation to "dollar"/"$" is `nummod` (mostly holds in EWT, though with "$" there are several instances that are incorrectly `compound`)
