### ISSUE TITLE
Preposition incorporation in Chinese

### ISSUE THREAD

**Issue by rafael75012** [UniversalDependencies/docs#763]
In Chinese, some PPs allow the incorporation of the preposition into the verb they follow.
It can be identified by the insertion of the aspectual suffix 了, behind the V+P (跳在了桌子上), but not inbetween (*跳了在桌子上).

```
跳在 桌子 上
jump+at table on
```

```
寫在 火車 上
write+at train on
```

```
跑向 電梯
run+toward elevator
```

Option 1
The verb and the preposition are two tokens, annotated as we normally do (**obl** and **case** relations).

<img width="153" alt="image" src="https://user-images.githubusercontent.com/24861889/107060286-1271a780-67d7-11eb-9cd7-c1077f17e4c7.png">

Option 2
The verb and the preposition are two tokens, annotated with **compound**.

<img width="148" alt="image" src="https://user-images.githubusercontent.com/24861889/107060483-4f3d9e80-67d7-11eb-9799-7de6a5aa11be.png">

Actually, **compound:vv** has been sporadically used in one Chinese treebank, but I am not sure it is the right way, because this relation is _specific_ to resultative and phase complements, and also those are verbs.
On the other hand, using the raw **compound** relation would not be totally in line with UD guidelines, because this relation is normally for noun-noun compounds, and also these compounds are freeer and more productive than the verb-prep words.

Option 3
The verb and the preposition form one token.

<img width="129" alt="image" src="https://user-images.githubusercontent.com/24861889/107060569-6a101300-67d7-11eb-8de4-fa8f8ba788cb.png">

The problem with Option 3 is that it adds important workload if the initial tokenization doesn't fit.
And the question is which morphological feature to use to specify that the token contains a preposition incorporation.
The **Incorporated=[]** feature has recently been introduced (https://universaldependencies.org/udw20/papers/2020.udw2020-1.22.pdf) for incorporated arguments of the verb.
I don't know what are the counterarguments against using it for the Chinese incorporated prepositions, concretely **Incorporated=[case]**.

Option 2 and Option 3 prevent from crossing links that Option 1 inevitably triggers when the suffix 了 is inserted.

<img width="163" alt="image" src="https://user-images.githubusercontent.com/24861889/107063153-50bc9600-67da-11eb-90bb-aac735f8712c.png">

**Comment by amir-zeldes** [comment]
Overall this looks fairly similar to phrasal verbs in Germanic languages, for which English and German use `compound:prt`. Since in English the tokens are spelled separately, we basically see option 2 (with the prt subtype). Option 3 seems more similar to the situation in German, where discontinuous cases are analyzed as `compound:prt`, and adjacent cases in which the particle element precedes the verb are tokenized as a single token (simply because that's when German orthography doesn't use a space). 

The German treebanks don't annotate this with a special incorporation feature AFAIK, though some native German corpora (not UD) include a morpheme by morpheme breakdown of complex verbs, including such elements when they are spelled together. I think if a subtype of compound is used, maybe `compound:prt` should be considered (since it's similar and already in use), and perhaps tokenization should follow whatever most tools for Chinese do? 

I would also point out that even if it looks like Option 3 puts workload on the tokenization, not choosing Option 3 also puts a load on tokenization, since you would need to correctly *not* treat them as one token. So either way the tokenizer needs to make some decision...

**Comment by rafael75012** [comment]
These English and German particles correspond (_roughly_ of course) in Chinese to what we actually annotate with **compound:dir** and **compound:vv**.
`
run back ~ 跑 回來`

`eat up ~ 吃 完`

 These English, German, and Chinese compounds can stand alone as words.

But this is not the case for the Chinese verb-prep compounds, which obligatorily take an argument.
`
*跳在
jump+at
`

`
*寫在
write+at
`

`
*跑向
run+toward
`

**Comment by amir-zeldes** [comment]
Some Germanic ones also require an object (German "umbringen" 'kill', originally "bring+around", English "pick up"), and they're not always directional (or at least not anymore, for example "take over" meaning "begin to control"). 

In any case I think it's the most similar construction I know of in UD, if you want to re-use an existing label, but of course you can also make a new subtype specifically for this construction.

**Comment by dan-zeman** [comment]
> On the other hand, using the raw compound relation would not be totally in line with UD guidelines, because this relation is normally for noun-noun compounds, and also these compounds are freeer and more productive than the verb-prep words.

I don't think this is true. The universal relation `compound` can be used for any type of compounding that is morphosyntactically different from other syntactic relations; subtypes are optional. Noun-noun compounds are in no way prominent, they just happen to be a typical subtype **in English.**

But I'm not against a well-defined subtype, it would be an improvement especially if used consistently across the Chinese treebanks.

**Comment by rafael75012** [comment]
> But I'm not against a well-defined subtype, it would be an improvement especially if used consistently across the Chinese treebanks.

Why not use a feature in this case? For instance **Incorporated=[]** I mention in the first post?

The (a) compounds annotated with **compound:vv** and **compound:vo** are freer than these (b) incorporated compounds: they can be separated by potential markers, aspectual suffix, and even adverbs and objects; while in (b) nothing can intervene inbetween the components.

So the use of a morphological feature rather than a syntactic subtype could specify that the components are in contrast more bonded in (b) than in (a).

**Comment by dan-zeman** [comment]
> Why not use a feature in this case?

One or the other. The discussion of `compound` subtypes applies if you treat the preposition as a separate word. If you treat it as a morpheme of the verb, then a feature is in place.

Treating it as incorporation would be especially useful if you also want to treat the aspectual marker as a bound morpheme of the verb. If, on the other hand, you will still attach it as an auxiliary, then I don't think we should call the process incorporation.

**Comment by rafael75012** [comment]
For incorporated prepositions V-P, in contrast to V-V compounds and V-Object compounds, nothing even not an aspectual suffix can intervene inbetween. 

So I wonder whether it corresponds to what @amir-zeldes refers in Germanic languages:

> adjacent cases in which the particle element precedes the verb are tokenized as a single token (simply because that's when German orthography doesn't use a space).

Then, treating this V-P compounds congruously as one token could maintain parallelism between languages.

In this case, a morphological feature could be used I think.

**Comment by amir-zeldes** [comment]
> treating this V-P compounds congruously as one token could maintain parallelism between languages

One point that makes it easier to decide about tokenization for German is that there are spaces, and "umbringen" etc. must be spelled together, so there is no doubt it is 'one word' in that sense. For Chinese it's less obvious what the general thinking is about these words. Looking at auto-select behavior by double clicking on words in Chrome, I notice that unlike noun compounds, if you double click on any part of "跳在", only one character is selected. Compare this to "桌子", where double clicking on either character auto-selects the whole 'word'.

But of course Chrome's double click behavior is by no means a gold standard for Chinese word segmentation - I just wonder what a survey of Chinese speakers would tell you about whether this is a 'two token compound' or just a single lexical item period (=1 token).

**Comment by dan-zeman** [comment]
> I just wonder what a survey of Chinese speakers would tell you

I think there are standards regarding Chinese word segmentation, both official (GB) and de-facto (influential corpora like the Penn Chinese Treebank). Maybe the treebank follows one of them, and there is thus an existing rule that covers this?

(In the past I've been asked about the segmentation standard used in Chinese GSD but since there is no info in the README file, I couldn't tell that person anything useful.)

**Comment by rafael75012** [comment]
The Penn Chinese Treebank has the three following solutions (p. 17 https://repository.upenn.edu/cgi/viewcontent.cgi?article=1038&context=ircs_reports):

(1) If P is 给, 为, 成, 作, 到, 出, 自, 向, 入, 以 and the verb is monosyllabic, treat V+P as one token.

(2) If P is 给, 为, 成, 作, 到, 出, 自, 向, 入, 以 and the verb is plurisyllabic, treat V+P as a compound formed by two tokens, and linked by the relation VRD (for Verb-resultative and verb directional compounds)

(3) If P is 在, 似, treat syntactically V+P as two tokens

How this categorization has been drawn is not explained, and is not in line with the 了 test, because if it were, there is no reason to separate the preposition 给 and the preposition 在, as they can behave similarly: 交给**了**保罗 ('give to Paul'), 跳在**了**桌子上 ('jump onto the table')
