### ISSUE TITLE
pronoun duplication

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#764]
In Welsh the pronominal possessor  can be repeated using a so-called independent pronoun. So both _fy nhŷ_ and _fy nhŷ i_ mean "my house". The second pronoun is optional, but frequent. Especially in spoken Welsh, there is a third form: _tŷ (f)i_ or (with the mutation normally caused by _fy_, even in its absence): _nhŷ (f)i_
```
1  fy    fy  PRON/dep   ...   2 nmod:poss
2  nhŷ   tŷ  NOUS       ...
```

```
1  fy    fy  PRON/dep    ...   2 nmod:poss
2  nhŷ   tŷ  NOUS        ...
3  i     i   PRON/indep  ...   3
```

```
2  nhŷ   tŷ  NOUS        ...
3  (f)i  i   PRON/indep  ...   3
```
What deprel would be appropriate here? `nmod:poss`, `dislocated`, `compound`(`:redup`) ?
In other issues compound was proposed for other kinds of duplications (#238, #307 and #449), however this is not a dislocation neither a compound.

The same construction is also used for direct objects on verbnouns (cf. #752)

```
1	Mae	VERB   ...
2	o 	PRON   ...
3	wedi	ADP   ...
4	fy	PRON/dep	5	obj
5	ngweld	NOUN/verbnoun	1	xcomp
6	i	PRON/indep	5	obj (?)
```

Is the deprel of _6 i_ also an `obj`?

**Comment by ftyers** [comment]
There is also something similar in K'iche'. I would analyse it simply as `nmod` or `nmod:poss` with the idea that it's something like "my house (of me)"

**Comment by jheinecke** [comment]
I agree for the possessive. But what would you to in the case of verbnoun (_fy ngweld i_)? both, _fy_ and _i_ are `obj`. I tried to find similar examples in other treebanks, but the closest I found is in French-Spoken _lui il vient_ ("he comes") where _il_ is subject of _vient_, and _lui_ is `dislocated` (attached to _vient_ as well). But as mentioned above, the Welsh is is not a dislocation. Currently I use `obj` as the least bad solution...

**Comment by Stormur** [comment]
Are the pronouns used with the verbnoun functioning in the same way as with the noun? I mean, could it be sensible to consider a more nominal relation like `nmod` in this case, too, if the verbnoun is "embedded" in a nominal context? Is the `ADP` _wedi_ also depending on it?

**Comment by jheinecke** [comment]
verbnouns behave syntactically as nouns. With the difference of posessives which correspond to the direct object of regular verbs  _fy nhŷ i_ "my house of me" _fy ngwled i_ "my seeing  of me" (= "my being seen"). _wedi_ is a TAM for anteriority. _Mae o wedi fy ngweld i_ means "He is after my seeing of me" = " He has seen me"
So in case of the non-verbnouns, I think (this time using 3rd person pronouns)

_his house of him_
```
1	ei	ei	PRON	dep	P=3|Num=Sg|Gen=M	2	nmod:poss
2	dŷ	tŷ	NOUN	noun	_		0	root
3	e	e	PRON	indep	P=3|Num=Sg|Gen=M	2	nmod
```

should do (knowing that _ei_ and _e_ have identical reference)

For direct objects I still hesitate to make both pronouns `obj`

_his seeing of him_ (= _seeing him_)

```
1	ei	ei	PRON	dep	P=3|Num=Sg|Gen=M	2	nmod:poss
2	weld	gweld	NOUN	verbnoun	_		0	root
3	e	e	PRON	indep	P=3|Num=Sg|Gen=M	2	nmod

**Comment by Stormur** [comment]
Maybe, also to avoid the embarrassment of a double, but actually repeated `obj`, from what you say (a preposition used to convey aspect, the same possessives as for nouns, the verbnoun marked as `NOUN`....) the whole construction might be treated in a fully nominal way? I do not know, the verbal interpretation (i.e. using `obj`) almost looks to me like an "analogical reinterpretation", in the sense that in most other European languages "more verbal" forms are used, so we want to see the same here... but it really looks different, like a modal construction (with `xcomp`) or a non-verbal predicate. In the latter case, the verbnoun could be the root. So would something like this not be acceptable? 

```
1	Mae	VERB    5? cop?  /  0  root
2	o 	PRON    5? nsubj? / 1  nsubj
3	wedi	ADP     5  case  
4	fy	PRON	5  nmod:poss
5	ngweld	NOUN	0  root  / 1  xcomp?
6	i	PRON	5  nmod(:poss)
```


For the copula part, I followed your translation. By the way, does not the validator complain for a nominal `xcomp`? 
Of course, I understand that the main difficulty is the elusivity of nominal forms of verbs, which are somewhat syntactically ambiguous, which was discussed at length elsewhere... 

Sorry for any misunderstandings, I am trying to better understand this (for me) unusual construction! :slightly_smiling_face:

**Comment by jheinecke** [comment]
Currently it is annotated like

```
1	Mae	VERB    0  root
2	o 	PRON    1  nsubj
3	wedi	AUX     5  aux
4	fy	PRON	5  obj
5	ngweld	NOUN	1  xcomp?
6	i	PRON	5  obj
```
In fact, in my copy of the Welsh treebank I use `nmod:obj` instead of `obj` since with real verbs other pronouns are used. But currently I change them to `obj` to stress the "object function" of these pronouns.
The validator is OK with that. I followed the Irish treebank which annotates this construction similarly: _... tá sé ag obair_ (UD_Irish-IDT/ga_idt-ud-train.conllu, sent-id 915

```
15      tá      bí      VERB    PresInd Mood=Ind|Tense=Pres     1       conj    _       _
16      sé      sé      PRON    Pers    Gender=Masc|Number=Sing|Person=3        15      nsubj   _       _
17      ag      ag      ADP     Simp    _       18      case    _       _
18      obair   obair   NOUN    Noun    VerbForm=Vnoun  15      xcomp   _       _
```
with the difference that in Welsh _wedi_ is a TAM (other can be in its place like _yn_, _am_, _ar_, _heb_, _newydd_) so it is tagged `AUX` and uses the deprel `aux`.

**Comment by Stormur** [comment]
> with the difference that in Welsh _wedi_ is a TAM (other can be in its place like _yn_, _am_, _ar_, _heb_, _newydd_) so it is tagged `AUX` and uses the deprel `aux`.

I saw that in your first post _wedi_ is annotated as an `ADP`, and now I am wondering if it and all these other elements also work "regularly" as prepositions in Welsh and Irish. This would be one of the decisive arguments for how to treat such constructions, including _fy - i_...

> In fact, in my copy of the Welsh treebank I use `nmod:obj` instead of `obj` since with real verbs other pronouns are used. But currently I change them to `obj` to stress the "object function" of these pronouns.

But if this is the case, then probably there is not much choice as to leave them as `nmod`s, as you are already doing, no? If I understand that pronouns functioning as objects assume other forms.

**Comment by jheinecke** [comment]
you spotted it right, I made an error in my earlier posting, _wedi_ should be AUX, not ADP. Since my question was about the doubled object, I did not recheck the rest. 
So you propose putting all arguments of verbnouns as `nmod` which they are syntactically? Even though from a semantic point of view it's the object?

**Comment by sylvainkahane** [comment]
> So you propose putting all arguments of verbnouns as nmod which they are syntactically? Even though from a semantic point of view it's the object?

Yes the UD annotation is supposed to be syntactic. For instance, in English, _Chomsky_ will be `nmod` in _the critic of Chomsky_ , no matter if it is agent or patient.

**Comment by dan-zeman** [comment]
> For direct objects I still hesitate to make both pronouns obj

You cannot have two children of one predicate both attached as `obj`.

And I, too, would use `nmod`, following syntax and ignoring semantics.

**Comment by jheinecke** [comment]
@dan-zeman that's exactyl why I hesitate(d) :-) Since in Welsh the verbnoun is far more frequent (currently 3025 verbnouns against 756 inflected verbs (other than the auxiliary _bod_ ) annotating (semantic) objects as `nmod` would result many nmod-dependents on a same head (verbnoun) and we would lose information. I think in this case I should create `nmod:obj` Welsh-specific deprels or another standard is needed (Irish and Scottish-Gaelic also use obj/obl for dependents of verbnouns (tagged `NOUN`)
