### ISSUE TITLE
Singulative in Beja

### ISSUE THREAD

**Issue by RZiane** [UniversalDependencies/docs#766]
Hello everyone,
We are currently preparing a Universal Dependencies Treebank of Beja, a Cushitic language spoken in Sudan. 
This language as several singulative suffixes for collective nouns (different from singular nouns which are unmarked), we couldn't find the morphological feature that is associated to this kind of morphology in UD. Do you have any ideas or suggestion to this issue? 

Here are a few examples:

buːb-aːji=t 
sparrow-SING=F

i=malak-taːji dhaːj j-ʔi 
the angel came to him

uːn i=ʤamiːl-aːj 
"this Djamilay' (Djamila is the name of a tribe)

ʤoːhar-aːji=t ti=joːt jhaks-eːtiːt 
'after the monster had taken one jewel' (ʤoːhar 'jewels")

Thanks in advance. 

Martine Vanhove (LLACAN, CNRS)
Rayan Ziane (M2 University of Orléans)

**Comment by dan-zeman** [comment]
> buːb-aːji=t
> sparrow-SING=F

So _bu:b_ means “sparrows” and _bu:ba:jit_ means “sparrow”? Can't we simply annotate the former as `Number=Plur` and the latter as `Number=Sing`, despite the latter being morphologically more complex? Or would “sparrow” also have the unmarked singular form that you mentioned?

**Comment by sylvainkahane** [comment]
_bu:b_ is a collective/massive noun. The singulative is not a singular: it means something like 'a piece of X'.

**Comment by dan-zeman** [comment]
In that case, perhaps both _bu:b_ and _bu:ba:jit_ should have `Number=Coll`, and a language-specific feature should distinguish the singulative form.

**Comment by bulbulistan** [comment]
Same thing crops up in Arabic, how is it handled there?

**Comment by ftyers** [comment]
There is also a singulative in Chukchi (Dunn, 1999: §6.3.3), but we treat it as a derivation as it comes before other derivational affixes.

----
* Michael Dunn (1999) *A Grammar of Chukchi*. Ph.D. thesis, Australian National University.

**Comment by colinbatchelor** [comment]
There is also a singulative/collective distinction in Breton and Welsh but the treebanks just mark the singular/plural distinction.

**Comment by RZiane** [comment]
Thanks to all of you for your answers, we couldn't find any other way to represent the phenomenon than with a language specific boolean feature called Singulative with a Yes value.
