### ISSUE TITLE
Getting the CoNNL-U environment work for dep examples

### ISSUE THREAD

**Issue by Traubert** [UniversalDependencies/docs#769]
I added a dependency example by directly copying a sentence from our treebank, akk_RIAO, as per https://spyysalo.github.io/annodoc/.

You can see my attempt here: https://github.com/UniversalDependencies/docs/blob/397ddf726123327878ee61ac7c958117c710517d/_akk/dep/advmod-neg.md

It doesn't seem to be rendering correctly:
https://universaldependencies.org/akk/dep/advmod-neg.html

Any ideas what went wrong?

**Comment by martinpopel** [comment]
What about deleting the apostrophe (or unclosed left single quote) in`title: 'advmod:neg`?
(I am no expert on Annodoc, just noticed this.)

**Comment by dan-zeman** [comment]
> What about deleting the apostrophe (or unclosed left single quote) intitle: 'advmod:neg?

Or rather add the missing apostrophe at the end of that line. [The result](https://universaldependencies.org/akk/dep/advmod-neg.html) looks to me like an error in the MarkDown header rather than in the CoNLL-U snippet.

**Comment by Traubert** [comment]
Thanks @martinpopel and @dan-zeman, I'm a klutz, it was indeed the quoting.
