### ISSUE TITLE
advmod attached to nomimal

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#779]
https://universaldependencies.org/u/dep/advmod.html

This page start saying that 

> An adverbial modifier of a word is a (non-clausal) adverb or adverbial phrase that serves to modify a predicate or a modifier word.

But in https://universaldependencies.org/u/overview/syntax.html we have an example were `right` is advmod of `midnight`.  Is it a condradiction? We do have an example in Portuguese that suggest an analysis where and advmod attached to a PROPN:

> `pelo menos o Judiciário...`

```
CF950-2> Mas eu imagino que deveria se dotar, pelo menos o Judiciário, de medidas que possibilitassem a concessão do perdão judicial.

─┮  
 │ ╭─╼ Mas CCONJ cc 1 3  
 │ ├─╼ eu PRON nsubj 2 3  
 ╰─┾ imagino VERB root 3 0  
   │ ╭─╼ que SCONJ mark 4 5  
   ├─┾ deveria VERB ccomp 5 3  
   │ │                                ╭─╼ se PRON expl:pass 6 7  
   │ ├────────────────────────────────┾ dotar VERB xcomp 7 5  
   │ │                                ├─╼ , PUNCT punct 8 7  
   │ │ ╭─┮ por ADP advmod 9 13        │ 
   │ │ │ ├─╼ o DET fixed 10 9         │ 
   │ │ │ ╰─╼ menos ADV fixed 11 9     │ 
   │ │ ├─╼ o DET det 12 13            │ 
   │ ╰─┶ Judiciário PROPN nsubj 13 5  │ 
   │                                  │ ╭─╼ , PUNCT punct 14 16  
   │                                  │ ├─╼ de ADP case 15 16  
   │                                  ╰─┾ medidas NOUN obl 16 7  
   │                                    │ ╭─╼ que PRON nsubj 17 18  
   │                                    ╰─┾ possibilitassem VERB acl:relcl 18 16  
   │                                      │ ╭─╼ a DET det 19 20  
   │                                      ╰─┾ concessão NOUN obj 20 18  
   │                                        │ ╭─╼ de ADP case 21 23  
   │                                        │ ├─╼ o DET det 22 23  
   │                                        ╰─┾ perdão NOUN nmod 23 20  
   │                                          ╰─╼ judicial ADJ amod 24 23  
   ╰─╼ . PUNCT punct 25 3  
```

**Comment by nschneid** [comment]
Yes, there are adverbs that can premodify NPs. Your example is "pelo menos" 'at least'.

Another example in EWT:

- The Spanish trains and the Istanbul bombings are **only** the beginning.

EWT has advmod(beginning, only) and tags "only" as ADV. Note that this precedes the article, unlike how an adjective would behave.

Maybe we should add a hedge to the definition of advmod, because it is not 100% limited to predicate modifiers.

**Comment by dan-zeman** [comment]
Agreed with @nschneid. UD lacks a dedicated relation for a modifier word that is neither a determiner, nor a numeral or adjective, and it modifies a nominal. In the languages I have seen this (including Czech), these modifier words are typically adverbs (I think just a small subset of adverbial phrases can occur here, such as _only_, _not only_, _especially_), so `advmod` makes sense.

Some treebanks use the subtype [advmod:emph](https://universaldependencies.org/u/dep/advmod-emph.html) for this.

**Comment by dan-zeman** [comment]
Added a warning to the documentation (8d4d7f70c124458e30877dea58d54f3eff41cef2), closing.
