### ISSUE TITLE
Status suffixes in the Mayan languages

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#781]
Status suffixes are a particular feature of the Mayan languages. These are suffixes that appear on verbs (and directionals which historically come from verbs). The particular status suffix a verb bears is conditioned by an amalgamation of morphosyntactic facts about the clause, including:
- the transitivity of the verb, 
- whether the verb is a root verb (i.e., CVC form) or has undergone derivation, 
- the tense-aspect-mood of the clause, and 
- whether the verbform is an simple or dependent.

A verb has dependent status if it is volitive (imperative, optative, hortative) or if it incorporates movement.

In K’iche’ there are four status suffixes:
- *-ik*: intransitive, phrase final, independent
- *-oq*: intransitive , phrase final, dependent
- *-u* ∼ *-o*: transitive, phrase final, independent
- *-u’* ∼ *-a’* ∼ *-o’*: transitive, phrase final, dependent

![imatge](https://user-images.githubusercontent.com/449545/116892440-bf698e00-ac27-11eb-98eb-c59d9ebbf453.png)

In this example, the directional, itself derived from a verb, bears the status suffix *-ik*. This indicates that:
- the verb is intransitive, 
- is non-dependent (e.g. is neither volitive nor incorporates movement), and
- is at the edge of a prosodic phrase

The main verb *tzaq* ‘fall’ does not bear its own status suffix because, in K’iche’, these suffixes only appear at the edges of certain prosodic phrases. These is no such phrase break between the verb and directional, and so only the latter bears the status suffix. 

I would like to propose analysing these status suffixes as `aux`, as they are function words which accompany the verb and express/contribute to aspect and mood.  For instance, swapping the *-ik* and *-oq* status suffixes on an intransitive verb (in certain aspects) is enough to change the interpretation from conditional to imperative.

**Comment by Stormur** [comment]
If I have understood welI, I would personally fully agree with the interpretation as an auxiliary (meaning both `AUX` and `aux`), but I have two questions/remarks:

1. should the `aux` relation better not go from the suffix to the verb directly? 
2. is this directional element also some kind of auxiliary, I mean: is it a functional element? Or is it something like phrasal verbs in English? In the former case, could the whole block _b'ik_ be seen as the `AUX`, and the suffix determine its particular mrphological features?
3. What morphological features are assigned to the `SS`?

**Comment by ftyers** [comment]
> If I have understood welI, I would personally fully agree with the interpretation as an auxiliary (meaning both `AUX` and `aux`), but I have two questions/remarks:
> 
> 1. should the `aux` relation better not go from the suffix to the verb directly?

I originally had that, but the issue is that if you have something like TV DIR SS then the SS is selected for the intransitive not for the transitive. So it's clear that the directional is governing it.

> 2. is this directional element also some kind of auxiliary, I mean: is it a functional element? Or is it something like phrasal verbs in English? In the former case, could the whole block _b'ik_ be seen as the `AUX`, and the suffix determine its particular mrphological features?

It is not a functional element according to my understanding.

> 3. What morphological features are assigned to the `SS`?

No morphological features, although potentially there could be a `PhraseFinal=Yes` language specific feature...

**Comment by dan-zeman** [comment]
Are these suffixes ever written separately? I briefly looked at _ik_ in the data and it seems to me that it is always cut off the verb using the MWT mechanism.

I feel uncomfortable about cutting a suffix off a verb, only to attach it as an auxiliary in the next step. One could propose to do that with inflectional suffixes in hundreds of other languages, but UD does not focus on relation between individual morphemes. ([The tokenization guidelines](https://universaldependencies.org/u/overview/tokenization.html) say: "The UD annotation is based on a lexicalist view of syntax, which means that dependency relations hold between words. [...] there is no attempt at segmenting words into morphemes.") Instead, I would keep it with the verb as one word ("do not segment unless you really have to"), and reflect it using language-specific features: `Status=Plain|Dep`, `Subcat=Intr|Tran`, `PhraseFinal=Yes`.

If the directional has the suffix, the features would go with the directional.

Annotating the directional as `ADV` and `advmod` seems to be a sensible approximation with the means UD has, but as I think of it now, another option might be to keep the directionals as a special type of verbs (`VERB`, `VerbType=Dir`), and connect them to the main verb via `compound:svc`.

**Comment by ftyers** [comment]
> Are these suffixes ever written separately? I briefly looked at ik in the data and it seems to me that it is always cut off the verb using the MWT mechanism.

In K'iche' at least they are written together. The reason I went for this strategy is that they appear both on verbs and these *directionals*, also it's not clear exactly what they are.

> Instead, I would keep it with the verb as one word ("do not segment unless you really have to"), and reflect it using language-specific features: Status=Plain|Dep, Subcat=Intr|Tran, PhraseFinal=Yes.

The disadvantage with that is that it makes searching harder (at the moment it's easy to search for "all verbs with a dependent that has the lemma *ik*". In addition the value of `Subcat` would conflict for the root and for a valency-altered form (e.g. the passive or antipassive. The root would be `Subcat=Tran` but the status suffix would be `Subcat=Intr`. 

> Annotating the directional as ADV and advmod seems to be a sensible approximation with the means UD has, but as I think of it now, another option might be to keep the directionals as a special type of verbs (VERB, VerbType=Dir), and connect them to the main verb via compound:svc.

I'm not sure about this. They don't have any valency, so I'd prefer to not have them as verbs. It is a small and finite set.

**Comment by ftyers** [comment]
In an effort to appease the validator before the release deadline I've changed `aux:ss` to `dep:ss`, but I would like to continue the discussion :)

**Comment by dan-zeman** [comment]
> In K'iche' at least they are written together. The reason I went for this strategy is that they appear both on verbs and these _directionals_, also it's not clear exactly what they are.

If it's not clear then it is safer not to make them words (there will be fewer things that we must say about them) :-)

> > Instead, I would keep it with the verb as one word ("do not segment unless you really have to"), and reflect it using language-specific features: Status=Plain|Dep, Subcat=Intr|Tran, PhraseFinal=Yes.
> 
> The disadvantage with that is that it makes searching harder (at the moment it's easy to search for "all verbs with a dependent that has the lemma _ik_".

So if the directionals are marked somehow (which I think would be nice in any case), it would now be searching for "all verbs that have particular features, or a directional dependent with such features. That does not look difficult – I do similar searches all the time.

> In addition the value of `Subcat` would conflict for the root and for a valency-altered form (e.g. the passive or antipassive. The root would be `Subcat=Tran` but the status suffix would be `Subcat=Intr`.

Ah, yes. So if we need (or want) to annotate also the root `Subcat`, we can do what we do in UD in similar situations: layered features. I would probably go for making the default layer the one of the actual form (suffix), i.e., `Subcat=Intr|Subcat[root]=Tran`.
 
> > Annotating the directional as ADV and advmod seems to be a sensible approximation with the means UD has, but as I think of it now, another option might be to keep the directionals as a special type of verbs (VERB, VerbType=Dir), and connect them to the main verb via compound:svc.
> 
> I'm not sure about this. They don't have any valency, so I'd prefer to not have them as verbs. It is a small and finite set.

Okay, not a big deal. They can be a special type of adverbs as well (`AdvType=Dir`?) But a subtype of the `compound` relation is not necessarily excluded. I think this is the first language with directionals in UD, so we don't have a precedent yet.

**Comment by Stormur** [comment]
If these elements are in any sense adverbial directionals and they retain a "full-word status", then I think that the relation to go is `advmod` rather than compound (cfr. #761), possibly a subtype of it (`advmod:dir`?): this would make them easy to retrieve. And in addition to that, they might be particular `ADV`s which can take some set of (morphological) features, such as `AdvType=Dir` proposed by Dan. 

> > If I have understood welI, I would personally fully agree with the interpretation as an auxiliary (meaning both `AUX` and `aux`), but I have two questions/remarks:
> > 
> > 1. should the `aux` relation better not go from the suffix to the verb directly?
> 
> I originally had that, but the issue is that if you have something like TV DIR SS then the SS is selected for the intransitive not for the transitive. So it's clear that the directional is governing it.

I am not sure if I understand what is happening here, but now I am curious :slightly_smiling_face:  Do you mean that _tzaq_ is basically transitive, and the directional makes it intransitive as we see in the example, and thus can select the _ik_ suffix?

**Comment by ftyers** [comment]
> And in addition to that, they might be particular ADVs which can take some set of (morphological) features, such as AdvType=Dir proposed by Dan.

The [`AdvType=Dir`](https://universaldependencies.org/quc/feat/AdvType.html) relation is already used :)

> I am not sure if I understand what is happening here, but now I am curious slightly_smiling_face Do you mean that tzaq is basically transitive, and the directional makes it intransitive as we see in the example, and thus can select the ik suffix?

Not quite, but let's take a few  examples:

1. *Kakitik ixim ri achijabʼ.* "The men sew the maize"
   * Ka-ø-ki-tik ixim ri achij-abʼ
   * IMPF-B3SG-A3PL-sew maize the man-PL
2. *Ketikon ri achijabʼ.* "The men sew"
   * K-e-tik-on ri achij-abʼ
   * IMPF-B3PL-sew-AP the man-PL
3. *Ketikonik.* "They sew"
   * K-e-tik-on-ik
   * IMPF-B3PL-sew-AP-SS

So in (1) it's a transitive verb with both subject and object agreement and an expressed subject and object. It could equally well be *Kakitiko* Ka-ø-ki-tik-o "[They] sew [it]". In (2) the verb has been antipassivised which means the object agreement is omitted, any object would need to be introduced with an oblique. In (3) the verb is antipassivised as before but the subject is left unspecified which leaves the verb at a phrase boundary and thus the status suffix (note intransitive *-ik* not transitive *-o*) appears.

**Comment by ftyers** [comment]
> If it's not clear then it is safer not to make them words (there will be fewer things that we must say about them) :-)

In some ways I agree and in some I disagree. I wanted to avoid the `Foc=kaan` thing like in Finnish and I didn't know how to split up the `Feature=Value` pairs in another way. Also the segmentation comes from a morphological analyser which also splits them in this way. I'm not completely against not splitting them. But I want to get more of a Pan-Mayan perspective before changing anything. We should have a project on Uspanteko this summer, so no doubt it will come up. I also think that this is reasonably restricted to Mayan languages, but I'd love to hear some other input! 

> So if the directionals are marked somehow (which I think would be nice in any case), it would now be searching for "all verbs that have particular features, or a directional dependent with such features. That does not look difficult – I do similar searches all the time.

The problem is that now in order to search for something you have to remember and type in 3 features instead of just 1 lemma, e.g. *ik* or `Subcat=Intr|PhraseFinal=Yes|Status=Ind`. It's less ergonomic and I'm not sure what it gains.

> Ah, yes. So if we need (or want) to annotate also the root Subcat, we can do what we do in UD in similar situations: layered features. I would probably go for making the default layer the one of the actual form (suffix), i.e., Subcat=Intr|Subcat[root]=Tran.

I don't like this for some reason. I do and do want to include the transitivity, in any language with polypersonal agreement it is a core part of the grammar. 

> Okay, not a big deal. They can be a special type of adverbs as well (AdvType=Dir?) But a subtype of the compound relation is not necessarily excluded. I think this is the first language with directionals in UD, so we don't have a precedent yet.

Agree, this is how it is done at the moment.
