### ISSUE TITLE
Part of the agreement paradigm written with a space

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/docs#782]
In K'iche', the formal 2nd person singular and plural is formed with a clitic item that follows the verb and is written with a space (see *la* and *alaq* below).

![imatge](https://user-images.githubusercontent.com/449545/116960244-bdd7ae80-ac97-11eb-948a-1a63e9a36a55.png)

This isn't a pronoun, at least no-one analyses it as a pronoun and it is considered to be part of the agreement paradigm.

I wanted to call it `AUX` -- `aux` as it is part of the verb complex, just written separately, but that doesn't seem possible. 

Currently it is `PRON` and `Clitic=Yes|Polite=Form|PronType=Prs`. But then what should the relation be? Neither `nsubj` nor `obj` seem right, nor does `expl`. The validator chokes on `aux`, so I'm a bit stumped. Thoughts?

**Comment by Stormur** [comment]
Hm, if it really isn't a pronoun and just acts as a "clitic morpheme" for person/number agreement, then I would also agree with an `AUX` interpretation... why isn't it possible?

But if it is indeed a pronoun, the fact that it may be obligatory and appear together with a "main" subject would make me veer towards an `expl`, maybe a thing like `expl:nsubj`. It might be not so conceptually different from those obligatory object clitics like in Greek or Bulgarian (if I am not mistaken).

**Comment by ftyers** [comment]
> Hm, if it really isn't a pronoun and just acts as a "clitic morpheme" for person/number agreement, then I would also agree with an AUX interpretation... why isn't it possible?

There is a fixed list of valid functions for auxiliaries in the validator and I can't make it fit with any of them :)
```
        <select name=function1>
          <option>-----</option>
          <option value="Aspect=Perf">Periphrastic aspect: perfect</option>
          <option value="Aspect=Imp">Periphrastic aspect: imperfect</option>
          <option value="Aspect=Dur">Periphrastic aspect: durative</option>
          <option value="Aspect=Prog">Periphrastic aspect: progressive</option>
          <option value="Aspect=Prosp">Periphrastic aspect: prospective</option>
          <option value="Aspect=Iter">Periphrastic aspect: iterative</option>
          <option value="Tense=Past">Periphrastic tense: past</option>
          <option value="Tense=Pres">Periphrastic tense: present</option>
          <option value="Tense=Fut">Periphrastic tense: future</option>
          <option value="Voice=Pass">Periphrastic voice: passive</option>
          <option value="Voice=Cau">Periphrastic voice: causative</option>
          <option value="Mood=Cnd">Periphrastic mood: conditional</option>
          <option value="Mood=Sub">Periphrastic mood: subjunctive</option>
          <option value="Mood=Imp">Periphrastic mood: imperative</option>
          <option value="Mood=Irr">Periphrastic mood: irrealis</option>
          <option value="neg">Needed in negative clauses (like English “do”, not like “not”)</option>
          <option value="int">Needed in interrogative clauses (like English “do”)</option>
          <option value="Mood=Nec">Modal auxiliary: necessitative (“must, should”)</option>
          <option value="Mood=Pot">Modal auxiliary: potential (“can, might”)</option>
          <option value="Mood=Des">Modal auxiliary: desiderative (“want”)</option>
        </select>
```

**Comment by ftyers** [comment]
In an effort to appease the validator before the release deadline I've changed `aux` to `dep:agr`, but I would like to continue the discussion :)

**Comment by dan-zeman** [comment]
> There is a fixed list of valid functions for auxiliaries in the validator and I can't make it fit with any of them :)

The list is there to make people think twice about their would-be auxiliaries and not let them register wildly anything and everything :) But it is not necessarily fixed, if a discussion like this one reveals that additional auxiliary functions should be approved.

Auxiliaries often carry some or all of the agreement features but until now I assumed that there is always some more verbal feature (`Tense`, `Aspect`, `Voice` etc.) involved, too. So it seems like we need a separate function

<pre>
  &lt;option value="agr"&gt;Cross-reference of core argument(s) without additional TAMVE features&lt;/option&gt;
</pre>

right?

If so, then we may want to mention it explicitly in the [documentation of AUX](https://universaldependencies.org/u/pos/AUX_.html).

**Comment by ftyers** [comment]
> The list is there to make people think twice about their would-be auxiliaries and not let them register wildly anything and everything :) But it is not necessarily fixed, if a discussion like this one reveals that additional auxiliary functions should be approved.

Yes, I think it's good in general, I just think we should be a bit more broad in our definition. Also I could see this as being something we want to save for the next revision, or at least have more discussion of. 

>     <option value="agr">Cross-reference of core argument(s) without additional TAMVE features</option>

I think that is an excellent option!

**Comment by dan-zeman** [comment]
> > ```
> > <option value="agr">Cross-reference of core argument(s) without additional TAMVE features</option>
> > ```
> 
> 
> I think that is an excellent option!

Implemented.
https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=quc
