### ISSUE TITLE
Relation for topicality and dialogues

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#783]
I was wondering if there is an "official" way to mark syntactically expressed topicality as different from a (nominal) subject, and fro mwhat I saw it seems that it has not been discussed explicitly in any issue.

I am not an expert of such languages (so please feel free to correct me), but from what I know Japanese is an example of language which distinguishes the topic and the subject, by means of the two postpositions _wa_ and _ga_, and in the literature I find examples where they seem to coexist, such as (I am able to write only the transcription):

_Aiko **wa** me **ga** aoi desu_ ~'As for Aiko, her eyes are blue', i.e. 'Aiko has blue eyes / Aiko's eyes are blue'

How does _Aiko wa_ needs to be treated here? It does not look as an oblique/adverbial clause, but rather as a paratactical, albeit very grammaticalised, construction.

The same goes for Chinese (again from literature, again only transcription), where as far as I have learnt a topic-comment structure is quite standard:

_nèike shù yèzi dà_ ~'That tree - the leaves are big', i.e. 'That tree has big leaves / That tree's leaves are big'

Sometimes this kind of topic-comment juxtaposition is used to express possession, as maybe in these examples, but not always. 

----

This phenomenon may be less evident in many European languages, but for me this more general question arose while looking for a fitting relation for e.g. dialogues:

_NAME1 bla bla bla...
NAME2 bla bla bla..._

I think of this as a variant of a topic-comment structure, in that it is something like "As for NAME1, he says: ...", and I was considering a paratactic relation for this. However, `parataxis`, especially with no subtype, seems too generic to me, not least because this is not simply a juxtaposition of two sentences or elements. In any case, if both the speaker name and their line are part of the same "sentence", it seems to me that the speaker name is somehow subordinated to the line, and not the other way round, lest obtaining a very unwieldily asymmetric syntactic tree. 

I saw the Italian language-specific [`parataxis:nsubj`](https://universaldependencies.org/it/dep/parataxis-nsubj.html) relation, which might go into the right direction, but the speaker is only indirectly the "subject" of their line.

**Comment by dan-zeman** [comment]
For Japanese, see Section 4.3 of [this upcoming CL article](https://doi.org/10.1162/coli_a_00402).

**Comment by Stormur** [comment]
Hm, thanks, this is interesting! I had not considered it favouring the parasintactic aspect, but did I miss something or was this part of the documentation updated recently?

Anyway, has there been some discussion or porposal about distinguishing this (systematic) kind of dislocation from afterthoughts (sentence 63 in the article) or redundant elements (last examples [here](https://universaldependencies.org/u/dep/dislocated.html))? The latter one in particular seems to be a different construction.

OK, anyway, with regard to theatrical roles, which is a very particular case, would `dislocated` fit better than `parataxis`?

**Comment by dan-zeman** [comment]
Within the current guidelines, the closest thing to theatrical roles I can think of is [reported speech](https://universaldependencies.org/u/dep/parataxis.html#treatment-of-reported-speech), which has been annotated as `parataxis`. Though in theatre plays, the speech verb is typically elided.

**Comment by amir-zeldes** [comment]
> OK, anyway, with regard to theatrical roles, which is a very particular case, would dislocated fit better than parataxis?

Unless there is a strong reason to do otherwise, I would not treat a theatrical speaker label as part of the sentence, but rather encode it as a speaker attribute, which would be more consistent with spoken data. Instead of:

```CoNLL-U
1	Kim	Kim	PROPN	NNP	_	0	root	_	_
2	:	:	PUNCT	:	_	1	punct	_	_
3	hello	hello	INTJ	UH	_	1	parataxis	_	_
```

I would much rather see:

```CoNLL-U
# speaker = Kim
1	hello	hello	INTJ	UH	_	0	root	_	_
```

But of course if someone literally say "Kim colon , hello", then you need to keep the name as a token, so there should be a general answer to the question either way (in which case `parataxis` seems ok to me).

**Comment by Stormur** [comment]
Yes, the case is of a text (a written source) where the role, or more in general the speaker, is prepended to the actual sentence(s), possibly with no punctuation. For example:

_SPEAKER1 blablabla. blablabla, blablabla. SPEAKER2 bla! blablabla. blablabla. SPEAKER1 ....._

It does not really make sense to split it into two sentences, as the two parts still have a relation; we cannot remove the names either. I was musing about a relation of topicality maybe because I was distracted by the orthography, but in the end it is indeed a kind of marginalised ellipsis of the verb of saying, so `parataxis`. I still think that a subtype like `parataxis:role` or `parataxis:speaker` could help highlight this particular occurrence.

**Comment by nschneid** [comment]
Related to #933
