### ISSUE TITLE
acomp page missing?

### ISSUE THREAD

**Issue by omarzd** [UniversalDependencies/docs#789]
Hello. I could not find the page describing the `acomp` relation. The [2014 reference Stanford paper](https://nlp.stanford.edu/pubs/USD_LREC14_paper_camera_ready.pdf) mentions that `acomp` can be generalized within `xcomp`. But I still think that `acomp` should be mentioned for reference and completion. A hyperlink on `acomp` could lead to the same page as [`xcomp`](https://universaldependencies.org/u/dep/xcomp.html) with the latter page making a note about `acomp`. [The Stanford typed dependencies manual (2008)](https://downloads.cs.stanford.edu/nlp/software/dependencies_manual.pdf) mentions `acomp`.

**Comment by nschneid** [comment]
Stanford Dependencies and Universal Stanford Dependencies were precursors to Universal Dependencies; UD has never included an `acomp` relation. The UDv2 relations are listed at https://universaldependencies.org/u/dep/.

If you're curious about the older papers, some of the history of the evolution of UD is explained at https://universaldependencies.org/introduction.html. The two most current papers on UD are:

* Nivre et al. (2020). [Universal Dependencies v2: An Evergrowing Multilingual Treebank Collection](https://www.aclweb.org/anthology/2020.lrec-1.497/). LREC.
* de Marneffe et al. (2021). [Universal Dependencies](https://doi.org/10.1162/coli_a_00402). *Computational Linguistics*.
