### ISSUE TITLE
Inconsistent examples in nmod and obl

### ISSUE THREAD

**Issue by kirandhakal25** [UniversalDependencies/docs#790]
Example 2 in [`nmod`](https://universaldependencies.org/en/dep/nmod.html) and example 5 in [`obl`](https://universaldependencies.org/u/dep/obl.html) are the same
- give the toys to the children

But they have different dependency trees. And this seems inconsistent.

**Comment by nschneid** [comment]
Good catch! The nmod one was outdated. I've fixed it.
