### ISSUE TITLE
optional plurals

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#800]
In https://github.com/UniversalDependencies/UD_Portuguese-Bosque/issues/328, we have identified at least one case in the Bosque Portuguese corpus where a text contains a popular technique to mark an optional plural:

> .. o(s) tratamento(s) ..  / ... the treatment(s) ...

This can actually be interpreted as a conjunction or a disjunction of readings depending on the context. I am sure this is style is not used only in Portuguese. The question is how we should annotate these tokens? What should be the lemma? The Features of Number?

**Comment by nschneid** [comment]
Here are some cases in English EWT, where the parentheses and plural suffix are separate tokens: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=6100c12994118&clustering=N.upos
With this tokenization I think UPOS=`X`, lemma=s probably make sense. Dunno whether there should be morphological features on the suffix.

GUM has 2 instances that don't tokenize the suffix and use `Number=Plur`: http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=6100c2aaed557&clustering=N.upos

**Comment by amir-zeldes** [comment]
I'm not so sure we should be tokenizing these things apart... And I don't think they are literally equivalent to a disjunction. I think they're "their own thing" to some extent, so I would prefer some feature or something if anything, or maybe just `Number=Plur,Sing`? BTW we have the same with Gender in gendered nouns/adjectives in many languages (German: WissenschaftlerInnen "female/male scientists", Hebrew חבר/ה "male/female friend" - note it's just one friend!)

**Comment by arademaker** [comment]
Yes, I agree with @amir-zeldes and it also makes more sense to me something in the features.

**Comment by dan-zeman** [comment]
Related issue: #224
