### ISSUE TITLE
adjective phrases

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#805]
> The adjective can initiate the phrase (e.g. fond of steak), conclude the phrase (e.g. very happy), or appear in a medial position (e.g. quite upset about it). The dependents of the head adjective—i.e. the other words and phrases inside the adjective phrase—are typically adverb or prepositional phrases, **but they can also be clauses (e.g. louder than you are**). Adjectives and adjective phrases function in two basic ways, attributively or predicatively. 

From https://en.wikipedia.org/wiki/Adjective_phrase

So according to https://universaldependencies.org/u/dep/amod.html, the `amod` relation can also be used to clauses?

**Comment by nschneid** [comment]
The dependents of the head adjective can be clauses, yes. See https://universaldependencies.org/u/overview/specific-syntax.html#comparatives for the treatment of comparative constructions specifically.

**Comment by manning** [comment]
[This post has been edited to correct an earlier mistaken statement, as discussed below.]

As in the overall [relation table](https://universaldependencies.org/u/dep/index.html), `amod` is used for connecting a modifier to a nominal but is not used connecting an adjective-headed clauses (like relative clauses). A modified modifier or a modifier with dependents is still a modifier, and so _certain_ in any of _a certain man_, _a very certain man_ or _a man certain that he is correct is dangerous_ would be an `amod`. However in the nominal _a man who is certain_, _certain_ would be an `acl`. The adjective _certain_ can also be used with a clausal complement. If done predicatively (_He is certain that he is correct_) then it is the head (`root`) of the sentence with a `ccomp` complement. If done as a noun modifier (_a man certain that he is correct is dangerous_) it is probably reasonable to still regard the complement as a `ccomp` complement of _certain_, but in practice there is variation and `advcl` has also been used.

**Comment by nschneid** [comment]
> If done as a noun modifier (_a man certain that he is correct is dangerous_) then _certain_ is an _acl_ of _man_ (and we still have a `ccomp` complement of _certain_).

Wait, really? That's not what's implemented in EWT: http://match.grew.fr/?corpus=UD_English-EWT@dev&custom=611878606f678

**Comment by amir-zeldes** [comment]
> amod is not used connecting to clauses

Right, if the modifier itself is a clause headed by an adjective, it will not be amod (for example a relative headed by an ADJ, like "a car which is blue/acl:relcl"

> a man certain that he is correct is dangerous ... That's not what's implemented in EWT

My understanding is the same as @nschneid . This is also not what is implemented in UD_English-GUM (or I think several other corpora as well?). I think the external function of an adjective (i.e. whether or not it is an attributive adjective modifier, and therefore `amod`) is a separate question from whether or not it is modified by a clause itself.

By analogy, I believe if a noun has a clause modifier, that does not make *it* into a clausal modifier: it can still be a simple `nmod` or `obl`, and then internally it can dominate a clause. If my understanding of this is wrong please let me know!

**Comment by manning** [comment]
Okay, I agree, I was wrong. I'll retract that bit, and edit the post above!
