### ISSUE TITLE
Question about POS tagging

### ISSUE THREAD

**Issue by muchang** [UniversalDependencies/docs#809]
Hi, I raised a question when I was investigating the POS tagging errors.

For two instances of the same word, if the heads that they attach to are the same words with the same POS tags, whether we could say that the POS tags for these two instances should be the same? 

For example, for the following two sentences:
```
This is a nice shop.
This nice shop is well-known. 
```
The "nice"s both attach NOUN "shop"s, thus, they should have the same POS tags.

Is this principle always true?

**Comment by dan-zeman** [comment]
Not necessarily:

1. _I want to know **that** person._
2. _I want to know **that** he is a good person._

In 1, _that_ modifies directly the noun _person_, and it is a `DET`. In 2, _that_ modifies the clause (but attaches to its head, _person_), and it is a `SCONJ`.

**Comment by muchang** [comment]
Thanks! It makes a lot of sense.
