### ISSUE TITLE
grew search interface

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#811]
http://match.grew.fr

How can I ask to include the Portuguese-Bosque and Portuguese-GSD dev branches in the grew interface?

**Comment by nschneid** [comment]
@kimgerdes?

**Comment by dan-zeman** [comment]
@bguil?

**Comment by dan-zeman** [comment]
I use [Udapi](http://udapi.github.io/) to search (and process) the dev branches, or any other unreleased data.

**Comment by bguil** [comment]
I can add these two dev corpora in Grew-match (and other ones if needed).
I will close the issue when it's done.

**Comment by bguil** [comment]
The two corpora (`dev` branch) are available on Grew-match:

 * [UD_Portuguese-Bosque@dev](http://match.grew.fr/?corpus=UD_Portuguese-Bosque@dev)
 * [UD_Portuguese-GSD@dev](http://match.grew.fr/?corpus=UD_Portuguese-GSD@dev)

After each push, a corpus should be updated automatically on Grew-match in maximum one hour.

Note that you also have access to *relation tables*. For each relation found in the corpus, a table is produced, showing the distributions of the `upos` of the governor, the `upos` of the dependant and the combination of both: Choose a relation on the left in the following pages (all numbers in tables can be clicked to see the corresponding sentences).

 * [Tables for UD_Portuguese-Bosque](http://match.grew.fr/_meta/UD_Portuguese-Bosque@dev_table.html)
 * [Tables for UD_Portuguese-GSD](http://match.grew.fr/_meta/UD_Portuguese-GSD@dev_table.html)

These *relation tables* were useful to find inconsistencies in French data.

**Comment by arademaker** [comment]
Thank you @bguil , I will try to have local installation of grew-match too, is it possible, right?  Udapi is very useful @dan-zeman , but it is very useful to have a search interface and the ability to link queries in the issues.

**Comment by arademaker** [comment]
Just checking, dev branches can be updated at any time not during the freezing period, right @dan-zeman?

**Comment by dan-zeman** [comment]
Yes:

- dev branch can be updated any time except data freeze period (during that period it can be updated only if pre-negotiated with the release team (currently me), or if explicitly asked by the release team to fix something)
- this rule is not enforced by technical means (i.e., the dev branch is not locked during data freeze)
- master branch is updated only as a step of the release procedure (it is locked for most users, and no pull requests against it are accepted, not even during the data freeze period)

**Comment by arademaker** [comment]
Hi @dan-zeman, sorry for highjacking the thread, but I would like to ask you to consider once more the last rule! Not making PR into master means that for all repositories the [insights page](https://github.com/UniversalDependencies/UD_Portuguese-Bosque/graphs/contributors) shows you as the main contributor always. Is it too hard to adapt the current release workflow?  Once more, sorry for insisting on that.

(update:  sorry, I may be wrong! I see now that a commit on DEV is propagated to MASTER anyway. In the past I may have missed something.. Please ignore)

**Comment by dan-zeman** [comment]
Yes, after merging dev into master, the dev commit history becomes also part of the master commit history, regardless whether the merge occurred via a pull request, or directly via git merge.

Handling 250+ repositories smoothly during release requires some automation, and I have a script that applies `git merge` on all treebanks without any need for PR (but it may choke if the contents of the master branch has changed since the last release). Clicking on the merge button of PRs would be an extra work, which is not needed.

**Comment by bguil** [comment]
@arademaker
> I will try to have local installation of grew-match too, is it possible, right?

Yes, it is documented here: https://grew.fr/grew_match/install/.
