### ISSUE TITLE
regex in grew

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/docs#812]
The two corpora (`dev` branch) are available on Grew-match:

 * [UD_Portuguese-Bosque@dev](http://match.grew.fr/?corpus=UD_Portuguese-Bosque@dev)
 * [UD_Portuguese-GSD@dev](http://match.grew.fr/?corpus=UD_Portuguese-GSD@dev)

After each push, a corpus should be updated automatically on Grew-match in maximum one hour.

Note that you also have access to *relation tables*. For each relation found in the corpus, a table is produced, showing the distributions of the `upos` of the governor, the `upos` of the dependant and the combination of both: Choose a relation on the left in the following pages (all numbers in tables can be clicked to see the corresponding sentences).

 * [Tables for UD_Portuguese-Bosque](http://match.grew.fr/_meta/UD_Portuguese-Bosque@dev_table.html)
 * [Tables for UD_Portuguese-GSD](http://match.grew.fr/_meta/UD_Portuguese-GSD@dev_table.html)

These *relation tables* were useful to find inconsistencies in French data.

_Originally posted by @bguil in https://github.com/UniversalDependencies/docs/issues/811#issuecomment-916975320_

**Comment by arademaker** [comment]
according to https://grew.fr/doc/pattern/ it should work, right? I don't know where to report issues about grew, the gitlab instance is not public, we can't open issue there, right?

```
pattern {
  N [ lemma = re"Sra?\.|Senhora?|Dra?\.|Doutora?"]
}
```

**Comment by bguil** [comment]
For some old implementation (bad) reason, it is not a valid syntax. I will try to fix this.

In the mean time, for searching for a lemma starting with and *A*, you have to write: 

```
pattern {
  N[];                % search for a new node N
  N.lemma = re"A.*";  % add an additional constraint
}
```

Note the the regexp syntax used is described here: http://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html#VALregexp

Regarding the place to report issues, it's true that the Inria Gitlab instance is not open for this. I also have to find an easier way to interact with users…

**Comment by bguil** [comment]
The syntax with regexp in node declaration is now available.

**Comment by amir-zeldes** [comment]
@bguil for some reason I still can't get regex disjunction to work in grew-match, using either syntax. For example:

`pattern { N[]; N.lemma = re"(necessary|possible)"; N2 [form="to"]; N < N2}`

Fails to match anything in EWT, but this works fine:

`pattern { N[]; N.lemma = re"necessary"; N2 [form="to"]; N < N2}`

Is there some special way that disjunction works?

**Comment by arademaker** [comment]
@amir-zeldes, disjunction didn't work for me then I learn you need to use `\|`. See the link above to https://ocaml.org/api/Str.html#VALregexp.

**Comment by amir-zeldes** [comment]
I see, thanks!

**Comment by arademaker** [comment]
@bguil , can we search in the enhanced dependencies graph using grew? 

ps: to bad using this issue for asking about grew. Maybe you can crate a dummy repo in GitHub just for holding issues about grew?

**Comment by bguil** [comment]
I've open a repository for this: https://github.com/grew-nlp/grew
Please report any issues, questions and remarks about Grew there. Thanks
