### ISSUE TITLE
What even is a copula

### ISSUE THREAD

**Issue by aryamanarora** [UniversalDependencies/docs#822]
Many issues coming up following:
- UniversalDependencies/docs#821
- UniversalDependencies/docs#823

Underlyingly, the problem is that it's not clear what a copula is per UD guidelines, and it's not clear when the dependency structure should be `nsubj` from predicate or from the verb.

UD guidelines mention 6 different types of copular constructions:
1. Equation (aka identification):  “she is my mother” ਉਹ ਮੇਰੀ ਮਾਂ ਹੈ
2. Attribution: “she is nice” ਉਹ ਚੰਗੀ ਹੈ
3. Location: “she is in the bathroom” ਉਹ ਬਾਥਰੂਮ ਵਿੱਚ ਹੈ
4. Possession: “the book is hers” ਕਿਤਾਬ ਉਸਦੀ ਹੈ
5. Benefaction: “the book is for her” ਕਿਤਾਬ ਉਸ ਲਈ ਹੈ
6. Existence: “there is food (in the kitchen)” (ਰਸੋਈ ਵਿੱਚ) ਖਾਣਾ ਹੈ

All 6 use the same verb in Punjabi.

**Comment by aryamanarora** [comment]
One of the issues that just came up is what to do when two obliques could be analysed as the predicate.
- ਉਨ੍ਹਾਂ ਦਾ ਜਨਮ 12 ਦਸਬੰਰ, 1950 ਨੂੰ ਬੰਗਲੌਰ 'ਚ ਹੋਇਆ।\
*unhā̃ dā janam 12 disambar, 1950 nū̃ baṅgalūrū 'c hoiā.*\
"His birth happened on 12 December, 1950 in Bengaluru."

(Note this uses the normal copula in Punjabi, just in perfective aspect.) Seems weird to prefer "in Bengaluru" as the predicate over "on 12 December, 1950", since they can be swapped around in the sentence without changing meaning. In fact I'd find it weird to claim that either oblique is a predicate at all here, much like the case with Hebrew:
> There may be other paraphrases of course, but I don't feel any syntactic dependency difference between these

Would it be a stretch to parse it as:
```
┐ ਉਨ੍ਹਾਂ ਦਾ ਜਨਮ (root)
├─ 12 ਦਸਬੰਰ, 1950 ਨੂੰ (obl:tmod)
├─ ਬੰਗਲੌਰ 'ਚ (obl:lmod)
├─ ਹੋਇਆ (cop)
└─ । (punct)
```

An in general, not treat obliques as predicates?

**Comment by nschneid** [comment]
Is this the same as English: "His birth was on 12 December, 1950 in Bengaluru"? There I think we'd take the first PP as the root.

**Comment by dan-zeman** [comment]
This was discussed extensively in December 2016 when the v2 guidelines were being prepared. Treating locations (and sometimes temporal specifications) as predicates was a major move for some treebanks. The possibility of having two adverbial-like candidates for the predicate was one of the major counterarguments but it was eventually dismissed (for better or worse; I'm not siding with either opinion here and I don't want to re-open that discussion, I'm just trying to recall the historical background). Chances are that based on the context, you can point at one of the adverbials and say it's the more salient one, then make it the predicate and the other will be its `advmod` or `obl`. If this is not obvious, you can take the first one as @nschneid says. And finally, you could also link the two adverbials via a `conj` (but I don't think I've seen anybody doing this).
