### ISSUE TITLE
Copulas besides ਹੋਣਾ in Punjabi

### ISSUE THREAD

**Issue by aryamanarora** [UniversalDependencies/docs#823]
* ਮੁਕਾਬਲਾ ਨੂੰਹ-ਸੱਸ ਵਿੱਚ ਰਿਹਾ "The competition remained [/was] between the daughter-in-law and mother-in-law."
* ?ਮੁਕਾਬਲਾ ਨੂੰਹ-ਸੱਸ ਵਿੱਚ ਰਹਿੰਦਾ ਹੈ "The competition continues to be between ..."

ਰਹਿਣਾ is sort of a progressive-aspect copula in sentences like these. If you substitute the normal copula in ਹੋਣਾ you only modify Aktionsart, not the semantics or arg structure here. So should this be allowed to be `cop`? But it might be able to take a full verb's paradigm...

Note that ਰਹਿਣਾ can definitely behave as a normal `VERB`:
* ਮੈਂ ਦਿੱਲੀ ਵਿੱਚ ਰਹਿੰਦਾ ਹਾਂ "I live in Delhi"

**Comment by dan-zeman** [comment]
I second what @amir-zeldes writes. The UD guidelines quite clearly state that the special copula treatment should be restricted to just one lemma unless there are very strong reasons for the opposite. Separate verbs like _to become_ and _to remain_ exist in many languages and they should not be copulas in UD, even if in some of those languages the traditional grammar classifies them as copulas or pseudo-copulas. If I'm not mistaken, the verb _to become_ is even listed as a counter-example somewhere in the guidelines. You could persuade the [auxiliary registration system](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=pa) that you need multiple copulas by pretending they have deficient paradigms but I don't think it would be a good idea (I am assuming that there are no verbs in Punjabi that would have a non-deficient paradigm in the same sense, i.e., they would have morphological forms for the three different aktionsarts).
