### ISSUE TITLE
CorrectForm overloaded with Style=Expr and Typo=Yes.

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/docs#826]
Given the eye-dialect word `'Tain't`, I can annotate that as:
```
1-3	'Tain't	_	_	_	_	_	_	_	_
1	'T	it	PRON	PRP	Style=Expr	_	_	_	CorrectForm=It|ExprStyle=Eye
2	ai	be	AUX	VBP	Style=Expr	_	_	_	CorrectForm=is|ExprStyle=Eye
3	n't	not	PART	RB	_	_	_	_	_
```

NOTE: I'm using `ExprStyle=Eye` to denote eye-dialect words, to extend the `Style=Expr` annotation.

However, given the typo `'T'ain't`, the `CorrectForm` is overloaded in both the `'T` token and the `ai` token, e.g.:
```
1-3	'T'ain't	_	_	_	_	_	_	_	_
1	'T	it	PRON	PRP	Style=Expr	_	_	_	CorrectForm=It|ExprStyle=Eye
2	'ai	be	AUX	VBP	Style=Expr|Typo=Yes	_	_	_	CorrectForm=ai,is|ExprStyle=Eye
3	n't	not	PART	RB	_	_	_	_	_
```

In this case, is `CorrectForm=ai,is` the correct way to annotate this (like with multiple enumeration entries)? In this case, how do I indicate which is associated with `Typo=Yes` and which is associated with the `Style=Expr`, as the ordering is not defined?

Or should `CorrectForm` be used on the `1-3` token range? E.g.:
```
1-3	'T'ain't	_	_	_	Typo=Yes	_	_	_	CorrectForm='Tain't
1	'T	it	PRON	PRP	Style=Expr	_	_	_	CorrectForm=It|ExprStyle=Eye
2	'ai	be	AUX	VBP	Style=Expr	_	_	_	CorrectForm=is|ExprStyle=Eye
3	n't	not	PART	RB	_	_	_	_	_
```

It may be better to limit `CorrectForm` to `Typo=Yes` and have something like `CorrectForm[Form]` (for `Style=From`) or `CorrectForm[en]` (for the standard English non-dialectal form), or maybe a separate `LangForm` to be more universal. For example:
```
1-3	'T'ain't	_	_	_	_	_	_	_	_
1	'T	it	PRON	PRP	Style=Expr	_	_	_	LangForm=It|ExprStyle=Eye
2	'ai	be	AUX	VBP	Style=Expr|Typo=Yes	_	_	_	CorrectForm=ai|ExprStyle=Eye|LangForm=is
3	n't	not	PART	RB	_	_	_	_	_
```

**Comment by dan-zeman** [comment]
I would assume that `CorrectForm` shows the word form after all necessary corrections have been made. If words with `Style=Expr` need correcting, then `CorrectForm` should not show _ai_ because that form is not yet correct (even if it gets rid of a typo). So the obvious candidate here is `CorrectForm=is`. If you want to also preserve the partially corrected _ai_, then I would suggest that you invent some extra [MISC](https://universaldependencies.org/misc.html) markup for that purpose.

**Comment by rhdunn** [comment]
Thanks. In this case I've gone with using `Typo=Yes` and `CorrectForm` on the `1-3` token, as it is the combined token that is the typo. This then allows me to use `CorrectForm=is` for the `ai` part of the word, as that is the dialectal part of that combined word.

My question arose because in this case if a spell/grammar checker is trained on the data, and encounters this, using:
```
1-3	'T'ain't	_	_	_	_	_	_	_	_
1	'T	it	PRON	PRP	Style=Expr	_	_	_	CorrectForm=It|ExprStyle=Eye
2	'ai	be	AUX	VBP	Style=Expr|Typo=Yes	_	_	_	CorrectForm=is|ExprStyle=Eye
3	n't	not	PART	RB	_	_	_	_	_
```

would mean that it cannot easily isolate fixing typos and changing style from informal or dialectal to formal or standard English.

**Comment by nschneid** [comment]
Would [`Style=Vrnc`](https://universaldependencies.org/u/feat/Style.html#Vrnc) (vernacular) be more appropriate here?

I'm not sure it should be considered a typo at all if it is an intentionally nonstandard spelling.

**Comment by rhdunn** [comment]
The `Typo=Yes` here is for the `'` between `'T` ("it") and `ain't` ("isn't" / "is not"), not the regional/dialectal usage. -- Other usages in the texts of the author use `'Tain't` or in some cases `'Taint`. Note: `t'` can be used dialectally (e.g. in Yorkshire) for "the", e.g.:
> t'other day

And yes, you are right. -- `Style=Vrnc` is more appropriate than my `Style=Expr|ExprStyle=Eye` annotation.

I'm using `CorrectForm` here to denote the standard English form/usage. It may be better to have something like `StandardForm=It` for use with `Style=Vrnc`.

For reference, this is in Lucy Maud Montgomery's novel Rainbow Valley:
> 'T'ain't fit for a dog to be out, is it?"

compared with the usage in her novel Anne's House of Dreams:
> 'Tain't often I can entertain in such style.

**Comment by rhdunn** [comment]
Regarding `Style=Vrnc`, the documentation for [Style=Expr](https://universaldependencies.org/u/feat/Style.html#expr-expressive-emotional) includes:
> [en] ..., dialectal or colloquial pronunciation (Hahvahd), ...

which is why I've been using that. -- Maybe the docs should be updated to note that `Style=Vrnc` (for dialectal pronunciation) or `Style=Coll` (for colloquial pronunciation) should be used instead in that case.

**Comment by nschneid** [comment]
To date, I think `Expr` is the only `Style` value we have been using for English, but we haven't been marking things like "ain't".

**Comment by nschneid** [comment]
Maybe this is a legitimate typo within a particular author's style, but in general it seems hard to tell for dialectal forms. If *T'ain't*, *'T'ain't*, *T'aint*, *'Tain't* are all attested  in English I don't think it helps much to mark one of them as a typo.

**Comment by rhdunn** [comment]
That makes sense. Thanks.
