### ISSUE TITLE
What is a sentence? (i.e. how to split paragraphs into sentences)

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/docs#834]
For simple sentences, a sentence ends with sentence terminal punctuation (e.g. `[.?!]`). For more complex sentences, it is not as clear how to segment a text into sentences with separate `sent_id` annotations.

### Case 1 -- Sentence within another sentence delimited with "--"
> "And yet this woman--who knows what her art may have been?--how long it may have been premeditated, and how deeply contrived by her!--Who is she?--Who can she be?--Whom did I ever hear him talk of as young and attractive among his female acquaintance?--Oh! no one, no one--he talked to me only of myself."
>
> &mdash; Jane Austen; Sense and Sensibility [1811]

My thinking here is to create separate sentences for each of the punctuation followed by `--`, and keeping "Oh! no one, no one--he talked to me only of myself." as a single sentence (see Case 2).

> She drew her arrow to her eye--alas, she knew the art only too well!--and took careful aim.
>
> &mdash; Lucy Maud Montgomery; The Story Girl [1911]

My thinking is that this is a single sentence. The inner sentence ("alas, she knew the art only too well!") is a sub-clause within the outer sentence.

### Case 2 -- Continuations with non-capitalised words.
> What race is this?--oh! the three-minute one.
>
> &mdash; Lucy Maud Montgomery; Kismet [1899]

My thinking here is that this should be 3 sentences even though the intention from the capitals is for it to be a single sentence. Or 2 sentences, with "oh! the three-minute one." being a single sentence, treated like "oh, the three minute one.".

> "Ugh! ugh! ugh!--ugh! ugh! ugh!--ugh! ugh! ugh!--ugh! ugh! ugh!--ugh! ugh! ugh!"
>
> &mdash; Edgar Allan Poe; The Cask of Amontillado [1846]

My thinking here is that this is a single sentence.  Poe is using the `--` to indicate breaks in the coughing, and the `!` to indicate that the "ugh" is an interjection (in this case, a cough sound).

### Case 3 -- After speech text
> "I suppose you have heard that I am going away, Rob?" she said at last.
>
> &mdash; Lucy Maud Montgomery; The Magical Bond of the Sea [1903]

My thinking here is that "she said at last." is a separate sentence. This is especially the case where that occurs after multiple sentences. For example (I don't have a source text example here):

> "What? How?" said Susan.

Another more complex case that I haven't found source text for would be if the quote occurs within another sentence:

> I muttered "What? How can this be!" quietly to myself.

Gramatically, <I muttered "What? How can this be!" quietly to myself.>, <What?>, and <How can this be!> would be 3 sentences, but annotating this as a single sentence would go against the "single tree" principle. So my thinking would be to split this lexically into <I muttered "What?>, <How can this be!">, and <quietly to myself.>. -- Is that correct?

Are there any annotations to connect these sentences together into the larger sentence/clause they form?

**Comment by dan-zeman** [comment]
Some comments:

If, for whatever reason, one UD sentence (tree) contains multiple segments that appear autonomous and almost like independent sentences, their main predicate nodes can be connected via a left-to-right `parataxis` relation.

If two segments are syntactically related (by something else than `parataxis`), then they should preferably be kept in one sentence (tree).

I agree with your solution for Cases 1 and 2 above. For Case 3, the reporting clause is normally kept together with the direct speech in one sentence. It is trickier when the direct speech contains multiple sentences; I think a common approach is to keep the closest direct sentence together with the reporting clause, and make the others independent. However, if the direct speech is nested in the reporting clause, I would keep it all as one tree even if the direct speech looks like multiple sentences.

**Comment by Stormur** [comment]
I think that not too much relevance should be given to punctuation marks nor capitalisation in general. Often they coincide with our intuitive notion of a sentence, but as often they just point out to different rythms in the uttering. I broadly agree with the `parataxis`-rule of thumb of @dan-zeman. It is more meaningful to see how complex sentences are built by means of "horizontal" relations like `conj` than to have smaller, split, artifically simple sentences.

I also agree that case 3 has to be kept together, where _What?_ is an (elliptic) co-ordinate to _How can this be!_ (which is just a question like _What?_, notwithstanding the exclamation mark).
