### ISSUE TITLE
English EWT - semantic role annotations

### ISSUE THREAD

**Issue by ashnaahmad** [UniversalDependencies/docs#835]
On the [page](https://universaldependencies.org/treebanks/en_ewt/index.html) for the English EWT treebank, there is a list of tags and features which occur in the treebank, some of which are event-semantic information (e.g. tense). I'm wondering if there is some version of the corpus online with annotations for semantic information, e.g. roles like 'agent', 'patient', 'theme', 'goal' and 'location' as well as tense and aspect?

**Comment by nschneid** [comment]
The UD project only covers morphology and syntax (so "tense" should be understood as grammatical tense, not semantic tense). However, PropBank has annotated semantic roles in the EWT corpus: https://github.com/propbank/propbank-release

**Comment by ashnaahmad** [comment]
> The UD project only covers morphology and syntax (so "tense" should be understood as grammatical tense, not semantic tense). However, PropBank has annotated semantic roles in the EWT corpus: https://github.com/propbank/propbank-release

That's great, thanks for referring me to it! Is it possible to use these annotations without access to the full LDC dataset which is referred to in the readme? I.e. if I have the UD EWT dataset and this PropBank project, is that enough to be able to fully annotate the dataset?

**Comment by nschneid** [comment]
I'm not sure—the PropBank annotation was originally done on top of Penn Trees but perhaps they have released the semantic roles in another form. You'd have to ask them.

**Comment by arademaker** [comment]
Hi @chiapudding I have been working on the projection of the SRL annotations provided by  https://github.com/propbank/propbank-release into the UD syntactic analysis of the EWT sentences provided by https://github.com/UniversalDependencies/UD_English-EWT. I hope to make the data publicly available in the near future.

**Comment by ashnaahmad** [comment]
Hi @arademaker that's amazing! I may have to do that myself because I'm going to need those SRL annotations asap for my undergrad thesis (due in March!) but I'm sure they'll be very useful for future research :)
