### ISSUE TITLE
نحوه نصب نسخه فارسی این کتابخانه در ویندوز یا لینوکس

### ISSUE THREAD

**Issue by CS-ABD** [UniversalDependencies/docs#837]
با سلام
من چطور می توانم نسخه فارسی این کتابخانه را که زحمت کشیدید نصب کنم؟
تگر امکان دارد راهنمای کار با آن را هم بخصوص قسمت pos tagger را توضیح بدهید
باتشکر

**Comment by nschneid** [comment]
I believe this is asking for a Persian POS tagger. One option is Stanza, https://stanfordnlp.github.io/stanza/ & https://github.com/stanfordnlp/stanza.

**Comment by CS-ABD** [comment]
> I believe this is asking for a Persian POS tagger. One option is Stanza, https://stanfordnlp.github.io/stanza/ & https://github.com/stanfordnlp/stanza.

Thank you professor...

**Comment by phsfr** [comment]
You can also use this model based on UDPipe trained on UD_PerDT:
https://github.com/phsfr/UD_PerDT_DependencyModel
