### ISSUE TITLE
Model performance for specific dependency tag 

### ISSUE THREAD

**Issue by carissaad** [UniversalDependencies/docs#841]
Is there any information on the model performance for a specific dependency tag for the Indonesian GSD model? The dependency tag I'm working with is the "amod" tag.

**Comment by dan-zeman** [comment]
I'm afraid there isn't. (And it is also not clear what model you mean. This repository is about data, not about a particular model. Depending on the parser you are using, you can train many different models.)

**Comment by carissaad** [comment]
@dan-zeman I'm sorry, to be exact I was referring to the dependency tagger used with the Indonesian GSD Treebank. Thank you for the reply!
