### ISSUE TITLE
Ideophones

### ISSUE THREAD

**Issue by LanguageStructure** [UniversalDependencies/docs#842]
How are ideophones ideally to be treated as POS and as dependencies?

**Comment by nschneid** [comment]
This came up in https://arxiv.org/abs/2109.10952 ("oink oink", "tuk tuk"/'knock knock'). If I recall correctly we used `INTJ`.

**Comment by LanguageStructure** [comment]
Is it possible to include IDEO as a POS?

**Comment by dan-zeman** [comment]
No. Not as UPOS, those are fixed forever, and I don't see why `INTJ` couldn't be used for these words. But you can use XPOS and features to distinguish them.

**Comment by LanguageStructure** [comment]
In Tupían languages, Mundurukú, for example, and also in some African languages, ideophones are part of the vocabulary, always the same for some meanings. It is possible to tell a story only with ideophones. Although, these differ morphosyntactically from verbs becasue they do not combine with 'verbal moprhology' (exceptions, for example, in Akuntsu, where it combines with some of the verbal moprhology). This is the same distribution found with adjectives. In this sense, since there is a POS adjectives, there could be one IDEO. If you say they re fixed, I'd use VERB with XPOS ideo.

**Comment by dan-zeman** [comment]
Okay. If they normally take the function of a predicate, then treating them as a subclass of `VERB` sounds reasonable. Perhaps a language(family)-specific feature `VerbType=Ideo` would be useful, too? (UD-based models are more likely to look at features than at XPOS.)

**Comment by LanguageStructure** [comment]
I subscribe to `VerbType=Ideo`. It is indeed more appropriate than just the XPOS.
