### ISSUE TITLE
Duplicates and one-token sentences

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#844]
I wanted to check whether there are duplicate sentences in the Welsh Treebank, so I added a tool to ConlluEditor to check (and also to find similar sentences using a simple Levenshtein distance).
I run the tool on all UD 2.9 treebanks and found many identical duplicates (and even more with Levenshtein distance 1) in nearly all treebanks. In two treebanks every sentence occurs at least twice. When the duplicates are all in train or dev, this won't do much harm, but when duplicates appear in test or in test or train, test results may not reflect the quality of the data or tool one expects.
Some treebanks have quite a lot of one-token-sentences. I did not check all TBs, but this may be for cases where entire texts have been annotated, including one-token sentences (like Wikipedia the headline "Reference").

What is the official policy about duplicates and one-token sentences? Unless I'm mistaken, they are not rejected by the validator.
Should we purge them or just mention their existence in the documentation or add a metadata information that a sentence is duplicate of a list of other sentences

**Comment by dan-zeman** [comment]
This has been discussed in the past, see e.g. #227 and #445. There is also the tool [overlap.py](https://github.com/UniversalDependencies/tools/blob/master/overlap.py) in the tools repository.

Essentially, the policy is that the treebank maintainers should decide what is naturally occurring duplicate sentence, and what is accidentally copied document, boilerplate from the web etc. Long duplicates should be avoided but there is no strict threshold on the length of a sentence that cannot be repeated (I also don't think it can be resolved without human intervention).

As for one-token sentences, they are not a problem if the data consists of complete, unshuffled documents (which is highly encouraged!), and such sentences occur naturally.

A side note: Occasionally there is also overlap across corpora of the same language. Whenever this happens, people should make every effort to ensure that the corresponding parts end up in the same part (train/dev/test).

**Comment by jheinecke** [comment]
I apparently missed this issues. Indeed, One token sentences are less a problem (however in test-files they'll always have a LAS of 100% and in this way are not helpful. 
But overlaps between test on the one hand and train/dev on the other should be at least marked. Anyway, I'll delete duplicates from the Welsh TB

**Comment by dan-zeman** [comment]
> Anyway, I'll delete duplicates from the Welsh TB

If you have independent individual sentences, then it is reasonable to delete them. But if you have complete documents, you should not cut one sentence off the document just because the same sentence incidentally appeared elsewhere in the corpus. The removal may be beneficial for training and testing syntactic parsers, but it will break the document structure and thus affect other models that people may want to build on whole documents.

**Comment by jheinecke** [comment]
in my case there are indeed (8 or so) individual sentences which occur(ed) in test and dev or train

**Comment by nschneid** [comment]
In EWT emails, for example, we have duplicated sentences due to quoted replies. Should there be a standard way to mark these as duplicates so that when the parse is updated, we can check that it is consistent across copies of the sentence?
