### ISSUE TITLE
Clarifying the standard for CorrectForm

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#845]
The [guidelines for typos](https://universaldependencies.org/u/overview/typos.html) describe `CorrectForm` (in MISC) as an option for providing the corrected spelling in cases of typos (`Typo=Yes`) as well as abbreviations (`Abbr=Yes`) and expressive style (`Style=Expr`). But it is not clear where it is *required* and whether it can occur without one of those three companion features. As such, `CorrectForm` is both overloaded (#826) and underspecified.

There is also a related feature `ModernForm` which is paired with `Style=Arch` for historical forms.

I would like to discuss a more precise standard for `CorrectForm`. Questions:

1. Should it be required if `Typo=Yes` is given? My thinking is yes, for uniformity, though at present some treebanks may assume the lemma is the correct form by default.
2. Should it be required if `Abbr=Yes`, and can it contain multiple words? My thinking is that it should be optional, with a recommendation to provide it only for nonstandard abbreviations (it is not necessary to spell out "USA", for example, and maybe not "OMG"). I suspect there will be nonstandard abbreviations that are worth expanding as multiple words.
3. Should it be required if `Style=Expr` (and maybe other values for `Style`)? I would tentatively say yes, especially for expressive lengthening ("noooooo"), but perhaps some stylistically marked words have no corresponding "standard" word?
4. Should it reflect contextual casing (e.g. sentence-initial or all-caps), or canonical casing like lemmas?
5. Should `CorrectForm` ever be allowed if there is no `Typo` or `Style`? My guess is no. Same for `ModernForm` without `Style=Arch`.
6. Should `CorrectForm` be paired with a feature indicating anomalous character encoding, e.g. `SpecialEncoding=Yes`? This would help for nonprintable characters in the token like soft hyphens (UniversalDependencies/UD_English-EWT#83), and potentially with mojibake (not a typo in the sense that a user typed something incorrectly, the encoding just got messed up in conversion somehow).

**Comment by dan-zeman** [comment]
> But it is not clear where it is _required_ and whether it can occur without one of those three companion features.

I think it is actually clear that it is neither required nor forbidden without additional features. Under the v2 guidelines, almost everything in MISC is optional, the only exception being `SpaceAfter=No`.

I believe it should stay optional, although perhaps encouraged in certain situations. For large treebanks it may be a lot of manual work to supply correct forms of all typos.

Also note that `Style`, unlike `Typo`, has not fully acquired the status of a universal feature.

**Comment by nschneid** [comment]
> For large treebanks it may be a lot of manual work to supply correct forms of all typos.

Are large treebanks currently marking them as typos but not supplying a correct form? I'm not sure how much value there is in merely marking something as a typo without explaining what the correct spelling is.

Another option to consider is a conditional requirement: *if* the treebank specifies `CorrectForm` on any token, it must supply it on all relevant tokens, as a matter of consistency.

> it is neither required nor forbidden without additional features

Are there situations in which you think flexibility is needed to allow a `CorrectForm` without any accompanying feature to explain why it is there? I guess I'm worried that without explicit indication, a user might naively assume it implies a typo but there could actually be several other explanations.

**Comment by dan-zeman** [comment]
> > For large treebanks it may be a lot of manual work to supply correct forms of all typos.
> 
> Are large treebanks currently marking them as typos but not supplying a correct form? I'm not sure how much value there is in merely marking something as a typo without explaining what the correct spelling is.

Depending on the original annotated resource, you may have the information that a word form is wrong, but the information about the correct form may simply not be part of the annotation. The value is pretty obvious: When looking at the various morphological forms actually occurring in the corpus, you are warned that this one is wrong; depending on what you are doing, you may want to exclude it from the statistics you collect.

> Another option to consider is a conditional requirement: _if_ the treebank specifies `CorrectForm` on any token, it must supply it on all relevant tokens, as a matter of consistency.

Meaning that you are not allowed to manually fix a typo you stumbled upon unless you are ready to do the same for the entire corpus.
 
> > it is neither required nor forbidden without additional features
> 
> Are there situations in which you think flexibility is needed to allow a `CorrectForm` without any accompanying feature to explain why it is there? I guess I'm worried that without explicit indication, a user might naively assume it implies a typo but there could actually be several other explanations.

If we accept that this MISC attribute must be regulated by the guidelines, then this can be discussed. But it would probably also mean that `Style` should become same-class citizen as `Typo`, otherwise it does not make sense.

**Comment by nschneid** [comment]
OK, I think the bigger question to discuss in our next meeting is to what extent features supporting canonicalization should be considered optional nice-to-haves whose implementation may be idiosyncratic to a treebank, vs. establishing a more standardized approach that would allow a treebank that opts in to be fully normalized.

**Comment by amir-zeldes** [comment]
> Depending on the original annotated resource, you may have the information that a word form is wrong, but the information about the correct form may simply not be part of the annotation

This is currently the situation for GUM!

> Meaning that you are not allowed to manually fix a typo you stumbled upon unless you are ready to do the same for the entire corpus.

That's a good point; I think this by itself is reason enough not to make it mandatory (though personally I think it would be great to add it where possible; maybe it can be added to the star rating of corpora?)

**Comment by Stormur** [comment]
`Style` seems to still be in an ambiguous position where it is not clear if it refers to use (e.g. different registers), expressivity, ortohgraphic normativism or formal variants. This is a point that should be made clearer and as a feature I think it should focus on just one of these (e.g., there already exists `Form`).

With regard to `CorrectForm`, I don't know how useful it might be if we take the lemma to already be a canonical form. It is really difficult to define under which assumptions a form is "incorrect", especially in historical documents. I don't know if it ca nreally be annotated meaningfully, or at least, I thought this when trying to implement it in the Latin treebanks.

**Comment by dan-zeman** [comment]
> though personally I think it would be great to add it where possible; maybe it can be added to the star rating of corpora?

So what would be the ranking metric? Out of words that have `Typo=Yes`, what is the percentage of those that also have `CorrectForm` in MISC? With the ideal being 100%?

**Comment by amir-zeldes** [comment]
> So what would be the ranking metric? Out of words that have Typo=Yes, what is the percentage of those that also have CorrectForm in MISC? With the ideal being 100%?

Well, yes, but somehow it needs to be a bonus score, such that having Typo and no CorrectForm is better than having no Typo at all. The problem I see with this is that, if a corpus happens to have no Typos, it scores lower than a corpus that has them with annotations, and the same as a corpus with typos but no such annotation. Does that make sense?

**Comment by nschneid** [comment]
Is there a corpus that legitimately has no typos?

**Comment by amir-zeldes** [comment]
Some corpora are small, so yeah, I would expect so?

**Comment by arademaker** [comment]
I have been using both CorrectForm and Typo in the Portuguese-Bosque. I just fixed a few cases that were missing the Typo. In one case, I have a CorrectForm in an MWT, but I am unsure how/where to add the Typo.

https://github.com/UniversalDependencies/UD_Portuguese-Bosque/blob/workbench/documents/CP0549.conllu#L117-L120

Nevertheless, I am still very unsure about the benefits of adding that information to the corpus. I must confess that in a few cases during the data maintenance, I adopted the ... well ... 'inexcusable' decision to change the text instead of adding Typo/CorrectForm. I guess on the practical side of data maintenance, it is tough to avoid that temptation. 

But my point is that these annotations will always be exceptions and, as such, are not helpful in teaching statistical parsers anything. Considering that training parsers are one of the most pragmatic uses of these corpora. On the other hand, imagine a corpus derived from text extracted from PDF documents. It would be unreal to expect annotators to keep all noise on the data. Moreover, what is the limit between noise introduced from data transformation and typo from the text's author? In Bosque, it is not always clear when we have one case or the other. So I usually add CorrectForm with Typo.

**Comment by amir-zeldes** [comment]
> not helpful in teaching statistical parsers

Maybe, but if you want to know how common typos are in a certain text type, what kinds of words they affect how often/when, and what kind of parsing errors they cause compared to the CorrectForm version of the text, then they can be helpful. 

> I usually add CorrectForm with Typo

It's easy enough to add Typo=Yes automatically to tokens that have CorrectForm (unless it's spoken language, then I guess it should be called Disfluency=Yes?)

**Comment by sylvainkahane** [comment]
> Is there a corpus that legitimately has no typos?

For spoken corpora, Type does not make sense. If there is a typo in the transcription, we just correct it.

**Comment by amir-zeldes** [comment]
Right, but you might still have disfluencies for which you may want to have CorrectForm. GUM has these for example (and currently also has Typo=Yes in such cases, though it is clearly a misnomer).

**Comment by sylvainkahane** [comment]
I am not sure it is a good idea to use `Typo` for false starts. We have a lot of interrupted word in spoken corpora and in some case we don't know what would have been said and we cannot propose a `CorrectForm`.
But I have just found, in a new spoken corpus, a case where it could be appropriate to use `Typo`: it when the speaker produces a wrong form.
The example is in French: _Je me suis assié_ 'I sat down', but the form _assié_ is not the right form of the past participle of this verb (_assié_ is not an orthographic typo of the transcriber, it is an orthographic trick used by the transcriber for this strange form). So here I need `CorrectForm=assis` and so maybe `Typo=Yes` (even if is not exactly a typo).

**Comment by dan-zeman** [comment]
> if a corpus happens to have no Typos, it scores lower than a corpus that has them with annotations, and the same as a corpus with typos but no such annotation.

For a typo-less corpus, _CorrectForms/Typos_ is undefined because of division by zero. Declaring it to be 100% would solve the issue.

**Comment by amir-zeldes** [comment]
Yes, computationally that sounds fine, I just wonder if a corpus that has no typo annotations (possibly because it was never checked for typos) should score higher than a corpus with Typo annotations, 90% of which have been corrected. That would make the first corpus score higher than the second, even though arguably if the first corpus was never checked for typos, actually corpus2 has higher quality. 

Maybe having Typo should add a score bonus, which achieves its maximum value at 100% corrections, but which is only given to a corpus without Typo if the developers assert that this is because typos have been checked but don't actually occur in the data?

**Comment by dan-zeman** [comment]
Hmm.

The script does not know whether the treebank maintainer thinks the typos have been checked. It would have to be a new metadata line in README, and it would have to be described in the release checklist and covered in the validation infrastructure. Maintainers of 243 treebanks would have to add this line in their README files (or at least those that believe typos have been checked in their treebanks); `Typo=Yes` is currently (UD 2.11) used in 39 languages.

If the treebank maintainer declares that typos have been checked, we don't have means to verify how well it was done.

If you mark just one typo with `Typo=Yes` and `CorrectForm=XXX`, you are seen as having done a good job, regardless of the fact that there may be 100 other typos undiscovered and unmarked in your treebank. This is probably the case of several treebanks – I have myself annotated random typos I spotted when fixing other errors in treebanks, but I never checked a treebank systematically for typos. And I think that 100 typos unmarked out of 101 is a bigger flaw than all typos marked but some of them missing the `CorrectForm` counterpart.

Which makes me wonder whether adding a metric like this to the star ranking is worth the effort.

**Comment by nschneid** [comment]
Seems like overkill to me. Star rankings are just heuristic. What could be done is to add a warning to the validator ("The treebank has no instances of Typo=Yes: consider adding this along with a CorrectForm to indicate lexical errors.").

**Comment by amir-zeldes** [comment]
Yeah, I agree, it sounds not very feasible.
