### ISSUE TITLE
Multiple gender and gender agreement

### ISSUE THREAD

**Issue by LanguageStructure** [UniversalDependencies/docs#861]
What would be the best way to mark the lemma if nouns have two genders, e.g. dependent on the gender of the possessor? Although feminine is the default, the masculine form is often unpredictable (the same applies to the gender of auxiliaries). In other words, both forms must be given, as they would be in a dictionary. Can the value of the lemma be lemma1/lemma2  (contain a slash)?

**Comment by wellington36** [comment]
I see the lemma as the most naive form of the token, if in the case of the language you are working it keeps in the feminine, then this would be the form.

**Comment by LanguageStructure** [comment]
Thanks, @wellington36 

Can I have a slash in the lemma column?

**Comment by wellington36** [comment]
I believe that only if it is part of the text, as in this example (from English-GUM):

```
36	|	|	PUNCT	SYM	Typo=Yes	42	punct	42:punct	XML=<sic></sic></ref>
```

**Comment by nschneid** [comment]
The guidelines for lemmas: https://universaldependencies.org/u/overview/morphology.html#lemmas

**Comment by LanguageStructure** [comment]
@nschneid thanks. It does not mention it. I would like to have something like 
1      form      lemma1/lemma2      NOUN       n

**Comment by dan-zeman** [comment]
In general it is expected that the lemma is a single canonical form of the word selected according to language-specific rules (e.g. the nominative singular form of a noun). Providing two forms with a slash would violate this expectation. The LEMMA field is not a dictionary. For example, in many languages, a plural form, a genitive form etc. is not predictable and has to be listed in dictionaries but it is **not** part of the lemma in UD.

Gender is usually considered a lexical feature of nouns, and in the rare cases where there are pairs of semantically related nouns with different genders, it is often treated as two nouns with two different lemmas (e.g. _actor_ vs. _actress_; they are not lumped under one lemma _actor/actress_).

At present, the validator does not bark at you if you put a slash in the lemma of a noun, although I think such a test might be useful in the future. (Note however that even now you won't be able to register an auxiliary lemma that contains special characters.)

**Comment by LanguageStructure** [comment]
@dan-zeman I understand your point, but in this case, it is not about forms such as genitive or plural. Many nouns have two forms which are not predictable. I think the solution will be to use the 10th column. For he lemma, I will stick to the gender of the given form.
