### ISSUE TITLE
Understanding Validation Report

### ISSUE THREAD

**Issue by MathieuDehouck** [UniversalDependencies/docs#862]
Dear All,

I assume this is moslty a question for Dan, but in the last week before freeze, maybe someone else can help.

I am working on the umbrian IKUVINA treebank, it's far from being over, but I managed to pull something for next release.
On the validation page, I have 0 L1 to L6 errors, but I have an L0 error.
* [L0 Repo lang-spec-doc] UD_Umbrian-IKUVINA: Language 'xum' does not have the one-page documentation summary in the docs repository (the file exists but it seems incomplete).

Looking at other pages and at the guidelines for lang-specific doc I can't seem to understand what's missing, the page is there with a minimal doc, nothing great yet but I'm working on it.
Also, I can't seem to run the check_files perl script on my computer, as a non perl user, I am a bit stuck.

So, I was wondering if someone could help me understand what's going wrong with the page or what documents are missing.

Thank you very much

**Comment by dan-zeman** [comment]
The validator (or, in this case, the script `check_files.pl`) checks that the file `docs/_xum/index.md` exists and that it does not seem ridiculously small. The error will disappear when more documentation is provided.

**Comment by MathieuDehouck** [comment]
Great.

Thank you very much for the explanation.
And sorry for the disturbance then.
I'll work on the doc.
