### ISSUE TITLE
English "at once" Annotation

### ISSUE THREAD

**Issue by mehmetoguzderin** [UniversalDependencies/docs#863]
Hello,

I notice that EWT annotates "at once" as follows: "at" is an ADV with advmod, the head is "once" ADV, and "once" has udeprel of advmod.

Whereas, GUM annotates "at once" as follows: "at" is an ADP with case, the head is "once" ADV, and "once" has udeprel of obl.

Which one is more UD guidelines consistent approach? What should other languages with tokenized structure of such adverbials do in such cases? Should they go all ADV like EWT or ADV with ADPs?

Thank you!
Oguz

**Comment by nschneid** [comment]
My feeling is that "at once" is a preposition + adverb combination, and so `ADP` and `case` are appropriate as in the GUM analysis. (ADV/advmod may have been due to errors in automatic conversion.) Not so sure about `obl` vs. `advmod` for how the entire phrase modifies the verb.

Note that "at least" (non-quantity) and "as well (as)" are considered fixed expressions: https://universaldependencies.org/en/dep/fixed.html

Here are some that should potentially be reanalyzed as ADP+ADV, including "at once" and "at best": http://universal.grew.fr/?custom=626d828225a34

**Comment by mehmetoguzderin** [comment]
@nschneid Thank you; it would be great to have a general thumb rule to "advmod" vs. "obl" in such cases, like if it can live with a "fixed" style, then certainly "advmod" or vice versa, etc.

**Comment by nschneid** [comment]
Related: "all of a sudden", "all the sudden"

**Comment by dan-zeman** [comment]
I think _at_ is `ADP`. But using the `case` relation seems odd (the relation is supposed to occur within nominals, and _once_ is not a noun, hence _at once_ is not a nominal). For the same reason, taking the adverb _once_ as the head and attaching it to something as `obl` is problematic (while `advmod` is not much better, as it normally attaches adverbs but not preposition-adverb pairs).

Considering all this, the least disturbing analysis seems to be a fixed multi-word adverb: `fixed(at, once); advmod(XXX, at)`. The POS tags could then easily stay `ADP` for _at_ and `ADV` for _once_.

**Comment by nschneid** [comment]
I worry about the `fixed` approach because prepositions can license adjectives/adverbs somewhat productively. For example in COCA:

<img width="91" alt="image" src="https://user-images.githubusercontent.com/985263/166248092-1a78935b-019a-4b1b-b091-3377b471433b.png">
<img width="98" alt="image" src="https://user-images.githubusercontent.com/985263/166248393-121fb0ff-c78d-41eb-9d61-bc2020745f1c.png">

and many others ("in earnest", "for free", ...)

**Comment by amir-zeldes** [comment]
I agree with @nschneid - I don't love expanding the fixed list, and this is a productive pattern. I think this is one of those cases where we are looking at something like unary derivation (ADV gets 'wrapped' in something which allows it to serve as a prep. argument), which can't be expressed well using dependencies. In general I think UD then prioritizes preserving the 'higher' relations, which makes obl + case appropriate here, even if it obscures some of the internal workings of the structure (which are partly represented by the POS tag)

**Comment by nschneid** [comment]
It seems like English uses ADP + ADJ to derive idiomatic phrases that act like adverbs: "at random" ~ "randomly", "for free" ~ "freely" ('at no cost', not in its normal sense of 'uninhibited'), etc.

"at once" is perhaps the clearest ADP + ADV combination (unusual for "once" to be an ADJ).

**Comment by Stormur** [comment]
I also dislike the `fixed` approach and think conversely that an `ADV` couched into a more "nominal" construction (`ADP`+`case`+`obl`) is still acceptable and does not interfere with computational treatment. 

Actually, such a construction is one of many clues that let one wonder whether a word like _once_ really is an adverb; surely it is not a "conventional" adverb. If a general interpretation of temporality allows us to label _once_ with `AdvType=Tim` as a so-called temporal adverb, this already sets it apart; but most importantly, to me it is questionable if such "adverbs" aren't really to be treated as `PRON`s, a fact which would also be a very simple explanation for their widespread use in similar "nominal environments" and would also produce a more consistent annotation.

**Comment by nschneid** [comment]
True, "once" is temporal and patterns a bit like today/tomorrow/now (they are often bare adverbials but can be marked with a preposition: "by today/tomorrow/now").

"Once" can also mark clauses with a meaning similar to 'when' ("Once they have left, ..."). Kind of like "now that".

In UD terms I don't think we should call them `PRON`s, but perhaps they are pro-adverbs. "Today", "tomorrow", "here", and "there" are deictic, like some pronouns/determiners.

**Comment by Stormur** [comment]
> "Once" can also mark clauses with a meaning similar to 'when' ("Once they have left, ..."). Kind of like "now that".

Probably it is more an `SCONJ` here.

> In UD terms I don't think we should call them `PRON`s, but perhaps they are pro-adverbs. "Today", "tomorrow", "here", and "there" are deictic, like some pronouns/determiners.

I think this should be seriously discussed. For example, if we look at the guidelines for PRON and read...

> Pronouns are words that substitute for nouns or noun phrases, whose meaning is recoverable from the linguistic or extralinguistic context. Pronouns under this definition function like nouns.

... then why should we not label these temporal (and locational) elements as `PRON`? They are deictic, they are substituting more complex expressions; they would be "oblique pronouns". It is true that the notion of pronoun seems most of the time traditionally restricted to those of the personal type, possibly part of an inflectional paradigm, but nothing prevents us considering pronouns of other kinds, too. 

Reading the definition of pro-adverb [here](https://glossary.sil.org/term/pro-adverb), this "adverbial function" corresponds in fact to the "oblique" in UD. And the definition of [pro-form](https://glossary.sil.org/term/pro-form) closely corresponds to that of PRON in UD. Curiously, UD refers only to nouns and not to "phrases, clauses, or sentences", and I wonder why it is so.

**Comment by nschneid** [comment]
@Stormur note the PronType feature:

https://universaldependencies.org/u/feat/PronType.html
> This feature typically applies to [pronouns](https://universaldependencies.org/u/pos/PRON.html), pronominal adjectives ([determiners](https://universaldependencies.org/u/pos/DET.html)), pronominal [numerals](https://universaldependencies.org/u/pos/NUM.html) (quantifiers) and pronominal [adverbs](https://universaldependencies.org/u/pos/ADV.html).

https://universaldependencies.org/en/feat/PronType.html
> In English, this feature applies to [pronouns](https://universaldependencies.org/en/pos/PRON.html), [determiners](https://universaldependencies.org/en/pos/DET.html) and pronominal [adverbs](https://universaldependencies.org/u/pos/ADV.html).
