### ISSUE TITLE
UD Documentation in PDF format?

### ISSUE THREAD

**Issue by yosiasz** [UniversalDependencies/docs#867]
Greetings

Is there a UD standards available in PDF format?

https://universaldependencies.org/

Thanks

**Comment by dan-zeman** [comment]
I don't think there is a PDF version of the documentation. First, the documentation is a hypertext site, so it would not be trivial to make it one document; second and more important, it is a living organism (the docs changing constantly), so the PDF would quickly become outdated.

If you need an off-line version of the documentation, perhaps you could use the snapshot of the website that is published with every UD release (but sometimes there are issues with the hyperlinks being used locally).
