### ISSUE TITLE
obl:npmod entry missing in documentation

### ISSUE THREAD

**Issue by nesor** [UniversalDependencies/docs#872]
(https://universaldependencies.org/u/dep/obl.html)
... although it occurs at least in some English treebanks

**Comment by nschneid** [comment]
Language-specific subtypes like `obl:npmod` and `nmod:npmod` do not have universal-level documentation pages, but you can access language-specific documentation for English at: https://universaldependencies.org/en/dep/

**Comment by nesor** [comment]
Thank you!

I was confused when I noticed that English is not listed at https://universaldependencies.org/u/dep/obl.html, although it is at https://universaldependencies.org/u/dep/nmod.html, and there’s a link from https://universaldependencies.org/en/dep/nmod.html to https://universaldependencies.org/en/dep/nmod-npmod.html. I can see now that the language-specific pages linked from the list of treebanks are more useful, but somehow I failed to notice them. I always started from the list of relations for all languages.

**Comment by nschneid** [comment]
Huh you're right, I guess plain `obl` was never added to the English docs. Let me do that now.

**Comment by nschneid** [comment]
(Also updated the English `nmod` page for good measure)

**Comment by nesor** [comment]
Thanks!
