### ISSUE TITLE
Enhanced dependencies for cross-serial vs distributive semantics of relations

### ISSUE THREAD

**Issue by danielhers** [UniversalDependencies/docs#875]
See UniversalDependencies/docs#876. Opening an issue here since languages other than English also have similar constructions.
Constructions like "respectively" makes predicts explicitly non-distributive but rather cross-serial semantically. Should EUD account for that or ignore this modifier?

**Comment by dan-zeman** [comment]
I have transferred the original issue from UD_English-EWT to docs, where it became #876, so we have it with the whole thread here. (It belongs here anyway, as it is about the guidelines, not about EWT.) Closing this issue as a duplicate.

**Comment by danielhers** [comment]
Oh, sorry I had failed to find it. Thanks!

**Comment by dan-zeman** [comment]
No problem. You could not find it because I transferred it _after_ you created the new issue :-)
