### ISSUE TITLE
How to annotate a Thai classifier, determiner and noun with the relation clf

### ISSUE THREAD

**Issue by leky40** [UniversalDependencies/docs#878]
Dear,

I am working on my MA thesis (UD Treebank for Thai). I was wondering how a Thai classifier, determiner and noun would be annotated with the relation `clf` I was trying to understand the [Chinese samples in the UD website](https://universaldependencies.org/u/dep/clf.html) because it is quite similar to the ones in Thai. However, I am not really sure where an arc should go from and to.

The Thai sentence is:

  แมว           ตัว            นั้น            รัก         เจ้าของ
NOUN     NOUN        DET       VERB       NOUN
  cat     (classifier)     that        love         owner

In Thai, when a classifier is used with a determiner, the determiner modifies the classifier. And both classifier and determiner modify a noun. As for this Thai sample, should the arc goes from the classifier to the determiner? I am quite confused because the way of this arc heading from and to is different from the Chinese one in the UD website.

Could anyone please explain this and how I should annotated this Thai sentence with aa classifier?

Thank you

Siriluck

**Comment by dan-zeman** [comment]
Is it correct to assume that the fluent English translation of the example is "That cat loves its owner."?

**Comment by leky40** [comment]
@dan-zeman Yes. the English translation is correct. In the Thai sentence, no possessive pronoun is used to express whose owner is. It's like underneath meaning which we understand ourselves. Sometimes I forgot not to make this clearer in English translation.

**Comment by dan-zeman** [comment]
> In Thai, when a classifier is used with a determiner, the determiner modifies the classifier. And both classifier and determiner modify a noun.

How do we know that the determiner modifies the classifier? If it is so, then I can imagine an analysis like this:
![that-cat](https://github.com/UniversalDependencies/docs/assets/663752/986dd1ce-a206-407d-9170-e2b7b55f8f09)

``` latex
\begin{dependency}[edge vertical padding=1ex]
  \begin{deptext}
    \thai{แมว} \& \thai{ตัว} \& \thai{นั้น} \& \thai{รัก} \& \thai{เจ้าของ} \\
    mæw  \& tạw  \& nận  \& rạk  \& cêāk̄hxng \\
    NOUN \& NOUN \& DET  \& VERB \& NOUN \\
    cat  \& CLF  \& that \& love \& owner \\
  \end{deptext}
  \depedge[edge unit distance=2ex]{4}{1}{nsubj}
  \depedge{1}{2}{clf}
  \depedge{2}{3}{det}
  \depedge{4}{5}{obj}
  \deproot{4}{root}
  \deptrans{That cat loves its owner.}
\end{dependency}
```

**Comment by sylvainkahane** [comment]
Currentlty we have two different analysis of classifiers in Chinese treebanks. For a sequence, NUM CL N, where CL is the classifier, the analysis is:
1) N -[nummod]-> NUM -[clf]-> CL,
in UD_Chinese-HK,  UD_Chinese-CFL, and UD_Classical-Chinese-Kyoto;
2) N -[clf]-> CL -[nummod]-> NUM, 
in UD_Chinese-GSD and UD_Chinese-PUD.

Analysis 1 is the one that has been chosen after the long discussion in #374. It is coherent with UD principles, if we consider that the classifier is a function word and the numeral is a content word. A SUD analysis should probably be similar to Analysis 2. (By the way, I don't know who is in charge of GSD and PUD, but if everyone agree, our team, which is developing new treebanks for Chinese could change the analysis in GSD and PUD.)

I don't know what are the difference between Thai and Chinese, but I think that the classifier should also be considered as a function word in Thai and Analysis 1 adopted, even in the case of a determiner, that is N -[det]-> DET -[clf]-> CL for a sequence DET CL N.

**Comment by leky40** [comment]
How do we know that the determiner modifies the classifier? If it is so, then I can imagine an analysis like this:

Your analysis is the same as mine. But when I compared it with the Chinese example in UD, I am very quite confused. 

Your question is very good. I am thinking so hard what can pinpoint the determiner modifies the classifier. I even asked myself if the determiner actually modified the head noun (cat), and if so, why?

In Thai, a modifier (adj and adv) is always placed after a noun to be modified, except a quantifier placed before a noun. 

What I could think of (it might not be a good / appropriate answer) is the classifier (ตัว) is used to express the characteristic of the cat (head noun) and also to count. This is what a classifier functions, but its POS is a noun. And the determiner (นี้) is used to specify which cat. And the determiner modifies the noun which is the classifier (ตัว). And this whole NP (ตัวนี้) (classifier + determiner) modifies the head noun (cat) to express specific and definiteness towards the head noun. 

To express specific information towards a noun to be modified Thai, all modifiers (which can be a word and/or a clause) are placed after what is modified. 

In this Thai sentence, the determiner cannot skip modifying the classifier and then modify the head noun instead. However, when a classifier is omitted --  just a noun and determiner, a determiner modifies a noun. 

Omitting a classifier can be found a lot in speaking and some kinds of writing. Sometimes using it has some reasons, such as emphasising, clarifying, etc.

So I think that a basic answer is that a determiner modifies a noun. And in this Thai sentence, ตัว is a noun and functions as a classifier. Then, the determiner นี้ modifies ตัว; and this whole NP ตัวนี้ modifies the head noun แมว. 

I am not sure if what I explain here answers your question @dan-zeman . I am pretending to be a non-native Thai speaker as well to cover all the possible questions which might be raised. I am still raising some questions out of your question, and asked some of my Thai friends and arguing with them now :) 

Hope this could be clear decently.

**Comment by leky40** [comment]
@dan-zeman  I corrected the phonetic glossing for this Thai sentence. 

แมว     ตัว   นั้น   รัก     เจ้าของ
mɛɛw tua  nán rák    câwkhɔ̌ŋ

**Comment by leky40** [comment]
@sylvainkahane  Could you please elaborate this statement of yours?

> but I think that the classifier should also be considered as a function word in Thai 

Why should a classifier in Thai be a function word? Thai has a lot of classifiers, like a lot a lot. I as a native speaker cannot even remember all of them. And they are used differently also regarding to different factors, like hierarchical ones. And the words used as classifiers can be used and referred to something else. They can also be used to compound with another word. 

I still cannot see how a classifier in Thai should be a function word.

**Comment by leky40** [comment]
@sylvainkahane If you remember, there is another structure / construction I presented you.

From the Thai sentence above,  N N(used as CL) DET can have ADJ / VERB (a stative verb) added between N (head noun) and N (used as CL) as well. A relative clause can even be added between them also.

N **ADJ / VERB** N(used as CL) DET 

แมว ดำ ตัว นั้น
cat black (CL) that

When another word is added in this structure, the classifier should still be considered a function word?

**Comment by sylvainkahane** [comment]
I try to develop my analysis. I think that the determiner and the classifier form a phrase. Your example with an adjective (N ADJ CL DET) confirms this intuition.
Then we have to decide what is the head of the phrase CL DET. UD considers the content word to be the head, so DET is the best candidate.
You also said that the classifier can be omitted in some genres, which is also a good argument to consider that DET is the head.
