### ISSUE TITLE
Annotation of numeric intervals (2001-2010)

### ISSUE THREAD

**Issue by jheinecke** [UniversalDependencies/docs#880]
Is there a standard or an idea for a future standard to handle tokens like two numbers seperated by a hyphen (matching this regex ` [0-9]+-[0-9]+`). These can be 
1. just hyphens for readability (as in ISBN or telephone numbers)
2. intervals: "WW2 lasted 1939-1945", "elle est cependant pillée dans les années 1225-1230"
3. inprecision: "10-20 people where present"
4. (tennis) results: "il let bat 10-4"

I first check in the current treebanks showed, that these are nearly always annotated ad a single token, with UPOS NUM, feature NumType=Card (and NumForm=Digit (instead of Combi) for treebanks which use this feature. At least for the 2nd case, I wonder whether this should better split up into three tokens and annotated accordingly ("WW2 lasted [from] 1939 to 1945") (with or without the empty word "from" in this example). Maybe this can be annotated similarly like "from 2001 to 2010" which is being discussed in #871?

**Comment by sylvainkahane** [comment]
In Spoken French, we analyzed most of these examples as a coordination. But is spoken data the problem is a bit different because we have necessary two tokens.
See http://universal.grew.fr/?custom=62cec597a623b
(I think that some of our examples could be reanalyzed as reformulations rather than coordination, but you will see that some examples correspond to your cases.)

**Comment by dan-zeman** [comment]
I support splitting intervals into multiple tokens and treating them as coordination. This is what you will find in data converted from the Prague treebanks, e.g., in UD_Czech-PDT: [http://hdl.handle.net/11346/PMLTQ-JTCC](http://hdl.handle.net/11346/PMLTQ-JTCC).

Some related ideas can be found in [my paper about dates and times in UD](https://aclanthology.org/2021.udw-1.15.pdf) (Section 7).

**Comment by dan-zeman** [comment]
Related: #871.

**Comment by amir-zeldes** [comment]
I'm all for tokenizing them apart (this is also the general LDC corpus practice). 

I think whether it's a coordination or not should be decided on a language by language basis using syntactic criteria. For English, I think the normal reading of the dash is as the preposition "to" (or sometimes "through" or "until/till"), and I have argued against treating it exceptionally as a CCONJ in this case, see the discussion in #871. Of course, there are arguments for both analyses and I wouldn't be surprised if there are languages where the case for either of the two analyses is stronger than in English.

**Comment by jheinecke** [comment]
I didn't think of that before, but if only intervals`2010-2020` are split (MWT) but not other (single) hyphens between numbers, the tokenisation will be difficult
