### ISSUE TITLE
Clausal complements of NOUN, ADJ and ADV

### ISSUE THREAD

**Issue by MagaliDuran** [UniversalDependencies/docs#881]
There are subordinate clauses modifying nominal predicates that are identical to typical advcl. Should we annotate them as dependents on acl or advcl?
Ex:
- He is a teacher, although he doesn't teach anymore.
- She is still beautiful, although she has aged.

Along the same lines: how should we annotate clausal complements of adjectives and adverbs that present argumental structure? 
Ex:
- We are close to winning the race.
- We are afraid of losing the fight.

We are annotating the latter as dependents on acl, following the tradition of Brazilian Portuguese standard grammars that treat them as nominal complement clauses. However, we would like to confirm this interpretation, since there are not examples of  these cases in UD guidelines (as far as we can see).

Thank you

**Comment by nschneid** [comment]
Per current guidelines the choice between `advcl` vs. `acl` depends strictly on the head, so `acl` for noun-headed clausal complements as well as adjuncts, and `advcl` for verb/adjective/adverb-headed clausal complements as well as adjuncts.

Strenuous objections have been raised about the lack of a core vs. non-core distinction for dependent clauses, e.g. in [this paper](https://aclanthology.org/C18-1324), and the policy may be revisited in the future.

**Comment by nschneid** [comment]
This tension also applies with verb heads: see for example "They heard about you missing classes" under [`advcl`](https://universaldependencies.org/u/dep/advcl.html). Arguably "about you missing classes" is a complement, but because of the preposition we are forced to use `advcl` rather than `ccomp`.

**Comment by amir-zeldes** [comment]
I think even under existing policies, if the clause modifies the predication and not the noun itself, it's advcl by analogy to an obl modifying a nominal predication.

If that's right, then this example is advcl (and I think it definitely should be):

He is a teacher, although he doesn't teach/advcl anymore.

**Comment by MagaliDuran** [comment]
> Per current guidelines the choice between `advcl` vs. `acl` depends strictly on the head, so `acl` for noun-headed clausal complements as well as adjuncts, and `advcl` for verb/adjective/adverb-headed clausal complements as well as adjuncts.
> 
> Strenuous objections have been raised about the lack of a core vs. non-core distinction for dependent clauses, e.g. in [this paper](https://aclanthology.org/C18-1324), and the policy may be revisited in the future.

Thank you, Nathan. Very interesting paper. The non-distinction of adjuncts and arguments, applied to phrasal complements is not equally applied to clausal complements and this creates a discomfort. However, the solution to equalizing the two forms, phrasal and clausal complements, seems to be different for those who advocate the distinction between arguments and adjuncts and those who advocate no distinction.
In Portuguese, we are using advcl exclusively for adverbial clauses. Various clauses introduced by preposition (followed by non-finite verbal forms) or by preposition + SCONJ relativizers (followed by finite verbal forms) are annotated as xcomp and ccomp. We had not even considered annotating prepositional clauses as advcl. But I agree that it is inconsistent to say that a phrasal complement is non-core and that its clausal equivalent is core.
The burden of our linguistic traditions and the idiosyncrasies of our languages seem to influence the way we look at these problems.

**Comment by dan-zeman** [comment]
Yes, it is inevitable that traditional grammars are sometimes in conflict with the UD guidelines (as well as different traditional grammars are in conflict with each other). Naturally, UD data are supposed to follow the UD guidelines in such cases.

I agree with @amir-zeldes that in clauses with nominal predicates, one has to distinguish whether the nested clause modifies the outer clause/predication as a whole, or it only modifies the nominal that acts as a predicate. Hence we have `advcl` in _He is a teacher, although he doesn't teach anymore_ but `acl:relcl` in _He is a teacher whom the students love_.

Furthermore, if the nested clause modifies an adjective or adverb, even if that adjective/adverb is not a predicate of a clause, one has to use the relations that are used for dependents of clauses. (The first rule is: if the head is not a nominal, do not use a relation that is reserved for modifiers of nominals.) Therefore, in _We are afraid of losing the fight_, the modifier _of losing the fight_ cannot be `acl` or `nmod`. Instead, it has to be `advcl` or `obl` (depending on whether the modifier is a clause or a nominal, i.e., whether _losing_ is a `VERB` or a deverbal `NOUN`).

**Comment by MagaliDuran** [comment]
@dan-zeman, so you mean that advcl should always be used when modifying a predicate, be it verbal or nominal? It would be interesting to add at least one example of a nominal predicate (NOUN) modified by advcl in the Guidelines. 

By the way, the term "nominal" in "nominal predicates" includes adjectives and adverbs (as opposed to verbal predicates), hence the possible interpretation that acl, used to annotate clausal nominal modifiers, could be used to modify adjectives and adverbs as well.

Again, it is not explicit in the guidelines that clausal complements of verbs, adverbs and adjectives. whenever introduced by a preposition, should be annotated as advcl. If so, should the following clauses be advcl?

- You could stop them from doing that.
- They heard about you missing classes. (@nschneid  example)
- They complained about having to do that.
- We look forward to welcoming you. 

In fact, several prepositions used to introduce a infinitive subordinate clause in Portuguese correspond to the English "to", which is always interpreted as part of the infinitive and not as a preposition, such as:

- Ele gosta de nadar. (He likes to swim.)
- Ele começou a pensar. (He has started to think.)

Since the term "adverbial" can give rise to a very narrow interpretation, it would be crucial to make it explicit that advcl is also used to annotate complements of verbs, adjectives and adverbs introduced by prepositions.

I particularly dislike this, as clausal complements annotated as xcomp in one language would correspond to clausal complements annotated as advcl in another language.

**Comment by Stormur** [comment]
> Strenuous objections have been raised about the lack of a core vs. non-core distinction for dependent clauses, e.g. in [this paper](https://aclanthology.org/C18-1324), and the policy may be revisited in the future.

If I remember well, this paper is not really about a lack of core/oblique distinction for clauses, which actually is there: `csubj`/`*comp` vs. `advcl`. It's more on using different labels to make it fully clear and avoid some asymmetries which might act as confusing (and I have to say that I like that proposal). 

> In fact, several prepositions used to introduce a infinitive subordinate clause in Portuguese correspond to the English "to", which is always interpreted as part of the infinitive and not as a preposition, such as:
> 
>     * Ele gosta de nadar. (He likes to swim.)
> 
>     * Ele começou a pensar. (He has started to think.)
> 
> 
> Since the term "adverbial" can give rise to a very narrow interpretation, it would be crucial to make it explicit that advcl is also used to annotate complements of verbs, adjectives and adverbs introduced by prepositions.
> 
> I particularly dislike this, as clausal complements annotated as xcomp in one language would correspond to clausal complements annotated as advcl in another language.

Indeed, this is not the case. Nothing prevents that a construction where a subordinate is introduced by some connector, be it `ADP` or `SCONJ` or else, is treated as a core clausal argument, if it can be clearly identified like this. There is no "automatic" rule dependning on the presence or absence of such a connector. The examples that you give in Portuguese are to me clearly `xcomp` with no doubts. 

The English example _They heard about you missing classes_ is very different from these: it is the clausal realisation of an oblique argument, as opposed to something like _They heard you missing classes_ (whatever is the sound of missing classes). And this is expressed through a preposition here, but in a language like e.g. Latin it might just be visible from the inflection of a nominal verb form.

**Comment by amir-zeldes** [comment]
I agree with @MagaliDuran that the advcl label is confusing for clausal complements introduced by a preposition. One of Adam's points in the paper cited above is that it is basically a misnomer for something that might better be designated as `cobl` (clausal equivalent of obl, an oblique clause). But since we cannot add major labels while still under UD V2, we are somewhat stuck with the current situation. 

I've been tempted to consider a sublabel `advcl:arg` or maybe just `advcl:obl`, but I think this is a larger issue that should maybe be resolved globally whenever a possible V3 is discussed.

**Comment by nschneid** [comment]
What about reinterpreting `acl` as "(oblique) argument clause" and `advcl` as "adverbial/modifier/adjunct clause"? It would be a major change of interpretation (that would not be done lightly of course) but could circumvent the prohibition on changing the deprel names before v3.

**Comment by amir-zeldes** [comment]
I think that would create two problems, one is that it would be the only `acl` attached to a verb, and two that the term 'argument' is canonically rejected by UD (whether we think that is a good idea or not). Overall I think it would be cleaner to use a subtype, which could trivially be converted to a new major relation in the longer term.

**Comment by nschneid** [comment]
OK but then to fully capture clausal complementation we'd need `advcl:obl` as well as `acl:obl` for adpositionally-marked clausal complements of nominalizations and `acl:comp` for other clausal complements of nominalizations:

- `ccomp`: Have you decided **that/whether you'll attend tomorrow**?
- `xcomp`: Have you decided **to attend tomorrow**?
- `advcl:obl`: Have you decided **about attending tomorrow**?
- `acl:comp`: your decision **that you'll attend tomorrow**
- `acl:xcomp`?: your decision **to attend tomorrow**
- `acl:obl`: your decision **about attending tomorrow**
- `acl:relcl`: your decision **that you made yesterday**

**Comment by Stormur** [comment]
I am not able to follow these suggestions. `advcl` _already is_ the clausal oblique relation, and it has nothing to do with the presence of prepositions/conjunctions, at least not universally. But surel ya renaming to `cobl` or similar would help.

`acl` is not truly core or oblique in that it is part of the modifier/non-modifier dichotomy, the same as `amod`/`nmod`. What is confusing here is that it does not have the `mod` suffix, and `cl` seems to point to the core/oblique distinction; that is why one could propose `cmod` instead.

**Comment by amir-zeldes** [comment]
I am not as bothered by the absence of acl:obl since unlike `advcl`, the term `acl` isn't heavily laden with existing meaning in linguistics (no non-UD linguist calls PP object clauses "adverbial clauses" IMO). I'd be more interested in `acl:comp`, but that runs into whether or not we want to invest in arg/adjunct distinctions, which UD generally discourages. 

In any case I feel like these are probably not things to decide quickly on the tracker, but more mid to long-term discussions for a larger face to face panel discussion, maybe something to discuss at Dagstuhl next year?

**Comment by nschneid** [comment]
Yeah this needs a bigger discussion

**Comment by MagaliDuran** [comment]
By the way, the guidelines mention that the head of xcomp may be an adjective, as far as I understand:

"An open clausal complement (xcomp) of a verb or an ADJECTIVE is a predicative or clausal complement without its own subject.” 

This might suggest that adjective complements should be annotated with xcomp, do you agree? If so, "afraid of losing the fight" could be xcomp?

**Comment by nschneid** [comment]
I agree that some adjective complements are xcomp. Most often, xcomp applies to infinitival clauses. Examples in EWT include "reluctant to get involved" and "worth hitting up" (note that "worth" is an exceptional ADJ that can also take an object).

I'm not sure about "afraid of losing", though. "Interested in breeding" is `advcl` in EWT. My guess is that *prepositional* (as opposed to infinitival) dependents of adjectives have not been recognized as complements.

**Comment by amir-zeldes** [comment]
> prepositional (as opposed to infinitival) dependents of adjectives have not been recognized as complements

Yes, I would guess that's because they are obliquely mediated (by the preposition), and therefore not seen as core. I guess infinitive 'to' is traditionally not considered a preposition in that construction, so it gets away with being called 'core', when other prepositions are considered to introduce obliques.

**Comment by dan-zeman** [comment]
> It would be interesting to add at least one example of a nominal predicate (NOUN) modified by advcl in the Guidelines.

Good idea. Added in https://github.com/UniversalDependencies/docs/commit/a00ec2fea61f98d0038a8e62c08892886ed0da8b.
