### ISSUE TITLE
Letter used like a number in/as an entity-identifier: UPOS and feats

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#882]
We have identifiers (for an entity such as an apartment) that can be letters, numbers, or both. So, in a street address, what is the right way to handle:

- Apt. **1** - NUM, `NumForm=Digit`, `NumType=Card`
- Apt. **A** - PROPN? no numeric features because no digits involved?
- Apt. **1A** - NUM? [`NumForm=Combi`](https://universaldependencies.org/u/feat/NumForm.html) because it contains both letters and digits, or `NumForm=Digit` because it contains a digit and the alphabetic part is not a closed-class suffix?

Related: #654, #156

**Comment by amir-zeldes** [comment]
+1 for Combi

**Comment by dan-zeman** [comment]
I think it's `PROPN`, and no `NumForm` is needed.

**Comment by nschneid** [comment]
@dan-zeman So as soon as it contains a letter it ceases to be numeric? What about postal codes, which in some countries are strictly numeric but in others contain a mixture of letters and numbers?

**Comment by dan-zeman** [comment]
> So as soon as it contains a letter it ceases to be numeric? What about postal codes, which in some countries are strictly numeric but in others contain a mixture of letters and numbers?

Yes, a rule like that seems to me easy enough to apply, and reasonably close to what the tags are supposed to mean. I am quite fine with US zip codes being `NUM` and British ones being `PROPN`. Maybe I would find it too odd if some zip codes **in one country** contain letters and others only digits; I'm not aware of any such country, but if it happens, then I can imagine a rule that all zip codes in that country are `PROPN`.

**Comment by nschneid** [comment]
What about the proposed clarification in #883?

**Comment by dan-zeman** [comment]
> What about the proposed clarification in #883?

Sounds good to me.

(And I especially like using _130XE_ as an example :-))
