### ISSUE TITLE
advcl:relcl for relative clauses modifying clauses

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#886]
>  * maybe they had bad teachers, which is a problem
>  * acl:relcl(had,problem)
>  * nsubj(problem,which)

Once again, we run into issues with deprels mixing POS/phrase type and grammatical relation. I think it's fair to say this is indeed a relative clause, but it's an adverbial rather than adnominal relative clause. So should it be `advcl:relcl`?

While some of the supplements arguably modify a nominal indirectly, and thus `acl` could be argued, this one is pretty clearly modifying a verb or VP/clause.

_Originally posted by @nschneid in https://github.com/UniversalDependencies/docs/issues/762#issuecomment-768546866_

**Comment by nschneid** [comment]
The core group has decided to adopt `advcl:relcl` for such cases. Even though most relative clauses are adnominal, it would be technically wrong to use `acl:relcl` for non-adnominal uses of relative clauses. English guidelines will be updated accordingly. (`advcl:relcl` is [already in use](https://universaldependencies.org/ext-dep-index.html#advcl) for some languages.)

**Comment by Stormur** [comment]
Nice. I have recently been stumbling very much on these kinds of "metaclauses" which recur often in some rhetoric styles. 

Until now in Latin we have used `advcl:pred`, subsuming these modifying clauses under the phenomenon of secondary predication: in fact, there seems to be (at least in Latin) no other way to refer to a clause taken as a whole, instead than to a single argument (like in the case of a "depictive"), than another finite clause making use of a "generic" relative element in the neutral grammatical gender, which can be in singular or (more rarely) in plural, and is needed for reference. Though surely the notion of _expansion_ that underlies both secondary predications and adnominal relative clauses creates grey zones. Actually, I think that this use of advcl can open up new ways to treat some cases often annotated as `parataxis`.

However, is the core group meant to be that of UD or only of English treebanks?

**Comment by nschneid** [comment]
We mostly discuss universal issues but have been doing a deep dive into English relative constructions. The hope is to then pursue typological guidelines for relative constructions.

**Comment by Stormur** [comment]
So will this be part of future UD amendments?

**Comment by nschneid** [comment]
Once we have better universal guidelines we can announce it as a clarification. Subtypes are technically optional and we're not really changing the meaning of `acl:relcl` as defined [here](https://universaldependencies.org/u/dep/acl-relcl.html).
