### ISSUE TITLE
Feature request for Portuguese

### ISSUE THREAD

**Issue by adripag** [UniversalDependencies/docs#889]
We are a group of linguists at four universities in Brazil engaged in coordinating annotation projects to build treebanks for Brazilian Portuguese. 
We find it relevant to our projects to be able to annotate morphological features pertaining to Degree, more specifically to diminutives, augmentatives and superlatives.

Several POS categories can yield diminutive and augmentative forms in Portuguese:  NOUN, ADJ, ADV, VERB (non-finite forms), PROPN. 

We would like to request the inclusion of  Degree=Dim, Degree=Augm within the features ascribable to NOUN, ADJ, ADV, VERB, PROPN. Degree=Sup within the features ascribable to ADJ, ADV and VERB in Portuguese.

Below are examples of instances we would like to annotate.

Degree=Dim:

**Risquinho** na sobrancelha cresce depois? NOUN
Conheça a história de **Joãozinho** e Maria. PROPN
Assobiava **baixinho**.  ADV
Festa com café da manhã incluso, tudo **organizadinho** pela nossa equipe. VERB (past participle)
Aumentei o som e sai **dançandinho**. VERB (gerund)
Peça para a picanha vir bem passada se não vem bem **palidazinha**. ADJ

Degree=Augm

João comprou um **apartamentão**. NOUN
A casa da minha avó tinha um **varandão** imenso. NOUN
O filme foi **ignoradaço** pela turma. VERB (past participle)
Me lembro que foi **comentadaço** pela net afora.  VERB (past participle)
Deu certo e foi **rapidaço**. ADJ
Tomo um banho **rapidão**. ADV
Uma doença rara, com um nome **complicadão**. ADJ

Degree=Sup

A atriz foi **aplaudidíssima**. VERB (passive past participle)
O lugar fica **pertíssimo** da minha casa. ADV
Você está **certíssimo**. ADJ

Adriana Pagano (UFMG), Ariani Di Felippo (UFSCar), Cláudia Freitas (PUC-Rio), Elvis de Souza (PUC-Rio) and  Magali Duran (ICMC/USP).

**Comment by dan-zeman** [comment]
`Degree=Sup` already exists but given [its definition](https://universaldependencies.org/u/feat/Degree.html), I think that `Degree=Abs` (which also already exists) would be more appropriate for

_A atriz foi <b>aplaudidíssima</b>._

`Degree=Dim` has not (yet) been added to the universal guidelines but it is used as a language-specific value in Afrikaans ([see here](https://universaldependencies.org/ext-feat-index.html#degree)) and it could be documented and used for Portuguese as well. Similarly, one could document and use `Degree=Aug` for augmentatives.

**Comment by Stormur** [comment]
I just report that also Latin currently uses `Degree=Abs` (and not `Sup`) for the same reasons mentioned by @dan-zeman , and that `Degree=Dim` (not limited to `ADJ`s) is in course of being added, especially starting with documentation and then regular implementation. Since Portuguese is a descendant of Latin, we are really speaking of the same exact features and values as you show. Augmentative is not present in Latin, but I think `Degree=Aug` is surely the way to go.

**Comment by arademaker** [comment]
Interesting discussion. @leoalenc and I have discussed the augmentatives and diminutives for a while. We had a paper about our approach in the [HPSG Grammar for Portuguese](https://github.com/LR-POR/PorGram/issues/78) for the evaluative morphology. Unfortunately, the paper was not accepted last year, and we are revising it to submit it again. There are also open issues that I plan to solve in the following weeks in the Bosque; see [this](https://github.com/UniversalDependencies/UD_Portuguese-Bosque/issues/279). This discussion is all also connected with our full-form dictionary for Portuguese; see [here](https://github.com/LR-POR/MorphoBr/issues/91).

As @dan-zeman also pointed out, we are also considering the reuse of the language-specific values from https://universaldependencies.org/ext-feat-index.html#degree.

**Comment by leoalenc** [comment]
> Interesting discussion. @leoalenc and I have discussed the augmentatives and diminutives for a while. We had a paper about our approach in the [HPSG Grammar for Portuguese](https://github.com/LR-POR/PorGram/issues/78) for the evaluative morphology. Unfortunately, the paper was not accepted last year, and we are revising it to submit it again. There are also open issues that I plan to solve in the following weeks in the Bosque; see [this](https://github.com/UniversalDependencies/UD_Portuguese-Bosque/issues/279). This discussion is all also connected with our full-form dictionary for Portuguese; see [here](https://github.com/LR-POR/MorphoBr/issues/91).
> 
> 
> 
> As @dan-zeman also pointed out, we are also considering the reuse of the language-specific values from https://universaldependencies.org/ext-feat-index.html#degree.
> 
> 

@arademaker , thank you for pointing that out. In that paper of ours as well as in the cited issue of the Bosque repository we had argued for the representation of  diminutives, augmentatives and absolute superlatives with the values _dim_, _aug_, and _abs_ assigned to the feature _degree_. So I'm very glad that it seems that these values will be included into the UD standard.

**Comment by adripag** [comment]
@dan-zeman 
We have discussed all comments and contributions and prepared an md  file with the feature Degree for Portuguese. Not sure where or to whom we should submit this.
Thanks for your assistance.

**Comment by arademaker** [comment]
Can you send it to me?

**Comment by dan-zeman** [comment]
[Degree.md](https://github.com/UniversalDependencies/docs/blob/pages-source/_pt/feat/Degree.md) for Portuguese [already exists](https://universaldependencies.org/pt/feat/Degree.html), so it should be enough to submit a pull request with the proposed additions.

In the meantime, `Degree=Dim` and `Degree=Aug` are [available universally](https://universaldependencies.org/u/feat/Degree.html). But languages that have their own documentation of `Degree` must repeat the values there, otherwise they get masked.

**Comment by arademaker** [comment]
Just reporting that I already submitted the PR and this issue was solved.
