### ISSUE TITLE
broken link to SIL's Glossary of Linguistic Terms

### ISSUE THREAD

**Issue by leoalenc** [UniversalDependencies/docs#890]
In the UD documentation, SIL's [Glossary of Linguistic Terms](https://glossary.sil.org/term) is often cited, for example, in the page on the [AUX](https://universaldependencies.org/u/pos/AUX_.html) POS tag we find the following link:

http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/WhatIsAnAuxiliaryVerb.htm

However, clicking on the link throws a `404 Not Found` error. The correct link should be:

https://glossary.sil.org/term/auxiliary-verb

**Comment by arademaker** [comment]
In 36fe0d97c4 I solved the broken links for EN and PT documentation.

**Comment by arademaker** [comment]
Maybe @dan-zeman can double-check the PR and accept it https://github.com/UniversalDependencies/docs/pull/892

Let me know if I should have worked in another branch. It is not clear to me the current situation. We have the gh-pages, pages-source and master.

**Comment by dan-zeman** [comment]
> Let me know if I should have worked in another branch. It is not clear to me the current situation. We have the gh-pages, pages-source and master.

pages-source is the branch to work with. gh-pages should not be touched manually, and master should not exist.

**Comment by arademaker** [comment]
Ok, so ignore or close my PR to master. I will redo the changes in a branch based on pages-source

**Comment by dan-zeman** [comment]
> Ok, so ignore or close my PR to master. I will redo the changes in a branch based on pages-source

OK, closed. (And master removed once again.)
