### ISSUE TITLE
Jussive in older Czech?

### ISSUE THREAD

**Issue by cinkova** [UniversalDependencies/docs#921]
What Mood is assigned to the archaic Czech imperative, sometimes ending with _ž_, expressing  the desire that something happens? Is it Jussive? Examples: _Budiž světlo!_ (Let it be light!) _Vás však neprobudiž smích náš ani lkání!_ (Let neither our laughter nor our whining wake you up!). An example without _ž_: _Zavzni moje tiché noční přání: Dobrou noc!_ (Let my quiet night wish sound: Good night!). I will annotate it with Jussive and 3rd Person until I am told otherwise.

**Comment by dan-zeman** [comment]
This is a question about guidelines, not about bugs in a particular treebank, so I am going to move the issue to the docs repository.

**Comment by dan-zeman** [comment]
I don't think we need `Mood=Jus` in Czech. This can be safely annotated as 3rd person imperative: `Mood=Imp | Number=Sing | Person=3`. There are a few such examples in PDT, so the imperative paradigm of _být_ "to be" looks like this:

```
buď      VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Sing|Person=2|Polarity=Pos                                     52
budiž    VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Sing|Person=3|Polarity=Pos                                     14
buď      VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Sing|Person=3|Polarity=Pos                                      1
Buďme    VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Plur|Person=1|Polarity=Pos                                      1
buďte    VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Plur|Person=2|Polarity=Pos                                     22
Nebuďte  VerbForm=Fin|Mood=Imp|Aspect=Imp|Number=Plur|Person=2|Polarity=Neg                                      1
```

**Comment by cinkova** [comment]
Then I would suggest updating the documentation for Czech, since it explicitly lists only the 1st and 2nd person with Imperative.

**Comment by dan-zeman** [comment]
Good point. Fixed in https://github.com/UniversalDependencies/docs/commit/0dfefdc36507a107a2f2888bf90dc45ee95dcff9.

**Comment by martinpopel** [comment]
I am no expert on this, but according to [MorfFlex2.0](http://lindat.mff.cuni.cz/services/morphodita/), these archaic imperative forms can be used in the second person as well. For some words (staniž, dejž,...) it is the only option, for other (budiž, zavzni,...) both 2nd and 3rd person are available (I have no explanation for this):

Token | Lemma | XPOS
-- | -- | --
staniž | stát-2_^(stanu_staneš) | Vi-S---2--A-P-3
dejž | dát-1 | Vi-S---2--A-P-2
budiž | budiž | TT-------------
  | být | Vi-S---2--A-I-2
  | být | Vi-S---3--A-I-2
zavzni | zavznít_,h_^(^GC**zaznít) | Vi-S---2--A-P--
  | zavznít_,h_^(^GC**zaznít) | Vi-S---3--A-P-4

We cannot use [Mood=Jus](https://universaldependencies.org/u/feat/Mood.html#Jus) together with [Mood=Imp](https://universaldependencies.org/u/feat/Mood.html#Imp) (theoretically, we could use `Mood=Imp|Jus`, but that would suggest there is an ambiguity between the two moods, which is not the case). So I would also stay with `Mood=Imp` - this way, we also don't need to reannotate other Czech UD treeebanks.

Note that all the listed MorfFlex2.0 analyses have [234] on the last position of XPOS, where the meaning is:
2 Variant, rarely used, bookish, or archaic
3 Very archaic, also archaic + colloquial
4 Very archaic or bookish, but standard at the time 
I think, we could merge all these style tags into [Style=Arch](https://universaldependencies.org/u/feat/Style.html#Arch), which would help us to distinguish the 2nd person archaic imperative (e.g. "dejž")  from its modern variant ("dej").
