### ISSUE TITLE
Czech Style Arch vs. Rare

### ISSUE THREAD

**Issue by cinkova** [UniversalDependencies/docs#922]
So far, I have been annotating archaic **lexemes** with `Arch`, but archaic **forms** and **orthography** with `Rare`, as I have understood it from the documentation. I also standardize the lemma whenever I can, since 19th-century Czech is very close to truly modern Czech. OK?

**Comment by dan-zeman** [comment]
The [Style feature in the Czech](https://universaldependencies.org/cs/feat/Style.html) data is there only to preserve the last (fifteenth) position of the PDT (XPOS) tag. It is a language-specific feature, it does not have the universal status in UD, although there are multiple languages that use it. The description of the values in the Czech UD documentation is either based on the documentation of PDT, or on observations from the data, the examples are taken from the data. But to be honest, I don't think their usage is well defined, and their annotation probably is not much consistent. If you think you need this feature, feel free to come up with a consistently applicable definition.

The distinction between lexemes, inflection and orthography is one issue.

Independently from that, `Style=Arch` seems problematic once you collect texts from multiple historical periods. You could find phenomena that sound archaic now but they were normal in the first half of the 20th century. And if we annotate texts from the 14th century, almost everything will be archaic from today's perspective, but it wasn't archaic at the time the text was written.

Providing modern lemmas to the old forms is definitely useful. But even here we may actually need two perspectives. One lemma (the main one, I'd suggest, i.e., the one in the LEMMA column) would be the modern one and it would really represent the lexeme including all its historical variants. But then for historical stages of the language, one may want to see what the canonical form (e.g., infinitive) would look like in that period.

**Comment by dan-zeman** [comment]
I have removed `Style=Arch` [from the Czech documentation](https://github.com/UniversalDependencies/docs/commit/fd952ca28300cfa3e0cc83607b42d90ab6308a19) and from the existing Czech treebanks.
