### ISSUE TITLE
Document Typo=Yes as allowed on multiword token (or its component words, but not both)

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#924]
UniversalDependencies/UD_Spanish-GSD#16 raised a case where something is a misspelling only in the context of a combination of words into an MWT, whereas the component words in isolation would be correctly spelled.

Currently a multiword token must not have any FEATS. The UD core group has decided that `Typo=Yes` should be allowed on an MWT, provided that it does not appear on any of the component words. (Allowing both could lead to confusion about the redundancy.)

This needs to be documented on at least:

- [Format page](https://universaldependencies.org/format.html)
- [Typos page](https://universaldependencies.org/u/overview/typos.html)

@dan-zeman would you mind doing this since you have an example?

**Comment by coltekin** [comment]
I realize this is already a finalized decision, but, could this also be evidence for `Typo=Yes`  not being a _morphological feature_, but should go into the `MISC` column?

**Comment by dan-zeman** [comment]
> I realize this is already a finalized decision, but, could this also be evidence for `Typo=Yes` not being a _morphological feature_, but should go into the `MISC` column?

I agree it is not a morphological feature in the narrow sense. But it is useful to have it together with the other features in FEATS because it signals that what you see in FORM is not the correct result of combining LEMMA and (the other) FEATS. So when collecting inflected forms of a lexeme from the corpus, I know that this one needs special treatment or should be ignored completely.

**Comment by amir-zeldes** [comment]
Just to add another standardization perspective, this is only an adjustment to also allow the annotation on MWTs, and does not affect any policy regarding regular tokens. Any changes at that level would affect a massive amount of treebanks and associated tools, creating a breaking change in the format for a variety of applications, so even if there are good theoretical reasons for an annotation to be in MISC vs. FEATS, changes like this should not be undertaken unless there is a very strong reason.

**Comment by nschneid** [comment]
Still needs guidelines documentation

**Comment by dan-zeman** [comment]
> Still needs guidelines documentation

Where exactly? (In addition to the two guidelines pages where I described it.)

**Comment by nschneid** [comment]
In the commit I just see validator changes.

- [Format page](https://universaldependencies.org/format.html)
- [Typos page](https://universaldependencies.org/u/overview/typos.html)
- [Changes page](https://universaldependencies.org/changes.html) (amendment)

**Comment by nschneid** [comment]
Oh I didn't realize "closed as completed" linked to a separate commit. 609ddf2 Odd that it doesn't preview the message for that commit.

**Comment by dan-zeman** [comment]
> In the commit I just see validator changes.

[The commit that closed the issue](https://github.com/UniversalDependencies/docs/commit/609ddf20d5afb080d8feb2595231231137073097) does not touch the validator (which is in a different repo anyway). Instead, it modifies the Format page and the Typos page.

**Comment by dan-zeman** [comment]
But you are right that the amendment is not described on the Changes page, which I did not realize.

**Comment by nschneid** [comment]
I can add that

**Comment by nschneid** [comment]
Before pushing the changes page I want to check the other changes, but they're not showing up on https://universaldependencies.org/u/overview/typos.html for some reason
