### ISSUE TITLE
New seg. docs and closed class property of tags

### ISSUE THREAD

**Issue by mehmetoguzderin** [UniversalDependencies/docs#946]
The new segmentation document found at https://github.com/UniversalDependencies/docs/blob/pages-source/workgroups/newdoc/word_segmentation.md makes essential clarifications, particularly for languages that either lack spelling rules about explicit breaks or have under-defined rules.

While the document states,

> If there is no suitable UPOS tag for the surface token, but we can split it into parts that have clear UPOS categories, split it

I would like to kindly ask about the potential of an update to address the closed-class property of a UPOS tag as a suitability differentiator.

Would it be possible to specifically mention that if splitting a word maintains the closed class property of a UPOS tag, then it is considered suitable for splitting? Guidelining such a distinction would help ultimately resolve issues related to certain particles or affixes in languages like Turkish, such as the "-s[ae]" conditional, resolving the topic of producing the open class SCONJ, and I believe it would generalize really well to not only Turkic but also languages with similar concerns. I also think that it is better to encourage multi-word tokens in such cases to preserve the original spelling.

**Comment by mehmetoguzderin** [comment]
And I think in the new system of guideline changes, this would be a "CLARIFICATION" by "resolution of an important ambiguity in the guidelines (that doesn't negate a previous policy)" definition. https://universaldependencies.org/changes.html

**Comment by nschneid** [comment]
I suspect this was a draft that has not (yet) been officially incorporated into the guidelines. @dan-zeman?

**Comment by mehmetoguzderin** [comment]
I hope the entirety or relevant excerpts can be part of the guideline as the value proposition is quite high, and this issue's clarification request will provide a consistent and universal key principle for this matter.

**Comment by coltekin** [comment]
I was not aware of the work-in-progress new documentation, but it does not seem to be a major change of current practices. A quick comment on Turkish/Turkic segmentation:

> Guidelining such a distinction would help ultimately resolve issues related to certain particles or affixes in languages like Turkish, such as the "-s[ae]" conditional, resolving the topic of producing the open class SCONJ, and I believe it would generalize really well to not only Turkic but also languages with similar concerns. I also think that it is better to encourage multi-word tokens in such cases to preserve the original spelling.

I would be against introducing an `SCONJ` out of _-sA_, or similar suffixes in Turkish (likely for other Turkic languages, too). We do not need an overt SCONJ to annotate subordination (here, `advcl`). In-line with your final sentence above, I think it is also a good idea to preserve the original spelling (unless there are good reasons not to), and *not* to segment _-sA_ (I know some treebanks do). If segmented, however, it makes sense to mark it as `AUX`, parallel to the free version _ise_. Then, we would not need to enumerate all the forms with possible verbal affixes.

I also think that the solution to this particular problem is not in the universal guidelines, but a consensus between Turkic treebanks to follow similar practices as much as possible.

**Comment by mehmetoguzderin** [comment]
@coltekin As long as tokenized, even AUX is a much better choice, but I'd like to note that "ise" is not a free form of "-s[ae]r?" conditional (also known as hypothetical/conditional marker) but rather a contraction of "er-" (fully conjugated copula) and "-s[ae]r?" as "erser" to "ise" spelling, where, if "-s[ae]r?" is split, then it should treat a split to "ise" occasion too.

For Japonic, a good precedent has already been set by marking -ば conditional, which is the historical conditional (little context for readers, "-s[ae]r?" is the historical conditional marker, even at the earliest attestations of Turkic) too akin to "-s[ae]r?" as https://kobun.weblio.jp/content/ば defines in 一, as SCONJ. Please see the following in PUDLUW (from https://github.com/UniversalDependencies/UD_Japanese-PUDLUW/blob/master/ja_pudluw-ud-test.conllu file):

"If a Turkish employee quits,"
「トルコ人労働者がやめれば、」
|トルコ人労働者|が|やめれ|ば|、|
|-|-|-|-|-|
|NOUN|ADP|VERB|SCONJ|PUNCT|

This matter has implications for more than Turkic languages, but it is true that it resolves something Turkic languages still did not resolve internally through principled segmentation (well, other languages of similar matter too, where "training performance" was subject so far, oftentimes skipping the closed class property).

**Comment by mehmetoguzderin** [comment]
Just to note the relevancy to the OP, I said even AUX is much better as long as tokenized because it creates a set that preserves the **closed-class property** of UPOS  (which is, by inquiry, the detail to be set more explicitly in the guidelines to resolve ambiguity).

**Comment by dan-zeman** [comment]
> I suspect this was a draft that has not (yet) been officially incorporated into the guidelines. @dan-zeman?

All pages in the newdoc folder were meant as clarification, not as negation of a previous policy (we did not allow amendments when we started with newdoc). So it has not been fully incorporated because many pages are missing, but the pieces that are already there should be valid. Also newdoc is not exactly new any more, as the work on it started in May 2018 (though the [word segmentation page](https://universaldependencies.org/workgroups/newdoc/word_segmentation.html) is younger, I wrote most of it in January 2021).

**Comment by mehmetoguzderin** [comment]
@dan-zeman Since this additional sentence would not change guidelines, can I open a PR to propose a sentence (or phrase in an existing sentence) and exemplification of this? Should it include an entry in changes since this page is accessible through links on the website?

Also, I think the Turkic tag makes the issue look Turkic-specific, but there are at least three language families with relevance to this issue, and especially one already has concrete examples to demonstrate. Could it be possible to label with POS and universal maybe?

**Comment by dan-zeman** [comment]
I added the Turkic label because I saw that the thread evolved into a discussion of Turkish examples but feel free to add other labels that are relevant for the issue.

I did not understand though what you meant by maintaining the closed-class property of an UPOS tag. The original guideline assumes that you cannot assign an UPOS tag to the surface token but you can assign tags to the proposed parts; if the whole token has no UPOS tag, then there is no property that could be maintained after the potential split is done.

**Comment by mehmetoguzderin** [comment]
@dan-zeman Thank you very much for your kind reply. Maybe in concrete terms (module the really explicit i.e. content), I mean to evolve the sentence into sth like:

> If there is no suitable UPOS tag for the surface token but we can split it into parts that have clear UPOS categories producing the correct class as an open (i.e., can grow as the language evolves) or closed (i.e., an enumerable number of forms that do not depend on the size of NOUN or VERB tags) category per the tag, split it.

And I have an appropriate example to elaborate in the description.

Could this be possible to include as open or closed are part of the table in UPOS page clearly?

**Comment by dan-zeman** [comment]
> If there is no suitable UPOS tag for the surface token but we can split it into parts that have clear UPOS categories **producing the correct class as an open (i.e., can grow as the language evolves) or closed (i.e., an enumerable number of forms that do not depend on the size of NOUN or VERB tags) category per the tag**, split it.

So what is the contribution of the highlighted addition? If the parts have clear UPOS categories, then these categories are either open or close. They cannot be anything else, can they? And If they can't, then there is no way how the added condition could not hold, which would mean that it is not needed and we can keep the simpler wording.

**Comment by coltekin** [comment]
I also have difficulties understanding the general issue at hand (I guess the problem is beyond what I understood earlier). Can you please give a concrete example that demonstrates the problem?

**Comment by mehmetoguzderin** [comment]
@dan-zeman Could it then be acceptable to elaborate in the example section of that "split it" recommendation? I think the problem stems exactly at the following "..., then these categories are either open or close" phrase, where treebanks produce open classes for UPOS that should be closed class- splitting would solve it.

**Comment by mehmetoguzderin** [comment]
The contribution is to make it more explicit and visible that UPOS tags have associated openness and closedness, and following this as a "split it" principle provides a gentle & general solution. LUW treebanks in Japanese do this truly well, as pointed out in the ば example.

**Comment by dan-zeman** [comment]
> where treebanks produce open classes for UPOS that should be closed class

I agree that annotators should choose the correct tag, which includes correctly distinguishing between open and closed classes, but that is not specific to splitting, they should do it correctly for all words.

BTW I am not sure that a Japanese example is enlightening with respect to this section of the documentation page. This section is about splitting orthographic words into syntactic ones, and the page also says that such mechanism should not be applied to Japanese because there are no orthographic words in Japanese.

**Comment by mehmetoguzderin** [comment]
@dan-zeman I totally agree, along with the following clarification about how Japanese relates, I'd like to say that this document is a beautiful reference and including such an example pointing out openness and closeness would be really golden. If I could see such an explicit spelling a few years ago, it'd help me get up to speed with this nuance much more quickly and I could be doing more meaningful splits in my contributions.

Japanese language clarification: Maybe there are no orthographic words but there is **bunsetsu**. Had it been the case where bunsetsu (which is much more similar to spelling in existing languages which produces the open classes where it should be closed), then SCONJ and alike would suddenly become open class. But Japanese annotation makes the correct choice to not do that.

But I believe that almost all other languages will want their original spelling re-constructible. For that, multi-word tokens provide the perfect balance if people have a visible reference which makes it even more explicit to think about the category: preserve the spelling in MWT top, but at bottom, do the correct UPOS assignment and make sure it never violates open-close principle. Then official POS-ing of course goes as XPOS but that's already quite known.

**Comment by dan-zeman** [comment]
My point was that even bunsetsu has no visible boundaries in spelling. I am not saying that there are no word segmentation issues in Japanese, it's quite the opposite; but since these issues formally don't fall under MWT, I would prefer to illustrate MWT on examples from other languages.

> Had it been the case where bunsetsu (...), then SCONJ and alike would suddenly become open class.

If it is `SCONJ`, it is not open class. If it is tagged as, say, `NOUN`, then it is open class and maybe it should have been `SCONJ` instead but that is a mistake that could be made both with an independent single-word token and with something that has been cut off a multi-word token.

If the putative conjunction is part of a larger word and is not cut off as an independent word (maybe this is what you have in mind?) then it is neither open nor closed class. It does not exist as a word, so it has no UPOS tag, no class. I can imagine that in some language a conditional morpheme is treated as an inflection of a verb. Then it is part of something that gets the `VERB` tag, hence open class. But it's not that the conditional morpheme itself is open class. Only the whole word is, and rightly so.

> But I believe that almost all other languages will want their original spelling re-constructible.

Definitely. That's not for a language to decide, that's a requirement in UD in general.

**Comment by mehmetoguzderin** [comment]
@dan-zeman Right, I didn't mean to show MWT in Japanese but just spell how the segmentation which puts that particle into a syntactic word is chosen instead of coarser with regards to the closedness property. I think multi-word token considerations are really great in their verbosity in this document.

And I'd like to point out that I understood the intention in previous comment, but I apologize if I failed at representing the original while exemplifying what I had in mind. As I said, given the lack of potential for making the split it sentence a bit more verbose, I believe including just one more example in the explanation would help a lot for the wider audience. (Like, how this choice to make that morpheme a syntactic word produces a true SCONJ class, and otherwise, it would either be misrepresentation of open-close or no SCONJ at all. Please understand that I don't want to name which treebank I'm pointing with this specific morpheme to avoid pointing sharply, but it is not a Turkic treebank. I believe the proposed way to exemplify picks a correct way to segment & annotate without going into a hypothetical annotation in a language that does not have working example of this)
