### ISSUE TITLE
UDEasy on Mac, textboxes don't expand 

### ISSUE THREAD

**Issue by SterreLeufkens** [UniversalDependencies/docs#949]
I use the UD Easy tool to perform queries. I use it on my Macbook (M2 2022), Ventura 13.2.1, newest version of UD Easy. The textboxes in which I fill in node names, features, etc., do not expand, so I can only see half of the first letter I type (see screenshot). The queries work so it's not really a problem, but still, would be great if this could be changed. Or am I doing something wrong? 

<img width="601" alt="Scherm­afbeelding 2023-05-31 om 13 30 13" src="https://github.com/UniversalDependencies/docs/assets/135124428/d1dd98b1-c198-4df4-b041-1fe06131e829">

**Comment by nschneid** [comment]
Thanks for the question. However, this repository is for the UD guidelines. I think the place to post a question about UD Easy would be https://github.com/unipv-larl/udeasy

**Comment by SterreLeufkens** [comment]
Ah of course, you're right, thanks! I'll move it there.
