### ISSUE TITLE
Enhanced dependencies guidelines- doubts 

### ISSUE THREAD

**Issue by MagaliDuran** [UniversalDependencies/docs#951]
In enhanced dependencies guidelines, it is defined that: "If the relative clause has a nominal predicate, the relative pronoun may occupy the head position within the clause. In such cases no relation should be added from its parent to its co-referential element (because they are the same node). We should only add a nsubj relation from the antecedent to the nsubj of the relative clause (and remove the corresponding nsubj relation between the relative pronoun and the subject). The acl:relcl should remain the same as in basic dependencies."

Example  43 illustrates this case, but I think there could be a mistake, as the nsubj of the relative clause is added to the antecedent, but the cop and the advmod deprel remain added to the relative pronoun. Shouldn't  both, cop and advmod, be added to the antecedent as well? Shouldn't the guidelines include any relation and not only nsubj?

**Comment by dan-zeman** [comment]
The relevant section of the guidelines is [here](https://universaldependencies.org/u/overview/enhanced-syntax.html#relative-clauses).

**Comment by nschneid** [comment]
> In such cases no relation should be added from its parent to its co-referential element (because they are the same node).

It took me awhile to understand this sentence. But I think it is just saying that there is no enhanced dependency with the antecedent (the relativized noun) headed by something in the relative clause.

@MagaliDuran I see your point that if the antecedent is functioning as the predicate of the relative clause, and in the enhanced graph has a subject in the relative clause, then shouldn't it also head the clause-level modifiers within the relative clause?

@dan-zeman Is this an error, or is the intention that predicate-relatives have the relativizer as head for clause modifiers even in the enhanced graph?

**Comment by dan-zeman** [comment]
I don't know what the intention is. If I understand it correctly, the original proposal by @sebschu and @manning (2016) did not include an example with copula (but I did not check now). Later people found it in data and realized that they had to do something with it, so the guidelines were extended.

More generally I think the intentions behind the enhanced representation were to make the predicate-argument structure more explicit. From that perspective the `nsubj` relation seems more important than the other relations. I can imagine that the guidelines would say that other relations are redirected as well. But one would still have to say which ones, because the enhancements in enhanced UD typically do not apply to "less important" basic relations: for example, no transformations are applied to punctuation, perhaps with the exception of inserted empty nodes in gapping constructions, where punctuation would be reattached to the conjunct represented by the empty node.

**Comment by nschneid** [comment]
We recently worked on relative clause guidelines for English, which [mentions predicate relatives](https://universaldependencies.org/en/dep/acl-relcl.html#predicate-ellipsis-in-the-relative-clause) but only discusses basic dependencies.

In EWT, I have been treating this as an edge case and leaving the enhanced dependencies the same as the basic ones, without adding a `ref` edge: https://universal.grew.fr/?custom=6492bf3cb2cf9

I'm willing to consider a "deeper" solution to predicate relatives, but note that some of these are `advcl:relcl`, with the relative clause modifying an entire clause, so it would be muddying the waters to give a matrix clause predicate additional enhanced dependents from the relative clause—a subject and potentially other things like `cop`/`aux`/`advmod`.

> More generally I think the intentions behind the enhanced representation were to make the predicate-argument structure more explicit. From that perspective the `nsubj` relation seems more important than the other relations. I can imagine that the guidelines would say that other relations are redirected as well. But one would still have to say which ones, because the enhancements in enhanced UD typically do not apply to "less important" basic relations

If there is a `ref` edge to the antecedent, I'd expect all "normal" dependents of the relativizer to move to the antecedent in the enhanced representation. (We could make an exception for punct.) This is important for prepositional relatives:

- the book in which I read it
   * acl:relcl(book, read)
   * basic only: obl(read, which), case(which, in)
   * enhanced only: ref(book, which), obl:in(read, book), case(book, in)

**Comment by dan-zeman** [comment]
> If there is a `ref` edge to the antecedent, I'd expect all "normal" dependents of the relativizer to move to the antecedent in the enhanced representation. (We could make an exception for punct.) This is important for prepositional relatives:
> 
> * the book in which I read it
>   
>   * acl:relcl(book, read)
>   * basic only: obl(read, which), case(which, in)
>   * enhanced only: ref(book, which), obl:in(read, book), case(book, in)

I believe this is exactly the thing that should **not** be done in enhanced UD. The book still has its role in the matrix clause and, using your own words, it would be muddying the waters to pretend it has a case marker. BTW, if the case marker were a bound morpheme on the relative pronoun, you also would not move it to the modified noun.

**Comment by nschneid** [comment]
I see why that would be awkward for bound morphemes. But it is also awkward to have case subtypes on a relation where the dependent is different from the one which has the `case` dependent. I.e., obl:in(read, book) where the "in" is coming from case(which, in) seems like a bug magnet.

I'd almost rather drop the case/mark dependencies from the enhanced graph entirely, having moved the information to subtypes.

**Comment by nschneid** [comment]
We have to also consider preposition stranding with reduced relatives:

the book I read it in

The basic relation is obl(read, in). For EUD the options are
- case(book, in), obl:in(read, book)
- obl(read, in), obl:in(read, book) - this gives the impression of two oblique dependents of "read" when it's really just one

**Comment by MagaliDuran** [comment]
> > If there is a `ref` edge to the antecedent, I'd expect all "normal" dependents of the relativizer to move to the antecedent in the enhanced representation. (We could make an exception for punct.) This is important for prepositional relatives:
> > 
> > * the book in which I read it
> >   
> >   * acl:relcl(book, read)
> >   * basic only: obl(read, which), case(which, in)
> >   * enhanced only: ref(book, which), obl:in(read, book), case(book, in)
> 
> I believe this is exactly the thing that should **not** be done in enhanced UD. The book still has its role in the matrix clause and, using your own words, it would be muddying the waters to pretend it has a case marker. BTW, if the case marker were a bound morpheme on the relative pronoun, you also would not move it to the modified noun.

The example 43 refers only to nominal predicates in which the relative pronoun is the predicative, therefore, not prepositioned. The  nsubj arc crossing the cop and advmod arcs in the basic dependencies will produce a non projective graph, do you agree?

**Comment by MagaliDuran** [comment]
> We recently worked on relative clause guidelines for English, which [mentions predicate relatives](https://universaldependencies.org/en/dep/acl-relcl.html#predicate-ellipsis-in-the-relative-clause) but only discusses basic dependencies.
> 
> In EWT, I have been treating this as an edge case and leaving the enhanced dependencies the same as the basic ones, without adding a `ref` edge: https://universal.grew.fr/?custom=6492bf3cb2cf9

Nathan, in this case I would choose "ready" as the dependent of the acl:relcl  and "among whom" I would annotate as an obl of "ready".

**Comment by dan-zeman** [comment]
> The example 43 refers only to nominal predicates in which the relative pronoun is the predicative, therefore, not prepositioned. The nsubj arc crossing the cop and advmod arcs in the basic dependencies will produce a non projective graph, do you agree?

I don't know whether I agree that this would count as non-projective because I don't know whether we have a definition of non-projectivity for directed graphs that are not trees. If your question is rather whether I agree that we allow non-projectivity (assuming it can be redefined for graphs) as a result of enhanced annotation, then in general, I guess, yes, non-projectivity is not forbidden in UD. But I don't know what would be the best solution in this example (apart from the fact that the guideline is there and we should not change it lightly because people have been following the guideline and might get angry that they have to re-annotate stuff). If we were following the guidelines that hold for other types of relative clauses, then not even the subject relation would be enhanced. The guidelines (other than for the copular case) do not say that you should do anything with the dependents of the relative pronoun. One other option would be to temporarily pretend that the copular verb is the head and the nominal predicate is something like its core argument. That would mean that the modified noun is reattached as the core argument of the copula, and the relative pronoun is standardly attached as the `ref` dependent of the modified noun. Then we again transform the copula analysis to the UD style, and, voila, copula is now indeed attached to the modified noun; so is the subject of the relative clause, and perhaps also the adverbial _still_.

**Comment by MagaliDuran** [comment]
I am sorry! I finally understood the point. In the basic dependencies the nsubj is deleted. Only in enhanced dependencies nsubj is annotated as dependent of the antecedent.  It all makes sense now.

**Comment by nschneid** [comment]
> > We recently worked on relative clause guidelines for English, which [mentions predicate relatives](https://universaldependencies.org/en/dep/acl-relcl.html#predicate-ellipsis-in-the-relative-clause) but only discusses basic dependencies.
> > In EWT, I have been treating this as an edge case and leaving the enhanced dependencies the same as the basic ones, without adding a `ref` edge: https://universal.grew.fr/?custom=6492bf3cb2cf9
> 
> Nathan, in this case I would choose "ready" as the dependent of the acl:relcl and "among whom" I would annotate as an obl of "ready".

Yes good point, the first example at that link looks like an annotation error. The other 7 examples should be valid as predicate relatives.

**Comment by MagaliDuran** [comment]
> > The example 43 refers only to nominal predicates in which the relative pronoun is the predicative, therefore, not prepositioned. The nsubj arc crossing the cop and advmod arcs in the basic dependencies will produce a non projective graph, do you agree?
> 
> I don't know whether I agree that this would count as non-projective because I don't know whether we have a definition of non-projectivity for directed graphs that are not trees. If your question is rather whether I agree that we allow non-projectivity (assuming it can be redefined for graphs) as a result of enhanced annotation, then in general, I guess, yes, non-projectivity is not forbidden in UD. But I don't know what would be the best solution in this example (apart from the fact that the guideline is there and we should not change it lightly because people have been following the guideline and might get angry that they have to re-annotate stuff). If we were following the guidelines that hold for other types of relative clauses, then not even the subject relation would be enhanced. The guidelines (other than for the copular case) do not say that you should do anything with the dependents of the relative pronoun. One other option would be to temporarily pretend that the copular verb is the head and the nominal predicate is something like its core argument. That would mean that the modified noun is reattached as the core argument of the copula, and the relative pronoun is standardly attached as the `ref` dependent of the modified noun. Then we again transform the copula analysis to the UD style, and, voila, copula is now indeed attached to the modified noun; so is the subject of the relative clause, and perhaps also the adverbial _still_.

Thank you, Dan! I've learned a lot with your answer. I haven't understood the guidelines for example 43, but now I realized that the nsubj is only annotated in the enhanced dependencies and not in basic dependencies. This solves my doubt. Therefore, whenever the relative pronoun matches the head of the acl:relcl, the nsubj of acl:relcl should be deleted in the basic dependencies. In enhanced dependencies we add the nsubj directly to the antecedent, and insert a ref relation between the antecedent and the relative pronoun. Everything else remains the same.

**Comment by nschneid** [comment]
Wait I take it back regarding the EWT sentence. The original and some rephrasing:

- the conferees, among whom have been several Indian "scholars" and "analysts" ready to say and endorse anything for the sake of a free trip to New York or Vienna
- among the conferees were several scholars and analysts ready to say... - I think this is an inverted sentence
- several scholars and analysts ready to say... were among the conferees - "conferees" is the embedded predicate. So "whom" would be the relative clause predicate in the original.

**Comment by MagaliDuran** [comment]
> Wait I take it back regarding the EWT sentence. The original and some rephrasing:
> 
> * the conferees, among whom have been several Indian "scholars" and "analysts" ready to say and endorse anything for the sake of a free trip to New York or Vienna
> * among the conferees were several scholars and analysts ready to say... - I think this is an inverted sentence
> * several scholars and analysts ready to say... were among the conferees - "conferees" is the embedded predicate. So "whom" would be the relative clause predicate in the original.

Very good explanation! I agree with it!

**Comment by MagaliDuran** [comment]
Hi guys, me again

New doubts have arisen when I followed the enhanced dependencies guidelines to annotate the example illustrated in Figures 43 and 44. 

"He became chairman, which he still is."

The guidelines say:
1) no relation should be added from acl:relcl parent ["chairman"] to its co-referential element ["which"] (because they are the same node);
2) add a nsubj relation from the antecedent ["chairman"] to the nsubj of the relative clause ["he"] "
3) remove the corresponding nsubj relation between the relative pronoun and the subject [that is, the nsubj from "which"to "he"].

basic  (in black in Figure 44 of the guidelines)
became->he (nsubj)
became->chairman (xcomp)
chairman->which (acl:relcl) -> this goes against 1) ?
which->still (advmod)
which->is (cop)

enhanced (in blue in Figure 44 of the guidelines)
chairman-> which (ref)  this goes against 1) ?
chairman->he (token 6) (nsubj)

The second "he" (token 6) is outside the analysis of the basic dependencies and only participates in the enhanced ones. Is this correct?

**Comment by nschneid** [comment]
> 1. no relation should be added from acl:relcl parent ["chairman"] to its co-referential element ["which"] (because they are the same node);

I think this means, given that a basic `acl:relcl` edge from "chairman" to "which" exists (with "which" as the predicate of the relative clause), no *enhanced* relation should be added from inside the relative clause to "chairman" (in contrast to normal relative clauses). (I agree that this is confusingly worded, as noted in my first post above.)

> The second "he" (token 6) is outside the analysis of the basic dependencies and only participates in the enhanced ones. Is this correct?

No it should be the nsubj of "which" in basic dependencies (green edge in example 43).

**Comment by dan-zeman** [comment]
> > 1. no relation should be added from acl:relcl parent ["chairman"] to its co-referential element ["which"] (because they are the same node);
> 
> I think this means, given that a basic `acl:relcl` edge from "chairman" to "which" exists (with "which" as the predicate of the relative clause), no _enhanced_ relation should be added from inside the relative clause to "chairman" (in contrast to normal relative clauses). (I agree that this is confusingly worded, as noted in my first post above.)

In fact the above quote differs from [how it is worded in the guidelines](https://universaldependencies.org/u/overview/enhanced-syntax.html#relative-clauses). The guidelines say: "... the relative pronoun may occupy the head position within the clause. In such cases no relation should be added from its parent to its co-referential element (because they are the same node)." So, the co-referential element is the noun modified by the relative clause. The parent of the relative pronoun is also the modified noun, and their relation is `acl:relcl` (this is unlike normal relative clauses where the parent of the relative pronoun is a node inside the relative clause). I don't know what the emphasis on _enhanced_ means, @nschneid – this whole page is about moving from basic to enhanced representation, so if any relation is added, it will always be enhanced, right?

**Comment by nschneid** [comment]
Yeah I see that "added" means "added in the enhanced layer" but "parent" refers to the basic parent. How about changing the sentence to:

"Unlike most relative clauses, in cases where the relativizer serves as predicate, its antecedent will not have an additional enhanced edge attaching it to a parent in the relative clause. Instead, we..."

**Comment by MagaliDuran** [comment]
And how do you interpret the instructions that say " (and remove the corresponding nsubj relation between the relative pronoun and the subject)"? In:

"If the relative clause has a nominal predicate, the relative pronoun may occupy the head position within the clause. In such cases no relation should be added from its parent to its co-referential element (because they are the same node). We should only add a nsubj relation from the antecedent to the nsubj of the relative clause (and remove the corresponding nsubj relation between the relative pronoun and the subject). The acl:relcl should remain the same as in basic dependencies."

In fact, Figure 44  does not show the basic dependency between "which" and "he", which leads one to believe that the removal that the guidelines mention was done in the basic dependencies (arcs in black). In such Figure, "he" is only added to the enhanced dependencies (arcs in blue).

**Comment by dan-zeman** [comment]
> Yeah I see that "added" means "added in the enhanced layer" but "parent" refers to the basic parent. How about changing the sentence to:
> 
> "Unlike most relative clauses, in cases where the relativizer serves as predicate, its antecedent will not have an additional enhanced edge attaching it to a parent in the relative clause. Instead, we..."

Fixed in https://github.com/UniversalDependencies/docs/commit/8d4474bec4e6122caef70ccc0d1bacf818b50d64

**Comment by nschneid** [comment]
@MagaliDuran On the page, basic trees are shown on the left and enhanced graphs on the right. The black edges are shared between the two. Example 43 shows the basic dependency `which --nsubj--> he` in green. Example 44 does not have that and instead has the enhanced edge `chairman --nsubj--> he`. Does that make sense?

**Comment by dan-zeman** [comment]
> And how do you interpret the instructions that say " (and remove the corresponding nsubj relation between the relative pronoun and the subject)"? In:
> 
> "If the relative clause has a nominal predicate, the relative pronoun may occupy the head position within the clause. In such cases no relation should be added from its parent to its co-referential element (because they are the same node). We should only add a nsubj relation from the antecedent to the nsubj of the relative clause (and remove the corresponding nsubj relation between the relative pronoun and the subject). The acl:relcl should remain the same as in basic dependencies."
> 
> In fact, Figure 44 does not show the basic dependency between "which" and "he", which leads one to believe that the removal that the guidelines mention was done in the basic dependencies (arcs in black). In such Figure, "he" is only added to the enhanced dependencies (arcs in blue).

Example 43 (basic tree) has a green relation `nsubj(which, he)`, which is removed in Example 44 (enhanced graph).

Conversely, Example 44 (enhanced graph) has a blue relation `nsubj(chairman, he)`, which is added because it was not present in Example 43 (basic tree).

**Comment by nschneid** [comment]
(changed green to red for better contrast)

**Comment by MagaliDuran** [comment]
> @MagaliDuran On the page, basic trees are shown on the left and enhanced graphs on the right. The black edges are shared between the two. Example 43 shows the basic dependency `which --nsubj--> he` in green. Example 44 does not have that and instead has the enhanced edge `chairman --nsubj--> he`. Does that make sense?

Yes, sure. I thought that the black edges were the basic dependencies and not the shared relations. We are preparing guidelines for annotating enhanced dependencies in Portuguese and these clarifications were essential. Thank you @nschneid and @dan-zeman.

**Comment by MagaliDuran** [comment]
> (changed green to red for better contrast)

Thank you! This has greatly improved the visualization. I only realized there was green in the previous version of the basic dependencies when Dan mentioned it.

**Comment by dan-zeman** [comment]
> ([changed green to red](https://github.com/UniversalDependencies/docs/commit/0273f111211bbd24372cb0743b7c6953736288d7) for better contrast)

Just for the record, I was proposing to use red for this purpose when we were starting this doc page but I got outvoted by the core group. The reasoning was that we should not use red highlighting for anything that is not an error, right? (@jnivre, @fginter)
