### ISSUE TITLE
Tags use

### ISSUE THREAD

**Issue by Andres-Chandia** [UniversalDependencies/docs#952]
Hi there,
I'm starting just now in this topic, I would like to give standard morphological annotation to Mapudüngun morphological analyses.
Sorry if my question is too naive, but I can not figure out the proper way to tag, for instance, a  transitive/intransitive verb, until now I'm using -IV and -TV...
I use a nomenclature like this: -IV.elu_give+PASS.nge23+CF.ke14+IPD.fu8+IND.y4+1.Ø3+PL.iñ2
As Mapudüngun is an agglutinative language, in the glosses I represent...
in the case of the root: -PoS.root_meaning,
in the case of the suffixes: +SUFFIXTAG.formSLOT, being the slot where the suffix is located identified by the number at the end of the suffix tag.
Thanks in advance...

**Comment by dan-zeman** [comment]
There is a language-specific feature [Subcat](https://universaldependencies.org/u/feat/Subcat.html) that [some languages use](https://universaldependencies.org/ext-feat-index.html#subcat) to express transitivity: a transitive verb gets `Subcat=Trans`, an intransitive verb gets `Subcat=Intr`.

You can represent the morphemic segmentation and corresponding glosses in the MISC column in the optional attributes [MSeg](https://universaldependencies.org/misc.html#mseg) and [MGloss](https://universaldependencies.org/misc.html#mgloss).

The main annotation in the UPOS and FEATS columns refers to the whole word and not to individual morphemes. Hence for your example you will probably have `VERB` in UPOS (if I correctly understand that the whole thing is a verb) and in features `Mood=Ind|Number=Plur|Person=1|Subcat=Intr|Voice=Pass` (and maybe something to represent your CF and IPD, I have no idea what those glosses mean).

**Comment by Andres-Chandia** [comment]
Ok, so it is juts to represent in a corpus... There is some way to do representation for analysis glosses, in the way I put it in the previous example? Something that does not make the glosses too intricate?

**Comment by dan-zeman** [comment]
The MSeg and MGloss attributes in the MISC column are for glosses. But UD does not attempt to standardize the tags used in the glosses; you would have to adopt some other standard for that. [UniMorph](https://unimorph.github.io/schema/) could be useful.

**Comment by Andres-Chandia** [comment]
Thanks a lot Dan, I will dig into that...
