### ISSUE TITLE
Clause chaining in UD

### ISSUE THREAD

**Issue by sylvainloiseau** [UniversalDependencies/docs#956]
What could be a appropriate way for encoding clause chaining in UD?

Clause chaining is a construction for linking a serie of clauses; in all clauses but the last one the verb is not fully inflected and inherit some features from the verb of the final clause, which is fully inflected.  Clause chaining is common in particular in Papuan languages.  We are starting a treebank for the Tuwari language, a Papuan language where clause chaining is pervasive.

Languages using clause chaining often (but not always) have a switch reference system, i.e. a marker at the end of the medial clauses that express whether the subject of the following clause is coreferential with the subject of the current one or not.

The first of the two following examples illustrates clause chaining in a language having a switch-reference system, the second example illustrates a language without switch reference.

In (1) (Tauya, MacDonald Lorna (1990) A grammar of Tauya, Mouton/Berlin), the two medial verbs inherit from the final verb the specification for mood (here, indicative).  The subject stay the same, thus each clause has the "-pa" suffix for 'SS' ('same subject'), instead of the "-te" for 'different subject'.

(1) Tauya
ya mei  fofe-pa  momune-pa  ni-e-’a
1S hear come-SS sit-SS eat-1/2S-IND
‘I came hear, sat down and ate.’

In Tuwari, the medial verb are marked with "-ne", the final one by "-io". In (2), the medial verb "afeteli" is not inflected but for the medial marker; the final verb is inflected for mood ('irrealis'), illocutionary force ('affirmative'), agree with the gender and number of the subject,  and have a marker of final verb.

(2) Tuwari
a   opsono-ma   afeteli-ne nepia-ma      I-nai-m-wi-io
1SG village-dir leave-med  far_away-dir  go-IRR-AFF-SG.M-FIN
'I will leave the village and go far away'

Clause chain has been analysed either as subordination, coordination, or as a third clause linking type, cosubordination (Olson 1981, Foley and Van Valin 1984).  Unlike subordinates, medial clauses are not embedded (they are not complement or adjunct of the final clause). However, alike subordinates (and unlike coordinates) clauses, medial clauses have a dependency relationship for a particular inflectional category with the final clause.

In Foley 2010 (Clause linkage and nexus in Papuan languages, In Brill I. ed (2010) Clause linking and clause hierarchy: Syntax and pragmatics, Benjamins/Amsterdam, 27-50, clause chain are characterized as an instance of coordination " that differs from normal clausal coordination in the type of constituents coordinated ».

Depending on languages, clause chains can interweave in various ways with other clause linking strategies.

Regarding UD, one possibility could be to use "conj", with a specification "conj:chain » (https://universaldependencies.org/u/dep/conj.html). 

However with "conj" "The head of the relation is the first conjunct", whereas in clause chain we would like the head of the relation to be the last verb.

Another solution suggested for Coptic (https://universaldependencies.org/cop/specific-syntax.html) is advcl and we could introduce advcl:chain, again with the last verb as the head; however the medial clause is not an oblique constituent of the matrix clause.

Do you have a better solution in mind?
Thank you for any advice.
Sylvain Loiseau

**Comment by dan-zeman** [comment]
I think I would use `advcl`. The construction resembles converb clauses in some Asian languages _(having summoned his ministers, the king said...)_ They, too, would often be translated to English using coordination _(the king summoned his ministers and said)._ Such constructions are also analyzed as `advcl` dependents of the last verb. And in the morphological features, the last verb is `VerbForm=Fin`, while the other verbs have a non-finite verb form, typically `VerbForm=Conv`.

**Comment by sylvainloiseau** [comment]
Thanks a lot for the comment. converb construction may be more clearly an adjunct (adverbial) subordination strategy. Many Papuan languages have a specific distinct subordination strategy that is more adverbial-like. For instance in Tuwari, the -mo subordinator:

teto		=se		otei-na-no		=mo		m-we			m-olu-ne	i-io
sibling	=F.SG	fight-?-PURP		=SUB		TOP-3SG.M		?-run-MED 	do-PRED
‘His sister was willing to fight him so that he ran away.’

Such -mo subordinates can be translated by a large array of constructions in English (while, since, when...); its core meaning is a presupposed information ( ‘Given that his sister was willing to fight him, he ran away.’) (I follow for instance Haiman 1978 "Conditionals are topics!").

By contrast, in clause chain the clauses are on the same topical and informative ground, and it can be problematic to consider the medial clauses as adjunct of the matrix clause on semantic ground. The typical semantic of the clause chain will be to express the consecutive steps of an action through a decomposition in simple events. In a clause chain, the nth medial clause will be linked (structurally, through argument management, as well as semantically), with the n+1th medial clause rather than directly to the final clause.

**Comment by Stormur** [comment]
> Depending on languages, clause chains can interweave in various ways with other clause linking strategies.
> 
> Regarding UD, one possibility could be to use "conj", with a specification "conj:chain » (https://universaldependencies.org/u/dep/conj.html).

From your description and the examples, I would also veer towards a treatment as `conj`. The fact that in some members of the co-ordination we see reduced markers and/or systematic ellipsis seems in line with general tendencies. 


> However with "conj" "The head of the relation is the first conjunct", whereas in clause chain we would like the head of the relation to be the last verb.

I udnerstand the problem, as in Latin we also often have this "problem", or better "ugliness" of annotation. I would say that some kind of flexibility in the directionality of `conj` could be implemented at some point. For the time being, probably we have to make do with it and I fear that choosing an inappropriate relation just to "get the structure straight" might lead to worse problems.

**Comment by dan-zeman** [comment]
> ... it can be problematic to consider the medial clauses as adjunct of the matrix clause

That's not a problem in UD, which does not recognize "adjunct" as a term.

> In a clause chain, the nth medial clause will be linked (structurally, through argument management, as well as semantically), with the n+1th medial clause rather than directly to the final clause.

Then it is possible to consider attaching it as `advcl` to the next clause, instead of the last one.

The UD guidelines do not have specialized relations for every construction in every language. Sometimes (often) it is necessary to look for the closest match, as opposed to perfect match. Given the information above, I find subordination better than coordination, and `advcl` better than the other subordinating relations.

**Comment by amir-zeldes** [comment]
> Then it is possible to consider attaching it as advcl to the next clause, instead of the last one.

We have a similar situation in Coptic and we use a chain of `advcl` as well.

**Comment by sylvainloiseau** [comment]
Thanks @Stormur @dan-zeman  and @amir-zeldes for the comments.

I agree with @Stormur that selecting the right relation is the most important.

If I understand correctly, both options are possible in the UD annotation scheme without any very decisive criteria to decide; it boils down to the question of whether one prefer to consider the medial clauses as coordinated or subordinated to their next clause.

In this situation, I'm tempted to follow the consensus about the syntactic analysis of clause chain, which today tends towards an analysis in coordination.

I'm also planning to use VerbForm=Med (Medial) on the verbs of the medial clauses.

**Comment by dan-zeman** [comment]
> In this situation, I'm tempted to follow the consensus about the syntactic analysis of clause chain, which today tends towards an analysis in coordination.

Indeed possible. By using the coordination analysis you are saying that none of the clauses is the head, hence you are fine with left-to-right relations as the prescribed technical solution.

**Comment by sylvainloiseau** [comment]
Yes, this is what is argued, for example, in the above-mentioned article by Foley; as for the orientation of the relation it is arbitrary and did not mean, in that particular case, headness, if I understand correctly. I must say that the analysis by Foley is couched in a different grammatical framework, and that the same analysis would most probably not have been done in a dependency framework, without the same apparatus of functional categories and projections. Still, it seems to me to be the current consensus not to see this construction as a structural subordination, by contrast with other constructions in those languages.

**Comment by sylvainkahane** [comment]
> By using the coordination analysis you are saying that none of the clauses is the head, hence you are fine with left-to-right relations as the prescribed technical solution.
> 
But coordination is now generally analyzed as a headed construction, where one of the two conjuncts adjoins on the other. The adjoined conjunct is the one that forms a phrase with the coordinating conjunction. 
Moreover in head- final language, the coordinating conjunction attaches to the first conjunct and the second conjunct is therefore the head. 
It is why we are many to ask the possibility of conj relations from right to left. Clause chaining in Tuwari is a new example.
