### ISSUE TITLE
Updates to Ancient Greek FEATS Options

### ISSUE THREAD

**Issue by mr-martian** [UniversalDependencies/docs#957]
So in the existing Ancient Greek treebanks, the following features are permitted:

Aspect=Imp|Perf, Case=Acc|Dat|Gen|Loc|Nom|Voc, Definite=Def, Degree=Abs|Cmp|Pos|Sup, Gender=Fem|Masc|Neut, Mood=Imp|Ind|Opt|Sub, Number=Dual|Plur|Sing, Person=1|2|3, Polarity=Neg, Poss=Yes, PronType=Dem|Int|Prs|Rcp|Rel, Tense=Fut|Past|Pqp|Pres, VerbForm=Fin|Gdv|Inf|Part, Voice=Act|Mid|Pass

In PTNK I currently have the following on definite articles and numbers:

PronType=Art
NumType=Card
NumType=Ord

Would the other treebank maintainers be OK with adding these features?

Are there any other features we should add?

Also, we should document how Tense and Aspect map onto the traditional paradigm names.

**Comment by dan-zeman** [comment]
@daghaug @gcelano

**Comment by Stormur** [comment]
Can I suggest adding [`InflClass`](https://universaldependencies.org/la/feat/InflClass.html)? It should be pretty straightforward for Ancient Greek. By the way, comments and suggestions are welcome.

**Comment by mr-martian** [comment]
I also note that forms of `τις` don't have `PronType` currently, and the validator is objecting to my use of `PronType=Ind`.

**Comment by dan-zeman** [comment]
Apparently the other Ancient Greek treebanks do not use `PronType=Ind` for any word currently. It can be registered with the validator but ideally it should be then added to those words in the other two treebanks, too.

**Comment by daghaug** [comment]
I'd be happy to add PronType=Ind in PROIEL. It would be only for τις right, or am I forgetting something?


Dag

________________________________

**Comment by mr-martian** [comment]
Yes, in PTNK `PronType=Ind` is only on the 2 instances of `τις`.

**Comment by gcelano** [comment]
In the AGDT original files, articles have their own POS label ("l"), so this could be used for PronType=Art. Numerals have their own POS label as well ("m"), but there is no distinction between cardinals or ordinals. There are annotation inconsistencies, though, because numerals have sometimes been annotated as adjectives. There is also an issue with the distinction of articles vs pronouns in cases such as τιμῆς τῆς Πριάμου, where I take τῆς as a pronoun, but some annotated it as an article.

**Comment by mr-martian** [comment]
In PTNK, τῆς would always be tagged as `DET`. What are the conditions in the other treebanks for labeling it a pronoun?

**Comment by gcelano** [comment]
Well, an article is expected to agree with its governor in number, gender, and case (τιμῆς τῆς Πριάμου means honor, that of Priam)

**Comment by mr-martian** [comment]
I wonder how well that corresponds to the set of cases in PTNK where something tagged `DET` has a relation that is not `det`.

**Comment by mr-martian** [comment]
My code for exporting PTNK to the UD repo strips the features under discussion, but I don't think we've actually reached a consensus on what to do about them.

**Comment by dan-zeman** [comment]
OK, but then it needs a new milestone. v2.13 is over.

**Comment by dan-zeman** [comment]
> My code for exporting PTNK to the UD repo strips the features under discussion, but I don't think we've actually reached a consensus on what to do about them.

@mr-martian There has not been any further discussion for a year now. So what are you going to do with the features? Can this issue be closed?

**Comment by mr-martian** [comment]
I have now enabled the features and stopped stripping them from PTNK.
