### ISSUE TITLE
Determiners on Clauses

### ISSUE THREAD

**Issue by mr-martian** [UniversalDependencies/docs#960]
In Ancient Greek, an infinitive verb can be preceded by a determiner as one way of forming an `advcl`. In the existing treebanks, this is tagged as `det` and so I have done the same.

However, when the verb is a copula, such as in the following fragment, this makes it pretty much impossible to distinguish between a determiner marking a subordinate clause and an actual determiner on the predicate noun and I was wondering what should be done about this, if anything.

```conllu
17	διὰ	διά	ADP	_	_	11	obl	_	Gloss=+G=through,by;-+A=because-of
18	τὸ	ὁ	DET	_	Case=Acc,Nom|Definite=Def|Gender=Neut|Number=Sing|PronType=Art	20	det	_	Gloss=the
19	σὲ	σέ	PRON	_	Case=Acc|Number=Sing|Person=2|PronType=Prs	20	nsubj	_	Gloss=you
20	γυναῖκα	γυνή	NOUN	_	Case=Acc|Gender=Fem|Number=Sing	17	acl:relcl	_	Gloss=woman,wife
21	αὐτοῦ	αὐτός	PRON	_	Case=Gen|Gender=Masc,Neut|Number=Sing|PronType=Prs	20	nmod:poss	_	Gloss=he,she,it,-self,same
22	εἶναι	εἰμί	AUX	_	Tense=Pres|VerbForm=Inf|Voice=Act	20	cop	_	Gloss=to-be|SpaceAfter=No
```
"because you are his wife"

Perhaps yet another `:outer` subtype? (I had originally labeled these as `mark`, but that validator doesn't allow that.)

**Comment by sylvainkahane** [comment]
If I well understand the construction, the "determiner" _τὸ_ transfers the clause into an NP and the ADP _διὰ_ combines with this NP. If it is the case, both of them should be dependent of the head of the clause, that is the noun _γυναῖκα_, the determiner by `det:outer` and the ADP by `case:outer`, no?

**Comment by Stormur** [comment]
Using `det:outer` would be another case where one could benefit from “transversal” documentation pages, as anything might be outer.

The `ADP` δια needs to be a `mark` since it introduces a clause (`advcl`).

**Comment by amir-zeldes** [comment]
I agree with everyone that this is a nominalized clause which receives an article, so `det` is correct, and since it is a copula predication, the head should be the lexical predicate. Additional `:outer` labels were discussed when `nsubj:outer` was proposed, but it was decided to avoid these due to the potential for proliferation of very rare labels that would result from this, since any type of clausal modifier could have outer variants. 

Personally I would also propose to avoid these - it is really just a normal determiner from the dependency function perspective, it's just that dependencies don't have a good way of marking clause boundaries or unary derivations. Fortunately these are pretty rare, so I think we can live with just using the regular dependencies for such cases (alternatively, some kind of MISC feature could be used, or if we really want phrase boundaries, concurrent phrase annotations outside of UD - some UD datasets have these too!)

**Comment by sylvainkahane** [comment]
> The ADP δια needs to be a mark since it introduces a clause (advcl).

Yes but the clause has been nominalized by the determiner. It is true that mark is used in UD treebanks in this case, but it is a pity.

**Comment by mr-martian** [comment]
> but it was decided to avoid these due to the potential for proliferation of very rare labels that would result from this, since any type of clausal modifier could have outer variants.

In my data it looks like it occurs around 100 times in 1500 sentences, which is more common than `aux`, `nsubj:outer`, `compound`, and `vocative`. Not sure if that changes the argument at all though.

I would be ok with plain `det` with a misc feature.

**Comment by Stormur** [comment]
> > The ADP δια needs to be a mark since it introduces a clause (advcl).
> 
> Yes but the clause has been nominalized by the determiner. It is true that mark is used in UD treebanks in this case, but it is a pity.

It does use a nominalisation strategy, but I think it still has to be treated fully as a clause, since it is one with a predicate as head (and no nominal internal head as the relatives, for example). So `mark` is useful to distinguish it (and goes together with `advcl` anyway). It is not so much different than e.g. a Latin accusative with infinitive, it is just that Greek requires a mark for definiteness. 

I would say that a `det:outer` is also quite useful here, else we would register a strange article for γυναίκα. The logic is really the same as for `cop:outer`… as said, it would be easier if some subtypes could be defines independently from the main relation (#955).

**Comment by nschneid** [comment]
Arguably the ideal interpretation of `:outer` would be not as a subtype per se, but as a feature on the relation. Maybe something to consider for UDv3.

**Comment by amir-zeldes** [comment]
> as a feature on the relation. something to consider for UDv3.

I think that would be better. I said this during the discussion of outer in general, but I just don't think it's a dependency relation. An `nsubj:outer` is really just a regular old `nsubj`; it just happens to nest another predication. It's true that this can apply to a variety of other relations, but some of those would be very rare and create practical problems for parsers. In the extreme case, we could have labels that only occur in dev or test sets, making them impossible for models to learn. Decoupling 'outer' status to another annotation type would circumvent this and make the more correct generalization about nesting, while leaving relations like `nsubj` to consistently just mean what they mean.

**Comment by mr-martian** [comment]
In Ancient Greek-PTNK I'm now adding `Outer=Yes` in MISC for cases like these, and not giving any indication of the nesting in the relation except for the ones where `:outer` is required. So now the original example:

```conllu
17	διὰ	διά	ADP	_	_	20	case	_	Gloss=+G=through,by;-+A=because-of|Outer=Yes
18	τὸ	ὁ	DET	_	Case=Acc,Nom|Definite=Def|Gender=Neut|Number=Sing|PronType=Art	20	det	_	Gloss=the|Outer=Yes
19	σὲ	σέ	PRON	_	Case=Acc|Number=Sing|Person=2|PronType=Prs	20	nsubj	_	Gloss=you
20	γυναῖκα	γυνή	NOUN	_	Case=Acc|Gender=Fem|Number=Sing	11	obl	_	Gloss=woman,wife
21	αὐτοῦ	αὐτός	PRON	_	Case=Gen|Gender=Masc,Neut|Number=Sing|PronType=Prs	20	nmod:poss	_	Gloss=he,she,it,-self,same
22	εἶναι	εἰμί	AUX	_	Tense=Pres|VerbForm=Inf|Voice=Act	20	cop	_	Gloss=to-be|SpaceAfter=No
```

**Comment by sylvainkahane** [comment]
I completely agree with @nschneid and @amir-zeldes that `outer` is a feature on the relation and not a subrelation marker. The solution proposed by @mr-martian to have a feature `Outer=Yes` on the dependent is ok and likely to be the best solution in the current UD framework, including for `nsubj:outer`. It is always possible to put on the dependent any piece of information concerning its relation with its governor. 

Nevertheless, it would be better to separate information concerning the word and the phrase it heads and information concerning its syntactic function and its relation with its governor. Clearly `outer` does not concern the dependent but the governor, and more precisely the fact that the "true" syntactic governor of the relation is not its UD governor. 
Note that `nsubj:pass` is also a bit problematic: `nsubj:pass` is not a syntactic subrelation of `subj`. the subject of a passive verbal forms is just an ordinary subject (at least in languages I know) and `pass`  rather works as a semantic feature.

**Comment by mr-martian** [comment]
> Clearly outer does not concern the dependent but the governor, and more precisely the fact that the "true" syntactic governor of the relation is not its UD governor.

It seems to me that there are two separate facts that we are trying to convey. One, as you describe, is that the verb in these examples is the head of two different phrases (a clause and a prepositional phrase). The second is that we want to convey which phrase each word is in. `Outer=Yes` directly expresses the latter and implicitly expresses the former.

**Comment by Stormur** [comment]
> Arguably the ideal interpretation of `:outer` would be not as a subtype per se, but as a feature on the relation. Maybe something to consider for UDv3.



> > as a feature on the relation. something to consider for UDv3.
> 
> I think that would be better. I said this during the discussion of outer in general, but I just don't think it's a dependency relation. An `nsubj:outer` is really just a regular old `nsubj`; it just happens to nest another predication. It's true that this can apply to a variety of other relations, but some of those would be very rare and create practical problems for parsers. In the extreme case, we could have labels that only occur in dev or test sets, making them impossible for models to learn. Decoupling 'outer' status to another annotation type would circumvent this and make the more correct generalization about nesting, while leaving relations like `nsubj` to consistently just mean what they mean.

Maybe this could led to apply the same logic as layers to dependency relation? So we could have something like

`cop[outer]`

and probably the same logic would apply to other subtypes like reported, allowing for

`csubj[reported]:pass`

whereas at the moment one has to choose either subtype.

**Comment by amir-zeldes** [comment]
> Maybe this could led to apply the same logic as layers to dependency relation? So we could have something like cop[outer]

That would still leave it in the deprel field, which parsers train on, so we would still have the issue of label proliferation, sparse labels possibly missing from train splits, difficulties building confusion matrices... I'd prefer to keep these distinctions outside of the deprel field.

**Comment by Stormur** [comment]
> Note that `nsubj:pass` is also a bit problematic: `nsubj:pass` is not a syntactic subrelation of `subj`. the subject of a passive verbal forms is just an ordinary subject (at least in languages I know) and `pass` rather works as a semantic feature.

This is actually not problematic, as, as noted in many other discussions, most if not all subrelations **are** semantic in nature. Moreover, I think that `pass` is actually needed for a meaningful annotation.

> Nevertheless, it would be better to separate information concerning the word and the phrase it heads and information concerning its syntactic function and its relation with its governor.

> That would still leave it in the deprel field, which parsers train on, so we would still have the issue of label proliferation, sparse labels possibly missing from train splits, difficulties building confusion matrices... I'd prefer to keep these distinctions outside of the deprel field.

This is true and we want to probably better clarify for the future what can be actually expressed as a subtype, and what not, and in case where else it can. But I am not completely sold to putting `Outer` in the `MISC` field, as in my opinion we are trying to annotate something that is very much present at the morphosyntactic level (think about word order, position of complementisers, transpositions and so on): it is not one of those "extra" or "functional" bits of information like `SpaceAfter` or `Gloss`.

**Comment by amir-zeldes** [comment]
I agree it's syntactic information - but at least in the case of outer, it corresponds to phrase structure distinctions (phrase nesting depth), and not to dependency labels (an nsubj:outer is just a normal subject in terms of valency and function in the argument structure)
