### ISSUE TITLE
Question about reparandum

### ISSUE THREAD

**Issue by Lguyogiro** [UniversalDependencies/docs#961]
If we have reparandum of a partial clause, or at least 2 elements that have a syntactic relation, how do we label the reparandum? at the token level or from head to head, and each part has its own internal structure? 

For example in the following sentence, imagine the speaker is correcting "went" to "stayed". Which annotation is the better treatment of reparandum.

![imagen](https://github.com/UniversalDependencies/docs/assets/7957321/ddf3cace-9948-4e90-99af-c34e817e080d)

![imagen](https://github.com/UniversalDependencies/docs/assets/7957321/a48e3d63-10f0-4f7d-8d5d-1a7b72948cb8)

The above sentence is just a toy example. The actual example I'm dealing with is a longer sentence in Nahuatl that follows this same structure, but the first instance of the verb is cut off and then the subject and verb are repeated:

![imagen](https://github.com/UniversalDependencies/docs/assets/7957321/eacdf53d-8238-43c2-a2f2-a5d983708dac)

**Comment by nschneid** [comment]
Good question. Based on the example at https://universaldependencies.org/u/dep/reparandum.html, I would use just one `reparandum` edge for the entire repaired sequence.

**Comment by Lguyogiro** [comment]
works for me. Thanks

**Comment by sylvainkahane** [comment]
Just to justify the choice to have only one reparandum: one principle is to connect together words that form a unit. Clearly in your toy example "he went" forms a unit and the two words must be connected (by a subj relation). Even when there is no clear relation, like in "and he and she went", "and he" must be connected. In such a case, "he" can be promoted as the head if this unit and "and" is a cc of "he".
