### ISSUE TITLE
Numbers with spaces

### ISSUE THREAD

**Issue by kant2002** [UniversalDependencies/docs#966]
I trying to create parser for CoNLL-U format and try to run it on Ukrainian UD

What I discover there
```
# sent_id = 2m0p
# text = У 1995-му Сінгапур із 26 000 дол. США на душу населення обійшов Британію (19 700).
# translit = U 1995-mu Sinhapur iz 26 000 dol. SŠA na dušu naselenńа obijšov Brytaniju (19 700).
1	У	у	ADP	Spsl	Case=Loc	2	case	2:case	Id=2m0q|LTranslit=u|Translit=U
2	1995-му	1995-ий	NOUN	Ao-mslf	Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing	12	obl	12:obl	Id=2m0r|LTranslit=1995-yj|Translit=1995-mu
3	Сінгапур	Сінгапур	PROPN	Npmsnn	Animacy=Inan|Case=Nom|Gender=Masc|Number=Sing	12	nsubj	12:nsubj	Id=2m0s|LTranslit=Sinhapur|Translit=Sinhapur
4	із	із	ADP	Spsi	Case=Ins	6	case	6:case	Id=2m0t|LTranslit=iz|Translit=iz
5	26 000	26000	NUM	Mlc-i	Case=Ins|NumType=Card|Uninflect=Yes	6	nummod	6:nummod	Id=2m0v|LTranslit=26000|Translit=26 000
6	дол	дол.	NOUN	Y	Abbr=Yes|Animacy=Inan|Case=Ins|Gender=Masc|Number=Plur|Uninflect=Yes	3	nmod	3:nmod	Id=2m0w|LTranslit=dol.|SpaceAfter=No|Translit=dol
7	.	.	PUNCT	U	_	6	punct	6:punct	Id=2m0x|LTranslit=.|Translit=.
8	США	США	PROPN	Np-pgn	Animacy=Inan|Case=Gen|Number=Ptan|Uninflect=Yes	6	nmod	6:nmod	Id=2m0y|LTranslit=SŠA|Translit=SŠA
9	на	на	ADP	Spsa	Case=Acc	10	case	10:case	Id=2m0z|LTranslit=na|Translit=na
10	душу	душа	NOUN	Ncfsan	Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing	6	nmod	6:nmod	Id=2m10|LTranslit=duša|Translit=dušu
11	населення	населення	NOUN	Ncnsgn	Animacy=Inan|Case=Gen|Gender=Neut|Number=Sing	10	nmod	10:nmod	Id=2m11|LTranslit=naselenńа|Translit=naselenńа
12	обійшов	обійти	VERB	Vmeis-sm	Aspect=Perf|Gender=Masc|Mood=Ind|Number=Sing|Tense=Past|VerbForm=Fin	0	root	0:root	Id=2m12|LTranslit=obijty|Translit=obijšov
13	Британію	Британія	PROPN	Npfsan	Animacy=Inan|Case=Acc|Gender=Fem|Number=Sing	12	obj	12:obj	Id=2m13|LTranslit=Brytanija|Translit=Brytaniju
14	(	(	PUNCT	U	_	15	punct	15:punct	Id=2m14|LTranslit=(|SpaceAfter=No|Translit=(
15	19 700	19700	NUM	Mlc-n	Case=Nom|NumType=Card|Uninflect=Yes	13	parataxis	13:parataxis	Id=2m16|LTranslit=19700|SpaceAfter=No|Translit=19 700
16	)	)	PUNCT	U	_	15	punct	15:punct	Id=2m17|LTranslit=)|SpaceAfter=No|Translit=)
17	.	.	PUNCT	U	_	12	punct	12:punct	Id=2m18|LTranslit=.|Translit=.
```

If you notice line 5 and 15 contains `26 000` and `19 700` in the form respectively. Since CoNLL is sensetive to whitespaces, this raises interesting question. How these numbers should be encoded. Also I think this case somehow should be documented, or at least hinted at possibilities of such situations.

/cc @msklvsk

**Comment by foxik** [comment]
Hi, the CoNLL-U format description https://universaldependencies.org/format.html allows "plain" spaces in three columns, quoting:
> _Fields other than FORM, LEMMA, and MISC must not contain space characters._

So the example is valid. My personal feeling is that spaces are generally discouraged in the FORM column, but allowed for various phenomena like the space-separated numbers. I think the usage of spaces in FORMs should be documented in a language-specific documentation -- indeed, on https://universaldependencies.org/uk/index.html you can find, quoting:
> _A whitespace separating digits in a large number is not treated as a word separator. For example, 1 000 000 (“1,000,000” by English rules) is one token._

FYI, I recall that also French uses spaces in numbers, https://universaldependencies.org/fr/index.html states that _Only numbers can contain spaces (following the regexp [0-9 ,]+)._. A quick grep in UD 2.12 files produced the following list of treebanks with spaces in FORMs in train data: `et_edt fi_tdt fr_gsd fr_partut fr_sequoia ja_gsdluw lt_alksnis lv_lvtb pl_pdb pt_bosque ru_syntagrus ru_taiga sv_talbanken uk_iu vi_vtb`).

**Comment by kant2002** [comment]
Okay. That make sense, probably I miss that documentation parts.

**Comment by AngledLuffa** [comment]
Also, Vietnamese uses spaces to separate syllables in words, so there is at
least one case where spaces are very common in the FORM column.

**Comment by kant2002** [comment]
Question, not sure if is it worth adding new issue

https://github.com/UniversalDependencies/tools/blob/b44f4e83836be4ac67d7a958486e1a20b05816f1/validate.py#L217-L221

here validation logic does not account for scenarios mentioned above, should validation script support this?

**Comment by martinpopel** [comment]
I don't see any problem in the validation script (or its logic). The columns in CoNLL-U are separated by tab characters ("\t"), so it is not affected by space characters.

**Comment by kant2002** [comment]
ooh. I again was too fast in making decisions. Thank you. I think I would appreciate that CoNLL-U format is so rigid.
