### ISSUE TITLE
Format of hyperlinks

### ISSUE THREAD

**Issue by Stormur** [UniversalDependencies/docs#980]
I would like to inquire about how to properly format intradocumentation hyperlinks: it seems that most of those that I put mimicking those I found in the Czech documentation are broken even if there is a page.

On a given documentation page, I am using (with code `la` for Latin):

* `la-dep/Name` for dependencies, and 
* `la-feat/Name` for features.

Also, sometimes I would like to give a more punctual references, and so I tried (inspired by the URLs)

* `la-feat/Name#Value`

but it does not seem to work.

Is there any documentation to write documentation? :grimacing:

**Comment by dan-zeman** [comment]
> Is there any documentation to write documentation?

There are a number of pages on how to write documentation but I don't remember which one (and whether any at all) answers your question:

* https://universaldependencies.org/contributing_language_specific.html
* https://universaldependencies.org/contributing.html
* https://universaldependencies.org/visualization.html
* https://daringfireball.net/projects/markdown/syntax

You should always be able to use local path to the HTML file generated by Jekyll, as in

```
[see here for Italian gender](/it/feat/Gender.html)
[or here for universal definition of vocative](/u/feat/Case.html#Voc)
```

In addition, our setup provides some shortcuts where you don't have to provide the URL and Jekyll will figure it out when generating the pages. If you are on a Latin-specific page and write just `[Name]()` I think you should by default get the Latin page with the corresponding feature, UPOS or relation. If it does not exist, you should get the corresponding universal page. If it does not exist either, but the corresponding page exists in one of the other languages, you will be redirected to one of them (picked randomly). I'm not sure whether you can link this way from a feature page to a relation page, or does it have to be inside one domain. But hopefully it can go across domains; there is no danger of name conflict.

The main problem I observed in the past was that these shortcuts did not adapt easily if a page did not exist first and then it was created.

**Comment by Stormur** [comment]
Thanks, I will try the different syntaxes and see what works!
