### ISSUE TITLE
"Semi-mandatory" subtypes

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#990]
I find [this language](https://universaldependencies.org/u/dep/index.html) very confusing:

<img width="1010" alt="image" src="https://github.com/UniversalDependencies/docs/assets/985263/f98ec690-8103-4b63-a934-9c32589741b9">

This seems incomplete as a policy: how are readers supposed to know which subtypes are semi-mandatory? I'm fine with the provided examples being semi-mandatory, but they are not presented as an exhaustive list ("include but not limited to the following").

Maybe we should change it to "the following are strongly recommended in languages that have the relevant construction", and consider adding a few more (`advcl:relcl`? `nmod:poss`?).

There are some subtypes [used in a lot of languages](https://universaldependencies.org/ext-dep-index.html) that may reflect legacy relations we don't necessarily want to recommend—e.g. `flat:name`, `flat:foreign`, `obl:tmod`.

**Comment by dan-zeman** [comment]
`advcl:relcl` probably should be added because it is a twin of `acl:relcl`, although rare.

I am against adding `nmod:poss`.

**Comment by jnivre** [comment]
I think it’s a good idea to remove the “including but not limited to” and try to make the list exhaustive (and update it if needed).

Joakim

**Comment by amir-zeldes** [comment]
Agreed!
